'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {Search,MapPin,Star,Clock,ChevronRight,Flame,Percent,Utensils,Truck,ShoppingBag} from 'lucide-react';
import {supabase} from '../../lib/supabase';

const fallbackBanners=[{title:'Discover great food near you',subtitle:'Delivery · Pickup · Dine-in',image_url:'',cta_label:'Explore restaurants',cta_url:'#restaurants'}];
export default function RestaurantMarketplace(){
 const [store,setStore]=useState(null),[platformSettings,setPlatformSettings]=useState({}),[rows,setRows]=useState([]),[banners,setBanners]=useState([]),[featured,setFeatured]=useState([]),[live,setLive]=useState({}),[q,setQ]=useState(''),[mode,setMode]=useState('delivery'),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{
  const {data:s}=await supabase.from('anaira_platform_stores').select('id,store_name,enabled,published').eq('store_type','restaurant').eq('enabled',true).eq('published',true).maybeSingle();
  if(!s){setLoading(false);return} setStore(s);
  const [{data:m},{data:b},{data:f},{data:ps}]=await Promise.all([
   supabase.from('anaira_store_memberships').select('restaurant_id,listing_override,sort_order,catalog_source,store_config,restaurants(id,name,city,address,logo,cover_image,cuisine,status,delivery_enabled)').eq('store_id',s.id).eq('enabled',true).order('sort_order'),
   supabase.from('anaira_store_banners').select('*').eq('store_id',s.id).eq('active',true).order('display_order'),
   supabase.from('anaira_marketplace_featured_items').select('*').eq('store_id',s.id).eq('active',true).order('display_order'),
   supabase.from('anaira_platform_settings').select('key,value').in('key',['restaurant_home_title','restaurant_home_subtitle','restaurant_home_theme','restaurant_home_show_popular','restaurant_home_show_offers','restaurant_home_show_search','restaurant_home_show_modes','restaurant_home_show_banners','restaurant_home_show_restaurants','restaurant_home_show_footer','restaurant_home_hero_image','restaurant_home_hero_mobile_image','restaurant_home_hero_overlay','restaurant_home_hero_cta','restaurant_home_hero_cta_url','restaurant_home_primary_color','restaurant_home_accent_color','restaurant_home_surface_color','restaurant_home_background_color','restaurant_home_text_color','restaurant_home_container_width','restaurant_home_restaurant_columns','restaurant_home_dish_columns','restaurant_home_banner_columns','restaurant_home_card_radius','restaurant_home_footer_text','restaurant_home_meta_title','restaurant_home_meta_description'])
  ]);
  const connected=(m||[]);
  let sourceRows=connected;
  if(!connected.length){ const {data:listed}=await supabase.from('anaira_marketplace_listings').select('restaurant_id,display_name,city,cover_image,approval_status,marketplace_visible,food_ordering_enabled').eq('marketplace_visible',true).eq('approval_status','approved').eq('food_ordering_enabled',true); sourceRows=(listed||[]).map((x,i)=>({restaurant_id:x.restaurant_id,sort_order:i,catalog_source:'restaurant_saas',listing_override:{title:x.display_name,city:x.city,cover_url:x.cover_image},restaurants:null})); }
  setPlatformSettings(Object.fromEntries((ps||[]).map(x=>[x.key,x.value?.value??x.value])));setRows(sourceRows);setBanners(b?.length?b:[]);setFeatured(f||[]);
  const ids=sourceRows.map(x=>x.restaurant_id);
  const pairs=await Promise.all(ids.map(async id=>{try{const r=await fetch(`/api/marketplace/restaurant/${id}`,{cache:'no-store'});const j=await r.json();return [id,j?.ok?j.data:null]}catch{return [id,null]}}));
  setLive(Object.fromEntries(pairs));
 }finally{setLoading(false)}})()},[]);
 const filtered=useMemo(()=>rows.filter(x=>{const r=x.restaurants||{},o=x.listing_override||{};return !q||`${o.title||r.name} ${r.city} ${r.cuisine}`.toLowerCase().includes(q.toLowerCase())}),[rows,q]);
 const popular=useMemo(()=>{const out=[];for(const f of featured){const snap=live[f.restaurant_id];const item=(snap?.menu||[]).find(i=>String(i.id)===String(f.external_item_id));if(item)out.push({...item,restaurant_id:f.restaurant_id,restaurantName:(rows.find(x=>x.restaurant_id===f.restaurant_id)?.listing_override?.title||rows.find(x=>x.restaurant_id===f.restaurant_id)?.restaurants?.name),image:f.image_override||item.image,badge:f.badge})} if(out.length)return out;for(const r of rows){const snap=live[r.restaurant_id];for(const i of (snap?.menu||[]).filter(x=>x.featured||x.is_popular).slice(0,4))out.push({...i,restaurant_id:r.restaurant_id,restaurantName:r.listing_override?.title||r.restaurants?.name,image:i.image})}return out.slice(0,12)},[featured,live,rows]);
 const offers=useMemo(()=>rows.flatMap(r=>(live[r.restaurant_id]?.offers||[]).slice(0,3).map(o=>({...o,restaurant_id:r.restaurant_id,restaurantName:r.listing_override?.title||r.restaurants?.name}))).slice(0,12),[rows,live]);
 return <main className="food-marketplace"><header className="food-header"><div className="food-top"><div><div className="food-brand">ANAIRA <span>FOOD</span></div><div className="food-location"><MapPin size={15}/> Delivering across your available restaurant zones</div></div>{platformSettings.restaurant_home_show_modes!==false&&<div className="food-actions"><button className={mode==='delivery'?'active':''} onClick={()=>setMode('delivery')}><Truck size={16}/> Delivery</button><button className={mode==='pickup'?'active':''} onClick={()=>setMode('pickup')}><ShoppingBag size={16}/> Pickup</button><button className={mode==='dine_in'?'active':''} onClick={()=>setMode('dine_in')}><Utensils size={16}/> Dine-in</button></div>}</div>
  <div className="food-hero" style={{'--hero-overlay':platformSettings.restaurant_home_hero_overlay??0.58}}><div className="food-hero-copy"><div className="food-kicker">RESTAURANT MARKETPLACE</div><h1>{platformSettings.restaurant_home_title||'Good food. Great restaurants.'}</h1><p>{platformSettings.restaurant_home_subtitle||'Browse live restaurant catalogs, offers and availability.'}</p>{platformSettings.restaurant_home_show_search!==false&&<div className="food-search"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search restaurants, cuisines or dishes..."/></div>}<a className="food-hero-cta" href={platformSettings.restaurant_home_hero_cta_url||'#restaurants'}>{platformSettings.restaurant_home_hero_cta||'Explore restaurants'} <ChevronRight size={16}/></a></div>{platformSettings.restaurant_home_hero_image?<picture><source media="(max-width: 760px)" srcSet={platformSettings.restaurant_home_hero_mobile_image||platformSettings.restaurant_home_hero_image}/><img src={platformSettings.restaurant_home_hero_image} alt=""/></picture>:banners[0]?.image_url?<picture><source media="(max-width: 760px)" srcSet={banners[0].mobile_image_url||banners[0].image_url}/><img src={banners[0].image_url} alt=""/></picture>:null}</div></header>
  <section className="food-wrap" id="restaurants" style={{'--store-width':`${platformSettings.restaurant_home_container_width||1240}px`,'--store-primary':platformSettings.restaurant_home_primary_color||'#073b2b','--store-accent':platformSettings.restaurant_home_accent_color||'#d4aa4c','--store-surface':platformSettings.restaurant_home_surface_color||'#fff','--store-bg':platformSettings.restaurant_home_background_color||'#f7f7f5','--store-text':platformSettings.restaurant_home_text_color||'#17352a','--store-radius':`${platformSettings.restaurant_home_card_radius||20}px`,'--restaurant-cols':platformSettings.restaurant_home_restaurant_columns||3,'--dish-cols':platformSettings.restaurant_home_dish_columns||4,'--banner-cols':platformSettings.restaurant_home_banner_columns||3}}>
   {platformSettings.restaurant_home_show_banners!==false&&banners.length>0&&<div className="food-banner-row">{banners.slice(0,4).map(b=><a key={b.id} className="food-banner" href={b.cta_url||'#restaurants'} style={{backgroundImage:`linear-gradient(90deg,#062b20aa,#062b2011),url(${b.image_url})`}}><small>{b.subtitle}</small><b>{b.title}</b>{b.cta_label&&<span>{b.cta_label} <ChevronRight size={14}/></span>}</a>)}</div>}
   {platformSettings.restaurant_home_show_offers!==false&&offers.length>0&&<><div className="food-section-head"><div><small><Percent size={14}/> OFFERS</small><h2>Offers for you</h2></div><span>Live restaurant offers</span></div><div className="dish-grid">{offers.map((o,n)=><article className="dish-card" key={`${o.restaurant_id}-${o.id||n}`}><div className="dish-image"><div><Percent size={28}/></div><span>{o.code||'OFFER'}</span></div><div><div className="dish-restaurant">{o.restaurantName}</div><h3>{o.title}</h3><p>{o.description||'Available on eligible orders'}</p><strong>{o.discount_type==='percent'?`${o.discount||o.discount_value}% OFF`:`₹${o.discount||o.discount_value} OFF`}</strong></div></article>)}</div></>}
   <div className="food-section-head"><div><small>EXPLORE</small><h2>Restaurants near you</h2></div><span>{filtered.length} restaurants</span></div>
   {platformSettings.restaurant_home_show_restaurants!==false&&(loading?<div className="food-empty">Loading live restaurants…</div>:!filtered.length?<div className="food-empty">No restaurants are currently published or connected to Restaurant SaaS.</div>:<div className="food-grid">{filtered.map(x=><RestaurantCard key={x.restaurant_id} row={x} live={live[x.restaurant_id]}/>)}</div>)}
   {platformSettings.restaurant_home_show_popular!==false&&popular.length>0&&<><div className="food-section-head"><div><small><Flame size={14}/> POPULAR DISHES</small><h2>Popular dishes</h2></div><span>From connected restaurants</span></div><div className="dish-grid">{popular.map((i,n)=><Dish key={`${i.restaurant_id}-${i.id}-${n}`} item={i}/>)}</div></>}
  </section>{platformSettings.restaurant_home_show_footer!==false&&<footer className="food-footer">{platformSettings.restaurant_home_footer_text||'Anaira Food — discover restaurants, order food and enjoy local dining.'}</footer>}
 </main>
}
function RestaurantCard({row,live}){const r=row.restaurants||{},o=row.listing_override||{},items=live?.menu||[],offers=live?.offers||[];return <article className="food-card"><Link href={`/store/${row.restaurant_id}`} className="food-cover"><img src={o.cover_url||r.cover_image||r.logo||'/assets/anaira-logo.webp'} alt=""/><div className="food-badge">{offers.length?'OFFERS':'MENU'}</div></Link><div className="food-card-body"><div className="food-meta"><span>{r.city||r.address||'Local'}</span><span>•</span><span>{r.cuisine||'Multi-cuisine'}</span></div><h3>{o.title||r.name}</h3><p>{o.tagline||'Live menu · Delivery · Pickup · Dine-in'}</p><div className="food-stats"><span><Clock size={14}/> {row.store_config?.delivery_eta_minutes||45} min est.</span><span>{items.length} dishes</span><span>{row.store_config?.delivery!==false?'Delivery':''}{row.store_config?.pickup!==false?' · Pickup':''}</span></div><div className="food-card-actions"><Link href={`/store/${row.restaurant_id}`}>View menu <ChevronRight size={15}/></Link></div></div></article>}
function Dish({item}){return <article className="dish-card"><div className="dish-image">{item.image?<img src={item.image} alt=""/>:<div><Utensils size={28}/></div>}{item.badge&&<span>{item.badge}</span>}</div><div><div className="dish-restaurant">{item.restaurantName}</div><h3>{item.name}</h3><p>{item.category||'Popular choice'}</p><strong>₹{item.price}</strong></div></article>}
