'use client';
import {useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import {supabase} from '../../../lib/supabase';

const GLOBAL_KEYS=['restaurant_home_title','restaurant_home_subtitle','restaurant_home_theme','restaurant_home_primary_color','restaurant_home_accent_color','restaurant_home_surface_color','restaurant_home_background_color','restaurant_home_text_color','restaurant_home_card_radius','restaurant_home_show_search','restaurant_home_show_offers','restaurant_home_show_popular','restaurant_home_show_banners','restaurant_home_show_footer','restaurant_home_hero_image','restaurant_home_hero_mobile_image','restaurant_home_hero_overlay','restaurant_home_hero_cta','restaurant_home_hero_cta_url','restaurant_home_footer_text'];
const defaults={restaurant_home_title:'Discover great food',restaurant_home_subtitle:'Local restaurants, live menus and direct ordering.',restaurant_home_theme:'forest',restaurant_home_primary_color:'#073b2b',restaurant_home_accent_color:'#d4aa4c',restaurant_home_surface_color:'#ffffff',restaurant_home_background_color:'#f7f7f5',restaurant_home_text_color:'#17352a',restaurant_home_card_radius:20,restaurant_home_show_search:true,restaurant_home_show_offers:true,restaurant_home_show_popular:true,restaurant_home_show_banners:true,restaurant_home_show_footer:true,restaurant_home_hero_image:'',restaurant_home_hero_mobile_image:'',restaurant_home_hero_overlay:.45,restaurant_home_hero_cta:'Order Now',restaurant_home_hero_cta_url:'',restaurant_home_footer_text:'Anaira Food — discover restaurants, order food and enjoy local dining.'};
function val(row){return row?.value?.value??row?.value}
export default function RestaurantStore(){
 const {id}=useParams(); const [loading,setLoading]=useState(true),[r,setR]=useState(null),[global,setGlobal]=useState(defaults),[membership,setMembership]=useState(null),[settings,setSettings]=useState(null),[banners,setBanners]=useState([]),[featured,setFeatured]=useState([]),[categories,setCategories]=useState([]),[items,setItems]=useState([]),[offers,setOffers]=useState([]),[cart,setCart]=useState([]),[selected,setSelected]=useState(null),[variants,setVariants]=useState([]),[addons,setAddons]=useState([]),[chosenVariant,setChosenVariant]=useState(null),[chosenAddons,setChosenAddons]=useState([]),[q,setQ]=useState(''),[category,setCategory]=useState('all'),[mode,setMode]=useState('delivery'),[coupon,setCoupon]=useState(''),[form,setForm]=useState({name:'',phone:'',address:''}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!id)return;(async()=>{try{
   const storesQ=await supabase.from('anaira_platform_stores').select('id,enabled,published,store_name,slug').eq('store_type','restaurant').eq('enabled',true).eq('published',true).limit(10);
   const store=(storesQ.data||[])[0];
   if(!store){setMsg(storesQ.error?.message||'Restaurant marketplace is not configured.');setLoading(false);return}
   const membershipsQ=await supabase.from('anaira_store_memberships').select('*').eq('restaurant_id',id).eq('store_id',store.id).eq('enabled',true).limit(10);
   const membershipRow=(membershipsQ.data||[])[0];
   if(!membershipRow){setMsg(membershipsQ.error?.message||'This restaurant is not published in the Restaurant Store.');setLoading(false);return}
   const property={id,store_id:store.id,name:membershipRow.listing_override?.title||'Restaurant',slug:membershipRow.listing_override?.slug||id,logo:membershipRow.listing_override?.logo_url||'',cover_image:membershipRow.listing_override?.cover_url||'',cuisine:membershipRow.listing_override?.cuisine||'',address:membershipRow.listing_override?.address||'',city:membershipRow.listing_override?.city||'',phone:membershipRow.listing_override?.phone||'',website:membershipRow.listing_override?.website||'',listing_override:membershipRow.listing_override||{},store_config:membershipRow.store_config||{},catalog_source:membershipRow.catalog_source||'local'};
   const [{data:ss},{data:g},{data:globalBanners},{data:localBanners},{data:fi},{data:localCategories},{data:localMenuRows},{data:localOffers},{data:live}]=await Promise.all([
    supabase.from('anaira_store_settings').select('*').eq('restaurant_id',property.id).eq('store_id',property.store_id).eq('store_type','restaurant').limit(10),
    supabase.from('anaira_platform_settings').select('key,value').in('key',GLOBAL_KEYS),
    supabase.from('anaira_store_banners').select('*').is('restaurant_id',null).eq('active',true).order('display_order'),
    supabase.from('anaira_store_banners').select('*').eq('restaurant_id',property.id).eq('active',true).order('display_order'),
    supabase.from('anaira_marketplace_featured_items').select('*').eq('restaurant_id',property.id).eq('active',true).order('display_order'),
    supabase.from('anaira_store_categories').select('*').eq('restaurant_id',property.id).eq('active',true).order('display_order').order('name'),
    supabase.from('anaira_marketplace_menu_items').select('*').eq('restaurant_id',property.id).eq('active',true).order('display_order').order('item_name').limit(1000),
    supabase.from('anaira_store_offers').select('*').eq('restaurant_id',property.id).eq('active',true).order('created_at',{ascending:false}),
    fetch(`/api/marketplace/restaurant/${property.id}`,{cache:'no-store'}).then(x=>x.json()).catch(e=>({ok:false,error:e.message}))
   ]);
   const resolvedStore=store||live?.store;
   if(!resolvedStore?.enabled||!resolvedStore?.published){setMsg('Restaurant marketplace is not currently published.');setLoading(false);return}
   // The public Store ID is the primary store. The Restaurant SaaS bridge is optional enrichment.
   // Never make a local Store Builder page unavailable just because the integration API fails.
   const membershipData=membershipRow;
   const resolvedMembership=membershipData||live?.membership||{restaurant_id:property.id,enabled:true,listing_override:property.listing_override||{},store_config:property.store_config||{},catalog_source:'local'};
   const gg={...defaults};(g||[]).forEach(x=>gg[x.key]=val(x));setGlobal(gg);setMembership(resolvedMembership);setSettings((ss||[])[0]||live?.settings||null);setR({...property,...(live?.restaurant||{}),...(resolvedMembership.listing_override||{}),listing_override:resolvedMembership.listing_override||{},store_config:resolvedMembership.store_config||{}});
   const snapshot=live?.ok?live.data||{}:{};
   const rawMenu=(Array.isArray(snapshot.menu)&&snapshot.menu.length?snapshot.menu:(localMenuRows||[]));
   const rawCategories=(Array.isArray(snapshot.categories)&&snapshot.categories.length?snapshot.categories:(localCategories||[]));
   const rawOffers=(Array.isArray(snapshot.offers)&&snapshot.offers.length?snapshot.offers:(localOffers||[]));
   const featuredRows=fi||[];
   const featuredIds=new Set(featuredRows.map(x=>String(x.external_item_id)));
   const menu=rawMenu.map(i=>{const f=featuredRows.find(x=>String(x.external_item_id)===String(i.id));return {...i,id:i.id,item_name:i.item_name||i.name,description:i.description,price:i.price,image_url:f?.image_override||i.image_url||i.image,featured:featuredIds.has(String(i.id))||!!i.featured,discount_price:i.discount_price??null,category_name:i.category_name||i.category,variants:(i.variants||[]).map(v=>({id:v.id,name:v.name,price:Number(v.price_delta||v.price||0)})),addons:(i.addons||[]).map(a=>({id:a.id,name:a.name,price:Number(a.price||a.price_delta||0)}))}});
   setItems(menu);setCategories(rawCategories.map((x,i)=>({id:String(x.id||i),name:x.name||x.category_name||'Menu'})));setOffers(rawOffers.map(o=>({id:o.id,code:String(o.code||o.id).toUpperCase(),title:o.title,discount_type:o.discount_type==='percent'?'percent':'amount',discount_value:o.discount_type==='percent'?o.discount:Number(o.discount||0),min_order_amount:Number(o.min_order_amount??o.min_order??0)})));setFeatured(snapshot.featured?.length?snapshot.featured:featuredRows);setBanners([...(snapshot.banners||[]),...(globalBanners||[]),...(localBanners||[])]);if(membershipData.store_config?.delivery===false)setMode('pickup');
   if(!live?.ok && !membershipData.listing_override?.title) setMsg('');
  }catch(e){setMsg(e.message)}finally{setLoading(false)}})()},[id]);
 const listing=r?.listing_override||{};const sc=r?.store_config||{};const cfg={...global,...sc};
 const effective={...global,...sc,logo_url:listing.logo_url||r?.logo||'',cover_url:listing.cover_url||r?.cover_image||global.restaurant_home_hero_image,gallery:Array.isArray(listing.gallery)?listing.gallery:[],title:listing.title||r?.name||'Restaurant',description:listing.description||'',tagline:listing.tagline||'',city:listing.city||r?.city||'',address:listing.address||r?.address||'',phone:listing.phone||r?.phone||'',website:listing.website||r?.website||'',whatsapp:listing.whatsapp||'',social_instagram:listing.social_instagram||'',social_facebook:listing.social_facebook||'',social_whatsapp:listing.social_whatsapp||''};
 const hero=effective.cover_url;const logo=effective.logo_url||'/assets/anaira-logo.webp';const accent=cfg.accent_color||global.restaurant_home_accent_color;const primary=global.restaurant_home_primary_color||'#073b2b';const background=cfg.store_background||global.restaurant_home_background_color||'#f7f7f5';const radius=Number(cfg.card_radius||global.restaurant_home_card_radius||20);const title=effective.title;const tagline=effective.tagline||r?.cuisine||'Fresh food • Direct ordering';const catalogLabel=membership?.catalog_source==='restaurant_saas'?'Restaurant SaaS + Store overrides':(membership?.catalog_source==='anaira_pos'?'ANAIRA POS + Store overrides':'ANAIRA Store catalog');const location=effective.city||effective.address||'India';
 const visible=useMemo(()=>items.filter(i=>(category==='all'||i.category_name===category)&&(!q||`${i.item_name} ${i.description||''}`.toLowerCase().includes(q.toLowerCase()))),[items,category,q]);
 const subtotal=cart.reduce((s,i)=>s+Number(i.unit_price||0)*i.quantity,0);const discount=useMemo(()=>{const o=offers.find(x=>x.code===coupon.trim().toUpperCase()&&subtotal>=x.min_order_amount);if(!o)return 0;return o.discount_type==='percent'?Math.min(subtotal,subtotal*o.discount_value/100):Math.min(subtotal,o.discount_value)},[coupon,offers,subtotal]);const deliveryFee=mode==='delivery'?Number(settings?.delivery_fee??sc.delivery_fee??0):0;const tax=Math.max(0,subtotal-discount)*Number(settings?.tax_percent??sc.tax_percent??0)/100;const total=Math.max(0,subtotal-discount)+deliveryFee+tax;
 function openItem(i){setSelected(i);setVariants(i.variants||[]);setAddons(i.addons||[]);setChosenVariant(null);setChosenAddons([])}
 function addSelected(){if(!selected)return;const unit=Number(selected.discount_price??selected.price)+Number(chosenVariant?.price||0)+chosenAddons.reduce((s,a)=>s+Number(a.price||0),0);const key=`${selected.id}:${chosenVariant?.id||'base'}:${chosenAddons.map(x=>x.id).sort().join(',')}`;setCart(c=>{const found=c.find(x=>x.key===key);return found?c.map(x=>x.key===key?{...x,quantity:x.quantity+1}:x):[...c,{key,name:selected.item_name,menu_item_id:selected.id,quantity:1,unit_price:unit,modifiers:{variant:chosenVariant?{id:chosenVariant.id,name:chosenVariant.name,price:chosenVariant.price}:null,addons:chosenAddons.map(a=>({id:a.id,name:a.name,price:a.price}))}}]});setSelected(null)}
 function updateQty(k,d){setCart(c=>c.map(x=>x.key===k?{...x,quantity:x.quantity+d}:x).filter(x=>x.quantity>0))}
 async function checkout(){if(!cart.length||!form.name||!form.phone){setMsg('Name, phone and at least one item are required.');return}setBusy(true);const response=await fetch(`/api/marketplace/restaurant/${r.id}/order`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({client_request_id:globalThis.crypto.randomUUID(),customer:{name:form.name,phone:form.phone},address:{text:form.address,type:mode,coupon:coupon||null,delivery_fee:deliveryFee,tax,discount},items:cart.map(i=>({menu_item_id:i.menu_item_id,quantity:i.quantity,modifiers:i.modifiers})),offer_id:null})});const data=await response.json();setBusy(false);if(!response.ok||!data.ok)setMsg(data.error||'Unable to place order');else{setMsg(`Order ${data.order?.order_id||''} received by the restaurant.`);setCart([]);setCoupon('')}}
 if(loading)return <main className="restaurant-store-v9"><div className="store-loading">Loading restaurant experience…</div></main>;if(!r)return <main className="restaurant-store-v9"><div className="store-loading">{msg||'Restaurant unavailable.'}</div></main>;
 const modes=[['delivery','Delivery'],['pickup','Pickup'],['dine_in','Dine-in']].filter(([m])=>sc[m]!==false);const globalBannerVisible=global.restaurant_home_show_banners!==false;const showPopular=cfg.show_popular!==false&&global.restaurant_home_show_popular!==false;const showOffers=cfg.show_offers!==false&&global.restaurant_home_show_offers!==false;const showGallery=cfg.show_gallery!==false;const showFooter=cfg.show_footer!==false&&global.restaurant_home_show_footer!==false;
 return <main className="restaurant-store-v9" style={{'--bg':background,'--surface':global.restaurant_home_surface_color||'#fff','--text':global.restaurant_home_text_color||'#17352a','--primary':primary,'--accent':accent,'--radius':`${radius}px`}}>
  <header className="v9-top"><div className="v9-brand"><img src={logo} alt=""/><div><b>{title}</b><small>ANAIRA RESTAURANT STORE</small></div></div><nav><a href="#menu">Menu</a><a href="#offers">Offers</a><a href="#about">About</a></nav><div className="v9-actions"><a href={`tel:${effective.phone||''}`}>Call</a><a href="#cart">Cart · {cart.reduce((s,x)=>s+x.quantity,0)}</a></div></header>
  <section className="v9-hero" style={{backgroundImage:hero?`linear-gradient(90deg,rgba(5,24,17,${Math.min(.92,Number(cfg.hero_overlay??global.restaurant_home_hero_overlay??.45)+.2)}),rgba(5,24,17,.16)),url(${hero})`:`linear-gradient(115deg,${primary},#14563e)`}}><div className="v9-hero-content"><span className="eyebrow">ANAIRA · VERIFIED RESTAURANT</span><h1>{title}</h1><p>{effective.description||tagline}</p><div className="v9-meta"><span>📍 {location}</span><span>🍽 {r.cuisine||'Restaurant'}</span><span>● Live menu</span></div><div className="v9-hero-buttons">{(cfg.hero_cta_url||global.restaurant_home_hero_cta_url)?<a href={cfg.hero_cta_url||global.restaurant_home_hero_cta_url} className="v9-gold-btn">{cfg.hero_cta_label||global.restaurant_home_hero_cta||'Order Now'} →</a>:<a href="#menu" className="v9-gold-btn">Order Now →</a>}<a href="#menu" className="v9-ghost-btn">Explore Menu</a></div></div><div className="v9-hero-card"><div className="v9-status"><i/> OPEN FOR ORDERS</div><strong>{settings?.timings?.open||'09:00'} – {settings?.timings?.close||'23:00'}</strong><span>{modes.map(x=>x[1]).join(' · ')}</span></div></section>
  <section className="v9-trust"><div><b>LIVE CATALOG</b><span>Restaurant SaaS menu</span></div><div><b>{items.length}+</b><span>Dishes available</span></div><div><b>{categories.length}</b><span>Categories</span></div><div><b>DIRECT</b><span>Order to restaurant</span></div></section>
  <main className="v9-container">
   {cfg.show_announcement!==false&&cfg.announcement&&<div className="v9-announcement">✦ {cfg.announcement}</div>}
   {globalBannerVisible&&banners.length>0&&<section className="v9-section"><div className="v9-heading"><div><span>PROMOTIONS</span><h2>Special experiences & offers</h2></div><small>Managed by ANAIRA + this restaurant</small></div><div className="v9-banner-grid">{banners.map(b=><a key={b.id} href={b.cta_url||'#'} className="v9-banner" style={{backgroundImage:`linear-gradient(90deg,rgba(5,24,17,.8),rgba(5,24,17,.1)),url(${b.image_url})`}}><div><small>FEATURED</small><h3>{b.title}</h3>{b.subtitle&&<p>{b.subtitle}</p>}{b.cta_label&&<strong>{b.cta_label} →</strong>}</div></a>)}</div></section>}
   {showPopular&&featured.length>0&&<section className="v9-section"><div className="v9-heading"><div><span>CURATED</span><h2>Popular at {title}</h2></div><small>Selected by the store team</small></div><div className="v9-featured-grid">{featured.slice(0,8).map(f=>{const i=items.find(x=>String(x.id)===String(f.external_item_id));return i?<article key={f.id} className="v9-featured" onClick={()=>openItem(i)}><div>{f.image_override||i.image_url?<img src={f.image_override||i.image_url} alt=""/>:<div className="v9-noimg">🍽</div>}<b>{f.badge||'POPULAR'}</b></div><h3>{f.title_override||i.item_name}</h3><span>₹{i.discount_price??i.price}</span></article>:null})}</div></section>}
   <section className="v9-section" id="menu"><div className="v9-heading"><div><span>LIVE MENU</span><h2>Order from our kitchen</h2></div><small>{items.length} items · {catalogLabel}</small></div><div className="v9-toolbar">{global.restaurant_home_show_search!==false&&<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search dishes…"/>}<div className="v9-cats"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>All</button>{categories.map(c=><button key={c.id} className={category===c.name?'active':''} onClick={()=>setCategory(c.name)}>{c.name}</button>)}</div></div>{showOffers&&offers.length>0&&<div className="v9-offers" id="offers">{offers.map(o=><div key={o.id}><b>{o.code}</b><span>{o.title}</span><strong>{o.discount_type==='percent'?`${o.discount_value}% OFF`:`₹${o.discount_value} OFF`}</strong></div>)}</div>}<div className="v9-menu-grid">{visible.map(i=><article key={i.id} className="v9-food" onClick={()=>openItem(i)}><div className="v9-food-img">{i.image_url?<img src={i.image_url} alt=""/>:<div className="v9-noimg">🍽</div>}{i.featured&&<b>FEATURED</b>}</div><div className="v9-food-body"><div><span>{i.category_name||'Menu'}</span><h3>{i.item_name}</h3></div><p>{i.description||'Freshly prepared from the restaurant kitchen.'}</p><div className="v9-price"><strong>₹{i.discount_price??i.price}</strong>{i.discount_price!=null&&<del>₹{i.price}</del>}<button>Add +</button></div></div></article>)}</div>{!visible.length&&<div className="store-empty">No dishes found.</div>}</section>
   {showGallery&&Array.isArray(effective.gallery)&&listing.gallery.length>0&&<section className="v9-section" id="about"><div className="v9-heading"><div><span>{cfg.gallery_title||'OUR PLACE'}</span><h2>{cfg.gallery_title||'Inside the restaurant'}</h2></div><small>{cfg.gallery_subtitle||'A look inside our restaurant'}</small></div><div className="v9-gallery">{effective.gallery.slice(0,12).map((u,i)=><img key={`${u}-${i}`} src={u} alt={`${title} ${i+1}`}/>)}</div></section>}
  </main>
  {cfg.show_cart!==false&&<aside className="v9-cart" id="cart"><div className="v9-cart-head"><div><span>YOUR ORDER</span><h2>Cart</h2></div><b>{cart.reduce((s,x)=>s+x.quantity,0)} items</b></div><div className="v9-modes">{modes.map(([v,l])=><button key={v} className={mode===v?'active':''} onClick={()=>setMode(v)}>{l}</button>)}</div><div className="v9-cart-lines">{cart.length?cart.map(i=><div className="v9-cart-line" key={i.key}><div><b>{i.name}</b><small>{i.modifiers?.variant?.name||''}{i.modifiers?.addons?.length?` · ${i.modifiers.addons.map(a=>a.name).join(', ')}`:''}</small><span>₹{i.unit_price}</span></div><div><button onClick={()=>updateQty(i.key,-1)}>−</button><b>{i.quantity}</b><button onClick={()=>updateQty(i.key,1)}>+</button></div></div>):<p>Your cart is empty. Add a dish to begin.</p>}</div><div className="v9-checkout"><div className="v9-coupon"><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="Coupon code"/><button onClick={()=>setMsg(offers.some(o=>o.code===coupon.trim().toUpperCase())?'Coupon ready to apply.':'Coupon not found.')}>Apply</button></div><div className="v9-totals"><span>Subtotal <b>₹{Math.round(subtotal)}</b></span><span>Discount <b>−₹{Math.round(discount)}</b></span><span>Delivery <b>₹{Math.round(deliveryFee)}</b></span><span>Tax <b>₹{Math.round(tax)}</b></span><strong>Total <b>₹{Math.round(total)}</b></strong></div><input placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Mobile number" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><textarea placeholder={mode==='delivery'?'Delivery address':'Table / pickup note'} value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><button className="v9-place" disabled={busy||!cart.length} onClick={checkout}>{busy?'Placing…':'Place Order · ₹'+Math.round(total)}</button>{msg&&<p className="v9-msg">{msg}</p>}</div></aside>}
  {showFooter&&<footer className="v9-footer"><div><img src={logo} alt=""/><div><b>{title}</b><span>{location}</span></div></div><div><span>{global.restaurant_home_footer_text}</span>{effective.social_instagram&&<a href={effective.social_instagram}>Instagram</a>}{effective.social_facebook&&<a href={effective.social_facebook}>Facebook</a>}{effective.social_whatsapp&&<a href={effective.social_whatsapp}>WhatsApp</a>}</div></footer>}
  {selected&&<div className="v9-modal-bg" onClick={()=>setSelected(null)}><div className="v9-modal" onClick={e=>e.stopPropagation()}><button onClick={()=>setSelected(null)}>×</button><h2>{selected.item_name}</h2><p>{selected.description}</p><h3>₹{selected.discount_price??selected.price}</h3>{variants.length>0&&<><h4>Choose a variant</h4>{variants.map(v=><label key={v.id}><input type="radio" name="v" checked={chosenVariant?.id===v.id} onChange={()=>setChosenVariant(v)}/><span>{v.name}</span><b>+₹{v.price}</b></label>)}</>}{addons.length>0&&<><h4>Add-ons</h4>{addons.map(a=><label key={a.id}><input type="checkbox" checked={chosenAddons.some(x=>x.id===a.id)} onChange={e=>setChosenAddons(c=>e.target.checked?[...c,a]:c.filter(x=>x.id!==a.id))}/><span>{a.name}</span><b>+₹{a.price}</b></label>)}</>}<button className="v9-place" onClick={addSelected}>Add to Cart</button></div></div>}
 </main>
}
