'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Hotel,Save,ExternalLink,Image as ImageIcon,MapPin,Plus,Trash2,Power,Pencil,X} from 'lucide-react';
import {AppShell,Header,Section} from '../../components';
import {supabase} from '../../../lib/supabase';
import MarketplaceImageUpload from '../MarketplaceImageUpload';
import HotelMediaUpload from '../../../components/anaira/HotelMediaUpload';

const defaults={
 hotel_marketplace_enabled:true,hotel_require_listing_approval:true,hotel_featured_enabled:true,hotel_marketplace_payment_mode:'platform',
 hotel_home_title:'Exceptional stays. Beautiful destinations.',
 hotel_home_subtitle:'Discover verified hotels, live room availability and direct booking experiences across ANAIRA.',
 hotel_home_theme:'luxury',hotel_home_show_search:true,hotel_home_show_banners:true,hotel_home_show_destinations:true,hotel_home_show_trust:true,hotel_home_show_footer:true,
 hotel_home_hero_image:'',hotel_home_hero_mobile_image:'',hotel_home_hero_video:'',hotel_home_hero_mobile_video:'',hotel_home_hero_media_type:'image',hotel_home_hero_mobile_media_type:'image',hotel_home_hero_overlay:'0.48',hotel_home_background_media_type:'image',hotel_home_background_image:'',hotel_home_background_video:'',hotel_home_background_mobile_media_type:'image',hotel_home_background_mobile_image:'',hotel_home_background_mobile_video:'',hotel_home_background_overlay:'0.48',hotel_home_hero_cta:'Explore hotels',hotel_home_hero_cta_url:'#hotels',
 hotel_home_primary_color:'#17372b',hotel_home_accent_color:'#c7a15a',hotel_home_surface_color:'#ffffff',hotel_home_background_color:'#f6f3ed',hotel_home_text_color:'#20362d',
 hotel_home_container_width:1240,hotel_home_card_radius:22,hotel_home_hotel_columns:3,hotel_home_destination_columns:5,
 hotel_home_destination_title:'Top destinations',hotel_home_destination_subtitle:'Explore the places guests are discovering across ANAIRA.',
 hotel_home_footer_text:'ANAIRA Hotels — discover stays, compare live availability and book with confidence.',
 hotel_home_meta_title:'ANAIRA Hotels | Hotel Marketplace',hotel_home_meta_description:'Discover hotels, live room availability and direct booking experiences on ANAIRA.'
};
const blankBanner={title:'',subtitle:'',image_url:'',mobile_image_url:'',video_url:'',mobile_video_url:'',media_type:'image',mobile_media_type:'image',cta_label:'Explore hotels',cta_url:'#hotels',display_order:0,active:true};
const blankDestination={name:'',subtitle:'',image_url:'',mobile_image_url:'',cta_label:'Explore hotels',cta_url:'',display_order:0,active:true};

export default function HotelMarketplaceSettings(){
 const [form,setForm]=useState(defaults),[store,setStore]=useState(null),[banners,setBanners]=useState([]),[destinations,setDestinations]=useState([]),
 [banner,setBanner]=useState(blankBanner),[destination,setDestination]=useState(blankDestination),[editingBannerId,setEditingBannerId]=useState(null),[editingDestinationId,setEditingDestinationId]=useState(null),[tab,setTab]=useState('design'),[msg,setMsg]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);

 useEffect(()=>{(async()=>{const {data,error}=await supabase.from('anaira_platform_settings').select('key,value').in('key',Object.keys(defaults));if(error){setError(error.message);return}
  const x={...defaults};(data||[]).forEach(r=>x[r.key]=r.value?.value??r.value);setForm(x);
  const {data:s}=await supabase.from('anaira_platform_stores').select('id,store_name').eq('store_type','hotel').maybeSingle();setStore(s||null);
  if(s){const [{data:b},{data:d}]=await Promise.all([
   supabase.from('anaira_hotel_store_banners').select('*').eq('store_id',s.id).order('display_order'),
   supabase.from('anaira_hotel_store_destinations').select('*').eq('store_id',s.id).order('display_order')
  ]);setBanners(b||[]);setDestinations(d||[])}
 })()},[]);

 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function save(){setSaving(true);setMsg('');setError('');const user=(await supabase.auth.getUser()).data.user?.id;
  for(const [key,value] of Object.entries(form)){const q=await supabase.from('anaira_platform_settings').upsert({key,value:{value},updated_by:user},{onConflict:'key'});if(q.error){setError(q.error.message);setSaving(false);return}}
  setMsg('Global Hotel Marketplace settings saved.');setSaving(false);
 }
 async function saveBanner(e){e.preventDefault();setError('');if(!store||!banner.title){setError('Banner title is required.');return}
  const payload={...banner,store_id:store.id,display_order:Number(banner.display_order)||0,updated_at:new Date().toISOString()};
  if(banner.media_type==='video'&&!banner.video_url){setError('Desktop banner video is required.');return}
  if(banner.media_type==='image'&&!banner.image_url){setError('Desktop banner image is required.');return}
  let q;
  if(editingBannerId) q=await supabase.from('anaira_hotel_store_banners').update(payload).eq('id',editingBannerId).select('*').single();
  else q=await supabase.from('anaira_hotel_store_banners').insert(payload).select('*').single();
  if(q.error){setError(q.error.message);return}
  setBanners(x=>(editingBannerId?x.map(i=>i.id===editingBannerId?q.data:i):[...x,q.data]).sort((a,b)=>(a.display_order||0)-(b.display_order||0)));
  setBanner(blankBanner);setEditingBannerId(null);setMsg(editingBannerId?'Promotional banner updated.':'Global hotel promotional banner added.');
 }
 function editBanner(b){setEditingBannerId(b.id);setBanner({...blankBanner,...b});setTab('hero');window.scrollTo({top:0,behavior:'smooth'});}
 function cancelBannerEdit(){setEditingBannerId(null);setBanner(blankBanner);}
 async function saveDestination(e){e.preventDefault();setError('');if(!store||!destination.name||!destination.image_url){setError('Destination name and image are required.');return}
  const payload={...destination,store_id:store.id,display_order:Number(destination.display_order)||0,cta_url:destination.cta_url||`/anaira/hotels?destination=${encodeURIComponent(destination.name)}`,updated_at:new Date().toISOString()};
  let q;
  if(editingDestinationId) q=await supabase.from('anaira_hotel_store_destinations').update(payload).eq('id',editingDestinationId).select('*').single();
  else q=await supabase.from('anaira_hotel_store_destinations').insert(payload).select('*').single();
  if(q.error){setError(q.error.message);return}
  setDestinations(x=>(editingDestinationId?x.map(i=>i.id===editingDestinationId?q.data:i):[...x,q.data]).sort((a,b)=>(a.display_order||0)-(b.display_order||0)));
  setDestination(blankDestination);setEditingDestinationId(null);setMsg(editingDestinationId?'Destination updated.':'Destination card added to the global hotel marketplace.');
 }
 function editDestination(d){setEditingDestinationId(d.id);setDestination({...blankDestination,...d});setTab('destinations');window.scrollTo({top:0,behavior:'smooth'});}
 function cancelDestinationEdit(){setEditingDestinationId(null);setDestination(blankDestination);}
 async function toggleBanner(b){const {error}=await supabase.from('anaira_hotel_store_banners').update({active:!b.active,updated_at:new Date().toISOString()}).eq('id',b.id);if(error){setError(error.message);return}setBanners(x=>x.map(i=>i.id===b.id?{...i,active:!b.active}:i))}
  async function delBanner(id){if(!window.confirm('Delete this global hotel banner? This cannot be undone.'))return;const {error}=await supabase.from('anaira_hotel_store_banners').delete().eq('id',id);if(error){setError(error.message);return}if(editingBannerId===id){setEditingBannerId(null);setBanner(blankBanner)}setBanners(x=>x.filter(i=>i.id!==id));setMsg('Global hotel banner deleted.')}
 async function toggleDestination(d){const {error}=await supabase.from('anaira_hotel_store_destinations').update({active:!d.active,updated_at:new Date().toISOString()}).eq('id',d.id);if(error){setError(error.message);return}setDestinations(x=>x.map(i=>i.id===d.id?{...i,active:!d.active}:i))}
  async function delDestination(id){if(!window.confirm('Delete this destination card? This cannot be undone.'))return;const {error}=await supabase.from('anaira_hotel_store_destinations').delete().eq('id',id);if(error){setError(error.message);return}if(editingDestinationId===id){setEditingDestinationId(null);setDestination(blankDestination)}setDestinations(x=>x.filter(i=>i.id!==id));setMsg('Destination deleted from the global hotel marketplace.')}

 const tabs=[['design','🎨 Brand & Design'],['hero','🖼 Hero & Promotions'],['destinations','📍 Top Destinations'],['layout','▦ Homepage Layout'],['rules','⚙ Marketplace Rules'],['seo','🔎 SEO & Footer']];
 return <AppShell active="/super-admin/hotel-marketplace-settings">
  <Header eyebrow="SUPER ADMIN • GLOBAL HOTEL STORE" title="ANAIRA Hotels — Marketplace Control Center" subtitle="Global hotel marketplace presentation, discovery, promotions and publishing are owned by Super Admin. Hotel PMS, rooms, rates, inventory and bookings remain operationally canonical in Hotel Management." actions={<div className="market-head-actions"><Link className="btn" href="/anaira/hotels" target="_blank"><ExternalLink size={15}/> Open Hotel Marketplace</Link><button className="btn primary" onClick={save} disabled={saving}><Save size={15}/>{saving?'Saving…':'Save All Changes'}</button></div>}/>
  <div className="market-control-hero"><div><div className="market-eyebrow"><Hotel size={15}/> GLOBAL HOTEL MARKETPLACE</div><h2>Ultra-premium hotel discovery for the entire ANAIRA network.</h2><p>Global branding, hero media, promotional campaigns and destination cards are platform-owned. Individual hotels keep control of their property master and operational inventory.</p></div><div className="market-hero-metrics"><span><b>GLOBAL</b><small>Store ownership</small></span><span><b>LIVE</b><small>HMS inventory</small></span><span><b>{destinations.length}</b><small>Destinations</small></span></div></div>
  <div className="store-control-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {msg&&<div className="notice success" style={{marginBottom:16}}>{msg}</div>}{error&&<div className="notice error" style={{marginBottom:16}}>{error}</div>}

  {tab==='design'&&<><Section title="Global Hotel Brand System" meta="Premium visual identity for /anaira/hotels. This does not duplicate hotel master data."><div className="card store-settings-grid">
   <label><span>Marketplace title</span><input value={form.hotel_home_title} onChange={e=>set('hotel_home_title',e.target.value)}/></label>
   <label><span>Marketplace subtitle</span><input value={form.hotel_home_subtitle} onChange={e=>set('hotel_home_subtitle',e.target.value)}/></label>
   <label><span>Theme preset</span><select value={form.hotel_home_theme} onChange={e=>set('hotel_home_theme',e.target.value)}><option value="luxury">Luxury Gold</option><option value="forest">Forest Luxury</option><option value="midnight">Midnight</option></select></label>
   <label><span>Primary color</span><input type="color" value={form.hotel_home_primary_color} onChange={e=>set('hotel_home_primary_color',e.target.value)}/></label><label><span>Accent / CTA color</span><input type="color" value={form.hotel_home_accent_color} onChange={e=>set('hotel_home_accent_color',e.target.value)}/></label>
   <label><span>Page background</span><input type="color" value={form.hotel_home_background_color} onChange={e=>set('hotel_home_background_color',e.target.value)}/></label><label><span>Surface color</span><input type="color" value={form.hotel_home_surface_color} onChange={e=>set('hotel_home_surface_color',e.target.value)}/></label><label><span>Text color</span><input type="color" value={form.hotel_home_text_color} onChange={e=>set('hotel_home_text_color',e.target.value)}/></label>
   <label><span>Content max width</span><input type="number" min="980" max="1600" value={form.hotel_home_container_width} onChange={e=>set('hotel_home_container_width',Number(e.target.value))}/></label>
   <label><span>Hotel cards per row</span><select value={form.hotel_home_hotel_columns} onChange={e=>set('hotel_home_hotel_columns',Number(e.target.value))}><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></label>
   <label><span>Destination cards per row</span><select value={form.hotel_home_destination_columns} onChange={e=>set('hotel_home_destination_columns',Number(e.target.value))}><option value="4">4</option><option value="5">5</option><option value="6">6</option></select></label>
   <label><span>Card radius</span><input type="number" min="8" max="40" value={form.hotel_home_card_radius} onChange={e=>set('hotel_home_card_radius',Number(e.target.value))}/></label>
  </div></Section>
  <Section title="Homepage Modules" meta="Turn global marketplace modules on or off without affecting hotel operational systems."><div className="card store-toggle-grid">{[['hotel_marketplace_enabled','Hotel Marketplace enabled'],['hotel_home_show_search','Search & availability search'],['hotel_home_show_banners','Hero & promotions'],['hotel_home_show_destinations','Top destinations'],['hotel_home_show_trust','Trust / booking benefits'],['hotel_home_show_footer','Footer']].map(([k,l])=><label key={k} className="check-field"><input type="checkbox" checked={!!form[k]} onChange={e=>set(k,e.target.checked)}/><span>{l}</span></label>)}</div></Section></>}

  {tab==='hero'&&<><Section title="Ultra HD Hero & Background Media" meta="Desktop, tablet and mobile can use responsive image or video. The hero background is separate from the right-side media card so the existing layout stays intact."><div className="card store-settings-stack">
   <HotelMediaUpload label="Desktop hero media" imageValue={form.hotel_home_hero_image} videoValue={form.hotel_home_hero_video} mediaType={form.hotel_home_hero_media_type} restaurantId={store?.id} folder="marketplace/hotels/hero" onTypeChange={v=>set('hotel_home_hero_media_type',v)} onChange={v=>set(form.hotel_home_hero_media_type==='video'?'hotel_home_hero_video':'hotel_home_hero_image',v)}/>
   <HotelMediaUpload label="Mobile / tablet hero media" imageValue={form.hotel_home_hero_mobile_image} videoValue={form.hotel_home_hero_mobile_video} mediaType={form.hotel_home_hero_mobile_media_type} restaurantId={store?.id} folder="marketplace/hotels/hero-mobile" onTypeChange={v=>set('hotel_home_hero_mobile_media_type',v)} onChange={v=>set(form.hotel_home_hero_mobile_media_type==='video'?'hotel_home_hero_mobile_video':'hotel_home_hero_mobile_image',v)}/>
   <HotelMediaUpload label="Desktop full green-background media" imageValue={form.hotel_home_background_image} videoValue={form.hotel_home_background_video} mediaType={form.hotel_home_background_media_type} restaurantId={store?.id} folder="marketplace/hotels/background" onTypeChange={v=>set('hotel_home_background_media_type',v)} onChange={v=>set(form.hotel_home_background_media_type==='video'?'hotel_home_background_video':'hotel_home_background_image',v)}/>
   <HotelMediaUpload label="Mobile / tablet full green-background media" imageValue={form.hotel_home_background_mobile_image} videoValue={form.hotel_home_background_mobile_video} mediaType={form.hotel_home_background_mobile_media_type} restaurantId={store?.id} folder="marketplace/hotels/background-mobile" onTypeChange={v=>set('hotel_home_background_mobile_media_type',v)} onChange={v=>set(form.hotel_home_background_mobile_media_type==='video'?'hotel_home_background_mobile_video':'hotel_home_background_mobile_image',v)}/>
   <div className="hero-save-bar"><div><b>Save Hero & Background Media</b><small>Upload or replace media, then save it to the marketplace.</small></div><button className="btn primary" type="button" onClick={save} disabled={saving}><Save size={15}/>{saving?'Saving…':'Save Hero & Background Media'}</button></div>
   <div className="store-settings-grid"><label><span>Hero overlay strength</span><input type="number" min="0" max="0.9" step="0.05" value={form.hotel_home_hero_overlay} onChange={e=>set('hotel_home_hero_overlay',e.target.value)} step="0.01"/></label><label><span>Background overlay strength</span><input type="number" min="0" max="0.9" step="0.05" value={form.hotel_home_background_overlay} onChange={e=>set('hotel_home_background_overlay',e.target.value)} step="0.01"/></label><label><span>Hero CTA label</span><input value={form.hotel_home_hero_cta} onChange={e=>set('hotel_home_hero_cta',e.target.value)}/></label><label className="full"><span>Hero CTA URL</span><input value={form.hotel_home_hero_cta_url} onChange={e=>set('hotel_home_hero_cta_url',e.target.value)}/></label></div>
  </div></Section>
  <Section title="Global Hotel Promotional Banners" meta="Image/video campaigns with desktop/mobile media, edit, replace, enable/disable and delete."><div className="card"><form className="store-settings-stack" onSubmit={saveBanner}>
   <div className="store-settings-grid"><label><span>Banner title</span><input value={banner.title} onChange={e=>setBanner({...banner,title:e.target.value})} required/></label><label><span>Subtitle</span><input value={banner.subtitle} onChange={e=>setBanner({...banner,subtitle:e.target.value})}/></label></div>
   <HotelMediaUpload label="Desktop banner media" imageValue={banner.image_url} videoValue={banner.video_url} mediaType={banner.media_type} restaurantId={store?.id} folder="marketplace/hotels/banners" onTypeChange={v=>setBanner({...banner,media_type:v})} onChange={v=>setBanner({...banner,[banner.media_type==='video'?'video_url':'image_url']:v})}/>
   <HotelMediaUpload label="Mobile / tablet banner media" imageValue={banner.mobile_image_url} videoValue={banner.mobile_video_url} mediaType={banner.mobile_media_type||'image'} restaurantId={store?.id} folder="marketplace/hotels/banners-mobile" onTypeChange={v=>setBanner({...banner,mobile_media_type:v})} onChange={v=>setBanner({...banner,[banner.mobile_media_type==='video'?'mobile_video_url':'mobile_image_url']:v})}/>
   <div className="store-settings-grid"><label><span>CTA label</span><input value={banner.cta_label} onChange={e=>setBanner({...banner,cta_label:e.target.value})}/></label><label><span>CTA URL</span><input value={banner.cta_url} onChange={e=>setBanner({...banner,cta_url:e.target.value})}/></label><label><span>Display order</span><input type="number" value={banner.display_order} onChange={e=>setBanner({...banner,display_order:e.target.value})}/></label></div>
   <div className="edit-actions"><button className="btn primary" type="submit"><ImageIcon size={15}/>{editingBannerId?'Save Banner Changes':'Add Global Hotel Banner'}</button>{editingBannerId&&<button className="btn" type="button" onClick={cancelBannerEdit}><X size={14}/> Cancel edit</button>}</div>
   </form><div className="admin-list-heading"><div><b>Manage Existing Global Hotel Banners</b><small>Edit, replace media, enable/disable or delete banners already added.</small></div><span>{banners.length} total</span></div><div className="banner-admin-list">{banners.length?banners.map(b=><article key={b.id}><div className="banner-admin-thumb">{b.media_type==='video'?(<video src={b.video_url} muted autoPlay loop playsInline/>):(<img src={b.image_url} alt=""/>)}</div><div><b>{b.title}</b><p>{b.subtitle||'No subtitle'} · order {b.display_order}</p><small>{b.active?'LIVE':'DISABLED'} · {b.media_type==='video'?'VIDEO':'IMAGE'}</small></div><div className="admin-record-actions"><button type="button" className="btn" onClick={()=>editBanner(b)}><Pencil size={13}/> Edit / Replace</button><button type="button" className="btn" onClick={()=>toggleBanner(b)}>{b.active?'Disable':'Enable'}</button><button type="button" className="btn danger" onClick={()=>delBanner(b.id)}><Trash2 size={13}/> Delete</button></div></article>):<div className="admin-empty-state">No global hotel banners added yet. Use <b>Add Global Hotel Banner</b> above to create the first one.</div>}</div></div></Section></>}
  {tab==='destinations'&&<><Section title="Top Destinations — 5 Premium Cards" meta="Super Admin can add destination cards, upload their images, control order and link each card to hotel search. The public marketplace shows five cards in one row on desktop."><div className="card destination-form-card">
   <form className="store-settings-stack" onSubmit={saveDestination}>
    <div className="store-settings-grid"><label><span>Destination name</span><input value={destination.name} onChange={e=>setDestination({...destination,name:e.target.value})} placeholder="Manali" required/></label><label><span>Short subtitle</span><input value={destination.subtitle} onChange={e=>setDestination({...destination,subtitle:e.target.value})} placeholder="Mountain escapes"/></label></div>
    <MarketplaceImageUpload label="Destination image" value={destination.image_url} onChange={v=>setDestination({...destination,image_url:v})} folder="marketplace/hotels/destinations"/>
    <MarketplaceImageUpload label="Mobile destination image (optional)" value={destination.mobile_image_url} onChange={v=>setDestination({...destination,mobile_image_url:v})} folder="marketplace/hotels/destinations-mobile"/>
    <div className="store-settings-grid"><label><span>CTA label</span><input value={destination.cta_label} onChange={e=>setDestination({...destination,cta_label:e.target.value})}/></label><label><span>CTA URL (optional)</span><input value={destination.cta_url} onChange={e=>setDestination({...destination,cta_url:e.target.value})} placeholder="/anaira/hotels?destination=Manali"/></label><label><span>Display order</span><input type="number" min="0" value={destination.display_order} onChange={e=>setDestination({...destination,display_order:e.target.value})}/></label></div>
    <div className="edit-actions"><button className="btn primary" type="submit">{editingDestinationId?<><Save size={15}/> Save Destination Changes</>:<><Plus size={15}/> Add Destination Card</>}</button>{editingDestinationId&&<button className="btn" type="button" onClick={cancelDestinationEdit}><X size={14}/> Cancel edit</button>}</div>
   </form>
  </div></Section>
  <Section title="Manage Existing Top Destinations" meta={`${destinations.filter(d=>d.active).length} active · ${destinations.length} total`}><div className="admin-list-heading"><div><b>Destination Management</b><small>Every destination you add appears here with Edit / Replace, Enable / Disable and Delete controls.</small></div><span>{destinations.length} total</span></div><div className="destination-admin-grid">{destinations.length?destinations.map(d=><article className="destination-admin-card" key={d.id}><div className="destination-admin-image">{d.image_url?<img src={d.image_url} alt={d.name}/>:<MapPin size={28}/>}<span>#{Number(d.display_order)+1}</span><div className="destination-card-actions"><button type="button" onClick={()=>editDestination(d)} title="Edit this destination"><Pencil size={13}/> Edit</button><button type="button" onClick={()=>toggleDestination(d)} title={d.active?'Disable this destination':'Enable this destination'}><Power size={13}/> {d.active?'Disable':'Enable'}</button><button type="button" className="delete" onClick={()=>delDestination(d.id)} title="Delete this destination"><Trash2 size={13}/> Delete</button></div></div><div className="destination-admin-body"><b>{d.name}</b><p>{d.subtitle||'No subtitle'}</p><div className="admin-record-actions"><button type="button" className="btn" onClick={()=>editDestination(d)}><Pencil size={13}/> Edit / Replace</button><button type="button" className="btn" onClick={()=>toggleDestination(d)}><Power size={13}/>{d.active?'Disable':'Enable'}</button><button type="button" className="btn danger" onClick={()=>delDestination(d.id)}><Trash2 size={13}/> Delete</button></div></div></article>):<div className="admin-empty-state">No destinations added yet. Add your first destination above; after saving it will appear here for editing and deletion.</div>}</div></Section></>}

  {tab==='layout'&&<Section title="Hotel Discovery Layout" meta="Control the premium marketplace composition and search experience."><div className="card store-section-layout"><div className="layout-preview"><div className="lp-hero">HERO / DESTINATION / DATES / SEARCH</div><div className="lp-row"><div>TOP DESTINATIONS × 5</div><div>TRUST SIGNALS</div></div><div>LIVE HOTEL DISCOVERY GRID</div><div>GLOBAL PROMOTIONS</div></div><div className="store-settings-grid"><label><span>Destination cards per row</span><select value={form.hotel_home_destination_columns} onChange={e=>set('hotel_home_destination_columns',Number(e.target.value))}><option value="4">4 columns</option><option value="5">5 columns</option><option value="6">6 columns</option></select></label><label><span>Destination section title</span><input value={form.hotel_home_destination_title} onChange={e=>set('hotel_home_destination_title',e.target.value)}/></label><label><span>Destination section subtitle</span><input value={form.hotel_home_destination_subtitle} onChange={e=>set('hotel_home_destination_subtitle',e.target.value)}/></label><label><span>Hotel cards per row</span><select value={form.hotel_home_hotel_columns} onChange={e=>set('hotel_home_hotel_columns',Number(e.target.value))}><option value="2">2 columns</option><option value="3">3 columns</option><option value="4">4 columns</option></select></label><label><span>Container width</span><input type="number" min="980" max="1600" value={form.hotel_home_container_width} onChange={e=>set('hotel_home_container_width',Number(e.target.value))}/></label><label><span>Card radius</span><input type="number" min="8" max="40" value={form.hotel_home_card_radius} onChange={e=>set('hotel_home_card_radius',Number(e.target.value))}/></label></div></div></Section>}

  {tab==='rules'&&<Section title="Hotel Marketplace Governance" meta="Global marketplace policy. Individual hotel stores remain under their Business Admin scope."><div className="card store-settings-grid"><label className="check-field"><input type="checkbox" checked={!!form.hotel_marketplace_enabled} onChange={e=>set('hotel_marketplace_enabled',e.target.checked)}/><span>Hotel Marketplace enabled</span></label><label className="check-field"><input type="checkbox" checked={!!form.hotel_require_listing_approval} onChange={e=>set('hotel_require_listing_approval',e.target.checked)}/><span>Require hotel listing approval</span></label><label className="check-field"><input type="checkbox" checked={!!form.hotel_featured_enabled} onChange={e=>set('hotel_featured_enabled',e.target.checked)}/><span>Featured hotels enabled</span></label><label><span>Marketplace payment mode</span><select value={form.hotel_marketplace_payment_mode} onChange={e=>set('hotel_marketplace_payment_mode',e.target.value)}><option value="platform">Platform</option><option value="direct">Direct to hotel</option><option value="hybrid">Hybrid</option></select></label></div></Section>}

  {tab==='seo'&&<Section title="Hotel Marketplace SEO & Footer" meta="Global metadata controlled by Super Admin."><div className="card store-settings-grid"><label><span>SEO title</span><input value={form.hotel_home_meta_title} onChange={e=>set('hotel_home_meta_title',e.target.value)}/></label><label><span>Footer text</span><input value={form.hotel_home_footer_text} onChange={e=>set('hotel_home_footer_text',e.target.value)}/></label><label className="full"><span>SEO description</span><textarea rows="4" value={form.hotel_home_meta_description} onChange={e=>set('hotel_home_meta_description',e.target.value)}/></label></div></Section>}

  <style jsx>{`
    .destination-admin-image{position:relative;overflow:hidden}
    .destination-card-actions{position:absolute;left:10px;right:10px;bottom:10px;display:flex;gap:6px;z-index:5}
    .destination-card-actions button{appearance:none;border:1px solid rgba(255,255,255,.72);background:rgba(12,37,28,.92);color:#fff;border-radius:9px;padding:8px 10px;display:inline-flex;align-items:center;justify-content:center;gap:5px;font-size:11px;font-weight:800;cursor:pointer;box-shadow:0 6px 18px rgba(0,0,0,.22);backdrop-filter:blur(8px)}
    .destination-card-actions button:hover{background:#c7a15a;color:#132f24}
    .destination-card-actions button.delete{background:#8f332d}
    .destination-card-actions button.delete:hover{background:#b9473d;color:#fff}
    .destination-admin-body{display:block!important;visibility:visible!important;opacity:1!important;padding:12px}
    .destination-admin-body>b,.destination-admin-body p{display:block!important;visibility:visible!important}
    @media(max-width:700px){.destination-card-actions{left:8px;right:8px;bottom:8px;display:grid;grid-template-columns:repeat(3,1fr)}.destination-card-actions button{padding:8px 5px;font-size:10px}.destination-admin-body .admin-record-actions{display:grid;grid-template-columns:1fr}.destination-admin-body .admin-record-actions .btn{width:100%}}
  `}</style>
  <div className="marketplace-final-save"><div><b>Final Marketplace Settings Save</b><small>Save Hero, Background, Design, Layout, Rules and SEO changes made on this page.</small></div><button className="btn primary" type="button" onClick={save} disabled={saving}><Save size={15}/>{saving?'Saving…':'Save All Marketplace Settings'}</button></div>
  <style jsx>{`
    .hero-save-bar,.marketplace-final-save,.admin-list-heading{display:flex;align-items:center;justify-content:space-between;gap:16px;border:1px solid rgba(23,55,43,.12);background:linear-gradient(135deg,#fff,#f7f3e9);border-radius:16px;padding:16px 18px;margin-top:16px;box-shadow:0 10px 28px rgba(20,40,30,.06)}
    .hero-save-bar b,.marketplace-final-save b,.admin-list-heading b{display:block;color:#17372b;font-size:14px}
    .hero-save-bar small,.marketplace-final-save small,.admin-list-heading small{display:block;color:#6b756f;font-size:11px;margin-top:4px}
    .admin-list-heading{margin:18px 0 12px}
    .admin-list-heading>span{font-size:11px;font-weight:800;color:#a17b32;background:#f4ead2;border-radius:999px;padding:6px 10px;white-space:nowrap}
    .admin-record-actions{display:flex;flex-wrap:wrap;gap:8px;align-items:center}
    .admin-record-actions .danger{border-color:rgba(170,55,45,.25);color:#a13d35}
    .admin-empty-state{grid-column:1/-1;padding:28px;text-align:center;border:1px dashed rgba(23,55,43,.18);border-radius:16px;background:#fbfaf7;color:#66716b;font-size:13px}
    @media(max-width:900px){.hero-save-bar,.marketplace-final-save,.admin-list-heading{align-items:flex-start;flex-direction:column}.hero-save-bar .btn,.marketplace-final-save .btn{width:100%}.admin-record-actions{width:100%}.admin-record-actions .btn{flex:1;min-width:110px}}
    @media(max-width:560px){.admin-record-actions{display:grid;grid-template-columns:1fr}.admin-record-actions .btn{width:100%}.hero-save-bar,.marketplace-final-save{padding:14px}}
  `}</style>
  <div className="store-control-footer"><b>Ownership boundary:</b> Super Admin controls the global hotel marketplace. Business Admin controls only the individual hotel's customer-facing store. PMS owns rooms, rates, inventory, availability and bookings. <Link href="/anaira/hotels" target="_blank">Preview global hotel store ↗</Link></div>
 </AppShell>
}
