'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Hotel,Save,ExternalLink,Image as ImageIcon,MapPin,Plus,Trash2,Power} from 'lucide-react';
import {AppShell,Header,Section} from '../../components';
import {supabase} from '../../../lib/supabase';
import MarketplaceImageUpload from '../MarketplaceImageUpload';

const defaults={
 hotel_marketplace_enabled:true,hotel_require_listing_approval:true,hotel_featured_enabled:true,hotel_marketplace_payment_mode:'platform',
 hotel_home_title:'Exceptional stays. Beautiful destinations.',
 hotel_home_subtitle:'Discover verified hotels, live room availability and direct booking experiences across ANAIRA.',
 hotel_home_theme:'luxury',hotel_home_show_search:true,hotel_home_show_banners:true,hotel_home_show_destinations:true,hotel_home_show_trust:true,hotel_home_show_footer:true,
 hotel_home_hero_image:'',hotel_home_hero_mobile_image:'',hotel_home_hero_overlay:'0.48',hotel_home_hero_cta:'Explore hotels',hotel_home_hero_cta_url:'#hotels',
 hotel_home_primary_color:'#17372b',hotel_home_accent_color:'#c7a15a',hotel_home_surface_color:'#ffffff',hotel_home_background_color:'#f6f3ed',hotel_home_text_color:'#20362d',
 hotel_home_container_width:1240,hotel_home_card_radius:22,hotel_home_hotel_columns:3,hotel_home_destination_columns:5,
 hotel_home_destination_title:'Top destinations',hotel_home_destination_subtitle:'Explore the places guests are discovering across ANAIRA.',
 hotel_home_footer_text:'ANAIRA Hotels — discover stays, compare live availability and book with confidence.',
 hotel_home_meta_title:'ANAIRA Hotels | Hotel Marketplace',hotel_home_meta_description:'Discover hotels, live room availability and direct booking experiences on ANAIRA.'
};
const blankBanner={title:'',subtitle:'',image_url:'',mobile_image_url:'',cta_label:'Explore hotels',cta_url:'#hotels',display_order:0,active:true};
const blankDestination={name:'',subtitle:'',image_url:'',mobile_image_url:'',cta_label:'Explore hotels',cta_url:'',display_order:0,active:true};

export default function HotelMarketplaceSettings(){
 const [form,setForm]=useState(defaults),[store,setStore]=useState(null),[banners,setBanners]=useState([]),[destinations,setDestinations]=useState([]),
 [banner,setBanner]=useState(blankBanner),[destination,setDestination]=useState(blankDestination),[tab,setTab]=useState('design'),[msg,setMsg]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);

 useEffect(()=>{(async()=>{const {data,error}=await supabase.from('anaira_platform_settings').select('key,value').in('key',Object.keys(defaults));if(error){setError(error.message);return}
  const x={...defaults};(data||[]).forEach(r=>x[r.key]=r.value?.value??r.value);setForm(x);
  const {data:s}=await supabase.from('anaira_platform_stores').select('id,store_name').eq('store_type','hotel').maybeSingle();setStore(s||null);
  if(s){const [{data:b},{data:d}]=await Promise.all([
   supabase.from('anaira_hotel_store_banners').select('*').eq('store_id',s.id).order('display_order'),
   supabase.from('anaira_hotel_store_destinations').select('*').eq('store_id',s.id).order('display_order')
  ]);setBanners(b||[]);setDestinations(d||[])}
 })()},[]);

 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function save(){setSaving(true);setMsg('');setError('');const user=(await supabase.auth.getUser()).data.user?.id;
  for(const [key,value] of Object.entries(form)){const q=await supabase.from('anaira_platform_settings').upsert({key,value:{value},updated_by:user},{onConflict:'key'});if(q.error){setError(q.error.message);setSaving(false);return}}
  setMsg('Global Hotel Marketplace settings saved.');setSaving(false);
 }
 async function addBanner(e){e.preventDefault();setError('');if(!store||!banner.title||!banner.image_url){setError('Banner title and desktop image are required.');return}
  const {data,error}=await supabase.from('anaira_hotel_store_banners').insert({...banner,store_id:store.id,display_order:Number(banner.display_order)||0}).select('*').single();
  if(error){setError(error.message);return}setBanners(x=>[...x,data].sort((a,b)=>(a.display_order||0)-(b.display_order||0)));setBanner(blankBanner);setMsg('Global hotel promotional banner added.');
 }
 async function addDestination(e){e.preventDefault();setError('');if(!store||!destination.name||!destination.image_url){setError('Destination name and image are required.');return}
  const payload={...destination,store_id:store.id,display_order:Number(destination.display_order)||0,cta_url:destination.cta_url||`/anaira/hotels?destination=${encodeURIComponent(destination.name)}`};
  const {data,error}=await supabase.from('anaira_hotel_store_destinations').insert(payload).select('*').single();
  if(error){setError(error.message);return}setDestinations(x=>[...x,data].sort((a,b)=>(a.display_order||0)-(b.display_order||0)));setDestination(blankDestination);setMsg('Destination card added to the global hotel marketplace.');
 }
 async function toggleBanner(b){const {error}=await supabase.from('anaira_hotel_store_banners').update({active:!b.active,updated_at:new Date().toISOString()}).eq('id',b.id);if(error){setError(error.message);return}setBanners(x=>x.map(i=>i.id===b.id?{...i,active:!b.active}:i))}
 async function delBanner(id){const {error}=await supabase.from('anaira_hotel_store_banners').delete().eq('id',id);if(error){setError(error.message);return}setBanners(x=>x.filter(i=>i.id!==id))}
 async function toggleDestination(d){const {error}=await supabase.from('anaira_hotel_store_destinations').update({active:!d.active,updated_at:new Date().toISOString()}).eq('id',d.id);if(error){setError(error.message);return}setDestinations(x=>x.map(i=>i.id===d.id?{...i,active:!d.active}:i))}
 async function delDestination(id){const {error}=await supabase.from('anaira_hotel_store_destinations').delete().eq('id',id);if(error){setError(error.message);return}setDestinations(x=>x.filter(i=>i.id!==id))}

 const tabs=[['design','🎨 Brand & Design'],['hero','🖼 Hero & Promotions'],['destinations','📍 Top Destinations'],['layout','▦ Homepage Layout'],['rules','⚙ Marketplace Rules'],['seo','🔎 SEO & Footer']];
 return <AppShell active="/super-admin/hotel-marketplace-settings">
  <Header eyebrow="SUPER ADMIN • GLOBAL HOTEL STORE" title="ANAIRA Hotels — Marketplace Control Center" subtitle="Global hotel marketplace presentation, discovery, promotions and publishing are owned by Super Admin. Hotel PMS, rooms, rates, inventory and bookings remain operationally canonical in Hotel Management." actions={<div className="market-head-actions"><Link className="btn" href="/anaira/hotels" target="_blank"><ExternalLink size={15}/> Open Hotel Marketplace</Link><button className="btn primary" onClick={save} disabled={saving}><Save size={15}/>{saving?'Saving…':'Save All Changes'}</button></div>}/>
  <div className="market-control-hero"><div><div className="market-eyebrow"><Hotel size={15}/> GLOBAL HOTEL MARKETPLACE</div><h2>Ultra-premium hotel discovery for the entire ANAIRA network.</h2><p>Global branding, hero media, promotional campaigns and destination cards are platform-owned. Individual hotels keep control of their property master and operational inventory.</p></div><div className="market-hero-metrics"><span><b>GLOBAL</b><small>Store ownership</small></span><span><b>LIVE</b><small>HMS inventory</small></span><span><b>{destinations.length}</b><small>Destinations</small></span></div></div>
  <div className="store-control-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {msg&&<div className="notice success" style={{marginBottom:16}}>{msg}</div>}{error&&<div className="notice error" style={{marginBottom:16}}>{error}</div>}

  {tab==='design'&&<><Section title="Global Hotel Brand System" meta="Premium visual identity for /anaira/hotels. This does not duplicate hotel master data."><div className="card store-settings-grid">
   <label><span>Marketplace title</span><input value={form.hotel_home_title} onChange={e=>set('hotel_home_title',e.target.value)}/></label>
   <label><span>Marketplace subtitle</span><input value={form.hotel_home_subtitle} onChange={e=>set('hotel_home_subtitle',e.target.value)}/></label>
   <label><span>Theme preset</span><select value={form.hotel_home_theme} onChange={e=>set('hotel_home_theme',e.target.value)}><option value="luxury">Luxury Gold</option><option value="forest">Forest Luxury</option><option value="midnight">Midnight</option></select></label>
   <label><span>Primary color</span><input type="color" value={form.hotel_home_primary_color} onChange={e=>set('hotel_home_primary_color',e.target.value)}/></label><label><span>Accent / CTA color</span><input type="color" value={form.hotel_home_accent_color} onChange={e=>set('hotel_home_accent_color',e.target.value)}/></label>
   <label><span>Page background</span><input type="color" value={form.hotel_home_background_color} onChange={e=>set('hotel_home_background_color',e.target.value)}/></label><label><span>Surface color</span><input type="color" value={form.hotel_home_surface_color} onChange={e=>set('hotel_home_surface_color',e.target.value)}/></label><label><span>Text color</span><input type="color" value={form.hotel_home_text_color} onChange={e=>set('hotel_home_text_color',e.target.value)}/></label>
   <label><span>Content max width</span><input type="number" min="980" max="1600" value={form.hotel_home_container_width} onChange={e=>set('hotel_home_container_width',Number(e.target.value))}/></label>
   <label><span>Hotel cards per row</span><select value={form.hotel_home_hotel_columns} onChange={e=>set('hotel_home_hotel_columns',Number(e.target.value))}><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></label>
   <label><span>Destination cards per row</span><select value={form.hotel_home_destination_columns} onChange={e=>set('hotel_home_destination_columns',Number(e.target.value))}><option value="4">4</option><option value="5">5</option><option value="6">6</option></select></label>
   <label><span>Card radius</span><input type="number" min="8" max="40" value={form.hotel_home_card_radius} onChange={e=>set('hotel_home_card_radius',Number(e.target.value))}/></label>
  </div></Section>
  <Section title="Homepage Modules" meta="Turn global marketplace modules on or off without affecting hotel operational systems."><div className="card store-toggle-grid">{[['hotel_marketplace_enabled','Hotel Marketplace enabled'],['hotel_home_show_search','Search & availability search'],['hotel_home_show_banners','Hero & promotions'],['hotel_home_show_destinations','Top destinations'],['hotel_home_show_trust','Trust / booking benefits'],['hotel_home_show_footer','Footer']].map(([k,l])=><label key={k} className="check-field"><input type="checkbox" checked={!!form[k]} onChange={e=>set(k,e.target.checked)}/><span>{l}</span></label>)}</div></Section></>}

  {tab==='hero'&&<><Section title="Ultra HD Hero Media" meta="Upload directly to ANAIRA media storage or paste an external image URL. Desktop and mobile crops are independent."><div className="card store-settings-stack">
   <MarketplaceImageUpload label="Desktop hero image" value={form.hotel_home_hero_image} onChange={v=>set('hotel_home_hero_image',v)} folder="marketplace/hotels/hero"/>
   <MarketplaceImageUpload label="Mobile hero image" value={form.hotel_home_hero_mobile_image} onChange={v=>set('hotel_home_hero_mobile_image',v)} folder="marketplace/hotels/hero-mobile"/>
   <div className="store-settings-grid"><label><span>Overlay strength</span><input type="number" min="0" max="0.9" step="0.05" value={form.hotel_home_hero_overlay} onChange={e=>set('hotel_home_hero_overlay',e.target.value)}/></label><label><span>Hero CTA label</span><input value={form.hotel_home_hero_cta} onChange={e=>set('hotel_home_hero_cta',e.target.value)}/></label><label className="full"><span>Hero CTA URL</span><input value={form.hotel_home_hero_cta_url} onChange={e=>set('hotel_home_hero_cta_url',e.target.value)}/></label></div>
  </div></Section>
  <Section title="Global Hotel Promotional Banners" meta="Campaign banners for the entire ANAIRA Hotels marketplace."><div className="card"><form className="store-settings-stack" onSubmit={addBanner}><div className="store-settings-grid"><label><span>Banner title</span><input value={banner.title} onChange={e=>setBanner({...banner,title:e.target.value})} required/></label><label><span>Subtitle</span><input value={banner.subtitle} onChange={e=>setBanner({...banner,subtitle:e.target.value})}/></label></div><MarketplaceImageUpload label="Desktop banner image" value={banner.image_url} onChange={v=>setBanner({...banner,image_url:v})} folder="marketplace/hotels/banners"/><MarketplaceImageUpload label="Mobile banner image" value={banner.mobile_image_url} onChange={v=>setBanner({...banner,mobile_image_url:v})} folder="marketplace/hotels/banners-mobile"/><div className="store-settings-grid"><label><span>CTA label</span><input value={banner.cta_label} onChange={e=>setBanner({...banner,cta_label:e.target.value})}/></label><label><span>CTA URL</span><input value={banner.cta_url} onChange={e=>setBanner({...banner,cta_url:e.target.value})}/></label><label><span>Display order</span><input type="number" value={banner.display_order} onChange={e=>setBanner({...banner,display_order:e.target.value})}/></label></div><button className="btn primary" type="submit"><ImageIcon size={15}/> Add Global Hotel Banner</button></form><div className="banner-admin-list">{banners.map(b=><article key={b.id}><img src={b.image_url} alt=""/><div><b>{b.title}</b><p>{b.subtitle||'No subtitle'} · order {b.display_order}</p><small>{b.active?'LIVE':'DISABLED'}</small></div><div><button className="btn" onClick={()=>toggleBanner(b)}>{b.active?'Disable':'Enable'}</button><button className="btn" onClick={()=>delBanner(b.id)}>Delete</button></div></article>)}</div></div></Section></>}

  {tab==='destinations'&&<><Section title="Top Destinations — 5 Premium Cards" meta="Super Admin can add destination cards, upload their images, control order and link each card to hotel search. The public marketplace shows five cards in one row on desktop."><div className="card destination-form-card">
   <form className="store-settings-stack" onSubmit={addDestination}>
    <div className="store-settings-grid"><label><span>Destination name</span><input value={destination.name} onChange={e=>setDestination({...destination,name:e.target.value})} placeholder="Manali" required/></label><label><span>Short subtitle</span><input value={destination.subtitle} onChange={e=>setDestination({...destination,subtitle:e.target.value})} placeholder="Mountain escapes"/></label></div>
    <MarketplaceImageUpload label="Destination image" value={destination.image_url} onChange={v=>setDestination({...destination,image_url:v})} folder="marketplace/hotels/destinations"/>
    <MarketplaceImageUpload label="Mobile destination image (optional)" value={destination.mobile_image_url} onChange={v=>setDestination({...destination,mobile_image_url:v})} folder="marketplace/hotels/destinations-mobile"/>
    <div className="store-settings-grid"><label><span>CTA label</span><input value={destination.cta_label} onChange={e=>setDestination({...destination,cta_label:e.target.value})}/></label><label><span>CTA URL (optional)</span><input value={destination.cta_url} onChange={e=>setDestination({...destination,cta_url:e.target.value})} placeholder="/anaira/hotels?destination=Manali"/></label><label><span>Display order</span><input type="number" min="0" value={destination.display_order} onChange={e=>setDestination({...destination,display_order:e.target.value})}/></label></div>
    <button className="btn primary" type="submit"><Plus size={15}/> Add Destination Card</button>
   </form>
  </div></Section>
  <Section title="Published Destination Cards" meta={`${destinations.filter(d=>d.active).length} active · ${destinations.length} total`}><div className="destination-admin-grid">{destinations.map(d=><article className="destination-admin-card" key={d.id}><div className="destination-admin-image">{d.image_url?<img src={d.image_url} alt={d.name}/>:<MapPin size={28}/>}<span>#{Number(d.display_order)+1}</span></div><div className="destination-admin-body"><b>{d.name}</b><p>{d.subtitle||'No subtitle'}</p><div><button className="btn" onClick={()=>toggleDestination(d)}><Power size={13}/>{d.active?'Disable':'Enable'}</button><button className="btn" onClick={()=>delDestination(d.id)}><Trash2 size={13}/>Delete</button></div></div></article>)}</div></Section></>}

  {tab==='layout'&&<Section title="Hotel Discovery Layout" meta="Control the premium marketplace composition and search experience."><div className="card store-section-layout"><div className="layout-preview"><div className="lp-hero">HERO / DESTINATION / DATES / SEARCH</div><div className="lp-row"><div>TOP DESTINATIONS × 5</div><div>TRUST SIGNALS</div></div><div>LIVE HOTEL DISCOVERY GRID</div><div>GLOBAL PROMOTIONS</div></div><div className="store-settings-grid"><label><span>Destination cards per row</span><select value={form.hotel_home_destination_columns} onChange={e=>set('hotel_home_destination_columns',Number(e.target.value))}><option value="4">4 columns</option><option value="5">5 columns</option><option value="6">6 columns</option></select></label><label><span>Destination section title</span><input value={form.hotel_home_destination_title} onChange={e=>set('hotel_home_destination_title',e.target.value)}/></label><label><span>Destination section subtitle</span><input value={form.hotel_home_destination_subtitle} onChange={e=>set('hotel_home_destination_subtitle',e.target.value)}/></label><label><span>Hotel cards per row</span><select value={form.hotel_home_hotel_columns} onChange={e=>set('hotel_home_hotel_columns',Number(e.target.value))}><option value="2">2 columns</option><option value="3">3 columns</option><option value="4">4 columns</option></select></label><label><span>Container width</span><input type="number" min="980" max="1600" value={form.hotel_home_container_width} onChange={e=>set('hotel_home_container_width',Number(e.target.value))}/></label><label><span>Card radius</span><input type="number" min="8" max="40" value={form.hotel_home_card_radius} onChange={e=>set('hotel_home_card_radius',Number(e.target.value))}/></label></div></div></Section>}

  {tab==='rules'&&<Section title="Hotel Marketplace Governance" meta="Global marketplace policy. Individual hotel stores remain under their Business Admin scope."><div className="card store-settings-grid"><label className="check-field"><input type="checkbox" checked={!!form.hotel_marketplace_enabled} onChange={e=>set('hotel_marketplace_enabled',e.target.checked)}/><span>Hotel Marketplace enabled</span></label><label className="check-field"><input type="checkbox" checked={!!form.hotel_require_listing_approval} onChange={e=>set('hotel_require_listing_approval',e.target.checked)}/><span>Require hotel listing approval</span></label><label className="check-field"><input type="checkbox" checked={!!form.hotel_featured_enabled} onChange={e=>set('hotel_featured_enabled',e.target.checked)}/><span>Featured hotels enabled</span></label><label><span>Marketplace payment mode</span><select value={form.hotel_marketplace_payment_mode} onChange={e=>set('hotel_marketplace_payment_mode',e.target.value)}><option value="platform">Platform</option><option value="direct">Direct to hotel</option><option value="hybrid">Hybrid</option></select></label></div></Section>}

  {tab==='seo'&&<Section title="Hotel Marketplace SEO & Footer" meta="Global metadata controlled by Super Admin."><div className="card store-settings-grid"><label><span>SEO title</span><input value={form.hotel_home_meta_title} onChange={e=>set('hotel_home_meta_title',e.target.value)}/></label><label><span>Footer text</span><input value={form.hotel_home_footer_text} onChange={e=>set('hotel_home_footer_text',e.target.value)}/></label><label className="full"><span>SEO description</span><textarea rows="4" value={form.hotel_home_meta_description} onChange={e=>set('hotel_home_meta_description',e.target.value)}/></label></div></Section>}

  <div className="store-control-footer"><b>Ownership boundary:</b> Super Admin controls the global hotel marketplace. Business Admin controls only the individual hotel's customer-facing store. PMS owns rooms, rates, inventory, availability and bookings. <Link href="/anaira/hotels" target="_blank">Preview global hotel store ↗</Link></div>
 </AppShell>
}
