import {db} from '../../../../lib/server/provider';
export const runtime='nodejs';
async function send(job,customer){const phone=customer?.phone,email=customer?.email;const body=job.message||`We'd love your feedback: ${job.review_url}`;if(job.channel==='whatsapp'){const token=process.env.WHATSAPP_ACCESS_TOKEN,id=process.env.WHATSAPP_PHONE_NUMBER_ID;if(!token||!id)throw new Error('WhatsApp Cloud API credentials not configured');if(!phone)throw new Error('Customer phone is missing');const r=await fetch(`https://graph.facebook.com/v22.0/${id}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:phone.replace(/\D/g,''),type:'text',text:{body}})});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'WhatsApp send failed');return {provider:'meta_whatsapp',provider_message_id:j.messages?.[0]?.id||null,response:j};}
 if(job.channel==='sms'){if(!phone)throw new Error('Customer phone is missing');if(process.env.TWILIO_ACCOUNT_SID&&process.env.TWILIO_AUTH_TOKEN&&process.env.TWILIO_FROM){const auth=Buffer.from(`${process.env.TWILIO_ACCOUNT_SID}:${process.env.TWILIO_AUTH_TOKEN}`).toString('base64');const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${process.env.TWILIO_ACCOUNT_SID}/Messages.json`,{method:'POST',headers:{Authorization:`Basic ${auth}`,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({From:process.env.TWILIO_FROM,To:phone,Body:body})});const j=await r.json();if(!r.ok)throw new Error(j.message||'Twilio SMS failed');return {provider:'twilio',provider_message_id:j.sid,response:j};}if(process.env.CRM_SMS_WEBHOOK_URL){const r=await fetch(process.env.CRM_SMS_WEBHOOK_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({to:phone,body,job})});if(!r.ok)throw new Error('SMS provider rejected request');return {provider:'webhook'};}throw new Error('SMS provider credentials not configured');}
 if(job.channel==='email'){if(!email)throw new Error('Customer email is missing');if(process.env.RESEND_API_KEY){const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from:process.env.RESEND_FROM,to:[email],subject:'We value your feedback',text:body})});const j=await r.json();if(!r.ok)throw new Error(j.message||'Email send failed');return {provider:'resend',provider_message_id:j.id,response:j};}if(process.env.CRM_EMAIL_WEBHOOK_URL){const r=await fetch(process.env.CRM_EMAIL_WEBHOOK_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({to:email,body,job})});if(!r.ok)throw new Error('Email provider rejected request');return {provider:'webhook'};}throw new Error('Email provider credentials not configured');}
 throw new Error(`Unsupported channel: ${job.channel}`)}
function authorize(req){const secret=process.env.CRON_SECRET;if(!secret)throw new Error('CRON_SECRET is not configured');const h=req.headers.get('authorization')||'';if(h!==`Bearer ${secret}`)throw new Error('Unauthorized cron request')}

export async function POST(req){try{authorize(req);const s=db();const now=new Date().toISOString();const {data:jobs,error}=await s.from('crm_review_request_jobs').select('*').in('status',['queued','retry']).lte('due_at',now).lte('next_attempt_at',now).lt('attempts',5).limit(50);if(error)throw error;let sent=0,failed=0;for(const j of jobs||[]){const claim=await s.from('crm_review_request_jobs').update({status:'processing',attempts:(j.attempts||0)+1}).eq('id',j.id).in('status',['queued','retry']).select().maybeSingle();if(!claim.data)continue;try{if(j.consent_required&&!j.consent_verified)throw new Error('Customer communication consent not verified');const {data:customer}=await s.from('crm_customers').select('phone,email,full_name').eq('id',j.customer_id).maybeSingle();const result=await send(j,customer);await s.from('crm_review_request_jobs').update({status:'sent',sent_at:new Date().toISOString(),last_error:null,provider:result.provider}).eq('id',j.id);await s.from('crm_review_delivery_log').insert({tenant_id:j.tenant_id,job_id:j.id,channel:j.channel,provider:result.provider,provider_message_id:result.provider_message_id||null,status:'sent',attempt:(j.attempts||0)+1,response:result.response||{}});sent++;}catch(e){const attempts=(j.attempts||0)+1;const dead=attempts>=5;const next=new Date(Date.now()+Math.min(86400000,Math.pow(2,attempts)*300000)).toISOString();await s.from('crm_review_request_jobs').update({status:dead?'dead_letter':'retry',attempts,last_error:e.message,next_attempt_at:next}).eq('id',j.id);await s.from('crm_review_delivery_log').insert({tenant_id:j.tenant_id,job_id:j.id,channel:j.channel,status:dead?'dead_letter':'failed',attempt:attempts, error:e.message});failed++;}}return Response.json({ok:true,sent,failed})}catch(e){return Response.json({ok:false,error:e.message},{status:500})}}

export async function GET(req){ return POST(req); }
