'use client';
import {useEffect,useMemo,useState} from 'react';
import {Section} from '../../components';
import {useTenantProperty,SetupHeader,SetupShell,Field,SelectField,SetupNav,ensureSelected} from '../setup-components';
import {supabase} from '../../../lib/supabase';
import MediaPicker from '../../../components/anaira/MediaPicker';

const defaults={hotel_name:'',short_name:'',legal_name:'',star_rating:'',phone:'',whatsapp:'',email:'',website:'',address:'',landmark:'',city:'',state:'',country:'India',postal_code:'',latitude:'',longitude:'',currency:'INR',timezone:'Asia/Kolkata',check_in_time:'12:00',check_out_time:'11:00',tax_percent:0,logo_url:'',cover_image_url:'',gallery:[],description:'',early_checkin_policy:'',late_checkout_policy:'',cancellation_policy:'',child_policy:'',pet_policy:'',smoking_policy:'',booking_engine_enabled:false,crm_integration_enabled:true};
const required=['hotel_name','phone','email','address','city','state','country','postal_code','currency','timezone','check_in_time','check_out_time'];
export default function HotelSetup(){
 const ctx=useTenantProperty(); const [rid,setRid]=useState(null); const [form,setForm]=useState(defaults); const [msg,setMsg]=useState(''); const [error,setError]=useState(''); const [saving,setSaving]=useState(false); const id=ensureSelected(ctx,rid);
 useEffect(()=>{if(!id)return;(async()=>{setMsg('');setError('');const {data,error}=await supabase.from('hms_settings').select('*').eq('restaurant_id',id).maybeSingle();if(error){setError(error.message);return}setForm({...defaults,...(data||{}),star_rating:data?.star_rating??'',tax_percent:data?.tax_percent??0, gallery:Array.isArray(data?.gallery)?data.gallery:[]});})()},[id]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 const missing=useMemo(()=>required.filter(k=>!String(form[k]??'').trim()),[form]);
 const completeness=Math.round(((required.length-missing.length)/required.length)*100);
 async function save(e){e.preventDefault();setMsg('');setError('');if(!id){setError('Select a property first.');return}if(missing.length){setError(`Complete required property fields: ${missing.map(k=>k.replaceAll('_',' ')).join(', ')}.`);return}const lat=form.latitude===''?null:Number(form.latitude),lng=form.longitude===''?null:Number(form.longitude),tax=Number(form.tax_percent||0),stars=form.star_rating===''?null:Number(form.star_rating);if(Number.isNaN(lat)||Number.isNaN(lng)||Number.isNaN(tax)||Number.isNaN(stars)){setError('Latitude, longitude, star rating and tax must be valid numbers.');return}if(lat!==null&&(lat<-90||lat>90)||lng!==null&&(lng<-180||lng>180)){setError('Latitude must be -90 to 90 and longitude -180 to 180.');return}if(tax<0||tax>100||stars!==null&&(stars<0||stars>5)){setError('Tax must be 0–100% and star rating must be 0–5.');return}setSaving(true);const payload={...form,restaurant_id:id,latitude:lat,longitude:lng,tax_percent:tax,star_rating:stars,gallery:Array.isArray(form.gallery)?form.gallery:[]};delete payload.id;delete payload.created_at;delete payload.updated_at;const {error:e2}=await supabase.from('hms_settings').upsert(payload,{onConflict:'restaurant_id'});setSaving(false);if(e2)setError(e2.message);else setMsg('Hotel property profile saved successfully.');}
 return <SetupShell active="/hotel-management" title="Hotel Property" subtitle="Business Admin property master: identity, contact, location, policies, media and booking settings." ctx={ctx}>
  <SetupHeader title="Hotel Property" subtitle="Property master data" ctx={ctx} rid={rid} setRid={setRid} actions={<span className="pill">Profile {completeness}% complete</span>}/>
  {!id?<div className="notice">Select a property to configure the hotel.</div>:<>
   <Section title="Property Identity" meta="Business Admin master data"><form className="card admin-form" onSubmit={save}>
    <Field label="Hotel Name *" value={form.hotel_name} onChange={v=>set('hotel_name',v)}/><Field label="Short Name" value={form.short_name} onChange={v=>set('short_name',v)}/><Field label="Legal Name" value={form.legal_name} onChange={v=>set('legal_name',v)}/><SelectField label="Star Rating" value={form.star_rating} onChange={v=>set('star_rating',v)} options={[['','Not specified'],['1','1 Star'],['2','2 Star'],['3','3 Star'],['4','4 Star'],['5','5 Star']]}/>
    <Field label="Description" value={form.description} onChange={v=>set('description',v)} full/>
    <Section title="Contact & Location" meta="Used by booking, marketplace and guest communication"><Field label="Phone *" value={form.phone} onChange={v=>set('phone',v)}/><Field label="WhatsApp" value={form.whatsapp} onChange={v=>set('whatsapp',v)}/><Field label="Email *" value={form.email} onChange={v=>set('email',v)} type="email"/><Field label="Website" value={form.website} onChange={v=>set('website',v)}/><Field label="Address *" value={form.address} onChange={v=>set('address',v)} full/><Field label="Landmark" value={form.landmark} onChange={v=>set('landmark',v)}/><Field label="City *" value={form.city} onChange={v=>set('city',v)}/><Field label="State *" value={form.state} onChange={v=>set('state',v)}/><Field label="Country *" value={form.country} onChange={v=>set('country',v)}/><Field label="PIN / Postal Code *" value={form.postal_code} onChange={v=>set('postal_code',v)}/><Field label="Latitude" value={form.latitude} onChange={v=>set('latitude',v)} type="number"/><Field label="Longitude" value={form.longitude} onChange={v=>set('longitude',v)} type="number"/></Section>
    <Section title="Operations & Tax" meta="Core property defaults"><Field label="Currency *" value={form.currency} onChange={v=>set('currency',v)}/><Field label="Timezone *" value={form.timezone} onChange={v=>set('timezone',v)}/><Field label="Check-in *" value={form.check_in_time||'12:00'} onChange={v=>set('check_in_time',v)} type="time"/><Field label="Check-out *" value={form.check_out_time||'11:00'} onChange={v=>set('check_out_time',v)} type="time"/><Field label="GST / Tax %" value={form.tax_percent} onChange={v=>set('tax_percent',v)} type="number"/></Section>
    <Section title="Policies" meta="Shown during booking and used by operations"><Field label="Early Check-in Policy" value={form.early_checkin_policy} onChange={v=>set('early_checkin_policy',v)} full/><Field label="Late Checkout Policy" value={form.late_checkout_policy} onChange={v=>set('late_checkout_policy',v)} full/><Field label="Cancellation Policy" value={form.cancellation_policy} onChange={v=>set('cancellation_policy',v)} full/><Field label="Child Policy" value={form.child_policy} onChange={v=>set('child_policy',v)} full/><Field label="Pet Policy" value={form.pet_policy} onChange={v=>set('pet_policy',v)} full/><Field label="Smoking Policy" value={form.smoking_policy} onChange={v=>set('smoking_policy',v)} full/></Section>
    <Section title="Branding & Media" meta="Real Supabase media library"><MediaPicker value={form.logo_url} restaurantId={id} folder="hotel/logo" label="Hotel Logo" onChange={v=>set('logo_url',v)}/><MediaPicker value={form.cover_image_url} restaurantId={id} folder="hotel/cover" label="Hotel Cover" onChange={v=>set('cover_image_url',v)}/><div style={{gridColumn:'1/-1'}}><MediaPicker value={form.gallery} multiple restaurantId={id} folder="hotel/gallery" label="Hotel Gallery" onChange={v=>set('gallery',v)}/></div></Section>
    <Section title="Booking & CRM" meta="Property-level feature switches"><div className="full" style={{display:'flex',gap:18,flexWrap:'wrap'}}><label><input type="checkbox" checked={!!form.booking_engine_enabled} onChange={e=>set('booking_engine_enabled',e.target.checked)}/> Direct Booking Engine</label><label><input type="checkbox" checked={!!form.crm_integration_enabled} onChange={e=>set('crm_integration_enabled',e.target.checked)}/> CRM Integration</label></div></Section>
    <div className="full"><button className="btn primary" disabled={saving}>{saving?'Saving…':'Save Property Profile'}</button>{msg&&<span style={{marginLeft:10,fontSize:11}}>{msg}</span>}{error&&<div className="notice error" style={{marginTop:10}}>{error}</div>}</div>
   </form></Section>
   <SetupNav/>
  </>}
 </SetupShell>
}
