'use client';
import {useEffect,useMemo,useState} from 'react';
import {useParams,useSearchParams} from 'next/navigation';

export default function MultiRoomBooking(){
 const params=useParams(); const id=params?.id; const search=useSearchParams();
 const [hotel,setHotel]=useState(null),[rooms,setRooms]=useState([]),[items,setItems]=useState([]),[f,setF]=useState({name:'',phone:'',email:'',checkIn:search.get('check_in')||'',checkOut:search.get('check_out')||''});
 const [verify,setVerify]=useState({id:null,otp:'',sent:false,verified:false}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState(null);
 useEffect(()=>{if(!id)return;(async()=>{try{const r=await fetch(`/api/public/booking/hotel/${id}`);const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||'Hotel not found');setHotel(x.hotel);setRooms(x.rooms||[])}catch(e){setMsg(e.message)}})()},[id]);
 const add=(r)=>setItems(a=>{const found=a.find(x=>x.room_type_id===r.id&&x.rate_plan_id===r.rates?.[0]?.id);if(found)return a.map(x=>x===found?{...x,quantity:(x.quantity||1)+1}:x);const rate=r.rates?.[0];return rate?[...a,{room_type_id:r.id,rate_plan_id:rate.id,adults:Math.max(1,Number(r.max_adults||2)),children:0,quantity:1}]:a});
 const payloadRooms=useMemo(()=>items.flatMap(x=>Array.from({length:x.quantity||1},()=>({room_type_id:x.room_type_id,rate_plan_id:x.rate_plan_id,adults:x.adults,children:x.children,addons:[]}))),[items]);
 async function sendOtp(){setBusy(true);try{const r=await fetch('/api/hotel/guest-otp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tenant_id:id,channel:'phone',phone:f.phone})});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||'OTP failed');setVerify(v=>({...v,id:x.verification_id,sent:true}));setMsg(`OTP sent to ${x.destination_masked||'your phone'}.`)}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function confirmOtp(){setBusy(true);try{const r=await fetch('/api/hotel/guest-otp',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({verification_id:verify.id,channel:'phone',phone:f.phone,otp:verify.otp})});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||'Invalid OTP');setVerify(v=>({...v,verified:true}));setMsg('Phone verified.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function submit(e){e.preventDefault();if(!verify.verified)return setMsg('Verify the guest phone first.');if(!payloadRooms.length)return setMsg('Add at least one room.');setBusy(true);try{const r=await fetch('/api/public/booking/multi-room',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({hotel_id:id,guest_name:f.name,phone:f.phone,email:f.email,check_in:f.checkIn,check_out:f.checkOut,rooms:payloadRooms,verification_id:verify.id,idempotency_key:`multi:${id}:${f.phone}:${f.checkIn}:${f.checkOut}`})});const x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||'Multi-room booking failed');setResult(x);setMsg('Multi-room reservation created and inventory held. Continue to payment from the booking reference.')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <main style={{minHeight:'100vh',background:'#f6f1e9',padding:40,fontFamily:'system-ui'}}><form onSubmit={submit} style={{maxWidth:1000,margin:'0 auto',background:'#fff',padding:32,borderRadius:24}}><small style={{letterSpacing:2,color:'#8b5c32',fontWeight:800}}>ANAIRA • MULTI-ROOM BOOKING</small><h1 style={{font:'500 42px Georgia,serif'}}>Book multiple rooms</h1><p>{hotel?.name||'Loading property…'} · Select rooms, verify the guest and create one master reservation.</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}>{[['name','Guest name'],['phone','Mobile'],['email','Email']].map(([k,l])=><label key={k}>{l}<input required={k!=='email'} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}<label>Check-in<input required type="date" value={f.checkIn} onChange={e=>setF({...f,checkIn:e.target.value})}/></label><label>Check-out<input required type="date" value={f.checkOut} onChange={e=>setF({...f,checkOut:e.target.value})}/></label></div><h2>Rooms</h2><div style={{display:'grid',gap:10}}>{rooms.map(r=><div key={r.id} style={{display:'flex',justifyContent:'space-between',gap:12,padding:14,border:'1px solid #e5d9cb',borderRadius:14}}><div><b>{r.name}</b><div>{r.rates?.[0]?.name||'Rate plan'} · ₹{Number(r.rates?.[0]?.rate||0).toLocaleString('en-IN')}/night</div></div><button type="button" onClick={()=>add(r)}>+ Add room</button></div>)}</div><p>Rooms selected: <b>{payloadRooms.length}</b></p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button type="button" onClick={sendOtp} disabled={busy||!f.phone}>Send OTP</button>{verify.sent&&!verify.verified&&<><input value={verify.otp} onChange={e=>setVerify({...verify,otp:e.target.value})} placeholder="OTP"/><button type="button" onClick={confirmOtp} disabled={busy||!verify.otp}>Verify</button></>}{verify.verified&&<b style={{color:'#28734b'}}>✓ Verified</b>}</div><button disabled={busy||!payloadRooms.length} style={{marginTop:18,padding:14,border:0,borderRadius:10,background:'#8b5c32',color:'#fff',fontWeight:900}}>{busy?'Processing…':'Create multi-room booking'}</button>{msg&&<div style={{marginTop:14,padding:12,background:'#faf5ed',borderRadius:10}}>{msg}</div>}{result&&<pre style={{whiteSpace:'pre-wrap',background:'#f6f1e9',padding:14,borderRadius:10}}>{JSON.stringify(result,null,2)}</pre>}</form></main>
}
