import { requireTenant } from '../../../../lib/server/auth';
import { db } from '../../../../lib/server/provider';
export const runtime='nodejs';
async function send(job){
  const p=job.payload||{}, channel=String(job.channel||'').toLowerCase();
  if(channel==='in_app')return {provider:'anaira',provider_message_id:job.id};
  if(channel==='whatsapp'){const token=process.env.WHATSAPP_ACCESS_TOKEN,phoneId=process.env.WHATSAPP_PHONE_NUMBER_ID;if(!token||!phoneId)throw new Error('WhatsApp provider credentials are not configured.');const r=await fetch(`https://graph.facebook.com/v22.0/${phoneId}/messages`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',to:String(p.phone||'').replace(/\D/g,''),type:'text',text:{body:p.body||p.message||''}})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error?.message||'WhatsApp send failed');return {provider:'whatsapp',provider_message_id:j.messages?.[0]?.id||null};}
  if(channel==='email'){if(!process.env.RESEND_API_KEY||!process.env.RESEND_FROM)throw new Error('Email provider credentials are not configured.');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.RESEND_FROM,to:[p.email],subject:p.subject||'Message from Anaira',text:p.body||p.message||''})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'Email send failed');return {provider:'resend',provider_message_id:j.id||null};}
  if(channel==='sms'){if(!process.env.TWILIO_ACCOUNT_SID||!process.env.TWILIO_AUTH_TOKEN||!process.env.TWILIO_FROM)throw new Error('SMS provider credentials are not configured.');const auth=Buffer.from(`${process.env.TWILIO_ACCOUNT_SID}:${process.env.TWILIO_AUTH_TOKEN}`).toString('base64');const r=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${process.env.TWILIO_ACCOUNT_SID}/Messages.json`,{method:'POST',headers:{Authorization:`Basic ${auth}`,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({From:process.env.TWILIO_FROM,To:p.phone,Body:p.body||p.message||''})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.message||'SMS send failed');return {provider:'twilio',provider_message_id:j.sid||null};}
  throw new Error(`Unsupported campaign channel: ${channel}`);
}
export async function POST(req){
  try{
    const body=await req.json().catch(()=>({}));const tenantId=String(body.tenantId||'');const {user}=await requireTenant(req,tenantId);const s=db(req.headers.get('authorization')?.slice(7));
    const {data:jobs,error}=await s.from('crm_campaign_queue').select('*').eq('tenant_id',tenantId).eq('status','queued').lte('available_at',new Date().toISOString()).order('created_at',{ascending:true}).limit(25);if(error)throw error;
    let sent=0,failed=0;for(const job of (jobs||[])){const claim=await s.from('crm_campaign_queue').update({status:'processing'}).eq('id',job.id).eq('tenant_id',tenantId).eq('status','queued');if(claim.error)continue;try{const r=await send(job);await s.from('crm_campaign_queue').update({status:'sent',sent_at:new Date().toISOString(),payload:{...(job.payload||{}),provider:r}}).eq('id',job.id).eq('tenant_id',tenantId);
      if(job.recipient_id){await s.from('crm_campaign_recipients').update({status:'sent',sent_at:new Date().toISOString()}).eq('id',job.recipient_id).eq('tenant_id',tenantId);await s.from('crm_campaign_attribution').insert({tenant_id:tenantId,property_id:job.property_id||null,campaign_id:job.campaign_id,customer_id:job.customer_id||null,recipient_id:job.recipient_id,event_type:'sent',revenue:0,reference_type:'campaign_queue',reference_id:job.id});}
      sent++;}catch(e){failed++;await s.from('crm_campaign_queue').update({status:Number(job.attempts||0)>=5?'failed':'queued',available_at:new Date(Date.now()+Math.min(3600000,2**Number(job.attempts||0)*60000)).toISOString(),last_error:e.message,attempts:Number(job.attempts||0)+1}).eq('id',job.id).eq('tenant_id',tenantId);if(job.recipient_id)await s.from('crm_campaign_recipients').update({status:Number(job.attempts||0)>=5?'failed':'queued'}).eq('id',job.recipient_id).eq('tenant_id',tenantId);}}
    await s.from('crm_audit_logs').insert({tenant_id:tenantId,actor_id:user.id,entity_type:'campaign_worker',action:'manual_run',after_data:{claimed:(jobs||[]).length,sent,failed}});
    return Response.json({ok:true,claimed:(jobs||[]).length,sent,failed});
  }catch(e){return Response.json({ok:false,error:e.message},{status:400});}
}
