import crypto from 'node:crypto';
import {createClient} from '@supabase/supabase-js';
const url=()=>process.env.NEXT_PUBLIC_SUPABASE_URL||"https://bhptqdoteucuymmdzsmg.supabase.co";
const publicKey=()=>process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||"sb_publishable_H5-rIfJOSp7kibp8oXsqow_-vDpdrRd";
export const db=(accessToken=null)=>{const serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY;const key=serviceKey||publicKey();if(!key)throw new Error('Server Supabase credentials are not configured.');const opts={auth:{persistSession:false,autoRefreshToken:false}};if(!serviceKey&&accessToken)opts.global={headers:{Authorization:`Bearer ${accessToken}`}};return createClient(url(),key,opts)};
const key=()=>{const v=process.env.ANAIRA_SECRET_KEY||process.env.ANAIRA_SECRET;if(!v)throw new Error('ANAIRA_SECRET_KEY is required for provider token encryption');return crypto.createHash('sha256').update(v).digest()};
export const seal=v=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv);const enc=Buffer.concat([c.update(String(v),'utf8'),c.final()]);return [iv.toString('base64'),c.getAuthTag().toString('base64'),enc.toString('base64')].join('.')};
export const open=v=>{const [i,t,e]=String(v).split('.');const d=crypto.createDecipheriv('aes-256-gcm',key(),Buffer.from(i,'base64'));d.setAuthTag(Buffer.from(t,'base64'));return Buffer.concat([d.update(Buffer.from(e,'base64')),d.final()]).toString('utf8')};
export async function googleToken(refreshToken){const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,refresh_token:refreshToken,grant_type:'refresh_token'})});const j=await r.json();if(!r.ok)throw new Error(j.error_description||'Google token refresh failed');return j.access_token;}
