import {db} from '../../../../lib/server/provider';
import {requireSeoFeature} from '../../../../lib/server/seoRuntime';
export async function GET(req){try{const siteId=new URL(req.url).searchParams.get('siteId');await requireSeoFeature(req,siteId,null,'seo-system.view');const s=db();const [t,a,o,h,j,p,k,r]=await Promise.all([
 s.from('crm_seo_tasks').select('id,status,priority,approval_required').eq('site_id',siteId),
 s.from('crm_seo_alerts').select('id,status,severity').eq('site_id',siteId),
 s.from('crm_seo_operation_jobs').select('id,status,job_type,attempt,error_message,scheduled_at,started_at,finished_at').eq('site_id',siteId).order('created_at',{ascending:false}).limit(50),
 s.from('crm_seo_history').select('*').eq('site_id',siteId).order('created_at',{ascending:false}).limit(50),
 s.from('crm_seo_automation_jobs').select('*').eq('site_id',siteId),
 s.from('crm_seo_pages').select('id').eq('site_id',siteId),
 s.from('crm_seo_keywords').select('id').eq('site_id',siteId).eq('active',true),
 s.from('crm_seo_issues').select('id,status,severity').eq('site_id',siteId)
 ]);for(const x of [t,a,o,h,j,p,k,r])if(x.error)throw x.error;return Response.json({ok:true,summary:{tasks:t.data||[],alerts:a.data||[],operations:o.data||[],history:h.data||[],automation:j.data||[],pages:p.data?.length||0,keywords:k.data?.length||0,issues:r.data||[]}})}catch(e){return Response.json({ok:false,error:e.message},{status:400})}}
export async function POST(req){try{const b=await req.json(),siteId=b.siteId;await requireSeoFeature(req,siteId,null,'seo-system.manage');const s=db();if(b.action==='create-task'){const {data,error}=await s.from('crm_seo_tasks').insert({site_id:siteId,issue_id:b.issue_id||null,title:b.title,description:b.description||null,task_type:b.task_type||'seo_fix',priority:b.priority||'normal',approval_required:Boolean(b.approval_required),source:b.source||'control-plane',recommendation:b.recommendation||{},action:b.action_payload||{}}).select().single();if(error)throw error;return Response.json({ok:true,task:data})}if(b.action==='enqueue'){const {data,error}=await s.from('crm_seo_operation_jobs').insert({site_id:siteId,job_type:b.job_type||'manual',priority:Number(b.priority)||100,payload:b.payload||{}}).select().single();if(error)throw error;return Response.json({ok:true,job:data})}if(b.action==='alert'){const {data,error}=await s.from('crm_seo_alerts').insert({site_id:siteId,alert_type:b.alert_type||'manual',severity:b.severity||'warning',title:b.title||'SEO alert',message:b.message||'',source:b.source||'control-plane',payload:b.payload||{}}).select().single();if(error)throw error;return Response.json({ok:true,alert:data})}throw new Error('Unsupported control-plane action')}catch(e){return Response.json({ok:false,error:e.message},{status:400})}}
