'use client';
import {useEffect,useMemo,useState} from 'react';
import {AppShell,Header,Section,Table,Kpi,Pill} from '../components';
import {supabase} from '../../lib/supabase';

const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const fmt=v=>v?new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—';
const short=v=>v?String(v).slice(0,8):'—';

function ActionForm({title,children,onSubmit,busy}){
 return <form onSubmit={onSubmit} className="card" style={{marginBottom:16}}>
   <h3>{title}</h3>{children}<button className="btn primary" disabled={busy} type="submit">{busy?'Saving…':'Save'}</button>
 </form>;
}
const Field=({label,...p})=><label style={{display:'grid',gap:5,marginBottom:10}}><span>{label}</span><input className="input" {...p}/></label>;
const Select=({label,children,...p})=><label style={{display:'grid',gap:5,marginBottom:10}}><span>{label}</span><select className="input" {...p}>{children}</select></label>;

export default function RestaurantCRM(){
 const [session,setSession]=useState(null),[properties,setProperties]=useState([]),[propertyId,setPropertyId]=useState(''),[tenant,setTenant]=useState('');
 const [customers,setCustomers]=useState([]),[visits,setVisits]=useState([]),[reservations,setReservations]=useState([]),[metrics,setMetrics]=useState([]);
 const [complaints,setComplaints]=useState([]),[reviews,setReviews]=useState([]),[feedback,setFeedback]=useState([]),[loyalty,setLoyalty]=useState([]),[churn,setChurn]=useState([]);
 const [prefs,setPrefs]=useState([]),[foodPrefs,setFoodPrefs]=useState([]),[tasks,setTasks]=useState([]),[requests,setRequests]=useState([]),[offers,setOffers]=useState([]);
 const [campaigns,setCampaigns]=useState([]),[messages,setMessages]=useState([]),[timeline,setTimeline]=useState([]),[segments,setSegments]=useState([]),[coupons,setCoupons]=useState([]),[vip,setVip]=useState([]),[orderEvents,setOrderEvents]=useState([]),[aiInsights,setAiInsights]=useState([]),[automationJobs,setAutomationJobs]=useState([]),[campaignJobs,setCampaignJobs]=useState([]);
 const [q,setQ]=useState(''),[tab,setTab]=useState('dashboard'),[selected,setSelected]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const property=useMemo(()=>properties.find(p=>p.id===propertyId)||null,[properties,propertyId]);
 const customerMap=useMemo(()=>Object.fromEntries(customers.map(c=>[c.id,c])),[customers]);
 const selectedCustomer=customerMap[selected]||null;
 const filteredCustomers=useMemo(()=>{const s=q.toLowerCase();return customers.filter(c=>`${c.full_name||''} ${c.phone||''} ${c.email||''}`.toLowerCase().includes(s))},[customers,q]);

 const load=async()=>{
  if(!tenant||!propertyId)return;setError('');setNotice('');
  const Q=[
   supabase.from('crm_customers').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('updated_at',{ascending:false}).limit(1000),
   supabase.from('crm_restaurant_visits').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('visit_at',{ascending:false}).limit(1000),
   supabase.from('crm_restaurant_customer_metrics').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).limit(1000),
   supabase.from('crm_complaints').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('opened_at',{ascending:false}).limit(500),
   supabase.from('crm_reviews').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('created_at',{ascending:false}).limit(500),
   supabase.from('crm_feedback').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('created_at',{ascending:false}).limit(500),
   supabase.from('crm_loyalty_accounts').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).limit(1000),
   supabase.from('crm_churn_scores').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).limit(1000),
   supabase.from('restaurant_reservations').select('*').eq('restaurant_id',tenant).eq('property_id',propertyId).order('reservation_date',{ascending:false}).limit(1000),
   supabase.from('crm_customer_preferences').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('created_at',{ascending:false}).limit(1000),
   supabase.from('crm_food_preferences').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('last_seen_at',{ascending:false}).limit(1000),
   supabase.from('crm_tasks').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('created_at',{ascending:false}).limit(500),
   supabase.from('crm_guest_requests').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('requested_at',{ascending:false}).limit(500),
   supabase.from('crm_commercial_offers').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('created_at',{ascending:false}).limit(500),
   supabase.from('crm_campaigns').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('created_at',{ascending:false}).limit(200),
   supabase.from('crm_message_log').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('created_at',{ascending:false}).limit(500),
   supabase.from('crm_timeline_events').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('occurred_at',{ascending:false}).limit(1000),
   supabase.from('crm_segments').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('created_at',{ascending:false}).limit(200),
   supabase.from('crm_coupon_definitions').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('created_at',{ascending:false}).limit(200),
   supabase.from('crm_vip_profiles').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).limit(500),
   supabase.from('crm_restaurant_order_events').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('created_at',{ascending:false}).limit(1000),
   supabase.from('crm_ai_insights').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('created_at',{ascending:false}).limit(500),
   supabase.from('crm_restaurant_automation_jobs').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('created_at',{ascending:false}).limit(500),
   supabase.from('crm_restaurant_campaign_jobs').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('created_at',{ascending:false}).limit(200)
  ];
  const rs=await Promise.all(Q); const bad=rs.find(x=>x.error); if(bad)setError(bad.error.message);
  const d=rs.map(x=>x.data||[]);
  [setCustomers,setVisits,setMetrics,setComplaints,setReviews,setFeedback,setLoyalty,setChurn,setReservations,setPrefs,setFoodPrefs,setTasks,setRequests,setOffers,setCampaigns,setMessages,setTimeline,setSegments,setCoupons,setVip,setOrderEvents,setAiInsights,setAutomationJobs,setCampaignJobs].forEach((fn,i)=>fn(d[i]));
 };
 useEffect(()=>{(async()=>{const {data:{session:s}}=await supabase.auth.getSession();setSession(s);if(!s)return;
   const p=await supabase.from('anaira_my_profile').select('restaurant_id').eq('id',s.user.id).maybeSingle();
   const props=await supabase.from('anaira_hospitality_properties_master').select('id,tenant_id,property_type,name,destination,city,active').eq('active',true).order('name');
   if(props.error){setError(props.error.message);return} const list=props.data||[];setProperties(list);
   const requested=new URLSearchParams(location.search).get('property');
   const chosen=list.find(x=>x.id===requested)||list.find(x=>x.tenant_id===p.data?.restaurant_id)||list[0];
   if(chosen){setPropertyId(chosen.id);setTenant(chosen.tenant_id)}
 })()},[]);
 useEffect(()=>{if(tenant&&propertyId)load()},[tenant,propertyId]);
 const switchProperty=id=>{const p=properties.find(x=>x.id===id);if(!p)return;setPropertyId(id);setTenant(p.tenant_id);const u=new URL(location.href);u.searchParams.set('property',id);history.replaceState({},'',u)};
 const action=async(actionType,customerId,payload={})=>{
   setBusy(true);setError('');setNotice('');
   try{const {data,error}=await supabase.rpc('anaira_restaurant_crm_action',{p_tenant_id:tenant,p_property_id:propertyId,p_action:actionType,p_customer_id:customerId||null,p_payload:payload});
     if(error)throw error;setNotice(`${actionType.replaceAll('_',' ')} completed`);await load();return data;
   }catch(e){setError(e.message||'Action failed');throw e}finally{setBusy(false)}
 };
 const submit=fn=>async e=>{e.preventDefault();await fn(e.currentTarget)};
 const totalSpend=metrics.reduce((n,x)=>n+Number(x.lifetime_spend||0),0),avgBill=visits.length?visits.reduce((n,x)=>n+Number(x.amount||0),0)/visits.length:0;
 const repeat=metrics.filter(x=>Number(x.total_visits||0)>1).length,vipCount=customers.filter(x=>x.vip).length,highChurn=churn.filter(x=>x.risk_level==='high').length;
 if(!session)return <AppShell><div className="auth-card"><h1>Sign in required</h1><a className="btn primary" href="/login">Open CRM Login</a></div></AppShell>;

 return <AppShell active="/restaurant-crm">
  <Header eyebrow="RESTAURANT CRM · PRODUCTION" title="Restaurant Customer CRM" subtitle="Property-scoped customer, POS, reservation, service, loyalty, marketing and retention operations." actions={<><select className="input" value={propertyId} onChange={e=>switchProperty(e.target.value)}>{properties.map(p=><option key={p.id} value={p.id}>{p.name} · {p.property_type}</option>)}</select><button className="btn" onClick={load}>Refresh</button></>}/>
  {property&&<div className="notice"><b>{property.name}</b> · {property.property_type} · {property.city||property.destination||'—'} · property scoped</div>}
  {error&&<div className="notice error">{error}</div>}{notice&&<div className="notice">{notice}</div>}
  <div className="grid kpis"><Kpi label="Customers" value={customers.length}/><Kpi label="Visits" value={visits.length}/><Kpi label="Spend" value={money(totalSpend)}/><Kpi label="Average Bill" value={money(avgBill)}/><Kpi label="Repeat" value={repeat}/><Kpi label="VIP" value={vipCount}/><Kpi label="High Churn" value={highChurn}/><Kpi label="Open Service" value={requests.filter(x=>x.status!=='completed').length+complaints.filter(x=>x.status!=='resolved').length}/></div>
  <div className="tabs" style={{display:'flex',flexWrap:'wrap',gap:8}}>
   {['dashboard','customers','visits','reservations','orders','service','preferences','loyalty','marketing','offers','intelligence','identity','ai','timeline','automation'].map(x=><button key={x} className={'btn '+(tab===x?'primary':'')} onClick={()=>setTab(x)}>{x.replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())}</button>)}
  </div>

  {tab==='dashboard'&&<><Section title="Restaurant CRM Control Dashboard"><Table columns={['Metric','Value']} rows={[['Customers',customers.length],['Visits',visits.length],['Lifetime Spend',money(totalSpend)],['Average Bill',money(avgBill)],['Repeat Customers',repeat],['Reservations',reservations.length],['Open Complaints',complaints.filter(x=>x.status!=='resolved').length],['Open Requests',requests.filter(x=>x.status!=='completed').length],['Loyalty Members',loyalty.length],['Offers',offers.length],['Campaigns',campaigns.length],['Queued Messages',messages.filter(x=>x.status==='queued').length],['High Churn',highChurn]]}/></Section><Section title="Customer Behaviour"><Table columns={['Customer','Visits','Spend','Avg Bill','Last Visit','Favourite Items']} rows={metrics.slice(0,100).map(x=>[<button className="btn" onClick={()=>{setSelected(x.customer_id);setTab('customers')}}>{customerMap[x.customer_id]?.full_name||short(x.customer_id)}</button>,x.total_visits||0,money(x.lifetime_spend),money(x.average_bill),fmt(x.last_visit_at),Array.isArray(x.favorite_items)?x.favorite_items.join(', '):JSON.stringify(x.favorite_items||'—')])}/></Section></>}

  {tab==='customers'&&<><Section title="Customer Operations" actions={<input className="input" placeholder="Search name / phone / email" value={q} onChange={e=>setQ(e.target.value)}/>}>
    <Table columns={['Customer','Phone','Email','Visits','Spend','VIP','Action']} rows={filteredCustomers.map(c=>{const m=metrics.find(x=>x.customer_id===c.id);return[<button className="btn" onClick={()=>setSelected(c.id)}>{c.full_name}</button>,c.phone||'—',c.email||'—',m?.total_visits||0,money(m?.lifetime_spend),<Pill>{c.vip?'VIP':'Standard'}</Pill>,<a className="btn" href={`/customer-360?property=${propertyId}&customer=${c.id}`}>360</a>]})}/></Section>
    {selectedCustomer&&<div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))'}}>
      <Section title={`${selectedCustomer.full_name} · Operations`}><p>{selectedCustomer.phone||'—'} · {selectedCustomer.email||'—'}</p><p>Restaurant revenue: <b>{money(selectedCustomer.total_restaurant_revenue)}</b> · Visits: <b>{selectedCustomer.total_restaurant_visits||0}</b></p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><a className="btn primary" href={`/customer-360?property=${propertyId}&customer=${selectedCustomer.id}`}>Open Customer 360</a><button className="btn" onClick={()=>action('add_timeline',selectedCustomer.id,{title:'Restaurant CRM customer reviewed',event_type:'customer_reviewed'})}>Add Timeline Event</button></div></Section>
      <ActionForm title="Add Task" busy={busy} onSubmit={submit(async f=>action('create_task',selected,{title:f.title.value,priority:f.priority.value,due_at:f.due_at.value||null}))}><Field label="Title" name="title" defaultValue="Restaurant customer follow-up" required/><Select label="Priority" name="priority"><option>normal</option><option>high</option><option>urgent</option></Select><Field label="Due" name="due_at" type="datetime-local"/></ActionForm>
      <ActionForm title="Add Complaint" busy={busy} onSubmit={submit(async f=>action('create_complaint',selected,{title:f.title.value,description:f.description.value,priority:f.priority.value}))}><Field label="Title" name="title" defaultValue="Restaurant service complaint" required/><Field label="Description" name="description"/><Select label="Priority" name="priority"><option>normal</option><option>high</option><option>urgent</option></Select></ActionForm>
      <ActionForm title="Add Food Preference" busy={busy} onSubmit={submit(async f=>action('create_food_preference',selected,{preference_type:f.type.value,value:f.value.value,confidence:Number(f.confidence.value||1)}))}><Select label="Type" name="type"><option>diet</option><option>allergy</option><option>cuisine</option><option>spice</option><option>favourite_item</option></Select><Field label="Value" name="value" required/><Field label="Confidence" name="confidence" type="number" step="0.01" min="0" max="1" defaultValue="1"/></ActionForm>
    </div>}</>}

  {tab==='visits'&&<Section title="POS / Restaurant Visit & Order Ledger"><Table columns={['Date','Customer','Order','Table','Guests','Amount','Payment']} rows={visits.map(v=>[fmt(v.visit_at),customerMap[v.customer_id]?.full_name||short(v.customer_id),short(v.order_id),v.table_number||'—',v.guest_count||0,money(v.amount),v.payment_method||'—'])}/></Section>}
  {tab==='reservations'&&<Section title="Property-scoped Reservations"><Table columns={['Date','Time','Guest','Party','Status','Table','Source']} rows={reservations.map(r=>[r.reservation_date,r.reservation_time,r.guest_name||r.customer_id||'—',r.party_size||0,<Pill>{r.status||'—'}</Pill>,r.table_id||'—',r.source||'—'])}/></Section>}
  {tab==='orders'&&<><Section title="Orders · Restaurant Order Commercial Lifecycle"><Table columns={['Date','Customer','Source','Order','Event','From','To','Amount','Payment']} rows={orderEvents.map(o=>[fmt(o.created_at),customerMap[o.customer_id]?.full_name||short(o.customer_id),o.order_source,short(o.order_id),o.event_type,o.from_status||'—',o.to_status||'—',o.amount!=null?money(o.amount):'—',o.payment_status||'—'])}/></Section>{selectedCustomer&&<ActionForm title={`Record Order Event · ${selectedCustomer.full_name}`} busy={busy} onSubmit={submit(async f=>action('record_order_event',selected,{order_id:f.order_id.value,order_source:f.source.value,event_type:f.event_type.value,from_status:f.from_status.value||null,to_status:f.to_status.value||null,amount:f.amount.value||null,payment_status:f.payment_status.value||null,idempotency_key:f.idempotency_key.value||null}))}><Field label="Order ID" name="order_id" required/><Select label="Source" name="source"><option>marketplace</option><option>delivery</option><option>bill</option></Select><Select label="Event" name="event_type"><option>order_created</option><option>accepted</option><option>preparing</option><option>ready</option><option>fulfilled</option><option>cancelled</option></Select><Field label="From status" name="from_status"/><Field label="To status" name="to_status"/><Field label="Amount" name="amount" type="number" step="0.01"/><Select label="Payment status" name="payment_status"><option value="">Not changed</option><option>pending</option><option>paid</option><option>captured</option><option>failed</option></Select><Field label="Idempotency key" name="idempotency_key" required/></ActionForm>}</>}

  {tab==='service'&&<><ActionForm title={selectedCustomer?`New Service Request · ${selectedCustomer.full_name}`:'Select a customer first'} busy={busy} onSubmit={submit(async f=>{if(!selected)throw new Error('Select a customer');await action('create_request',selected,{request_type:f.type.value,description:f.description.value,priority:f.priority.value})})}><Select label="Request Type" name="type"><option>restaurant_service</option><option>table_service</option><option>dietary</option><option>reservation</option><option>billing</option><option>other</option></Select><Field label="Description" name="description" required/><Select label="Priority" name="priority"><option>normal</option><option>high</option><option>urgent</option></Select></ActionForm><Section title="Open Complaints"><Table columns={['Customer','Title','Priority','Status','Resolution','Action']} rows={complaints.map(x=>[customerMap[x.customer_id]?.full_name||short(x.customer_id),x.title,x.priority,<Pill>{x.status}</Pill>,x.resolution||'—',x.status!=='resolved'?<button className="btn" onClick={()=>action('resolve_complaint',x.customer_id,{complaint_id:x.id,resolution:'Resolved by Restaurant CRM'})}>Resolve</button>:'—'])}/></Section><Section title="Service Requests"><Table columns={['Customer','Type','Description','Priority','Status','Action']} rows={requests.map(x=>[customerMap[x.customer_id]?.full_name||short(x.customer_id),x.request_type,x.description||'—',x.priority,<Pill>{x.status}</Pill>,x.status!=='completed'?<button className="btn" onClick={()=>action('complete_request',x.customer_id,{request_id:x.id})}>Complete</button>:'—'])}/></Section><Section title="Reviews & Feedback"><Table columns={['Customer','Rating','Text','Date']} rows={[...reviews.map(x=>[customerMap[x.customer_id]?.full_name||short(x.customer_id),x.rating||x.overall_rating||'—',x.review_text||x.comment||'—',fmt(x.created_at)]),...feedback.map(x=>[customerMap[x.customer_id]?.full_name||short(x.customer_id),x.overall_rating||'—',x.comment||'—',fmt(x.created_at)])]}/></Section></>}

  {tab==='preferences'&&<><Section title="Customer Preferences"><Table columns={['Customer','Key','Value','Source','Confidence']} rows={prefs.map(x=>[customerMap[x.customer_id]?.full_name||short(x.customer_id),x.preference_key,x.preference_value||'—',x.source||'manual',x.confidence??'—'])}/></Section><Section title="Food Preferences"><Table columns={['Customer','Type','Value','Frequency','Confidence','Last Seen']} rows={foodPrefs.map(x=>[customerMap[x.customer_id]?.full_name||short(x.customer_id),x.preference_type,x.value,x.frequency||0,x.confidence??'—',fmt(x.last_seen_at)])}/></Section></>}

  {tab==='loyalty'&&<><Section title="Canonical Restaurant Loyalty"><Table columns={['Customer','Points','Tier','Actions']} rows={loyalty.map(x=>[customerMap[x.customer_id]?.full_name||short(x.customer_id),x.points_balance||0,x.tier||'—',<div style={{display:'flex',gap:6}}><button className="btn" onClick={()=>action('earn_loyalty',x.customer_id,{amount:100,reference_id:`restaurant-${Date.now()}`})}>Earn ₹100</button><button className="btn" onClick={()=>{const p=Number(prompt('Points to redeem','100')||0);if(p>0)action('redeem_loyalty',x.customer_id,{points:p,reference_id:`restaurant-${Date.now()}`})}}>Redeem</button></div>])}/></Section></>}

  {tab==='marketing'&&<><ActionForm title="Create / Rule Segment" busy={busy} onSubmit={submit(async f=>{const {data,error}=await supabase.rpc('anaira_restaurant_segment_action',{p_tenant_id:tenant,p_property_id:propertyId,p_action:'create',p_payload:{name:f.name.value,definition:{domain:'restaurant'}}});if(error)throw error;const rules=[{rule_group:1,field_name:'total_visits',operator:'gte',value_json:Number(f.min_visits.value||0),conjunction:'AND',position:0}];const rr=await supabase.rpc('anaira_restaurant_segment_action',{p_tenant_id:tenant,p_property_id:propertyId,p_action:'replace_rules',p_segment_id:data.segment_id,p_payload:{definition:{domain:'restaurant'},rules}});if(rr.error)throw rr.error;const rc=await supabase.rpc('anaira_restaurant_segment_action',{p_tenant_id:tenant,p_property_id:propertyId,p_action:'recalculate',p_segment_id:data.segment_id});if(rc.error)throw rc.error;setNotice('Segment rules saved and recalculated');await load()})}><Field label="Name" name="name" defaultValue="Restaurant Repeat Customers" required/><Field label="Minimum visits" name="min_visits" type="number" min="0" defaultValue="2"/></ActionForm><ActionForm title="Create Campaign" busy={busy} onSubmit={submit(async f=>{const {error}=await supabase.from('crm_campaigns').insert({tenant_id:tenant,property_id:propertyId,name:f.name.value,channel:f.channel.value,status:'draft',scheduled_at:f.scheduled_at.value||null});if(error)throw error;setNotice('Campaign created in draft');await load()})}><Field label="Campaign name" name="name" required/><Select label="Channel" name="channel"><option>whatsapp</option><option>sms</option><option>email</option></Select><Field label="Schedule" name="scheduled_at" type="datetime-local"/></ActionForm><Section title="Campaigns"><Table columns={['Name','Channel','Status','Scheduled','Audience']} rows={campaigns.map(x=>[x.name,x.channel,<Pill>{x.status}</Pill>,fmt(x.scheduled_at),<button className="btn" onClick={()=>action('prepare_campaign',null,{campaign_id:x.id,min_visits:x.segment_id?null:0})}>Prepare Audience</button>])}/></Section><Section title="WhatsApp / Communication Queue"><Table columns={['Customer','Channel','Status','Provider ID','Created']} rows={messages.map(x=>[customerMap[x.customer_id]?.full_name||short(x.customer_id),x.channel,<Pill>{x.status}</Pill>,x.provider_message_id||'—',fmt(x.created_at)])}/></Section>{selectedCustomer&&<ActionForm title={`Queue WhatsApp · ${selectedCustomer.full_name}`} busy={busy} onSubmit={submit(async f=>action('queue_whatsapp',selected,{to:selectedCustomer.phone,body:f.body.value,template:f.template.value||null}))}><Field label="Message" name="body" required defaultValue={`Hello ${selectedCustomer.full_name}, thank you for visiting us.`}/><Field label="Template" name="template"/></ActionForm>}</>}

  {tab==='offers'&&<><ActionForm title={selectedCustomer?`Create Offer · ${selectedCustomer.full_name}`:'Select customer from Customers tab'} busy={busy} onSubmit={submit(async f=>{if(!selected)throw new Error('Select a customer');await action('create_offer',selected,{offer_type:f.type.value,title:f.title.value,price:Number(f.price.value||0),inventory_ref:f.inventory.value||null,expires_at:f.expires.value||null})})}><Select label="Type" name="type"><option>restaurant_upsell</option><option>cross_sell</option><option>loyalty_reward</option></Select><Field label="Title" name="title" defaultValue="Dessert / beverage upgrade" required/><Field label="Price" name="price" type="number" min="0" step="0.01" defaultValue="0"/><Field label="Inventory reference" name="inventory"/><Field label="Expires" name="expires" type="datetime-local"/></ActionForm><Section title="Offer Lifecycle"><Table columns={['Customer','Type','Title','Price','Status','Accept','Fulfil']} rows={offers.map(x=>[customerMap[x.customer_id]?.full_name||short(x.customer_id),x.offer_type,x.title,money(x.price),<Pill>{x.status}</Pill>,x.status==='proposed'?<button className="btn" onClick={()=>action('accept_offer',x.customer_id,{offer_id:x.id})}>Accept</button>:'—',x.status==='accepted'?<button className="btn" onClick={()=>{const reference=prompt('Payment reference');if(reference)action('record_offer_payment',x.customer_id,{offer_id:x.id,provider:'manual',reference,verified:'true',amount:x.price})}}>Verify Payment</button>:x.status==='paid'?<button className="btn" onClick={()=>action('fulfil_offer',x.customer_id,{offer_id:x.id})}>Fulfil</button>:'—'])}/></Section></>}

  {tab==='identity'&&<><ActionForm title="Identity Resolution" busy={busy} onSubmit={submit(async f=>{const {data,error}=await supabase.rpc('anaira_restaurant_identity_candidates',{p_tenant_id:tenant,p_property_id:propertyId,p_limit:50});if(error)throw error;setNotice(`Found ${(data||[]).length} duplicate candidates`);})}><p style={{marginTop:0}}>Find phone, email and name matches inside the selected property/tenant.</p><button className="btn" type="submit">Find Duplicate Candidates</button></ActionForm><Section title="Customer Property Relationships"><Table columns={['Customer','Property','Relationship']} rows={customers.map(c=>[c.full_name,property?.name||short(propertyId),'guest'])}/></Section>{selectedCustomer&&<ActionForm title={`Merge Customer · ${selectedCustomer.full_name}`} busy={busy} onSubmit={submit(async f=>{const duplicate=f.duplicate.value;if(!duplicate)throw new Error('Select duplicate customer');const {error}=await supabase.rpc('anaira_restaurant_identity_merge',{p_tenant_id:tenant,p_property_id:propertyId,p_survivor:selected,p_duplicate:duplicate,p_reason:f.reason.value||'Restaurant CRM identity merge'});if(error)throw error;setNotice('Identity merge completed');await load()})}><Select label="Duplicate customer" name="duplicate"><option value="">Select duplicate</option>{customers.filter(c=>c.id!==selected).map(c=><option key={c.id} value={c.id}>{c.full_name} · {c.phone||c.email||short(c.id)}</option>)}</Select><Field label="Reason" name="reason" defaultValue="Duplicate customer records"/></ActionForm>}</>}

  {tab==='intelligence'&&<><Section title="Churn / Retention"><Table columns={['Customer','Score','Risk','Factors','Calculated']} rows={churn.map(x=>[customerMap[x.customer_id]?.full_name||short(x.customer_id),x.score||'—',<Pill>{x.risk_level||'—'}</Pill>,JSON.stringify(x.factors||{}),fmt(x.calculated_at)])}/></Section><Section title="VIP Profiles"><Table columns={['Customer','Level','Manager','Amenities']} rows={vip.map(x=>[customerMap[x.customer_id]?.full_name||short(x.customer_id),x.vip_level||'—',x.dedicated_manager||'—',JSON.stringify(x.welcome_amenities||[])])}/></Section><Section title="Restaurant Metrics"><Table columns={['Customer','Dine-in','Takeaway','Delivery','Reservations','Coupons','Reviews','Complaints']} rows={metrics.map(x=>[customerMap[x.customer_id]?.full_name||short(x.customer_id),x.dine_in_visits||0,x.takeaway_visits||0,x.delivery_visits||0,x.reservation_count||0,x.coupons_used||0,x.reviews_count||0,x.complaints_count||0])}/></Section></>}

  {tab==='ai'&&<><Section title="Restaurant AI Intelligence"><Table columns={['Date','Customer','Type','Summary','Recommendation','Confidence','Model','Lifecycle']} rows={aiInsights.map(x=>[fmt(x.created_at),customerMap[x.customer_id]?.full_name||short(x.customer_id),x.insight_type,x.summary,x.recommendation||'—',x.confidence??'—',x.model_name?`${x.model_name} ${x.model_version||''}`:'—',<div style={{display:'flex',gap:6,flexWrap:'wrap'}}>{x.status==='generated'?<button className="btn" onClick={()=>action('review_ai_insight',x.customer_id,{insight_id:x.id})}>Review</button>:null}{x.status==='reviewed'?<button className="btn" onClick={()=>action('approve_ai_insight',x.customer_id,{insight_id:x.id})}>Approve</button>:null}{x.status==='approved'?<button className="btn" onClick={()=>action('execute_ai_insight',x.customer_id,{insight_id:x.id,action_type:'add_timeline'})}>Execute</button>:null}<Pill>{x.status||'generated'}</Pill></div>])}/></Section>{selectedCustomer&&<ActionForm title={`Record Provider AI Insight · ${selectedCustomer.full_name}`} busy={busy} onSubmit={submit(async f=>action('generate_ai_insight',selected,{insight_type:f.type.value,summary:f.summary.value,recommendation:f.recommendation.value,confidence:Number(f.confidence.value||0),model_name:f.model.value,model_version:f.version.value,input_snapshot:{source:'restaurant_crm_ui'}}))}><Select label="Type" name="type"><option>next_best_action</option><option>churn</option><option>upsell</option><option>cross_sell</option><option>sentiment</option></Select><Field label="Provider model" name="model" required/><Field label="Version" name="version"/><Field label="Summary" name="summary" required/><Field label="Recommendation" name="recommendation"/><Field label="Confidence" name="confidence" type="number" min="0" max="1" step="0.01"/></ActionForm>}</>}

  {tab==='timeline'&&<Section title="Canonical Restaurant Customer Timeline"><Table columns={['Date','Customer','Type','Title','Source','Amount']} rows={timeline.map(x=>[fmt(x.occurred_at),customerMap[x.customer_id]?.full_name||short(x.customer_id),x.event_type,x.title,x.source_system,x.amount?money(x.amount):'—'])}/></Section>}

  {tab==='automation'&&<><ActionForm title={selectedCustomer?`Queue Automation · ${selectedCustomer.full_name}`:'Select a customer first'} busy={busy} onSubmit={submit(async f=>{if(!selected)throw new Error('Select a customer');await action('queue_automation',selected,{trigger_type:f.trigger.value,action_type:f.action.value,run_at:f.run_at.value||null})})}><Select label="Trigger" name="trigger"><option>visit_completed</option><option>order_completed</option><option>reservation_confirmed</option><option>complaint_resolved</option><option>manual</option></Select><Select label="Action" name="action"><option>add_timeline</option><option>send_whatsapp</option><option>create_offer</option><option>recalculate_churn</option></Select><Field label="Run at" name="run_at" type="datetime-local"/></ActionForm><Section title="Restaurant CRM Automation"><Table columns={['Component','State','Operational path']} rows={[
    ['POS/Bill Sync','ACTIVE','Bill → Restaurant Visit → Metrics → Customer revenue'],
    ['Loyalty','ACTIVE','Canonical ledger RPC → balance/tier → audit/timeline'],
    ['Service Requests','ACTIVE','Create → property-scoped request → complete'],
    ['Complaints','ACTIVE','Create → resolve → audit'],
    ['Offers','ACTIVE','Propose → accept → fulfil → revenue'],
    ['WhatsApp','QUEUED','CRM → provider queue; provider delivery is external and never faked'],
    ['Campaigns','DRAFT','Audience/campaign persistence; provider delivery requires configured provider'],
    ['Churn','ACTIVE','Existing CRM churn worker populates risk scores'],
    ['Timeline','ACTIVE','Restaurant actions write canonical CRM timeline'],
    ['Audit','ACTIVE','Restaurant action RPC writes CRM audit record'],
    ['Campaign audience','QUEUED/READY','Segment → recipient snapshot → campaign job → provider'],
    ['Automation queue','QUEUED','Trigger → job queue → worker → action/result/retry'],
    ['AI','PROVIDER-INPUT','Provider output → model/version/input snapshot → audit/timeline']
  ]}/></Section><Section title="Automation Jobs"><Table columns={['Created','Trigger','Action','Status','Attempts']} rows={automationJobs.map(j=>[fmt(j.created_at),j.trigger_type,j.action_type,<Pill>{j.status}</Pill>,j.attempts])}/></Section><Section title="Campaign Jobs"><Table columns={['Created','Campaign','Status','Attempts']} rows={campaignJobs.map(j=>[fmt(j.created_at),short(j.campaign_id),<Pill>{j.status}</Pill>,j.attempts])}/></Section><Section title="Open Tasks"><Table columns={['Customer','Title','Priority','Status','Due','Action']} rows={tasks.map(x=>[customerMap[x.customer_id]?.full_name||short(x.customer_id),x.title,x.priority,<Pill>{x.status}</Pill>,fmt(x.due_at),x.status!=='completed'?<button className="btn" onClick={()=>action('complete_task',x.customer_id,{task_id:x.id})}>Complete</button>:'—'])}/></Section></>}
 </AppShell>
}
