'use client';
import {useEffect,useMemo,useState} from 'react';
import {AppShell,Header,Section,Table,Pill} from '../components';
import {supabase} from '../../lib/supabase';

export default function Users(){
 const [rows,setRows]=useState([]),[profiles,setProfiles]=useState([]),[permissions,setPermissions]=useState([]),[overrides,setOverrides]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(''),[saving,setSaving]=useState('');
 const load=async()=>{const [p,r,pr,up,pc]=await Promise.all([supabase.from('profiles').select('id,email,full_name,role,status,restaurant_id').order('email'),supabase.from('restaurants').select('id,name'),supabase.from('anaira_permission_profiles').select('profile_key,name,role_key').order('name'),supabase.from('anaira_user_profiles').select('user_id,restaurant_id,profile_key'),supabase.from('anaira_permissions').select('permission_key,name,module').order('module').order('permission_key')]);const bad=[p,r,pr,up,pc].find(x=>x.error);if(bad){setError(bad.error.message);return}const map=Object.fromEntries((r.data||[]).map(x=>[x.id,x.name]));const pm=Object.fromEntries((pr.data||[]).map(x=>[x.profile_key,x]));const um=Object.fromEntries((up.data||[]).map(x=>[x.user_id+'|'+x.restaurant_id,x.profile_key]));setProfiles(pr.data||[]);setPermissions(pc.data||[]);setRows((p.data||[]).map(x=>({...x,property:map[x.restaurant_id]||'Platform',profileKey:um[x.id+'|'+x.restaurant_id]||'',profileName:pm[um[x.id+'|'+x.restaurant_id]]?.name||'—'})));};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!selected){setOverrides([]);return}(async()=>{const {data,error}=await supabase.from('anaira_user_permissions').select('permission_key,allowed').eq('user_id',selected.id).eq('restaurant_id',selected.restaurant_id);if(error)setError(error.message);else setOverrides(data||[])})()},[selected]);
 const overrideMap=useMemo(()=>Object.fromEntries(overrides.map(x=>[x.permission_key,x.allowed===true])),[overrides]);
 const changeRole=async(row,role)=>{setSaving(row.id);const {error}=await supabase.rpc('anaira_set_user_role',{p_user_id:row.id,p_restaurant_id:row.restaurant_id,p_role_key:role});if(error)setError(error.message);else {await load();setSelected(null)}setSaving('')};
 const changeProfile=async(row,profile)=>{setSaving(row.id);const {error}=await supabase.rpc('anaira_assign_user_profile',{p_user_id:row.id,p_restaurant_id:row.restaurant_id,p_profile_key:profile});if(error)setError(error.message);else await load();setSaving('')};
 const setOverride=async(k,allowed)=>{if(!selected)return;setSaving(k);const {error}=await supabase.rpc('anaira_set_user_permission',{p_user_id:selected.id,p_restaurant_id:selected.restaurant_id,p_permission_key:k,p_allowed:allowed});if(error)setError(error.message);else setOverrides(x=>{const rest=x.filter(y=>y.permission_key!==k);return [...rest,{permission_key:k,allowed}]});setSaving('')};
 const reset=(email)=>supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/login'}).then(({error})=>error&&setError(error.message));
 const grouped={}; permissions.forEach(p=>(grouped[p.module]??=[]).push(p));
 return <AppShell active="/users"><Header eyebrow="USER MANAGEMENT" title="Users & Staff" subtitle="Tenant users, base roles, job profiles and individual permission overrides."/><Section title="User Directory" meta={`${rows.length} users`}>{error&&<div className="notice error">{error}</div>}<Table columns={['Name','Login ID','Role','Profile','Property','Status','Actions']} rows={rows.map(r=>[r.full_name||'—',r.email||'—',<select value={r.role||'staff'} onChange={e=>changeRole(r,e.target.value)} disabled={!r.restaurant_id||saving===r.id}><option value="admin">admin</option><option value="manager">manager</option><option value="staff">staff</option></select>,<select value={r.profileKey||''} onChange={e=>changeProfile(r,e.target.value)} disabled={!r.restaurant_id||saving===r.id}><option value="">No profile</option>{profiles.filter(p=>p.role_key===r.role).map(p=><option key={p.profile_key} value={p.profile_key}>{p.name}</option>)}</select>,r.property,<Pill tone={r.status==='active'?'success':'muted'}>{r.status||'—'}</Pill>,<><button className="btn" onClick={()=>setSelected(r)} disabled={!r.restaurant_id}>Permissions</button>{r.email&&<button className="btn" onClick={()=>reset(r.email)}>Reset</button>}</>])}/></Section>{selected&&<Section title={`User Permissions — ${selected.full_name||selected.email}`} meta={selected.profileName||selected.role}><div className="notice">These are user-specific overrides. They do not modify the global job-profile template.</div>{Object.entries(grouped).map(([module,list])=><div key={module} className="card" style={{marginBottom:12}}><div className="section-head"><h2>{module}</h2><span>{list.length} permissions</span></div><Table columns={['Permission','Override','Action']} rows={list.map(x=>[x.permission_key,overrideMap[x.permission_key]===undefined?'Inherited':overrideMap[x.permission_key]?'Allowed':'Denied',<div><button className="btn" disabled={saving===x.permission_key} onClick={()=>setOverride(x.permission_key,true)}>Allow</button> <button className="btn" disabled={saving===x.permission_key} onClick={()=>setOverride(x.permission_key,false)}>Deny</button></div>])}/></div>)}</Section>}<div className="notice">Business Admin can assign role/profile and set user-level overrides within the tenant. Global profile template editing remains Super Admin only.</div></AppShell>
}
