'use client';

import React,{useEffect,useMemo,useState} from 'react';

const BUSINESS={
  name:'Anaira Graphics & Digital Solution',
  short:'Anaira Graphics',
  phone:'097365 80084',
  phoneHref:'tel:+919736500084',
  whatsapp:'https://wa.me/919736500084',
  address:'Opp. Sood Petrol Pump, Akhara, Kullu, Himachal Pradesh 175101, India',
};

const SERVICE_CATS=['Graphics & Digital Design','Digital Printing','Web Design & Development','SEO & Local SEO','Social Media Marketing','Software & App Development','Signage & Display'];

function LeadForm({services,settings={}}){
 const [form,setForm]=useState({name:'',phone:'',email:'',service:'',message:'',website:''});
 const [state,setState]=useState({loading:false,ok:false,error:''});
 const submit=async e=>{e.preventDefault();setState({loading:true,ok:false,error:''});try{const r=await fetch('/api/anaira-graphics/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Unable to send enquiry');setForm({name:'',phone:'',email:'',service:'',message:'',website:''});setState({loading:false,ok:true,error:''});}catch(err){setState({loading:false,ok:false,error:err.message});}};
 return <form className="ag-form" onSubmit={submit}>
  <input className="ag-honeypot" tabIndex="-1" autoComplete="off" name="website" value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/>
  <div className="ag-form-grid"><label>{settings.nameLabel||'Name'}<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder={settings.formNamePlaceholder||''}/></label><label>{settings.phoneLabel||'Phone'}<input required inputMode="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder={settings.formPhonePlaceholder||''}/></label><label>Email <span>(optional)</span><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder={settings.formEmailPlaceholder||''}/></label><label>{settings.formServiceLabel||''}<select value={form.service} onChange={e=>setForm({...form,service:e.target.value})}><option value="">{settings.formServicePlaceholder||''}</option>{services.map(s=><option key={s.id||s.title} value={s.title}>{s.title}</option>)}</select></label></div>
  <label>{settings.formMessageLabel||''}<textarea required rows="5" value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder={settings.formMessagePlaceholder||''}/></label>
  {state.ok&&<div className="ag-form-success">{settings.formSuccess||''}</div>}{state.error&&<div className="ag-form-error">{state.error}</div>}
  <button className="ag-btn ag-btn-gold" disabled={state.loading}>{state.loading?(settings.formSending||''):(settings.formSubmit||'')}</button>
 </form>;
}

function ServiceModal({group,items,onClose,settings={}}){
 useEffect(()=>{if(!onClose)return; const prev=document.body.style.overflow; document.body.style.overflow='hidden'; const onKey=e=>{if(e.key==='Escape')onClose();}; window.addEventListener('keydown',onKey); return()=>{document.body.style.overflow=prev;window.removeEventListener('keydown',onKey);};},[onClose]);
 return <div className="ag-modal-backdrop" role="dialog" aria-modal="true" aria-label={`${group} services`} onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}>
   <div className="ag-service-modal">
    <div className="ag-modal-head"><div><div className="ag-kicker">{settings.allServicesLabel||'ALL SERVICES'}</div><h3>{group}</h3><p>{items.length} {settings.relatedServicesLabel||'related services'}</p></div><button className="ag-modal-close" onClick={onClose} aria-label={settings.closeLabel||"Close"}>×</button></div>
    <div className="ag-modal-service-grid">{items.map((x,i)=><article className="ag-modal-service" key={x.id||x.title}>
      <div className="ag-modal-service-image">{x.image_url?<img src={x.image_url} alt={x.alt_text||x.title}/>:<span>{x.icon||'✦'}</span>}</div>
      <div><small>{String(i+1).padStart(2,'0')}</small><h4>{x.title}</h4><p>{x.description}</p><div className="ag-service-modal-actions"><a href="#contact" onClick={onClose}>{settings.enquireLabel||"Enquire →"}</a>{x.buy_enabled&&<button type="button" onClick={()=>{window.dispatchEvent(new CustomEvent('ag:add-cart',{detail:x}));onClose()}}>{settings.addToCartLabel||"Add to cart"}</button>}{x.demo_url&&<a href={x.demo_url} target="_blank" rel="noreferrer">{settings.viewDemoLabel||"View Demo ↗"}</a>}</div></div>
    </article>)}</div>
   </div>
 </div>;
}

function ServiceGroup({group,items,settings={}}){
 const [expanded,setExpanded]=useState(false);
 const [modal,setModal]=useState(false);
 const visible=expanded?items:items.slice(0,3);
 return <div className="ag-service-group">
   <div className="ag-service-group-head"><div><h3>{group}</h3><span>{items.length} {settings.serviceCountLabel||'services'}</span></div><div className="ag-service-group-actions">
     {items.length>3&&<button type="button" className="ag-text-btn" onClick={()=>setExpanded(v=>!v)}>{expanded?(settings.showLessLabel||'Show Less ↑'):(settings.showMoreLabel||'Show More +')}</button>}
     <button type="button" className="ag-text-btn ag-view-all" onClick={()=>setModal(true)}>{settings.viewAllLabel||'View All ↗'}</button>
   </div></div>
   <div className="ag-service-grid">{visible.map((x,i)=><article className="ag-service" key={x.id||x.title}>
      <div className="ag-service-image">{x.image_url?<img src={x.image_url} alt={x.alt_text||x.title}/>:<div className="ag-service-image-placeholder">{x.icon||'✦'}</div>}</div>
      <div className="ag-service-top"><span>{x.icon||'✦'}</span><b>{String(i+1).padStart(2,'0')}</b></div><h3>{x.title}</h3><p>{x.description}</p><div className="ag-service-price">{x.buy_enabled&&x.price?`₹${Number(x.price).toLocaleString('en-IN')}${x.unit?` / ${x.unit}`:''}`:(settings.customQuoteLabel||'Custom quote')}</div><div className="ag-service-actions"><a href="#contact">{settings.enquireLabel||'Enquire →'}</a>{x.demo_url&&<a href={x.demo_url} target="_blank" rel="noreferrer">{settings.demoLabel||'Demo ↗'}</a>}{x.buy_enabled&&<button type="button" onClick={()=>window.dispatchEvent(new CustomEvent('ag:add-cart',{detail:x}))}>{settings.addToCartLabel||"Add to cart"}</button>}</div>
   </article>)}</div>
   {!expanded&&items.length>3&&<div className="ag-service-more-note">{settings.showingLabel||'Showing 3 of'} {items.length} · {settings.useLabel||'use'} <button type="button" onClick={()=>setExpanded(true)}>{settings.showMorePlainLabel||'Show More'}</button> {settings.orLabel||'or'} <button type="button" onClick={()=>setModal(true)}>{settings.viewAllPlainLabel||'View All'}</button></div>}
   {modal&&<ServiceModal group={group} items={items} settings={settings} onClose={()=>setModal(false)}/>} 
 </div>;
}

function ServiceCart({items,onClose,onChanged,settings={}}){
 const [checkout,setCheckout]=useState(false);const [form,setForm]=useState({name:'',phone:'',email:'',message:''});const [busy,setBusy]=useState(false);const [msg,setMsg]=useState('');
 const total=items.reduce((sum,x)=>sum+(Number(x.price)||0)*(x.qty||1),0);
 const submit=async e=>{e.preventDefault();setBusy(true);setMsg('');try{const r=await fetch('/api/anaira-graphics/order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer:form,items:items.map(x=>({id:x.id,qty:x.qty||1}))})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||'Unable to place order request');setMsg(`${settings.orderRequestSuccessPrefix||'Order request'} #${j.orderId||''} ${settings.receivedText||'received. We will contact you shortly.'}`);onChanged([]);}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 return <div className="ag-cart-backdrop" role="dialog" aria-modal="true" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside className="ag-cart-drawer"><div className="ag-cart-head"><div><div className="ag-kicker">{settings.cartTitle||'SERVICE CART'}</div><h3>{checkout?(settings.checkoutTitle||'Checkout'):(settings.selectedServicesTitle||'Your selected services')}</h3></div><button onClick={onClose}>×</button></div>{!checkout?<><div className="ag-cart-items">{items.map(x=><div className="ag-cart-item" key={x.id}><div><b>{x.title}</b><small>{x.unit||'Service'} · {settings.qtyLabel||'Quantity'} {x.qty||1}</small></div><strong>{x.price?`₹${(Number(x.price)*(x.qty||1)).toLocaleString('en-IN')}`:'Quote'}</strong><button onClick={()=>onChanged(items.filter(y=>y.id!==x.id))}>×</button></div>)}{!items.length&&<div className="ag-cart-empty">{settings.cartEmptyText||'Your cart is empty. Add a service from the service catalogue.'}</div>}</div><div className="ag-cart-total"><span>{settings.estimatedTotalLabel||'Estimated total'}</span><strong>{total?`₹${total.toLocaleString('en-IN')}`:(settings.customQuoteLabel||'Custom quote')}</strong></div><button className="ag-btn ag-btn-gold ag-cart-checkout" disabled={!items.length} onClick={()=>setCheckout(true)}>{settings.continueCheckoutLabel||'Continue to checkout →'}</button></>:<form className="ag-cart-checkout-form" onSubmit={submit}><p className="ag-cart-summary">{items.length} service{items.length>1?'s':''} · {total?`₹${total.toLocaleString('en-IN')}`:'Custom quote'}</p><label>{settings.nameLabel||'Name'}<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>{settings.phoneLabel||'Phone'}<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>{settings.emailLabel||'Email'}<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>{settings.deliveryNotesLabel||'Requirement / delivery notes'}<textarea rows="4" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></label>{msg&&<div className="ag-form-success">{msg}</div>}<div className="ag-cart-checkout-actions"><button type="button" onClick={()=>setCheckout(false)}>{settings.backLabel||'Back'}</button><button className="ag-btn ag-btn-gold" disabled={busy}>{busy?(settings.submittingLabel||'Submitting…'):(settings.placeOrderLabel||'Place Order Request →')}</button></div></form>}</aside></div>;
}

function ProjectCard({x,index,kind,settings={}}){
 const gallery=Array.isArray(x.gallery)?x.gallery.filter(Boolean):[];
 return <article className="ag-portfolio-card ag-project-card">
  <div className="ag-portfolio-image">{x.image_url?<img src={x.image_url} alt={x.alt_text||x.title}/>:<div className={`ag-portfolio-image-placeholder ${kind==='software'?'software':''}`}>{kind==='software'?'⌘':'↗'}</div>}</div>
  {gallery.length>0&&<div className="ag-project-gallery">{gallery.slice(0,3).map((u,i)=><img key={u+i} src={u} alt={`${x.title} ${i+1}`}/>)}</div>}
  <div className="ag-portfolio-top"><span>{kind==='software'?(settings.softwareProjectTypeLabel||'SOFTWARE / SAAS'):(settings.websiteProjectTypeLabel||'WEBSITE / WEB')}</span><b>{String(index+1).padStart(2,'0')}</b></div>
  <h3>{x.title}</h3><p>{x.description}</p>{x.tag&&<small>{x.tag}</small>}<a className="ag-project-link" href={`/anaira-graphics/demo/${x.id}`}>{settings.viewDemoLabel||"View Demo ↗"}</a>{x.live_url&&<a className="ag-project-link" href={x.live_url} target="_blank" rel="noreferrer">Open Live ↗</a>}
 </article>;
}

export default function AnairaGraphicsPage(){
 const [liveContent,setLiveContent]=useState({services:[],portfolio:[],settings:{}});
 const [cartItems,setCartItems]=useState([]);
 useEffect(()=>{const fn=e=>{const x=e.detail;if(!x?.id)return;setCartItems(prev=>prev.some(y=>y.id===x.id)?prev.map(y=>y.id===x.id?{...y,qty:(y.qty||1)+1}:y):[...prev,{...x,qty:1}]);};window.addEventListener('ag:add-cart',fn);return()=>window.removeEventListener('ag:add-cart',fn);},[]);
 useEffect(()=>{fetch('/api/anaira-graphics/content').then(r=>r.ok?r.json():null).then(j=>{if(j?.ok)setLiveContent({services:j.services||[],portfolio:j.portfolio||[],settings:j.settings||{}})}).catch(()=>{});},[]);
 const s=liveContent.settings||{};
 const serviceRows=liveContent.services||[];
 const portfolioRows=liveContent.portfolio||[];
 const serviceGroups=useMemo(()=>{const groups={};for(const x of serviceRows){const key=x.category||'Services';(groups[key]||(groups[key]=[])).push(x);}return Object.entries(groups);},[serviceRows]);
 const websites=portfolioRows.filter(x=>(x.portfolio_group||'Websites & Web Projects')==='Websites & Web Projects');
 const anaProducts=portfolioRows.filter(x=>(x.portfolio_group||'')==='Anaira Products & SaaS');
 const clientSoftware=portfolioRows.filter(x=>(x.portfolio_group||'')==='Client Software & Platforms');
 const otherProjects=portfolioRows.filter(x=>['Websites & Web Projects','Anaira Products & SaaS','Client Software & Platforms'].indexOf(x.portfolio_group||'')===-1);
 const publicSiteUrl=(process.env.NEXT_PUBLIC_SITE_URL||'').replace(/\/$/,'');
 const schema={'@context':'https://schema.org','@type':'ProfessionalService',name:s.businessName||'',description:s.heroDescription||'',telephone:s.phone||'',address:{'@type':'PostalAddress',streetAddress:s.address||'',addressLocality:'Kullu',addressRegion:'Himachal Pradesh',postalCode:'175101',addressCountry:'IN'},areaServed:[{'@type':'City',name:'Kullu'},{'@type':'State',name:'Himachal Pradesh'}],image:publicSiteUrl?`${publicSiteUrl}/anaira-graphics/logo.png`:'/anaira-graphics/logo.png',url:publicSiteUrl?`${publicSiteUrl}/anaira-graphics`:'/anaira-graphics'};
 const featuredImages=Array.isArray(s.featuredImages)?s.featuredImages.filter(x=>x&&x.url):[];
 const marqueeImages=featuredImages.length?featuredImages:portfolioRows.filter(x=>x.image_url).map(x=>({url:x.image_url,title:x.title,alt:x.alt_text}));
 return <main className="ag-site">
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  {cartItems.length>0&&<button className="ag-floating-cart" onClick={()=>setCartItems(prev=>prev)}>Cart · {cartItems.length}</button>}
  {cartItems.length>0&&<ServiceCart items={cartItems} settings={s} onClose={()=>setCartItems([])} onChanged={setCartItems}/>}
  <header className="ag-nav"><a href="#top" className="ag-brand"><img src="/anaira-graphics/logo.png" alt="Anaira Graphics & Digital Solution logo"/><span><b>ANAIRA</b><small>GRAPHICS & DIGITAL SOLUTIONS</small></span></a><nav><a href="#services">{s.navServices||''}</a><a href="#portfolio">{s.navWork||''}</a><a href="#process">{s.navProcess||''}</a><a href="#contact">{s.navContact||''}</a></nav><a className="ag-nav-cta" href={s.phoneHref||''}>{s.navCta||''}</a></header>
  <section id="top" className="ag-hero"><div className="ag-hero-glow ag-glow-one"/><div className="ag-hero-glow ag-glow-two"/><div className="ag-hero-copy"><div className="ag-eyebrow"><span/> {s.eyebrow||''} <span/></div><h1>{(s.heroTitle||'').split(' ').map((w,i)=><span key={i}>{w}{i===0||i===1?<em> </em>:' '}</span>)}</h1><p>{s.heroDescription||''}</p><div className="ag-hero-actions"><a className="ag-btn ag-btn-gold" href="#contact">{s.heroPrimary||''}</a><a className="ag-btn ag-btn-outline" href={s.whatsapp||''} target="_blank" rel="noreferrer">{s.heroSecondary||''}</a></div><div className="ag-trust-row"><span>{s.trust1||''}</span><i>•</i><span>{s.trust2||''}</span><i>•</i><span>{s.trust3||''}</span><i>•</i><span>{s.trust4||''}</span><i>•</i><span>{s.trust5||''}</span></div></div><div className="ag-hero-art"><div className="ag-art-ring ring-a"/><div className="ag-art-ring ring-b"/><div className="ag-art-card"><img src="/anaira-graphics/logo.png" alt=""/><strong>DESIGN<br/><span>BRAND</span><br/>GROW</strong></div><div className="ag-art-chip chip-a">{s.artChip1||''}</div><div className="ag-art-chip chip-b">{s.artChip2||''}</div><div className="ag-art-chip chip-c">{s.artChip3||''}</div></div></section>
  <section className="ag-proof"><div><strong>{s.proofTitle||''}</strong><span>{s.proofText||''}</span></div><a href="#portfolio">{s.proofLink||''}</a></section>
  <section className="ag-focus ag-focus-premium"><div className="ag-focus-inner"><div className="ag-focus-intro"><div className="ag-focus-heading"><div className="ag-kicker">{s.focusKicker||''}</div><h2>{s.focusTitle||''}</h2><div className="ag-focus-pills"><span>✦ &nbsp; {s.focusPill1||''}</span><span>◈ &nbsp; {s.focusPill2||''}</span><span>✧ &nbsp; {s.focusPill3||''}</span><span>✦ &nbsp; {s.focusPill4||''}</span></div></div><div className="ag-focus-sidecopy"><p>{s.focusText||''}</p><a href="#portfolio" className="ag-focus-reel"><b>▶</b><span><strong>{s.focusCtaTitle||''}</strong><small>{s.focusCtaText||''}</small></span><i>→</i></a></div></div><div className="ag-focus-grid">
   <a href="#portfolio" className="ag-focus-card focus-web"><span className="ag-focus-number">01</span><div className="ag-focus-visual ag-reference-visual">{s.webImage?<img className="ag-focus-reference-image" src={s.webImage} alt="Websites showcase"/>:<div className="ag-focus-reference-placeholder">WEB</div>}</div><div className="ag-focus-copy"><small>{s.webKicker||''}</small><h3>{s.webTitle||''}</h3><p>{s.webText||''}</p><div className="ag-focus-chips"><span>⌘<b>{(s.webChip1||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span><span>◇<b>{(s.webChip2||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span><span>▣<b>{(s.webChip3||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span><span>↗<b>{(s.webChip4||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span></div><div className="ag-focus-actions"><strong>{s.webAction||''} <i>→</i></strong><span>{s.webViewAll||''}</span></div></div></a>
   <a href="#portfolio" className="ag-focus-card focus-software"><span className="ag-focus-number">02</span><div className="ag-focus-visual ag-reference-visual">{s.softwareImage?<img className="ag-focus-reference-image" src={s.softwareImage} alt="Software showcase"/>:<div className="ag-focus-reference-placeholder">SOFTWARE</div>}</div><div className="ag-focus-copy"><small>{s.softwareKicker||''}</small><h3>{s.softwareTitle||''}</h3><p>{s.softwareText||''}</p><div className="ag-focus-chips"><span>⌘<b>{(s.softwareChip1||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span><span>▣<b>{(s.softwareChip2||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span><span>⌂<b>{(s.softwareChip3||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span><span>◇<b>{(s.softwareChip4||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span></div><div className="ag-focus-actions"><strong>{s.softwareAction||''} <i>→</i></strong><span>{s.softwareViewAll||''}</span></div></div></a>
   <a href="#services" className="ag-focus-card focus-creative"><span className="ag-focus-number">03</span><div className="ag-focus-visual ag-reference-visual">{s.designImage?<img className="ag-focus-reference-image" src={s.designImage} alt="Graphic design showcase"/>:<div className="ag-focus-reference-placeholder">DESIGN</div>}</div><div className="ag-focus-copy"><small>{s.designKicker||''}</small><h3>{s.designTitle||''}</h3><p>{s.designText||''}</p><div className="ag-focus-chips"><span>△<b>{(s.designChip1||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span><span>▦<b>{(s.designChip2||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span><span>▱<b>{(s.designChip3||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span><span>▤<b>{(s.designChip4||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span></div><div className="ag-focus-actions"><strong>{s.designAction||''} <i>→</i></strong><span>{s.designViewAll||''}</span></div></div></a>
   <a href="#services" className="ag-focus-card focus-print"><span className="ag-focus-number">04</span><div className="ag-focus-visual ag-reference-visual">{s.printImage?<img className="ag-focus-reference-image" src={s.printImage} alt="Digital printing and signage showcase"/>:<div className="ag-focus-reference-placeholder">PRINT</div>}</div><div className="ag-focus-copy"><small>{s.printKicker||''}</small><h3>{s.printTitle||''}</h3><p>{s.printText||''}</p><div className="ag-focus-chips"><span>▤<b>{(s.printChip1||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span><span>⚙<b>{(s.printChip2||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span><span>▣<b>{(s.printChip3||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span><span>♢<b>{(s.printChip4||'').split("\n").map((x,i)=><React.Fragment key={i}>{i>0&&<br/>}{x}</React.Fragment>)}</b></span></div><div className="ag-focus-actions"><strong>{s.printAction||''} <i>→</i></strong><span>{s.printViewAll||''}</span></div></div></a>
  </div><div className="ag-focus-stats"><div><b>◆</b><strong>{s.statsProjects||''}</strong><span>{s.statsProjectsLabel||''}</span></div><div><b>♧</b><strong>{s.statsClients||''}</strong><span>{s.statsClientsLabel||''}</span></div><div><b>☆</b><strong>{s.statsYears||''}</strong><span>{s.statsYearsLabel||''}</span></div><div><b>♜</b><strong>{s.statsComplete||''}</strong><span>{s.statsCompleteText||''}</span></div></div></div></section>
  {marqueeImages.length>0&&<section className="ag-image-marquee ag-featured-marquee"><div className="ag-marquee-label">{s.marqueeLabel||'FEATURED WORK · SCROLL'}</div><div className="ag-marquee-track">{[...marqueeImages,...marqueeImages].map((x,i)=><div className="ag-marquee-card" key={`${x.url}-${i}`}><img src={x.url} alt={x.alt||x.title||'Featured work'}/>{(x.title||'')&&<span>{x.title}</span>}</div>)}</div></section>}
  <section id="services" className="ag-section ag-services"><div className="ag-section-inner"><div className="ag-section-head"><div><div className="ag-kicker">{s.servicesKicker||''}</div><h2>{s.servicesTitle||''}</h2></div><p>{s.servicesText||''}</p></div>{serviceGroups.map(([group,items])=><ServiceGroup key={group} group={group} items={items} settings={s}/>)}</div></section>
  <section id="portfolio" className="ag-section ag-portfolio"><div className="ag-section-head"><div><div className="ag-kicker">{s.portfolioKicker||''}</div><h2>{s.portfolioTitle||''}</h2></div><p>{s.portfolioText||''}</p></div><div className="ag-portfolio-stats"><div><strong>{websites.length}+</strong><span>{s.webProjectsLabel||''}</span></div><div><strong>{anaProducts.length}+</strong><span>{s.anairaProductsLabel||''}</span></div><div><strong>{clientSoftware.length}+</strong><span>{s.clientSoftwareLabel||''}</span></div><div><strong>{serviceRows.length}+</strong><span>{s.servicesCountLabel||''}</span></div></div>
   <div className="ag-portfolio-category"><div className="ag-portfolio-category-head"><h3>{s.websitesCategoryTitle||''}</h3><span>{websites.length} {s.projectCountLabel||''}</span></div><div className="ag-portfolio-grid">{websites.map((x,i)=><ProjectCard key={x.id||x.title} x={x} index={i} kind="website" settings={s}/>)}</div></div>
   <div className="ag-portfolio-category ag-product-band"><div className="ag-portfolio-category-head"><h3>{s.anairaProductsCategoryTitle||''}</h3><span>{anaProducts.length} {s.systemCountLabel||''}</span></div><div className="ag-portfolio-grid">{anaProducts.map((x,i)=><ProjectCard key={x.id||x.title} x={x} index={i} kind="software" settings={s}/>)}</div></div>
   <div className="ag-portfolio-category"><div className="ag-portfolio-category-head"><h3>{s.clientSoftwareCategoryTitle||''}</h3><span>{clientSoftware.length} {s.projectCountLabel||''}</span></div><div className="ag-portfolio-grid">{clientSoftware.map((x,i)=><ProjectCard key={x.id||x.title} x={x} index={i} kind="software" settings={s}/>)}</div></div>
   {otherProjects.length>0&&<div className="ag-portfolio-category"><div className="ag-portfolio-category-head"><h3>{s.moreWorkCategoryTitle||''}</h3><span>{otherProjects.length} {s.projectCountLabel||''}</span></div><div className="ag-portfolio-grid">{otherProjects.map((x,i)=><ProjectCard key={x.id||x.title} x={x} index={i} kind={x.type==='software'?'software':'website'} settings={s}/>)}</div></div>}
  </section>
  <section className="ag-dark-section"><div className="ag-section ag-work"><div className="ag-kicker">{s.whyKicker||''}</div><h2>{s.whyTitle||''}</h2><div className="ag-work-grid"><div className="ag-work-card large"><span>01</span><h3>{s.why1Title||''}</h3><p>{s.why1Text||''}</p></div><div className="ag-work-card"><span>02</span><h3>{s.why2Title||''}</h3><p>{s.why2Text||''}</p></div><div className="ag-work-card"><span>03</span><h3>{s.why3Title||''}</h3><p>{s.why3Text||''}</p></div></div></div></section>
  <section id="process" className="ag-section ag-process"><div className="ag-kicker">{s.processKicker||''}</div><h2>{s.processTitle||''}</h2><div className="ag-process-grid">{
[['01',s.process1Title,s.process1Text],['02',s.process2Title,s.process2Text],['03',s.process3Title,s.process3Text],['04',s.process4Title,s.process4Text]]
.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)
}</div></section>
  <section className="ag-cta-band"><div><div className="ag-kicker">{s.ctaKicker||''}</div><h2>{s.ctaTitle||''}</h2></div><div><p>{s.ctaText||''}</p><a className="ag-btn ag-btn-light" href="#contact">{s.ctaButton||''}</a></div></section>
  <section id="contact" className="ag-section ag-contact"><div className="ag-contact-copy"><div className="ag-kicker">{s.contactKicker||''}</div><h2>{s.contactTitle||''}</h2><p>{s.contactText||''}</p><div className="ag-contact-list"><a href={s.phoneHref||''}><span>{s.contactPhoneLabel||''}</span><b>{s.phone||''}</b></a><a href={s.whatsapp||''} target="_blank" rel="noreferrer"><span>{s.contactWhatsappLabel||''}</span><b>{s.contactWhatsappText||''}</b></a><div><span>{s.contactLocationLabel||''}</span><b>{s.address||''}</b></div></div></div><div className="ag-contact-card"><LeadForm services={serviceRows} settings={s}/></div></section>
  <footer className="ag-footer"><a href="#top" className="ag-brand"><img src="/anaira-graphics/logo.png" alt="Anaira Graphics"/><span><b>ANAIRA</b><small>GRAPHICS & DIGITAL SOLUTIONS</small></span></a><p>{s.footerCopyright||''} · {s.footerTagline||''}</p><div><a href="#services">{s.navServices||''}</a><a href="#portfolio">{s.navWork||''}</a><a href="#contact">{s.navContact||''}</a></div></footer>
 </main>;
}