export const COMMON_SECTIONS = [
  {key:'profile',label:'Business Profile'},
  {key:'catalog',label:'Products / Services'},
  {key:'team',label:'Team / Staff'},
  {key:'operations',label:'Operations'},
  {key:'commerce',label:'Commerce / Billing'},
  {key:'customers',label:'Customers / Leads'},
  {key:'website',label:'Premium Website'},
  {key:'media',label:'Gallery & Testimonials'},
  {key:'seo',label:'SEO & Social'}
];

const F = (key,label,type='text',extra={}) => ({key,label,type,...extra});
const IMAGE = (key='image_url',label='Image') => F(key,label,'image');
const GALLERY = F('gallery','Gallery Images','gallery');
const COMMON_PROFILE = [F('name','Business Name'),F('owner_name','Owner / Contact'),F('phone','Phone'),F('email','Email'),F('website','Website'),F('address','Address','textarea'),F('city','City'),F('state','State'),F('country','Country','text',{default:'India'}),F('description','About Business','textarea'),F('opening_time','Opening Time'),F('closing_time','Closing Time')];

const schemas = {
 barber_shop:{primary:'Services',primaryIcon:'💈',entity:'Service',fields:[F('name','Service Name'),IMAGE(),F('category','Category'),F('description','Description','textarea'),F('price','Price','number'),F('duration_minutes','Duration (min)','number'),F('buffer_minutes','Buffer (min)','number'),F('commission_percent','Commission %','number'),F('online_booking','Online Booking','boolean')] ,secondary:{team:['name','role','photo_url','phone','email','commission_percent','bio'],resources:['name','resource_type','capacity'],products:['name','brand','sku','image_url','sale_price','stock_qty','reorder_level'],memberships:['name','price','billing_interval','benefits','image_url'],packages:['name','price','expiry_days','included_services','image_url']}},
 spa_wellness:{primary:'Treatments',primaryIcon:'💆',entity:'Treatment',fields:[F('name','Treatment Name'),IMAGE(),F('category','Category'),F('description','Description','textarea'),F('price','Price','number'),F('duration_minutes','Duration (min)','number'),F('therapist_type','Therapist Type'),F('room_required','Room Required','boolean'),F('contraindications','Contraindications','textarea'),F('online_booking','Online Booking','boolean')],secondary:{team:['name','role','photo_url','phone','email','specialization','bio'],resources:['name','resource_type','capacity'],products:['name','brand','sku','image_url','sale_price','stock_qty'],memberships:['name','price','billing_interval','benefits','image_url'],packages:['name','price','expiry_days','included_services','image_url']}},
 clinic_hospital:{primary:'Clinical Services',primaryIcon:'🏥',entity:'Service / Treatment',fields:[F('name','Service / Treatment'),IMAGE(),F('department','Department'),F('description','Description','textarea'),F('consultation_fee','Fee','number'),F('duration_minutes','Duration (min)','number'),F('online_booking','Online Appointment','boolean')],secondary:{team:['name','specialization','qualification','experience','registration','photo_url','phone','email','bio'],departments:['name','description','image_url'],rooms:['name','room_type','capacity'],patients:['name','phone','email','gender','dob','notes']}},
 dentist_doctor:{primary:'Medical / Dental Services',primaryIcon:'🦷',entity:'Treatment',fields:[F('name','Treatment'),IMAGE(),F('category','Specialization'),F('description','Description','textarea'),F('price','Consultation / Treatment Fee','number'),F('duration_minutes','Duration (min)','number'),F('online_booking','Online Booking','boolean')],secondary:{team:['name','specialization','qualification','experience','registration','photo_url','languages','bio'],patients:['name','phone','email','dob','allergies','notes'],services:['name','description','image_url','price','duration_minutes'],followups:['title','customer_name','date','notes']}},
 pharmacy:{primary:'Products',primaryIcon:'💊',entity:'Product',fields:[F('name','Product Name'),IMAGE(),F('brand','Brand'),F('sku','SKU'),F('category','Category'),F('batch','Batch'),F('expiry_date','Expiry Date','date'),F('mrp','MRP','number'),F('selling_price','Selling Price','number'),F('stock_qty','Stock Qty','number'),F('reorder_level','Reorder Level','number'),F('tax_percent','Tax %','number')],secondary:{brands:['name','logo_url','description'],suppliers:['name','phone','email','address'],prescriptions:['customer_name','doctor','prescription_number','date','notes'],delivery:['name','phone','address','order_reference','status']}},
 gym_yoga:{primary:'Classes & Programs',primaryIcon:'🏋️',entity:'Class / Program',fields:[F('name','Class / Program'),IMAGE(),F('category','Category'),F('description','Description','textarea'),F('trainer','Trainer'),F('duration_minutes','Duration (min)','number'),F('capacity','Capacity','number'),F('price','Price','number'),F('schedule','Schedule','textarea')],secondary:{team:['name','role','specialization','photo_url','phone','email','bio'],memberships:['name','price','billing_interval','benefits','image_url'],packages:['name','price','expiry_days','included_services','image_url'],products:['name','brand','sku','image_url','sale_price','stock_qty'],attendance:['member_name','date','class_name','status']}},
 retail_grocery:{primary:'Products',primaryIcon:'🛍️',entity:'Product',fields:[F('name','Product Name'),IMAGE(),F('category','Category'),F('brand','Brand'),F('sku','SKU'),F('description','Description','textarea'),F('price','Selling Price','number'),F('cost_price','Cost Price','number'),F('stock_qty','Stock Qty','number'),F('reorder_level','Reorder Level','number'),F('tax_percent','Tax %','number')],secondary:{categories:['name','image_url','description'],suppliers:['name','phone','email','address'],customers:['name','phone','email','address','notes'],delivery:['name','phone','address','delivery_fee','status']}},
 fashion:{primary:'Products & Collections',primaryIcon:'👗',entity:'Product',fields:[F('name','Product Name'),IMAGE(),GALLERY,F('collection','Collection'),F('category','Category'),F('sku','SKU'),F('size','Sizes'),F('color','Colors'),F('description','Description','textarea'),F('price','Price','number'),F('sale_price','Sale Price','number'),F('stock_qty','Stock Qty','number')],secondary:{collections:['name','description','image_url','season'],categories:['name','image_url'],team:['name','role','photo_url','bio'],offers:['title','description','image_url','discount_value']}},
 jewellery:{primary:'Jewellery Products',primaryIcon:'💎',entity:'Jewellery Item',fields:[F('name','Item Name'),IMAGE(),GALLERY,F('collection','Collection'),F('category','Category'),F('material','Material'),F('purity','Purity'),F('weight','Weight'),F('size','Size'),F('stone','Stone'),F('certificate','Certification'),F('sku','SKU'),F('price','Price','number'),F('stock_qty','Stock Qty','number')],secondary:{collections:['name','description','image_url'],certificates:['certificate_number','item_name','issuer','date','document_url'],team:['name','role','photo_url','phone','email'],customers:['name','phone','email','address']}},
 electronics_mobile:{primary:'Products & Devices',primaryIcon:'📱',entity:'Product / Device',fields:[F('name','Product / Model'),IMAGE(),GALLERY,F('brand','Brand'),F('model','Model'),F('variant','Variant'),F('sku','SKU'),F('imei','IMEI / Serial'),F('warranty','Warranty'),F('price','Price','number'),F('sale_price','Sale Price','number'),F('stock_qty','Stock Qty','number')],secondary:{brands:['name','logo_url','description'],suppliers:['name','phone','email','address'],repairs:['device','customer_name','issue','status','estimate','notes'],customers:['name','phone','email','address']}},
 automotive:{primary:'Automotive Services',primaryIcon:'🚗',entity:'Service',fields:[F('name','Service Name'),IMAGE(),F('category','Category'),F('description','Description','textarea'),F('price','Starting Price','number'),F('duration_minutes','Duration (min)','number'),F('parts_required','Parts / Materials'),F('online_booking','Online Booking','boolean')],secondary:{vehicles:['name','registration','make','model','year','vin','image_url','owner_name'],team:['name','role','specialization','photo_url','phone','email'],parts:['name','sku','brand','image_url','stock_qty','reorder_level'],jobs:['job_number','vehicle','customer_name','service','status','estimate','notes']}},
 real_estate:{primary:'Property Listings',primaryIcon:'🏠',entity:'Property',fields:[F('name','Property Title'),IMAGE(),GALLERY,F('property_type','Property Type'),F('listing_type','Sale / Rent'),F('location','Location'),F('price','Price','number'),F('bedrooms','Bedrooms','number'),F('bathrooms','Bathrooms','number'),F('area','Area'),F('amenities','Amenities','textarea'),F('description','Description','textarea'),F('status','Status')],secondary:{team:['name','role','photo_url','phone','email','bio'],locations:['name','city','state','description','image_url'],leads:['name','phone','email','requirement','budget','status'],viewings:['property','customer','agent','date','time','status']}},
 travel:{primary:'Travel Packages',primaryIcon:'✈️',entity:'Travel Package',fields:[F('name','Package Name'),IMAGE(),GALLERY,F('destination','Destination'),F('duration','Duration'),F('price','Price','number'),F('availability','Availability'),F('itinerary','Itinerary','textarea'),F('inclusions','Inclusions','textarea'),F('exclusions','Exclusions','textarea'),F('description','Description','textarea')],secondary:{destinations:['name','country','description','image_url'],team:['name','role','photo_url','phone','email','bio'],activities:['name','description','image_url','price','duration'],bookings:['customer_name','package','date','guests','status']}},
 education_coaching:{primary:'Courses & Programs',primaryIcon:'🎓',entity:'Course',fields:[F('name','Course Name'),IMAGE(),F('category','Category'),F('description','Description','textarea'),F('duration','Duration'),F('fee','Fee','number'),F('mode','Online / Offline'),F('capacity','Capacity','number'),F('syllabus','Syllabus','textarea')],secondary:{team:['name','role','qualification','specialization','photo_url','email','bio'],batches:['name','course','start_date','end_date','schedule','capacity'],students:['name','phone','email','course','batch','admission_date'],events:['name','date','image_url','description']}},
 legal:{primary:'Legal Services',primaryIcon:'⚖️',entity:'Legal Service',fields:[F('name','Service / Practice Area'),IMAGE(),F('description','Description','textarea'),F('fee','Starting Fee','number'),F('duration_minutes','Consultation Duration','number'),F('online_booking','Online Consultation','boolean')],secondary:{team:['name','role','specialization','qualification','photo_url','phone','email','bio'],clients:['name','phone','email','company','address','notes'],matters:['title','client','matter_type','status','next_date','notes'],documents:['name','client','matter','document_url']}},
 ca_accounting_tax:{primary:'Professional Services',primaryIcon:'📊',entity:'Service',fields:[F('name','Service Name'),IMAGE(),F('category','Category'),F('description','Description','textarea'),F('fee','Starting Fee','number'),F('billing_type','Billing Type'),F('online_enquiry','Online Enquiry','boolean')],secondary:{team:['name','role','qualification','specialization','photo_url','email','bio'],clients:['name','phone','email','company','address','tax_id'],engagements:['title','client','service','start_date','due_date','status'],tasks:['title','client','due_date','status','notes']}},
 it_agency:{primary:'Services & Projects',primaryIcon:'💻',entity:'Service / Project',fields:[F('name','Name'),IMAGE(),GALLERY,F('type','Service / Project'),F('description','Description','textarea'),F('price','Starting Price','number'),F('duration','Timeline'),F('technologies','Technologies'),F('featured','Featured','boolean')],secondary:{team:['name','role','specialization','photo_url','email','bio'],clients:['name','phone','email','company','website'],leads:['name','phone','email','company','requirement','budget','status'],case_studies:['name','image_url','description','results','url']}},
 repair_maintenance:{primary:'Repair Services',primaryIcon:'🔧',entity:'Service',fields:[F('name','Service Name'),IMAGE(),F('category','Category'),F('description','Description','textarea'),F('price','Starting Price','number'),F('duration_minutes','Duration (min)','number'),F('parts_required','Parts / Materials'),F('online_booking','Online Booking','boolean')],secondary:{team:['name','role','specialization','photo_url','phone','email'],jobs:['job_number','customer_name','asset','service','status','estimate','notes'],parts:['name','sku','brand','image_url','stock_qty','reorder_level'],customers:['name','phone','email','address','notes']}},
 cleaning:{primary:'Cleaning Services',primaryIcon:'🧹',entity:'Cleaning Service',fields:[F('name','Service Name'),IMAGE(),F('category','Category'),F('description','Description','textarea'),F('price','Starting Price','number'),F('duration_minutes','Duration (min)','number'),F('service_area','Service Area'),F('recurring','Recurring Available','boolean'),F('online_booking','Online Booking','boolean')],secondary:{team:['name','role','photo_url','phone','email'],areas:['name','city','pincode','travel_fee'],bookings:['customer_name','service','date','time','address','status'],packages:['name','price','included_services','image_url']}},
 veterinary:{primary:'Veterinary Services',primaryIcon:'🐕',entity:'Veterinary Service',fields:[F('name','Service Name'),IMAGE(),F('category','Category'),F('description','Description','textarea'),F('fee','Fee','number'),F('duration_minutes','Duration (min)','number'),F('online_booking','Online Booking','boolean')],secondary:{team:['name','specialization','qualification','photo_url','phone','email','bio'],pets:['name','species','breed','dob','gender','owner_name','photo_url','notes'],vaccinations:['pet_name','vaccine','date','next_due','notes'],patients:['name','owner_name','phone','species','breed','notes']}},
 photography:{primary:'Photography Packages',primaryIcon:'📸',entity:'Package',fields:[F('name','Package Name'),IMAGE(),GALLERY,F('category','Category'),F('description','Description','textarea'),F('price','Price','number'),F('duration','Duration'),F('deliverables','Deliverables','textarea'),F('locations','Locations'),F('featured','Featured','boolean')],secondary:{team:['name','role','specialization','photo_url','phone','email','bio'],portfolio:['name','image_url','gallery','category','description','url'],albums:['name','cover_image_url','description','date'],bookings:['customer_name','package','date','venue','status']}},
 events:{primary:'Events & Packages',primaryIcon:'🎉',entity:'Event / Package',fields:[F('name','Event / Package Name'),IMAGE(),GALLERY,F('event_type','Event Type'),F('description','Description','textarea'),F('price','Starting Price','number'),F('capacity','Capacity','number'),F('venue','Venue'),F('date','Date','date'),F('featured','Featured','boolean')],secondary:{team:['name','role','photo_url','phone','email','bio'],venues:['name','location','capacity','price','image_url','amenities'],vendors:['name','category','phone','email','image_url','notes'],bookings:['client','event','date','guests','status']}},
 coworking:{primary:'Workspace Inventory',primaryIcon:'🏢',entity:'Space',fields:[F('name','Space Name'),IMAGE(),F('space_type','Space Type'),F('description','Description','textarea'),F('capacity','Capacity','number'),F('price','Price','number'),F('billing_interval','Billing Interval'),F('amenities','Amenities','textarea'),F('available','Available','boolean')],secondary:{team:['name','role','photo_url','phone','email'],rooms:['name','room_type','capacity','price','image_url','amenities'],memberships:['name','price','billing_interval','benefits','image_url'],members:['name','phone','email','company','membership','start_date','status']}},
 logistics:{primary:'Logistics Services',primaryIcon:'🚚',entity:'Service',fields:[F('name','Service Name'),IMAGE(),F('service_type','Service Type'),F('description','Description','textarea'),F('base_rate','Base Rate','number'),F('delivery_time','Delivery Time'),F('service_area','Service Area'),F('active','Active','boolean')],secondary:{vehicles:['name','vehicle_type','registration','capacity','image_url','status'],team:['name','role','phone','email','photo_url','license_number'],shipments:['tracking_number','customer_name','origin','destination','weight','status','date'],warehouses:['name','location','capacity','image_url']}},
 construction_home_services:{primary:'Home Services',primaryIcon:'🏗️',entity:'Service',fields:[F('name','Service Name'),IMAGE(),F('category','Category'),F('description','Description','textarea'),F('starting_price','Starting Price','number'),F('duration','Estimated Duration'),F('service_area','Service Area'),F('online_enquiry','Online Enquiry','boolean')],secondary:{team:['name','role','specialization','photo_url','phone','email'],projects:['name','image_url','description','client','budget','status','start_date','end_date'],materials:['name','brand','sku','image_url','stock_qty','unit_cost'],visits:['customer','project','date','time','address','status']}},
 ecommerce:{primary:'Products',primaryIcon:'🛒',entity:'Product',fields:[F('name','Product Name'),IMAGE(),GALLERY,F('category','Category'),F('brand','Brand'),F('sku','SKU'),F('description','Description','textarea'),F('price','Price','number'),F('sale_price','Sale Price','number'),F('stock_qty','Stock Qty','number'),F('featured','Featured','boolean')],secondary:{categories:['name','image_url','description'],customers:['name','phone','email','address'],coupons:['title','code','discount_type','discount_value','expires_at'],shipping:['name','price','delivery_time','description']}},
 saas_subscription:{primary:'Plans & Pricing',primaryIcon:'☁️',entity:'Plan',fields:[F('name','Plan Name'),IMAGE(),F('description','Description','textarea'),F('price','Price','number'),F('billing_interval','Billing Interval'),F('trial_days','Trial Days','number'),F('features','Features','textarea'),F('usage_limit','Usage Limit'),F('featured','Featured','boolean')],secondary:{features:['name','description','image_url','included'],customers:['name','email','company','plan','status'],subscriptions:['customer','plan','start_date','renewal_date','status'],testimonials:['name','company','photo_url','quote','rating']}},
 creator_personal_brand:{primary:'Creator Offerings',primaryIcon:'👤',entity:'Offering',fields:[F('name','Offering Name'),IMAGE(),GALLERY,F('type','Type'),F('description','Description','textarea'),F('price','Price','number'),F('duration','Duration'),F('booking','Booking Available','boolean'),F('featured','Featured','boolean')],secondary:{content:['title','image_url','content_type','description','url','published_at'],audience:['name','email','phone','source','notes'],sponsors:['name','logo_url','contact','website','notes'],courses:['name','image_url','description','price','duration']}},
 non_profit:{primary:'Programs & Causes',primaryIcon:'🤝',entity:'Program',fields:[F('name','Program / Cause'),IMAGE(),GALLERY,F('category','Category'),F('description','Description','textarea'),F('goal','Goal','number'),F('raised','Raised','number'),F('location','Location'),F('status','Status')],secondary:{team:['name','role','photo_url','phone','email','bio'],campaigns:['name','image_url','description','goal','raised','start_date','end_date'],donors:['name','phone','email','amount','last_donation'],volunteers:['name','phone','email','role','availability'] }},
 other:{primary:'Products / Services',primaryIcon:'•',entity:'Item / Service',fields:[F('name','Name'),IMAGE(),GALLERY,F('category','Category'),F('description','Description','textarea'),F('price','Price','number'),F('duration','Duration'),F('featured','Featured','boolean')],secondary:{team:['name','role','photo_url','phone','email','bio'],customers:['name','phone','email','address','notes'],leads:['name','phone','email','requirement','budget','status'],bookings:['customer','item','date','time','status']}}
};

const WORKFLOW_FIELDS = {
 appointments:['reference','customer_name','service','staff','resource','date','time','duration_minutes','status','amount','notes'],
 walkins:['customer_name','service','staff','arrival_time','status','notes'],
 waitlist:['customer_name','service','preferred_date','preferred_time','staff','status','notes'],
 bookings:['reference','customer_name','service','date','time','guests','amount','status','notes'],
 orders:['reference','customer_name','items','amount','payment_status','fulfillment_status','notes'],
 payments:['reference','customer_name','amount','method','status','paid_at','notes'],
 invoices:['invoice_number','customer_name','amount','tax','status','due_date','notes'],
 inventory:['name','sku','image_url','category','stock_qty','reorder_level','unit_cost','status'],
 purchases:['reference','supplier','items','amount','status','date','notes'],
 commissions:['staff','reference','amount','rate','status','date','notes'],
 payroll:['staff','period','gross_amount','deductions','net_amount','status','paid_at','notes'],
 loyalty:['customer_name','points','tier','balance','status','notes'],
 reviews:['customer_name','rating','review','source','status','reply'],
 marketing:['name','channel','audience','message','scheduled_at','status'],
 reports:['name','period','metric','value','notes'],
 online_booking:['service','staff','date','time','deposit','confirmation','status'],
 leads:['name','phone','email','source','requirement','budget','status','notes'],
 analytics:['name','period','metric','value','notes'],
 support:['reference','customer_name','subject','priority','status','notes'],
 subscriptions:['customer','plan','start_date','renewal_date','amount','status'],
 refunds:['reference','customer_name','amount','reason','status','date'],
 returns:['reference','customer_name','order','reason','status','date'],
 shipping:['name','price','delivery_time','description','active'],
 discounts:['title','code','discount_type','discount_value','starts_at','expires_at','status'],
 faq:['question','answer','sort_order','active'],
 gallery:['title','image_url','description','sort_order'],
 testimonials:['name','company','photo_url','quote','rating'],
 faq_items:['question','answer','sort_order','active'],
};
const makeWorkflowFields=(key)=>(WORKFLOW_FIELDS[key]||['name','image_url','description','status','notes']).map(k=>typeof k==='string'?k:k);
const COMMON_WORKFLOW_MODULES=['customers','leads','appointments','bookings','payments','invoices','reviews','marketing','reports','online_booking'];
const commerceModules=['inventory','products','purchases','orders','refunds','returns','shipping','discounts','loyalty'];
const serviceModules=['appointments','walkins','waitlist','customers','resources','payments','invoices','commissions','payroll','memberships','packages','gift_cards','loyalty','reviews','marketing','reports','online_booking'];
const domainWorkflowModules={
 salon:serviceModules,
 barber_shop:serviceModules,
 spa_wellness:serviceModules,
 clinic_hospital:['departments','patients','appointments','walkins','waitlist','billing','payments','prescriptions','lab','insurance','reviews','marketing','reports','online_booking'],
 dentist_doctor:['patients','appointments','walkins','waitlist','billing','payments','prescriptions','followups','reviews','marketing','reports','online_booking'],
 pharmacy:[...commerceModules,'customers','prescriptions','delivery','payments','reports'],
 gym_yoga:['members','memberships','packages','classes','schedules','attendance','payments','customers','marketing','loyalty','reviews','reports','online_booking'],
 retail_grocery:[...commerceModules,'customers','delivery','payments','reports','reviews'],
 fashion:[...commerceModules,'customers','wishlist','payments','reviews','marketing','reports'],
 jewellery:[...commerceModules,'customers','certificates','wishlist','payments','reviews','reports'],
 electronics_mobile:[...commerceModules,'customers','sales','repairs','warranty','payments','reviews','reports'],
 automotive:['vehicles','appointments','customers','jobs','parts','inventory','estimates','invoices','payments','service_history','reviews','reports'],
 real_estate:['properties','locations','agents','leads','enquiries','viewings','bookings','documents','offers','customers','reports'],
 travel:['destinations','tours','packages','activities','vehicles','agents','bookings','customers','payments','offers','reviews','reports'],
 education_coaching:['courses','programs','teachers','students','batches','schedules','admissions','attendance','fees','exams','certificates','payments','reports'],
 legal:['team','clients','leads','matters','documents','appointments','billing','payments','tasks','reviews','reports'],
 ca_accounting_tax:['team','clients','leads','engagements','documents','compliance','deadlines','invoices','payments','tasks','reports'],
 it_agency:['services','team','projects','portfolio','clients','leads','proposals','packages','tasks','invoices','payments','case_studies','reviews','reports'],
 repair_maintenance:['services','team','customers','jobs','appointments','parts','inventory','estimates','invoices','payments','service_history','reviews','reports'],
 cleaning:['services','packages','team','areas','bookings','customers','recurring_jobs','schedules','addons','invoices','payments','reviews','reports','online_booking'],
 veterinary:['team','services','pets','patients','appointments','medical_records','vaccinations','prescriptions','pharmacy','billing','payments','followups','reviews','reports'],
 photography:['services','packages','portfolio','albums','team','availability','bookings','clients','contracts','invoices','payments','reviews','reports'],
 events:['event_types','packages','venues','services','vendors','team','bookings','customers','guests','tickets','payments','gallery','offers','reports'],
 coworking:['locations','rooms','spaces','memberships','plans','bookings','members','visitors','amenities','payments','invoices','access','reports'],
 logistics:['services','vehicles','drivers','customers','shipments','orders','tracking','routes','warehouses','rates','invoices','payments','documents','reports'],
 construction_home_services:['services','projects','team','workers','materials','suppliers','estimates','jobs','schedules','customers','invoices','payments','gallery','before_after','reviews','reports'],
 ecommerce:[...commerceModules,'categories','customers','cart','wishlist','payments','shipping','reviews','analytics'],
 saas_subscription:['products','plans','features','pricing','subscriptions','customers','trials','coupons','invoices','payments','usage','support','knowledge_base','testimonials','analytics'],
 creator_personal_brand:['content','services','courses','products','digital_products','portfolio','bookings','customers','sponsors','testimonials','offers','newsletter','gallery','seo','analytics'],
 non_profit:['causes','programs','projects','team','volunteers','donors','donations','campaigns','events','beneficiaries','gallery','stories','testimonials','reports'],
 other:['services','products','categories','team','customers','leads','appointments','orders','offers','gallery','testimonials','reviews','payments','reports']
};
export function getDomainSchema(type){
 const base=schemas[type]||schemas.other;
 const existing=base.secondary||{};
 const extra=domainWorkflowModules[type]||domainWorkflowModules.other;
 const secondary={...existing};
 for(const key of extra){ if(!secondary[key]) secondary[key]=makeWorkflowFields(key); }
 return {...base,secondary};
}
export function getCommonProfileFields(){return COMMON_PROFILE;}
