'use client';
import {useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {supabase} from '../../lib/supabase';

const DEFAULT_CARDS=[
 {title:'Flex & Banner Printing',category:'OUTDOOR PRINT',description:'Sharp, durable flex banners for shops, events, openings and promotions.',priceText:'Custom quote',image_url:''},
 {title:'Acrylic & 3D Boards',category:'SIGNAGE',description:'Premium acrylic, 3D letter and illuminated board solutions.',priceText:'Custom quote',image_url:''},
 {title:'Neon & Glow Signs',category:'LIGHTING',description:'Eye-catching neon and glow signage for high-visibility storefronts.',priceText:'Custom quote',image_url:''},
 {title:'Running Display',category:'DIGITAL DISPLAY',description:'Dynamic running displays and digital signage for businesses and public spaces.',priceText:'Custom quote',image_url:''},
 {title:'Digital Printing',category:'PRINTING',description:'Posters, stickers, brochures, visiting cards and promotional print work.',priceText:'Custom quote',image_url:''},
 {title:'Designing Work',category:'DESIGN',description:'Creative artwork and production-ready design for every printing requirement.',priceText:'Available',image_url:''}
];
const DEFAULT_CONTENT={template:'print_shop',heroOverlayColor:'#0b3b73',heroOverlayOpacity:0.72,heroVideoUrl:'',sliderTitle:'Featured Work',galleryTitle:'Our Work & Gallery',eyebrow:'PRINTING · SIGNAGE · DESIGN',heroTitle:'Printing work that makes your business impossible to miss.',heroText:'Premium printing, signage and creative design for shops, brands, events and businesses.',primaryCta:'Get a Quote →',secondaryCta:'WhatsApp Us',aboutTitle:'From artwork to final installation.',aboutText:'One place for professional printing, signage and design — with clear communication, quality production and dependable delivery.',serviceKicker:'WHAT WE DO',serviceTitle:'Printing & signage, presented professionally.',serviceText:'Choose a service, share your requirement and let the shop handle the production from design to delivery.',whyKicker:'WHY CHOOSE US',whyTitle:'Made to look good. Built to last.',why1:'Production-ready quality',why2:'Custom sizes & materials',why3:'Design support available',why4:'Fast local service',ctaKicker:'READY TO PRINT?',ctaTitle:'Send your requirement. We will prepare the right solution.',ctaText:'Share your size, quantity, design or reference image and get a quick quote.',contactTitle:'Let’s make your next sign stand out.',contactText:'Call or WhatsApp the shop for pricing, design and production details.',phoneLabel:'CALL',whatsappLabel:'WHATSAPP',locationLabel:'LOCATION',footerText:'Printing · Signage · Design',gstin:'',cards:DEFAULT_CARDS};
function mergeContent(landing,business){const p=landing?.theme?.printShop||{};return {...DEFAULT_CONTENT,...p,cards:Array.isArray(p.cards)&&p.cards.length?p.cards:DEFAULT_CARDS,heroTitle:p.heroTitle||`Premium printing & signage by ${business?.name||'your local print studio'}`};}

export default function ItAgencyPremiumLanding(){
 const search=useSearchParams(); const businessId=search.get('business')||search.get('id')||'';
 const [business,setBusiness]=useState(null),[landing,setLanding]=useState(null),[records,setRecords]=useState([]),[media,setMedia]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[form,setForm]=useState({name:'',phone:'',email:'',requirement:''}),[sent,setSent]=useState(false),[sending,setSending]=useState(false);
 useEffect(()=>{(async()=>{if(!businessId){setLoading(false);setError('Business ID is required.');return;}try{const token=(await supabase.auth.getSession()).data.session?.access_token;const r=await fetch(`/api/business/landing?business=${encodeURIComponent(businessId)}&type=it_agency`,{headers:token?{Authorization:`Bearer ${token}`}:{}});const j=await r.json();if(!r.ok)throw new Error(j.error||'Unable to load business website');setBusiness(j.business);setLanding(j.landing);setRecords(j.records||[]);setMedia(j.media||[]);}catch(e){setError(e.message)}finally{setLoading(false)}})()},[businessId]);
 const c=useMemo(()=>mergeContent(landing,business),[landing,business]);
 const phone=business?.phone||''; const wa=business?.whatsapp||((phone.replace(/\D/g,'').length>=10)?`https://wa.me/91${phone.replace(/\D/g,'').slice(-10)}`:'');
 const cards=useMemo(()=>{const saved=records.filter(r=>r.module_key==='primary'&&r.status!=='inactive'&&r.data?.show_on_website!==false).map(r=>({title:r.title,category:r.data?.category||'PRINTING',description:r.data?.description||'',priceText:r.data?.priceText||(r.data?.price!=null?`₹${Number(r.data.price).toLocaleString('en-IN')}`:'Custom quote'),image_url:r.data?.image_url||'',featured:!!r.data?.featured}));return saved.length?saved:c.cards;},[records,c.cards]);
 const gallery=media.filter(m=>m.media_type==='gallery'&&m.url); const slider=media.filter(m=>m.media_type==='slider'&&m.url); const featureSlides=(slider.length?slider:cards.filter(x=>x.image_url).map((x,i)=>({id:`card-${i}`,url:x.image_url,alt_text:x.title,title:x.title}))).slice(0,8);
 const reviews=records.filter(r=>r.module_key==='reviews'&&r.status!=='inactive');
 async function submitLead(e){e.preventDefault();if(!form.name||!form.phone||!form.requirement)return;setSending(true);try{const r=await fetch('/api/business/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({businessId,type:'it_agency',...form})});if(!r.ok)throw new Error('Unable to send enquiry');setSent(true);setForm({name:'',phone:'',email:'',requirement:''});}catch(e){setError(e.message)}finally{setSending(false)}}
 if(loading)return <main className="it-print-site"><div className="it-print-loading">Loading business website…</div></main>;
 if(error||!business)return <main className="it-print-site"><div className="it-print-loading"><h2>{error||'Business not found.'}</h2><p>Check the business ID and website publication status.</p></div></main>;
 const address=[business.address,business.city,business.state,business.country].filter(Boolean).join(', '); const hero=landing ? (landing.hero_image_url||'') : (business.cover_image||''); const logo=landing ? (landing.logo_url||'') : (business.logo||''); const overlayColor=c.heroOverlayColor||'#0b3b73'; const overlayOpacity=Number(c.heroOverlayOpacity??0.72);
 return <main className="it-print-site" style={{'--print-accent':landing?.theme?.accent||'#e11d2e'}}>
  <header className="it-print-hero" style={{'--hero-overlay':overlayColor,'--hero-opacity':overlayOpacity,...(hero?{backgroundImage:`url(${hero})`}: {})}}>{c.heroVideoUrl&&<video className="it-print-hero-video" src={c.heroVideoUrl} autoPlay muted loop playsInline poster={hero||undefined}/>}<div className="it-print-hero-overlay"/>
   <nav className="it-print-nav"><a href="#top" className="it-print-brand">{logo?<img src={logo} alt={business.name}/>:<span className="it-print-brand-mark">PS</span>}<strong>{business.name}</strong></a><div><a href="#services">Services</a><a href="#about">About</a><a href="#work">Work</a><a href="#contact">Contact</a>{phone&&<a className="it-print-nav-cta" href={`tel:${phone}`}>Call Now</a>}</div></nav>
   <div className="it-print-hero-inner"><span className="it-print-eyebrow">{c.eyebrow}</span><h1>{c.heroTitle}</h1>
    <p>{c.heroText}</p><div className="it-print-actions">{phone&&<a className="it-print-btn primary" href={`tel:${phone}`}>{c.primaryCta}</a>}{wa&&<a className="it-print-btn" href={wa} target="_blank" rel="noreferrer">{c.secondaryCta}</a>}</div><div className="it-print-proof"><span>✓ Quality production</span><span>✓ Custom sizes</span><span>✓ Design support</span><span>✓ Local service</span></div></div>
  </header>
  <section className="it-print-hero-bottom" aria-label="Printing and signage capabilities">
   <div className="it-print-hero-bottom-inner">
    <div className="it-print-capability"><span className="it-print-capability-icon">✦</span><div><b>Graphic Design</b><small>Creative artwork &amp; layouts</small></div></div>
    <div className="it-print-capability"><span className="it-print-capability-icon">▣</span><div><b>Flex Printing</b><small>Sharp outdoor prints</small></div></div>
    <div className="it-print-capability"><span className="it-print-capability-icon">◇</span><div><b>Acrylic Signs</b><small>Premium 3D boards</small></div></div>
    <div className="it-print-capability"><span className="it-print-capability-icon">✧</span><div><b>Neon Signs</b><small>Glow &amp; illuminated signs</small></div></div>
    <div className="it-print-capability"><span className="it-print-capability-icon">▤</span><div><b>Digital Print</b><small>Cards, posters &amp; brochures</small></div></div>
    <div className="it-print-capability"><span className="it-print-capability-icon">⌁</span><div><b>Running Display</b><small>Digital display solutions</small></div></div>
    <div className="it-print-capability"><span className="it-print-capability-icon">✓</span><div><b>Installation</b><small>Professional fitting</small></div></div>
   </div>
  </section>
  <section id="about" className="it-print-section it-print-about"><div><span className="it-print-kicker">{c.eyebrow}</span><h2>{c.aboutTitle}</h2><p>{c.aboutText}</p></div><div className="it-print-about-card"><b>{business.name}</b><span>{address}</span>{c.gstin&&<span><strong>GSTIN:</strong> {c.gstin}</span>}{business.email&&<a href={`mailto:${business.email}`}>{business.email}</a>}{phone&&<a href={`tel:${phone}`}>{phone}</a>}</div></section>
  <section className="it-print-bridge" aria-label="From artwork to production"><div className="it-print-bridge-inner"><div className="it-print-bridge-copy"><span className="it-print-kicker">FROM ARTWORK TO INSTALLATION</span><h2>One workflow. From design to the finished sign.</h2><p>Artwork, printing, finishing and installation — connected in one professional production flow.</p></div><div className="it-print-bridge-steps"><div><span>01</span><b>Design</b><small>Artwork ready for production.</small></div><div><span>02</span><b>Print & Build</b><small>Materials, colour and finishing.</small></div><div><span>03</span><b>Install</b><small>Delivered and fitted professionally.</small></div></div></div></section>
  <section id="services" className="it-print-section"><div className="it-print-section-head"><div><span className="it-print-kicker">{c.serviceKicker}</span><h2>{c.serviceTitle}</h2></div><p>{c.serviceText}</p></div><div className="it-print-card-grid">{cards.map((card,i)=><article className="it-print-card" key={`${card.title}-${i}`}>{card.image_url?<img src={card.image_url} alt={card.title}/>:<div className="it-print-card-placeholder"><span>{String(i+1).padStart(2,'0')}</span><b>{card.category}</b></div>}<div className="it-print-card-body"><span className="it-print-card-tag">{card.category}</span><h3>{card.title}</h3><p>{card.description}</p><strong>{card.priceText}</strong><a href="#contact">Enquire →</a></div></article>)}</div></section>
  {slider.length>0&&<section className="it-print-section it-print-slider-section"><div className="it-print-section-head"><div><span className="it-print-kicker">FEATURED WORK</span><h2>{c.sliderTitle||'Featured Work'}</h2></div><p>Selected printing, signage and design work.</p></div><div className="it-print-slider" aria-label="Featured work auto slider"><div className="it-print-slider-track">{[...slider,...slider].map((m,i)=><img key={`${m.id||i}-${i}`} src={m.url} alt={m.alt_text||m.title||'Featured work'} loading={i>2?'lazy':'eager'}/>)}</div></div></section>}
  <section className="it-print-dark"><div className="it-print-section"><span className="it-print-kicker">{c.whyKicker}</span><h2>{c.whyTitle}</h2><div className="it-print-why-grid">{[c.why1,c.why2,c.why3,c.why4].map((x,i)=><div key={i}><span>0{i+1}</span><b>{x}</b></div>)}</div></div></section>
  {gallery.length>0&&<section id="work" className="it-print-section"><span className="it-print-kicker">OUR WORK</span><h2>{c.galleryTitle||'Our Work & Gallery'}</h2><div className="it-print-gallery">{gallery.map((m,i)=><img key={m.id||i} src={m.url} alt={m.alt_text||m.title||'Print work'}/>)}</div></section>}
  {reviews.length>0&&<section className="it-print-section"><span className="it-print-kicker">CLIENT REVIEWS</span><h2>Trusted by businesses.</h2><div className="it-print-review-grid">{reviews.slice(0,6).map(r=><article key={r.id}><b>{r.data?.name||r.title}</b><span>{'★'.repeat(Math.max(1,Math.min(5,Number(r.data?.rating)||5)))}</span><p>“{r.data?.quote||''}”</p><small>{r.data?.company||r.data?.source||''}</small></article>)}</div></section>}
  <section className="it-print-cta"><div><span className="it-print-kicker">{c.ctaKicker}</span><h2>{c.ctaTitle}</h2><p>{c.ctaText}</p></div>{wa&&<a className="it-print-btn primary" href={wa} target="_blank" rel="noreferrer">WhatsApp for Quote →</a>}</section>
  <section id="contact" className="it-print-contact"><div><span className="it-print-kicker">CONTACT</span><h2>{c.contactTitle}</h2><p>{c.contactText}</p><div className="it-print-contact-actions">{phone&&<a className="it-print-btn primary" href={`tel:${phone}`}>{c.phoneLabel}: {phone}</a>}{wa&&<a className="it-print-btn" href={wa} target="_blank" rel="noreferrer">{c.whatsappLabel}</a>}<div><small>{c.locationLabel}</small><b>{address}</b></div></div></div><form className="it-print-enquiry" onSubmit={submitLead}><div><span>QUICK ENQUIRY</span><h3>Tell us what you want printed.</h3></div><input required placeholder="Your name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required placeholder="Phone number" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input type="email" placeholder="Email (optional)" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><textarea required rows="4" placeholder="Size, quantity, material, design or reference…" value={form.requirement} onChange={e=>setForm({...form,requirement:e.target.value})}/><button className="it-print-btn primary" disabled={sending}>{sending?'Sending…':'Send Enquiry →'}</button>{sent&&<small className="it-print-success">✓ Enquiry sent successfully.</small>}</form></section>
  <footer className="it-print-footer"><span>© {new Date().getFullYear()} {business.name}</span><span>{c.footerText} · Powered by Anaira</span></footer>
 </main>;
}
