'use client';
import {Suspense,useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {supabase} from '../../lib/supabase';

function SalonLandingInner(){
 const search=useSearchParams(); const id=search.get('business')||search.get('id');
 const [b,setB]=useState(null),[l,setL]=useState(null),[services,setServices]=useState([]),[staff,setStaff]=useState([]),[memberships,setMemberships]=useState([]),[packages,setPackages]=useState([]),[offers,setOffers]=useState([]),[loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{
  if(!id){setLoading(false);return}
  try{
   const token=(await supabase.auth.getSession()).data.session?.access_token;
   const r=await fetch(`/api/business/landing?business=${encodeURIComponent(id)}&type=salon`,{headers:token?{Authorization:`Bearer ${token}`}:{}});
   const d=await r.json();
   if(!r.ok) throw new Error(d.error||'Unable to load salon website');
   setB(d.business);setL(d.landing);setServices(d.services||[]);setStaff(d.staff||[]);setMemberships(d.memberships||[]);setPackages(d.packages||[]);setOffers(d.offers||[]);
  }catch(e){setB(null);setErr(e.message)}finally{setLoading(false)}
 })()},[id]);
 const [err,setErr]=useState('');
 if(loading)return <main className="salon-site-loading">Loading your salon experience…</main>;
 if(!b)return <main className="salon-site-loading"><strong>{err||'Salon not found.'}</strong><p>Check the business ID, login session, and whether the website is published.</p></main>;
 const theme=l?.theme||{}; const sections=theme.sections||{}; const accent=theme.accent||'#c8a35b'; const hero=l?.hero_image_url; const gallery=theme.gallery_urls||[]; const booking=theme.booking_url||`/business/salon/appointments?business=${id}`; const about=theme.about||b.description||'A refined salon experience built around expert stylists, thoughtful service and beautiful results.';
 const scroll=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'});
 return <main className="salon-site" style={{'--salon-accent':accent}}>
  <nav className="salon-site-nav"><a href="#top" className="salon-site-logo">{l?.logo_url?<img src={l.logo_url} alt=""/>:<span>{(b.name||'S').slice(0,1)}</span>}<b>{b.name}</b></a><div className="salon-site-links"><a href="#services">Services</a><a href="#team">Team</a><a href="#offers">Offers</a><a href="#story">About</a><a href="#contact">Contact</a></div><a className="salon-site-book" href={booking}>Book Appointment</a></nav>
  <section id="top" className="salon-hero" style={hero?{backgroundImage:`linear-gradient(90deg,rgba(8,17,13,.88),rgba(8,17,13,.45),rgba(8,17,13,.22)),url(${hero})`}:{}}><div className="salon-hero-copy"><div className="salon-kicker">{b.city||'BEAUTY'} · ESTABLISHED WITH CARE</div><h1>{l?.headline||b.name}</h1><p>{l?.subheadline||'Luxury hair, beauty and self-care — designed around you.'}</p><div className="salon-hero-actions"><a className="salon-gold-btn" href={booking}>Book Your Appointment</a><button className="salon-ghost-btn" onClick={()=>scroll('services')}>Explore Services ↓</button></div><div className="salon-hero-meta"><span>✦ Curated services</span><span>✦ Expert stylists</span><span>✦ Personalised care</span></div></div><div className="salon-hero-card"><span>YOUR NEXT LOOK</span><strong>starts here.</strong><p>Choose your service, preferred stylist and time.</p><a href={booking}>Reserve a slot →</a></div></section>
  {sections.offers!==false&&offers.length>0&&<section id="offers" className="salon-section salon-offers"><SectionHead eyebrow="EXCLUSIVE" title="Signature offers" sub="Thoughtful packages and seasonal privileges for our guests."/><div className="salon-offer-grid">{offers.slice(0,3).map(o=><article key={o.id}><span>{o.discount_type==='percent'?`${o.discount_value}% OFF`:o.discount_type==='fixed'?`₹${o.discount_value} OFF`:'SPECIAL'}</span><h3>{o.title}</h3><p>{o.description}</p><a href={booking}>Claim offer →</a></article>)}</div></section>}
  {sections.services!==false&&<section id="services" className="salon-section"><SectionHead eyebrow="THE MENU" title="Services, styled your way" sub="Every service is configured from your Salon Setup — pricing, duration and images stay in sync."/><div className="salon-service-grid">{services.length?services.map(s=><article className="salon-service-card" key={s.id}>{s.image_url&&<img src={s.image_url} alt=""/>}<div className="salon-service-body"><span>{s.duration_minutes} min</span><h3>{s.name}</h3><p>{s.description||'Personalised salon service delivered by our professional team.'}</p><div><strong>₹{Number(s.price||0).toLocaleString('en-IN')}</strong><a href={booking}>Book →</a></div></div></article>):<Empty text="Add your services in Salon Setup to populate this section."/>}</div></section>}
  {sections.about!==false&&<section id="story" className="salon-story"><div><div className="salon-kicker">OUR PHILOSOPHY</div><h2>{theme.about_title||'Beauty is personal.'}</h2><p>{about}</p><a className="salon-text-link" href={booking}>Experience the salon →</a></div><div className="salon-story-stat"><strong>{services.length||'—'}</strong><span>Signature services</span><strong>{staff.length||'—'}</strong><span>Beauty professionals</span></div></section>}
  {sections.team!==false&&<section id="team" className="salon-section salon-team"><SectionHead eyebrow="THE PEOPLE" title="Meet your beauty team" sub="Profiles and photos come directly from your Salon Setup."/><div className="salon-team-grid">{staff.length?staff.map(s=><article key={s.id}>{s.photo_url?<img src={s.photo_url} alt=""/>:<div className="salon-avatar-large">{s.name?.slice(0,1)}</div>}<div><span>{s.role||'Stylist'}</span><h3>{s.name}</h3><p>{s.bio||'Professional stylist focused on personalised results.'}</p></div></article>):<Empty text="Add stylists in Salon Setup to populate this section."/>}</div></section>}
  {sections.memberships!==false&&memberships.length>0&&<section className="salon-section salon-memberships"><SectionHead eyebrow="MEMBERSHIP" title="Make every visit more rewarding" sub="Flexible plans configured by your salon."/><div className="salon-plan-grid">{memberships.map(m=><article key={m.id}><span>{m.billing_interval}</span><h3>{m.name}</h3><strong>₹{Number(m.price||0).toLocaleString('en-IN')}</strong><ul>{(m.benefits||[]).slice(0,5).map((x,i)=><li key={i}>✓ {x}</li>)}</ul><a href={booking}>Enquire →</a></article>)}</div></section>}
  {sections.packages!==false&&packages.length>0&&<section className="salon-section"><SectionHead eyebrow="PACKAGES" title="Curated beauty journeys" sub="Service bundles with expiry and sessions managed from setup."/><div className="salon-package-grid">{packages.map(p=><article key={p.id}><span>{p.expiry_days} day validity</span><h3>{p.name}</h3><strong>₹{Number(p.price||0).toLocaleString('en-IN')}</strong><p>{p.description}</p><a href={booking}>Explore package →</a></article>)}</div></section>}
  {sections.gallery!==false&&gallery.length>0&&<section className="salon-gallery"><div className="salon-section-head"><div><div className="salon-kicker">THE LOOK</div><h2>Inside the salon</h2></div></div><div className="salon-gallery-grid">{gallery.map((u,i)=><img key={i} src={u} alt="Salon gallery"/> )}</div></section>}
  {sections.testimonials!==false&&<section className="salon-quote"><div className="salon-kicker">A LITTLE LOVE</div><blockquote>“The best salon experiences feel effortless — from the first hello to the final mirror moment.”</blockquote><span>{b.name}</span></section>}
  {sections.booking!==false&&<section className="salon-final-cta"><div><div className="salon-kicker">READY WHEN YOU ARE</div><h2>Your next favourite look is one appointment away.</h2><p>Choose your service and let our team take care of the rest.</p></div><a className="salon-gold-btn" href={booking}>Book Appointment →</a></section>}
  {sections.contact!==false&&<footer id="contact" className="salon-footer"><div><div className="salon-site-logo"><span>{(b.name||'S').slice(0,1)}</span><b>{b.name}</b></div><p>{b.address||[b.city,b.state,b.country].filter(Boolean).join(', ')}</p></div><div><b>Contact</b><p>{b.phone||''}<br/>{b.email||''}</p></div><div><b>Visit</b><p>{b.city||''}<br/>{b.state||''}</p></div><div><b>Book</b><p><a href={booking}>Reserve your appointment →</a></p></div></footer>}
 </main>
}
function SectionHead({eyebrow,title,sub}){return <div className="salon-section-head"><div><div className="salon-kicker">{eyebrow}</div><h2>{title}</h2><p>{sub}</p></div></div>}
function Empty({text}){return <div className="salon-empty-site">{text}</div>}


export default function SalonLanding(props){ return <Suspense fallback={<main className="domain-engine-page"><div className="card">Loading…</div></main>}><SalonLandingInner {...props}/></Suspense>; }
