'use client';
import {Suspense,useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {supabase} from '../../lib/supabase';
const modules=[['appointments','◷','Appointment Book','Calendar, walk-ins, waitlist, reschedule & no-show'],['services','✂','Services','Pricing, duration, add-ons & online booking'],['team','✦','Staff / Stylists','Schedules, commission, targets & leave'],['resources','▣','Resources','Chairs, rooms, beds & equipment'],['pos','₹','POS / Checkout','Services, retail, tips, discounts & payments'],['inventory','▤','Inventory','Products, stock, reorder & consumption'],['memberships','◆','Memberships','Plans, recurring billing & benefits'],['packages','◇','Packages','Sessions, expiry & redemption'],['giftcards','▰','Gift Cards','Issue, sell, redeem & balance'],['loyalty','★','Loyalty','Points, tiers, rewards & referrals'],['marketing','⌁','Marketing','WhatsApp, SMS, email, win-back & rebooking'],['reviews','★','Reviews','Google review requests & AI replies'],['online-booking','↗','Online Booking','Website, Google & social booking'],['landing','◈','Premium Website','Luxury front website builder'],['reports','◒','Reports','Revenue, staff, inventory & retention']];
function SalonDashboardInner(){const s=useSearchParams();const id=s.get('business')||s.get('id');const [b,setB]=useState(null),[counts,setCounts]=useState({});useEffect(()=>{if(!id)return;(async()=>{const [r,a,sv,st,pr,m,p]=await Promise.all([supabase.from('restaurants').select('name,city,state,phone').eq('id',id).maybeSingle(),supabase.from('salon_appointments').select('id',{count:'exact',head:true}).eq('business_id',id),supabase.from('salon_services').select('id',{count:'exact',head:true}).eq('business_id',id).eq('active',true),supabase.from('salon_staff').select('id',{count:'exact',head:true}).eq('business_id',id).eq('active',true),supabase.from('salon_products').select('id',{count:'exact',head:true}).eq('business_id',id).eq('active',true),supabase.from('salon_membership_plans').select('id',{count:'exact',head:true}).eq('business_id',id).eq('active',true),supabase.from('salon_packages').select('id',{count:'exact',head:true}).eq('business_id',id).eq('active',true)]);setB(r.data);setCounts({appointments:a.count||0,services:sv.count||0,staff:st.count||0,products:pr.count||0,memberships:m.count||0,packages:p.count||0})})()},[id]);if(!id)return <main className="salon-empty"><h1>Salon Dashboard</h1><p>Add <code>?business=BUSINESS_ID</code> to open a salon workspace.</p></main>;return <main className="salon-dash"><header className="salon-dash-head"><div><div className="eyebrow">ANAIRA SALON OS · LIVE WORKSPACE</div><h1>{b?.name||'Salon Management'}</h1><p>{[b?.city,b?.state].filter(Boolean).join(' · ')||'Premium salon operations'}</p></div><div className="salon-head-actions"><a className="btn" href={`/business/salon/landing?business=${id}`} target="_blank">Public Website ↗</a><a className="btn primary" href={`/business/salon/setup?business=${id}`}>Salon Setup</a></div></header><div className="salon-kpi-row"><K label="Appointments" v={counts.appointments}/><K label="Services" v={counts.services}/><K label="Stylists" v={counts.staff}/><K label="Products" v={counts.products}/><K label="Memberships" v={counts.memberships}/><K label="Packages" v={counts.packages}/></div><section className="salon-dash-hero"><div><span>THE SALON CONTROL CENTER</span><h2>Run the salon from one connected workspace.</h2><p>Appointments, customer CRM, POS, inventory, staff, memberships, marketing and your premium website are designed to work as one system.</p><a className="salon-gold-btn" href={`/business/salon/setup?business=${id}`}>Configure Salon →</a></div><div className="salon-dash-orbit"><b>CRM</b><b>POS</b><b>BOOKING</b><b>LOYALTY</b><b>MARKETING</b><b>WEBSITE</b></div></section><div className="salon-module-grid">{modules.map(([key,icon,title,desc])=><a key={key} href={`/business/salon/${key}?business=${id}`} className="salon-module-card"><i>{icon}</i><h3>{title}</h3><p>{desc}</p><span>Open module →</span></a>)}</div></main>}
function K({label,v}){return <div className="salon-kpi"><span>{label}</span><strong>{v}</strong><small>Configured in workspace</small></div>}


export default function SalonDashboard(props){ return <Suspense fallback={<main className="domain-engine-page"><div className="card">Loading…</div></main>}><SalonDashboardInner {...props}/></Suspense>; }
