'use client';
import {Suspense,useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {supabase} from '../../lib/supabase';
import {domainTable} from './domainStore';
import {businessConfig} from '../../app/businessTypeConfig';
import {getDomainSchema,getCommonProfileFields} from './BusinessDomainSchemas';

const esc=(s)=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const title=(s)=>String(s||'').replace(/[_-]+/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
const moduleLabel=(key)=>({team:'Team / Staff',resources:'Resources',products:'Products',memberships:'Memberships',packages:'Packages',customers:'Customers',leads:'Leads',projects:'Projects',portfolio:'Portfolio',collections:'Collections',categories:'Categories',offers:'Offers',services:'Services',rooms:'Rooms',patients:'Patients',pets:'Pets',vaccinations:'Vaccinations',bookings:'Bookings',jobs:'Jobs',parts:'Parts / Inventory',vehicles:'Vehicles',shipments:'Shipments',warehouses:'Warehouses',venues:'Venues',vendors:'Vendors',batches:'Batches',students:'Students',courses:'Courses',matters:'Matters',documents:'Documents',engagements:'Engagements',tasks:'Tasks',case_studies:'Case Studies',areas:'Service Areas',events:'Events',spaces:'Spaces',members:'Members',plans:'Plans',features:'Features',subscriptions:'Subscriptions',usage:'Usage',content:'Content',audience:'Audience',sponsors:'Sponsors',programs:'Programs',campaigns:'Campaigns',donors:'Donors',volunteers:'Volunteers',grants:'Grants',testimonials:'Testimonials',followups:'Follow-ups',delivery:'Delivery',repairs:'Repairs',attendance:'Attendance',certificates:'Certificates',prescriptions:'Prescriptions',billing:'Billing',reports:'Reports',inventory:'Inventory',sales:'Sales',orders:'Orders',storefront:'Storefront',tracking:'Tracking',access:'Access',rooms:'Rooms',venues:'Venues',bookings:'Bookings',bookings:'Bookings'})[key]||title(key);

const genericFields=(key)=>{
 const k=key.toLowerCase();
 if(k.includes('team')||k.includes('staff')||k.includes('doctor')||k.includes('lawyer')||k.includes('professional')||k.includes('photographer')||k.includes('trainer')||k.includes('agent')||k.includes('driver')||k.includes('worker')||k.includes('volunteer')||k.includes('vet')) return ['name','role','specialization','qualification','photo_url','phone','email','bio'];
 if(k.includes('product')||k.includes('item')||k.includes('catalog')||k.includes('service')||k.includes('treatment')||k.includes('offering')) return ['name','image_url','category','description','price','duration_minutes','sku','stock_qty','featured'];
 if(k.includes('customer')||k.includes('client')||k.includes('patient')||k.includes('member')||k.includes('donor')||k.includes('student')||k.includes('audience')||k.includes('lead')) return ['name','photo_url','phone','email','company','address','notes','status'];
 if(k.includes('project')||k.includes('case')||k.includes('matter')||k.includes('engagement')||k.includes('program')) return ['name','image_url','description','client','start_date','end_date','status','budget'];
 if(k.includes('booking')||k.includes('appointment')||k.includes('job')||k.includes('shipment')||k.includes('order')) return ['reference','customer_name','service','date','time','status','amount','notes'];
 if(k.includes('room')||k.includes('space')||k.includes('vehicle')||k.includes('warehouse')||k.includes('venue')||k.includes('resource')) return ['name','image_url','type','location','capacity','price','availability','description'];
 return ['name','image_url','description','category','price','status','notes'];
};

function Upload({businessId,onUploaded,multiple=false,label='Upload image(s)'}){
 const [busy,setBusy]=useState(false),[err,setErr]=useState('');
 async function go(e){const files=Array.from(e.target.files||[]);if(!files.length||!businessId)return;setBusy(true);setErr('');const urls=[];for(const f of files){const ext=(f.name.split('.').pop()||'jpg').toLowerCase();const path=`${businessId}/business-${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const q=await supabase.storage.from('anaira-business-assets').upload(path,f,{upsert:false,contentType:f.type});if(q.error){setErr(q.error.message);setBusy(false);return;}const {data}=supabase.storage.from('anaira-business-assets').getPublicUrl(path);urls.push(data.publicUrl);}onUploaded(multiple?urls:urls[0]);setBusy(false);e.target.value='';}
 return <div><label className="business-upload-btn">{busy?'Uploading…':label}<input hidden type="file" accept="image/*" multiple={multiple} onChange={go}/></label>{err&&<small className="business-error">{err}</small>}</div>;
}

function Field({field,value,onChange,businessId}){
 const type=field.type||'text';
 if(type==='boolean') return <label className="business-check"><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/><span>{field.label}</span></label>;
 if(type==='image') return <div className="business-field"><span>{field.label}</span><Upload businessId={businessId} label={value?'Replace image':'Upload image'} onUploaded={onChange}/>{value&&<img src={value} alt="" className="business-form-image"/>}</div>;
 if(type==='gallery') return <div className="business-field"><span>{field.label}</span><Upload businessId={businessId} multiple label="Upload gallery images" onUploaded={urls=>onChange([...(value||[]),...urls])}/>{(value||[]).length>0&&<div className="business-mini-gallery">{value.map((u,i)=><div key={u+i}><img src={u} alt=""/><button type="button" onClick={()=>onChange(value.filter((_,j)=>j!==i))}>×</button></div>)}</div>}</div>;
 if(type==='textarea') return <label className="business-field"><span>{field.label}</span><textarea rows="4" value={value||''} onChange={e=>onChange(e.target.value)} placeholder={field.placeholder||''}/></label>;
 return <label className="business-field"><span>{field.label}</span><input type={type==='number'?'number':type==='date'?'date':'text'} value={value??field.default??''} onChange={e=>onChange(type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)} placeholder={field.placeholder||''}/></label>;
}

function RecordEditor({schema,record,onSaved,businessId,type,moduleKey}){
 const fields=record?schema:(schema||[]); const [data,setData]=useState(record?.data||{}); const [saving,setSaving]=useState(false); const titleValue=data.name||data.title||data.reference||'';
 async function save(e){e.preventDefault();if(!businessId)return;setSaving(true);const titleValue2=data.name||data.title||data.reference||`${moduleLabel(moduleKey)} item`;const payload={business_id:businessId,business_type:type,module_key:moduleKey,title:titleValue2,data,status:data.status||'active',updated_at:new Date().toISOString()};const q=record?await supabase.from(domainTable(type)).update(payload).eq('id',record.id).select().single():await supabase.from(domainTable(type)).insert(payload).select().single();setSaving(false);if(!q.error)onSaved(q.data);}
 return <form onSubmit={save} className="business-record-form"><div className="business-record-grid">{fields.map((f,i)=>{const field=typeof f==='string'?F(f):f;return <Field key={field.key||i} field={field} value={data[field.key]} onChange={v=>setData(x=>({...x,[field.key]:v}))} businessId={businessId}/>})}</div><button className="business-primary" disabled={saving}>{saving?'Saving…':record?'Update':'Save'} {moduleLabel(moduleKey)}</button></form>;
}
function F(key){return {key,label:title(key),type:['price','fee','budget','amount','stock_qty','capacity','duration_minutes','commission_percent','trial_days','goal','raised'].includes(key)?'number':['image_url','photo_url','logo_url','cover_image_url'].includes(key)?'image':key==='gallery'?'gallery':key.endsWith('_date')||key==='date'?'date':key==='description'||key==='bio'||key==='notes'||key==='address'||key==='requirements'||key==='itinerary'||key==='inclusions'||key==='exclusions'||key==='amenities'||key==='benefits'||key==='deliverables'||key==='syllabus'?'textarea':'text'};}

function UniversalBusinessSetupInner({type}){
 const cfg=businessConfig(type),schema=getDomainSchema(type),search=useSearchParams(),requested=search.get('business')||search.get('id');
 const [businessId,setBusinessId]=useState(requested||''),[business,setBusiness]=useState({}),[landing,setLanding]=useState({}),[records,setRecords]=useState([]),[media,setMedia]=useState([]),[tab,setTab]=useState('profile'),[module,setModule]=useState('primary'),[msg,setMsg]=useState(''),[error,setError]=useState(''),[session,setSession]=useState(null),[editing,setEditing]=useState(null);
 const modules=useMemo(()=>Object.keys(schema.secondary||{}),[schema]);
 const currentFields=module==='primary'?schema.fields:(schema.secondary?.[module]||genericFields(module)).map(x=>typeof x==='string'?F(x):x);
 async function load(id){if(!id)return;setBusinessId(id);const [b,l,r,m]=await Promise.all([supabase.from('restaurants').select('*').eq('id',id).maybeSingle(),supabase.from('anaira_business_landing_pages').select('*').eq('business_id',id).maybeSingle(),supabase.from(domainTable(type)).select('*').eq('business_id',id).order('created_at',{ascending:false}),supabase.from('anaira_business_media').select('*').eq('business_id',id).order('sort_order')]);setBusiness(b.data||{});setLanding(l.data||{business_id:id,business_type:type,headline:b.data?.name||cfg.name,subheadline:b.data?.description||'',published:false,theme:{style:'premium',accent:'#c8a35b'}});setRecords(r.data||[]);setMedia(m.data||[]);}
 useEffect(()=>{(async()=>{const {data:{session:s}}=await supabase.auth.getSession();setSession(s);if(!s)return;if(requested){load(requested);return;}const {data:p}=await supabase.from('anaira_my_profile').select('restaurant_id').eq('id',s.user.id).maybeSingle();if(p?.restaurant_id)load(p.restaurant_id);})()},[requested]);
 const show=(m)=>{setTab('records');setModule(m);setEditing(null)};
 async function saveProfile(e){e.preventDefault();const clean={...business};['id','created_at','updated_at','owner_id','hospitality_type','hospitality_types'].forEach(k=>delete clean[k]);clean.business_type=type;const q=await supabase.from('restaurants').update(clean).eq('id',businessId);if(q.error)setError(q.error.message);else{await supabase.from('anaira_business_workspaces').upsert({business_id:businessId,business_type:type,setup_status:'configured',settings:clean},{onConflict:'business_id'});setMsg('Business profile saved.');}}
 async function saveLanding(e){e.preventDefault();const payload={business_id:businessId,business_type:type,slug:landing.slug||`${esc(business.name||cfg.name)}-${type}`,headline:landing.headline||business.name||cfg.name,subheadline:landing.subheadline||business.description||'',hero_image_url:landing.hero_image_url||null,logo_url:landing.logo_url||business.logo_url||null,theme:landing.theme||{style:'premium',accent:'#c8a35b'},sections:landing.sections||[],published:!!landing.published};const q=await supabase.from('anaira_business_landing_pages').upsert(payload,{onConflict:'business_id'});if(q.error)setError(q.error.message);else setMsg('Premium website saved.');}
 async function saveMedia(type2,url,title2=''){const q=await supabase.from('anaira_business_media').insert({business_id:businessId,business_type:type,media_type:type2,url,title:title2,sort_order:media.length});if(!q.error)setMedia(x=>[...x,q.data]);}
 async function deleteRecord(id){const q=await supabase.from(domainTable(type)).delete().eq('id',id);if(!q.error)setRecords(x=>x.filter(r=>r.id!==id));}
 if(!session)return <main className="business-setup-v11"><div className="business-empty"><h1>Sign in required</h1><a href="/login" className="business-primary">Open Login</a></div></main>;
 if(!businessId)return <main className="business-setup-v11"><div className="business-empty"><h1>{cfg.icon} {cfg.name} Setup</h1><p>No business is assigned to this account.</p></div></main>;
 const recordsFor=records.filter(r=>r.module_key===(module==='primary'?'primary':module));
 return <main className="business-setup-v11"><div className="business-setup-shell"><header className="business-setup-header"><div><div className="business-eyebrow">ANAIRA BUSINESS OS · {cfg.name.toUpperCase()}</div><h1>{cfg.icon} {business.name||cfg.name} <span>Setup Studio</span></h1><p>Complete business profile, domain operations, customer-facing content and premium website from one control center.</p></div><div className="business-actions"><a href={`/business/${type}/landing?business=${businessId}`} target="_blank" rel="noreferrer" className="business-secondary">Preview Website ↗</a><a href={`/business/${type}?business=${businessId}`} className="business-primary">Open Dashboard</a></div></header>{error&&<div className="business-alert error">{error}</div>}{msg&&<div className="business-alert success">✓ {msg}</div>}
 <div className="business-setup-body"><aside className="business-sidebar">{[['profile','Profile'],['records','Business Data'],['website','Premium Website'],['media','Gallery & Testimonials'],['seo','SEO & Social']].map(([k,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{l}</button>)}<div className="business-side-title">Business Modules</div><button className={tab==='records'&&module==='primary'?'active':''} onClick={()=>show('primary')}>{schema.primaryIcon} {schema.primary}</button>{modules.map(m=><button key={m} className={tab==='records'&&module===m?'active':''} onClick={()=>show(m)}>{moduleLabel(m)}</button>)}</aside>
 <section className="business-setup-content">
 {tab==='profile'&&<form className="business-card" onSubmit={saveProfile}><div className="business-section-head"><h2>Business Profile</h2><p>Everything that identifies the business across Anaira and the public website.</p></div><div className="business-grid">{getCommonProfileFields().map(f=><Field key={f.key} field={f} value={business[f.key]} businessId={businessId} onChange={v=>setBusiness(x=>({...x,[f.key]:v}))}/>)}</div><div className="business-grid"><Field field={F('logo_url')} value={business.logo_url} businessId={businessId} onChange={v=>setBusiness(x=>({...x,logo_url:v}))}/><Field field={F('cover_image_url','Cover / Hero Image')} value={business.cover_image_url} businessId={businessId} onChange={v=>setBusiness(x=>({...x,cover_image_url:v}))}/></div><button className="business-primary">Save Profile</button></form>}
 {tab==='records'&&<div className="business-records"><div className="business-card"><div className="business-section-head"><h2>{module==='primary'?schema.primary:moduleLabel(module)}</h2><p>Add and manage {module==='primary'?schema.entity.toLowerCase()+' records':moduleLabel(module).toLowerCase()} with business-specific fields and images.</p></div><RecordEditor key={editing?.id||'new-'+module} schema={currentFields} record={editing} onSaved={r=>{setRecords(x=>editing?x.map(a=>a.id===r.id?r:a):[r,...x]);setEditing(null);setMsg('Saved successfully.')}} businessId={businessId} type={type} moduleKey={module==='primary'?'primary':module}/></div><div className="business-card"><div className="business-section-head"><h3>Saved Records</h3><p>Click edit to update or delete an entry.</p></div>{recordsFor.length===0?<div className="business-empty-inline">No records yet.</div>:<div className="business-record-list">{recordsFor.map(r=><article key={r.id}><div className="business-record-media">{r.data?.image_url||r.data?.photo_url?<img src={r.data.image_url||r.data.photo_url} alt=""/>:<div>{schema.primaryIcon}</div>}</div><div className="business-record-info"><h3>{r.title}</h3><p>{r.data?.description||r.data?.bio||r.data?.category||r.data?.status||''}</p>{r.data?.price!=null&&<b>₹{Number(r.data.price).toLocaleString('en-IN')}</b>}</div><div className="business-record-actions"><button onClick={()=>setEditing(r)}>Edit</button><button onClick={()=>deleteRecord(r.id)}>Delete</button></div></article>)}</div>}</div></div>}
 {tab==='website'&&<form className="business-card" onSubmit={saveLanding}><div className="business-section-head"><h2>Premium Website Builder</h2><p>Turn the data above into a polished business website. Every section can be enabled or disabled.</p></div><div className="business-grid"><Field field={F('headline','Hero Headline')} value={landing.headline} onChange={v=>setLanding(x=>({...x,headline:v}))}/><Field field={F('subheadline','Hero Subheadline','textarea')} value={landing.subheadline} onChange={v=>setLanding(x=>({...x,subheadline:v}))}/><Field field={F('hero_image_url','Hero Image')} value={landing.hero_image_url} businessId={businessId} onChange={v=>setLanding(x=>({...x,hero_image_url:v}))}/><Field field={F('logo_url','Website Logo')} value={landing.logo_url} businessId={businessId} onChange={v=>setLanding(x=>({...x,logo_url:v}))}/><Field field={F('about','About Section','textarea')} value={landing.about} onChange={v=>setLanding(x=>({...x,about:v}))}/><Field field={F('cta_text','Primary CTA')} value={landing.cta_text||'Get Started'} onChange={v=>setLanding(x=>({...x,cta_text:v}))}/></div><div className="business-toggle-grid">{['hero','about','catalog','team','offers','gallery','testimonials','faq','contact','booking'].map(k=><label key={k}><input type="checkbox" checked={landing.sections?.find?.(x=>x.key===k)?.enabled??true} onChange={e=>setLanding(x=>({...x,sections:[...['hero','about','catalog','team','offers','gallery','testimonials','faq','contact','booking'].map(key=>({key,enabled:key===k?e.target.checked:(x.sections?.find?.(z=>z.key===key)?.enabled??true)}))]}))}/>{title(k)}</label>)}</div><div className="business-grid"><Field field={F('accent','Accent Color')} value={landing.theme?.accent||'#c8a35b'} onChange={v=>setLanding(x=>({...x,theme:{...(x.theme||{}),accent:v}}))}/><Field field={F('style','Website Style')} value={landing.theme?.style||'premium luxury'} onChange={v=>setLanding(x=>({...x,theme:{...(x.theme||{}),style:v}}))}/></div><label className="business-check"><input type="checkbox" checked={!!landing.published} onChange={e=>setLanding(x=>({...x,published:e.target.checked}))}/><span>Publish website</span></label><button className="business-primary">Save & Publish Settings</button></form>}
 {tab==='media'&&<div className="business-card"><div className="business-section-head"><h2>Gallery & Testimonials</h2><p>Add as many images and testimonials as the business needs. These appear on the premium landing page.</p></div><Upload businessId={businessId} multiple label="Upload multiple gallery images" onUploaded={async urls=>{for(const u of urls)await saveMedia('gallery',u,'Gallery image')}}/><div className="business-mini-gallery large">{media.filter(x=>x.media_type==='gallery').map(m=><div key={m.id}><img src={m.url} alt={m.alt_text||''}/><button type="button" onClick={async()=>{await supabase.from('anaira_business_media').delete().eq('id',m.id);setMedia(x=>x.filter(a=>a.id!==m.id));}}>×</button></div>)}</div><div className="business-divider"/><h3>Testimonial</h3><TestimonialForm businessId={businessId} businessType={type} onSaved={r=>setRecords(x=>[r,...x])}/></div>}
 {tab==='seo'&&<SeoForm businessId={businessId} businessType={type} landing={landing} setLanding={setLanding} onSaved={()=>setMsg('SEO settings saved.')}/>} 
 </section></div></div></main>;
}

function TestimonialForm({businessId,businessType,onSaved}){const [d,setD]=useState({name:'',company:'',quote:'',rating:5,photo_url:''});async function save(e){e.preventDefault();const q=await supabase.from(domainTable(businessType)).insert({business_id:businessId,business_type:businessType,module_key:'testimonials',title:d.name||'Testimonial',data:d});if(!q.error){onSaved(q.data);setD({name:'',company:'',quote:'',rating:5,photo_url:''});}}return <form onSubmit={save} className="business-grid"><Field field={F('name','Customer Name')} value={d.name} onChange={v=>setD(x=>({...x,name:v}))}/><Field field={F('company','Company / Role')} value={d.company} onChange={v=>setD(x=>({...x,company:v}))}/><Field field={F('photo_url','Customer Photo')} value={d.photo_url} businessId={businessId} onChange={v=>setD(x=>({...x,photo_url:v}))}/><Field field={F('rating','Rating','number')} value={d.rating} onChange={v=>setD(x=>({...x,rating:v}))}/><Field field={F('quote','Testimonial','textarea')} value={d.quote} onChange={v=>setD(x=>({...x,quote:v}))}/><button className="business-primary">Save Testimonial</button></form>}
function SeoForm({businessId,businessType,landing,setLanding,onSaved}){const [d,setD]=useState({title:landing?.seo?.title||'',description:landing?.seo?.description||'',keywords:landing?.seo?.keywords||'',canonical:landing?.seo?.canonical||''});async function save(e){e.preventDefault();const next={...landing,seo:d};const q=await supabase.from('anaira_business_landing_pages').update({seo:d}).eq('business_id',businessId);if(!q.error){setLanding(next);onSaved();}}return <form className="business-card" onSubmit={save}><div className="business-section-head"><h2>SEO & Social</h2><p>Search metadata for the business landing page.</p></div><div className="business-grid"><Field field={F('title','SEO Title')} value={d.title} onChange={v=>setD(x=>({...x,title:v}))}/><Field field={F('canonical','Canonical URL')} value={d.canonical} onChange={v=>setD(x=>({...x,canonical:v}))}/><Field field={F('description','Meta Description','textarea')} value={d.description} onChange={v=>setD(x=>({...x,description:v}))}/><Field field={F('keywords','Keywords','textarea')} value={d.keywords} onChange={v=>setD(x=>({...x,keywords:v}))}/></div><button className="business-primary">Save SEO</button></form>}


export default function UniversalBusinessSetup(props){ return <Suspense fallback={<main className="domain-engine-page"><div className="card">Loading…</div></main>}><UniversalBusinessSetupInner {...props}/></Suspense>; }
