import {db} from '../../../../lib/server/provider';
import {recordProvider,requireSeoFeature} from '../../../../lib/server/seoRuntime';
import crypto from 'node:crypto';
const targetOf=v=>typeof v==='string'?v:(v?.url||v?.target||v?.href||'');
const domainOf=v=>{try{return new URL(v).hostname.replace(/^www\./,'').toLowerCase()}catch{return null}};
const fp=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex');
function normalizeBacklink(x,siteId){const sourceUrl=targetOf(x.url_from||x.source_url||x.referring_url||x.referring_page||x),targetUrl=targetOf(x.url_to||x.target_url||x.destination_url),sourceDomain=domainOf(sourceUrl)||x.domain_from||x.referring_domain||null;const attrs=Array.isArray(x.attributes)?x.attributes:typeof x.attributes==='object'?(x.attributes||{}):{};const attrText=JSON.stringify(attrs).toLowerCase();const row={site_id:siteId,source_url:sourceUrl||sourceDomain||String(x.id||'unknown'),source_domain:sourceDomain,target_url:targetUrl||null,anchor_text:x.anchor||x.anchor_text||x.text||null,dofollow:x.dofollow??!attrText.includes('nofollow'),sponsored:x.sponsored??attrText.includes('sponsored'),ugc:x.ugc??attrText.includes('ugc'),first_seen_at:x.first_seen||x.first_seen_time||null,last_seen_at:x.last_seen||x.last_seen_time||null,source_rank:x.rank??x.page_from_rank??null,domain_rank:x.domain_from_rank??x.domain_rank??null,spam_score:x.url_from_spam_score??x.domain_from_spam_score??x.spam_score??null,status:x.is_broken?'broken':'live',raw:x,captured_at:new Date().toISOString()};row.fingerprint=fp([row.source_url,row.target_url,row.anchor_text]);return row}
async function provider(path,body){const auth=Buffer.from(`${process.env.DATAFORSEO_LOGIN}:${process.env.DATAFORSEO_PASSWORD}`).toString('base64');const r=await fetch(`https://api.dataforseo.com/v3/backlinks/${path}`,{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/json'},body:JSON.stringify([body])});const j=await r.json();if(!r.ok)throw new Error(j.status_message||j.error||'DataForSEO backlink request failed');const t=j.tasks?.[0];if(!t||t.status_code>=40000)throw new Error(t?.status_message||'DataForSEO backlink task failed');return t}
async function collect(target,{statusType='live',maxResults=20000}={}){const rows=[];let offset=0,token=null;while(rows.length<maxResults){const body={target,limit:1000,backlinks_status_type:statusType,mode:'as_is',include_subdomains:true,rank_scale:'one_hundred',exclude_internal_backlinks:true};if(token)body.search_after_token=token;else body.offset=offset;const task=await provider('backlinks/live',body);const batch=task.result||[];rows.push(...batch);const meta=task.result?.[0]?.search_after_token||task.search_after_token||task.result?.search_after_token||null;if(!batch.length)break;if(meta){token=meta;offset=0}else{offset+=batch.length;if(offset>20000)break}if(batch.length<1000&&!meta)break}return rows.slice(0,maxResults)}
export async function GET(req){try{const siteId=new URL(req.url).searchParams.get('siteId');await requireSeoFeature(req,siteId,'backlinks_enabled','seo-system.view');const s=db();const [b,d,h]=await Promise.all([s.from('crm_seo_backlinks').select('*').eq('site_id',siteId).order('captured_at',{ascending:false}).limit(5000),s.from('crm_seo_backlink_domains').select('*').eq('site_id',siteId).order('backlinks',{ascending:false}).limit(500),s.from('crm_seo_backlink_history').select('*').eq('site_id',siteId).order('metric_date',{ascending:false}).limit(365)]);return Response.json({ok:true,backlinks:b.data||[],domains:d.data||[],history:h.data||[],providerConfigured:Boolean(process.env.DATAFORSEO_LOGIN&&process.env.DATAFORSEO_PASSWORD)})}catch(e){return Response.json({ok:false,error:e.message},{status:400})}}
export async function POST(req){const started=Date.now();try{const {siteId,mode='backlinks',statusType='live',maxResults=20000,competitorDomain}=await req.json();const {site}=await requireSeoFeature(req,siteId,'backlinks_enabled');if(!process.env.DATAFORSEO_LOGIN||!process.env.DATAFORSEO_PASSWORD)throw new Error('DATAFORSEO_LOGIN and DATAFORSEO_PASSWORD are required');const target=(competitorDomain||site.domain).replace(/^https?:\/\//,'').replace(/^www\./,'').split('/')[0];if(mode==='summary'){const task=await provider('summary/live',{target,include_subdomains:true,backlinks_status_type:statusType,rank_scale:'one_hundred',internal_list_limit:1000});const r=task.result?.[0]||{};const summary={rank:r.rank??null,backlinks:r.backlinks??0,spam:r.backlinks_spam_score??null,referringDomains:r.referring_domains??r.referring_domains_count??0};await db().from('crm_seo_backlink_history').upsert({site_id:siteId,metric_date:new Date().toISOString().slice(0,10),rank:summary.rank,backlinks:summary.backlinks,referring_domains:summary.referringDomains,captured_at:new Date().toISOString()},{onConflict:'site_id,metric_date'});await recordProvider(siteId,'dataforseo_backlinks','configured',{latencyMs:Date.now()-started,summary});return Response.json({ok:true,provider:'dataforseo',summary})}
 const raw=await collect(target,{statusType,maxResults});const rows=raw.map(x=>normalizeBacklink(x,siteId)).filter(x=>x.source_url);const s=db();const {data:previous}=await s.from('crm_seo_backlinks').select('fingerprint,status').eq('site_id',siteId).limit(50000);const prevLive=new Set((previous||[]).filter(x=>x.status==='live').map(x=>x.fingerprint));const current=new Set(rows.map(x=>x.fingerprint));for(let i=0;i<rows.length;i+=500){const {error}=await s.from('crm_seo_backlinks').upsert(rows.slice(i,i+500),{onConflict:'site_id,fingerprint'});if(error)throw error}const stale=[...prevLive].filter(x=>!current.has(x));if(stale.length){for(let i=0;i<stale.length;i+=500)await s.from('crm_seo_backlinks').update({status:'lost',last_seen_at:new Date().toISOString()}).eq('site_id',siteId).in('fingerprint',stale.slice(i,i+500))}
 const domains=new Map();for(const r of rows){const d=r.source_domain||domainOf(r.source_url);if(!d)continue;const x=domains.get(d)||{site_id:siteId,domain:d,backlinks:0,dofollow:0,nofollow:0,domain_rank:r.domain_rank,spam_score:r.spam_score,first_seen_at:r.first_seen_at,last_seen_at:r.last_seen_at,status:'active',captured_at:new Date().toISOString()};x.backlinks++;if(r.dofollow)x.dofollow++;else x.nofollow++;domains.set(d,x)}for(const x of domains.values())await s.from('crm_seo_backlink_domains').upsert(x,{onConflict:'site_id,domain'});
 const summary={backlinks:rows.length,referringDomains:domains.size,newBacklinks:[...current].filter(x=>!prevLive.has(x)).length,lostBacklinks:stale.length};await s.from('crm_seo_backlink_history').upsert({site_id:siteId,metric_date:new Date().toISOString().slice(0,10),backlinks:rows.length,new_backlinks:summary.newBacklinks,lost_backlinks:summary.lostBacklinks,referring_domains:domains.size,captured_at:new Date().toISOString()},{onConflict:'site_id,metric_date'});await recordProvider(siteId,'dataforseo_backlinks','configured',{latencyMs:Date.now()-started,summary});return Response.json({ok:true,provider:'dataforseo',summary,persisted:rows.length,mode});
}catch(e){return Response.json({ok:false,error:e.message},{status:400})}}
