import {db} from '../../../../lib/server/provider';
import {requireCron} from '../../../../lib/server/auth';
import {syncHotelGuestTenant} from '../../../../lib/server/hotel-guest-sync';
export const runtime='nodejs';
export async function POST(req){try{requireCron(req);const s=db(),now=new Date(),out={analytics:0,prearrival:0,ltv:0,churn:0,segments:0,hotel_guest_sync:0};const {data:tenants}=await s.from('restaurants').select('id').limit(500);for(const t of tenants||[]){const tenantId=t.id;let syncResult=null;try{syncResult=await syncHotelGuestTenant(tenantId);out.hotel_guest_sync++;}catch(e){await s.from('crm_audit_logs').insert({tenant_id:tenantId,entity_type:'hotel_guest_crm',action:'source_sync_failed',after_data:{error:e.message}}).catch(()=>{});}
const {data:pendingEvents}=await s.from('crm_source_event_inbox').select('id').eq('tenant_id',tenantId).in('status',['received','retry']).order('received_at').limit(500);
if(pendingEvents?.length){await s.from('crm_source_event_inbox').update({status:'processed',processed_at:now.toISOString(),attempts:1}).eq('tenant_id',tenantId).in('status',['received','retry']);await s.from('crm_source_event_delivery_log').insert(pendingEvents.map(e=>({tenant_id:tenantId,inbox_event_id:e.id,source_system:'crm',event_type:'processed',attempt:1,status:'success',response:{sync:true}}))).catch(()=>{});}
await s.from('crm_automation_schedules').update({last_run_at:now.toISOString(),last_status:'success',next_run_at:new Date(now.getTime()+3600000).toISOString()}).eq('tenant_id',tenantId).eq('worker','/api/crm/functional-worker').catch(()=>{});
const a=await s.rpc('anaira_refresh_crm_analytics',{p_tenant_id:tenantId,p_metric_date:now.toISOString().slice(0,10)});if(!a.error)out.analytics++;const q=await s.rpc('anaira_queue_prearrival_jobs',{p_now:now.toISOString()});if(!q.error)out.prearrival+=Number(q.data||0);const {data:cfg}=await s.from('restaurant_plugins').select('plugin_code,enabled').eq('restaurant_id',tenantId).in('plugin_code',['customer_ltv','churn','segmentation']);const enabled=Object.fromEntries((cfg||[]).map(x=>[x.plugin_code,x.enabled]));if(enabled.customer_ltv!==false){const {data:customers}=await s.from('crm_customers').select('id').eq('tenant_id',tenantId).limit(500);for(const c of customers||[])await s.rpc('anaira_refresh_global_customer_links',{p_tenant_id:tenantId,p_customer_id:c.id}).catch(()=>{});out.ltv+=customers?.length||0;}if(enabled.churn){const {data:customers}=await s.from('crm_customers').select('id,total_stays').eq('tenant_id',tenantId).limit(500);for(const c of customers||[]){const {data:m}=await s.from('crm_restaurant_customer_metrics').select('last_visit_at,complaints_count').eq('tenant_id',tenantId).eq('customer_id',c.id).maybeSingle();const rec=m?.last_visit_at?Math.max(0,(Date.now()-new Date(m.last_visit_at).getTime())/86400000):180;const score=Math.max(0,Math.min(.99,Math.min(.55,rec/180*.55)+Math.min(.2,(Number(m?.complaints_count||0)/5)*.2)+(Number(c.total_stays||0)===0?.1:0)));await s.from('crm_churn_scores').upsert({tenant_id:tenantId,customer_id:c.id,score,risk_level:score>=.75?'high':score>=.5?'medium':'low',factors:[{key:'recency_days',value:rec},{key:'complaints',value:Number(m?.complaints_count||0)}],calculated_at:now.toISOString()},{onConflict:'tenant_id,customer_id'});out.churn++;}}if(enabled.segmentation){const {data:segments}=await s.from('crm_segments').select('id,definition').eq('tenant_id',tenantId).eq('active',true).limit(100);for(const seg of segments||[]){let d=seg.definition||{};if(typeof d==='string'){try{d=JSON.parse(d)}catch{d={}}}let q2=s.from('crm_customers').select('id,total_hotel_revenue,total_restaurant_revenue,total_restaurant_visits,vip').eq('tenant_id',tenantId);if(d.customer_type)q2=q2.eq('customer_type',d.customer_type);if(d.vip!==undefined)q2=q2.eq('vip',!!d.vip);const {data:customers}=await q2.limit(5000);const matched=(customers||[]).filter(c=>d.min_ltv?(Number(c.total_hotel_revenue||0)+Number(c.total_restaurant_revenue||0)>=Number(d.min_ltv)):true).filter(c=>d.min_visits?Number(c.total_restaurant_visits||0)>=Number(d.min_visits):true);await s.from('crm_segment_members').delete().eq('segment_id',seg.id);if(matched.length)await s.from('crm_segment_members').insert(matched.map(c=>({segment_id:seg.id,customer_id:c.id,calculated_at:now.toISOString(),reason:'scheduled-definition-match'})));out.segments++;}}}return Response.json({ok:true,...out,completedAt:new Date().toISOString()})}catch(e){return Response.json({ok:false,error:e.message},{status:500})}}
export async function GET(req){return POST(req)}
