'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {supabase} from '../../lib/supabase';

const BUCKET='anaira-media';
const ext=(name='')=>name.split('.').pop()?.toLowerCase()||'jpg';
const safe=(v)=>String(v||'').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-').replace(/^-|-$/g,'');

export default function MediaPicker({value,multiple=false,onChange,restaurantId,folder='media',label='Image',hint='Upload an image or choose one from Gallery',className=''}){
 const inputRef=useRef(null); const [open,setOpen]=useState(false),[files,setFiles]=useState([]),[loading,setLoading]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');
 const values=useMemo(()=>multiple?(Array.isArray(value)?value:[]):(value?[value]:[]),[value,multiple]);
 const prefix=`${restaurantId||'unassigned'}/${folder}`;
 async function load(){if(!restaurantId)return;setLoading(true);setError('');const {data,error:e}=await supabase.storage.from(BUCKET).list(prefix,{limit:200,sortBy:{column:'created_at',order:'desc'}});if(e)setError(e.message);else setFiles((data||[]).filter(x=>x.name&&!x.name.endsWith('/')).map(x=>{const path=`${prefix}/${x.name}`;return {name:x.name,path,url:supabase.storage.from(BUCKET).getPublicUrl(path).data.publicUrl}}));setLoading(false)}
 useEffect(()=>{if(open)load()},[open,restaurantId,folder]);
 async function upload(ev){const selected=[...(ev.target.files||[])];if(!selected.length||!restaurantId)return;setUploading(true);setError('');const urls=[];for(const file of selected){if(!file.type.startsWith('image/')){setError(`${file.name} is not an image.`);continue}if(file.size>10*1024*1024){setError(`${file.name} is larger than 10MB.`);continue}const path=`${prefix}/${Date.now()}-${safe(file.name)||`image.${ext(file.name)}`}`;const {error:e}=await supabase.storage.from(BUCKET).upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(e){setError(e.message);continue}urls.push(supabase.storage.from(BUCKET).getPublicUrl(path).data.publicUrl)}if(urls.length)onChange(multiple?[...values,...urls]:urls[0]);setUploading(false);ev.target.value='';}
 function pick(url){onChange(multiple?[...values.filter(x=>x!==url),url]:url);if(!multiple)setOpen(false)}
 function remove(url){onChange(multiple?values.filter(x=>x!==url):'')}
 return <div className={`media-picker ${className}`}>
   <div className="media-picker-head"><b>{label}</b><span>{hint}</span></div>
   <div className="media-picker-actions"><button type="button" className="btn" onClick={()=>inputRef.current?.click()} disabled={uploading}>{uploading?'Uploading…':'Upload'}</button><button type="button" className="btn" onClick={()=>setOpen(true)} disabled={!restaurantId}>Gallery</button>{values.length>0&&<button type="button" className="btn" onClick={()=>onChange(multiple?[]:'')}>Clear</button>}</div>
   <input ref={inputRef} type="file" accept="image/*" multiple={multiple} hidden onChange={upload}/>
   {error&&<div className="media-error">{error}</div>}
   {values.length>0&&<div className="media-selected">{values.map((url,i)=><div className="media-thumb" key={`${url}-${i}`}><img src={url} alt=""/><button type="button" onClick={()=>remove(url)}>×</button></div>)}</div>}
   {open&&<div className="media-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="media-modal"><div className="media-modal-head"><div><h3>ANAIRA Gallery</h3><small>{prefix}</small></div><button type="button" onClick={()=>setOpen(false)}>×</button></div>{loading?<p>Loading gallery…</p>:!files.length?<p className="media-empty">No uploaded images in this gallery yet.</p>:<div className="media-grid">{files.map(f=><button type="button" className={`media-gallery-item ${values.includes(f.url)?'selected':''}`} key={f.path} onClick={()=>pick(f.url)}><img src={f.url} alt=""/><span>{f.name}</span></button>)}</div>}</div></div>}
   <style jsx>{`.media-picker{border:1px solid #e5dfd2;border-radius:12px;padding:12px;background:#fbfaf7}.media-picker-head{display:flex;justify-content:space-between;gap:12px;align-items:center;font-size:12px}.media-picker-head span{font-size:10px;color:#777;font-weight:400}.media-picker-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.media-selected{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.media-thumb{width:72px;height:72px;border-radius:10px;overflow:hidden;position:relative;background:#eee}.media-thumb img{width:100%;height:100%;object-fit:cover}.media-thumb button{position:absolute;right:3px;top:3px;border:0;border-radius:50%;width:22px;height:22px;background:#000b;color:#fff;cursor:pointer}.media-error{margin-top:8px;color:#b42318;font-size:11px}.media-modal-backdrop{position:fixed;inset:0;background:#0008;z-index:9999;display:grid;place-items:center;padding:20px}.media-modal{width:min(920px,96vw);max-height:88vh;overflow:auto;background:#fff;border-radius:18px;padding:18px;color:#1d2923}.media-modal-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.media-modal-head h3{margin:0}.media-modal-head small{color:#777}.media-modal-head>button{border:0;background:#eee;border-radius:50%;width:34px;height:34px;font-size:22px}.media-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:12px}.media-gallery-item{border:2px solid transparent;border-radius:12px;background:#f6f4ef;padding:0;overflow:hidden;text-align:left;cursor:pointer}.media-gallery-item.selected{border-color:#c69b3c}.media-gallery-item img{width:100%;height:130px;object-fit:cover;display:block}.media-gallery-item span{display:block;padding:8px;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.media-empty{color:#777}@media(max-width:600px){.media-picker-head{display:grid}.media-grid{grid-template-columns:repeat(2,1fr)}}`}</style>
 </div>
}
