'use client';
import {useEffect,useState} from 'react';
import {SetupShell,SetupHeader,useTenantProperty,ensureSelected,SelectField,Field,Section,Table,Pill,hospitalityMeta} from '../setup-components';
import {supabase} from '../../../lib/supabase';
const STATES=['confirmed','checked_in','checked_out','cancelled','no_show'];
export default function PMS(){
 const ctx=useTenantProperty(); const[rid,setRid]=useState(null),[rows,setRows]=useState([]),[rooms,setRooms]=useState([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all'); const id=ensureSelected(ctx,rid); const m=hospitalityMeta(ctx.hospitalityType);
 async function load(){if(!id)return; const [a,b]=await Promise.all([supabase.from('hms_reservations').select('*,hms_guests(full_name,phone),hms_rooms(room_number,hospitality_type)').eq('restaurant_id',id).eq('hospitality_type',ctx.hospitalityType||'hotel').order('check_in',{ascending:true}),supabase.from('hms_rooms').select('id,room_number,room_type_id,status,hospitality_type').eq('restaurant_id',id).eq('hospitality_type',ctx.hospitalityType||'hotel').order('room_number')]); if(a.error)setMsg(a.error.message); else setRows(a.data||[]); setRooms(b.data||[])}
 useEffect(()=>{load()},[id]);
 async function transition(r,action,roomId){setBusy(true);setMsg(''); let q;if(action==='check_in'){q=await supabase.rpc('anaira_pms_check_in',{p_restaurant_id:id,p_reservation_id:r.id,p_room_id:roomId,p_notes:null})}else{q=await supabase.rpc('anaira_reservation_transition',{p_restaurant_id:id,p_reservation_id:r.id,p_action:action,p_notes:null})} setMsg(q.error?.message||`${action.replaceAll('_',' ')} completed.`); if(!q.error)await load();setBusy(false)}
 async function checkout(r){setBusy(true);const s=await supabase.from('hms_stays').select('id,actual_room_id,status').eq('restaurant_id',id).eq('reservation_id',r.id).in('status',['in_house','checked_in']).maybeSingle(); if(s.error||!s.data){setMsg(s.error?.message||'Active stay not found.');setBusy(false);return} const u=await supabase.from('hms_stays').update({status:'checked_out',check_out_at:new Date().toISOString()}).eq('id',s.data.id).eq('restaurant_id',id); if(!u.error){await supabase.from('hms_rooms').update({status:'dirty',housekeeping_status:'dirty',last_status_changed_at:new Date().toISOString()}).eq('id',s.data.actual_room_id).eq('restaurant_id',id); await supabase.from('hms_reservations').update({status:'checked_out',updated_at:new Date().toISOString()}).eq('id',r.id).eq('restaurant_id',id)} setMsg(u.error?.message||'Checked out; room sent to housekeeping.');await load();setBusy(false)}
 const shown=rows.filter(x=>filter==='all'||x.status===filter); return <SetupShell active="/hotel-management" title={`${m.label} PMS / Front Desk`} subtitle={`Arrivals, in-house guests, ${m.unit.toLowerCase()} assignment and departures.`} ctx={ctx}><SetupHeader title={`${m.label} PMS / Front Desk`} subtitle="Operational stay management" ctx={ctx} rid={rid} setRid={setRid}/>{id?<><Section title="Front Desk Board" meta={`${shown.length} reservations`}><div className="card"><SelectField label="Status" value={filter} onChange={setFilter} options={[['all','All'],...STATES]}/></div><Table columns={['Reservation','Guest','Dates',m.unit,'Status','Actions']} rows={shown.map(r=>[<b>{r.reservation_code}</b>,<>{r.hms_guests?.full_name||'—'}<br/><small>{r.hms_guests?.phone||''}</small></>,`${r.check_in} → ${r.check_out}`,r.hms_rooms?.room_number||'Unassigned',<Pill>{r.status}</Pill>,<div style={{display:'flex',gap:5,flexWrap:'wrap'}}>{r.status==='confirmed'&&<button className="btn" disabled={busy} onClick={()=>{const available=rooms.find(x=>x.status==='available'&&x.room_type_id===r.room_type_id); if(!available){setMsg('No matching available room.');return} transition(r,'check_in',available.id)}}>Check-in</button>}{r.status==='confirmed'&&<button className="btn" disabled={busy} onClick={()=>transition(r,'no_show')}>No-show</button>}{['confirmed','pending','hold'].includes(r.status)&&<button className="btn" disabled={busy} onClick={()=>transition(r,'cancel')}>Cancel</button>}{['in_house','checked_in'].includes(r.status)&&<button className="btn" disabled={busy} onClick={()=>checkout(r)}>Check-out</button>}</div>])}/></Section></>:<div className="notice">Select a property first.</div>}</SetupShell>}
