
'use client';
import {useEffect,useMemo,useState} from 'react';
import {AppShell,Header,Section} from '../components';
import {supabase} from '../../lib/supabase';

const fields={customers:['full_name','phone','email','gender','date_of_birth','anniversary_date','address_line1','city','state','country','preferred_language','customer_type','vip','notes'],leads:['customer_id','lead_type','source','stage','estimated_value','next_follow_up','notes'],corporate:['company_name','contact_name','phone','email','negotiated_rate_notes','payment_terms','credit_limit','active'],partners:['partner_type','name','contact_name','phone','email','commission_percent','active'],reviews:['source','external_review_id','author_name','rating','review_text','reviewed_at','language','status']};
const escapeCsv=v=>`"${String(v??'').replaceAll('"','""')}"`;
function template(type){return fields[type].join(',')+'\n'+fields[type].map(()=>escapeCsv('')).join(',')+'\n';}
function parseCsv(text){const out=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){cell+='"';i++;continue}if(c==='"'){q=!q;continue}if(c===','&&!q){row.push(cell);cell='';continue}if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(x=>x!=='')){out.push(row)}row=[];continue}cell+=c}if(cell||row.length){row.push(cell);if(row.some(x=>x!==''))out.push(row)}if(!out.length)return [];const header=out[0].map(x=>x.trim());return out.slice(1).map(r=>Object.fromEntries(header.map((h,i)=>[h,r[i]??''])))}
export default function ImportExport(){
 const [session,setSession]=useState(undefined),[tenantId,setTenantId]=useState(''),[type,setType]=useState('customers'),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[result,setResult]=useState(null),[error,setError]=useState('');
 useEffect(()=>{if(!supabase){setSession(null);return}supabase.auth.getSession().then(async({data})=>{setSession(data.session||null);if(data.session){const {data:p}=await supabase.from('anaira_my_profile').select('restaurant_id').eq('id',data.session.user.id).maybeSingle();setTenantId(p?.restaurant_id||'')}})},[]);
 const validRows=useMemo(()=>rows.map(r=>{const x={};for(const f of fields[type])x[f]=r[f]??'';return x}),[rows,type]);
 const onFile=async e=>{const f=e.target.files?.[0];if(!f)return;setError('');setResult(null);setRows(parseCsv(await f.text()))};
 const importNow=async()=>{if(!tenantId||!validRows.length)return setError('Choose a property and CSV with at least one row.');setBusy(true);setError('');setResult(null);try{let totals={processed:0,inserted:0,updated:0,failed:0,errors:[]};for(let i=0;i<validRows.length;i+=500){const batch=validRows.slice(i,i+500);const r=await fetch('/api/crm/import',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session.access_token}`},body:JSON.stringify({tenantId,entity:type,rows:batch})});const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error||'Import failed');totals.processed+=j.processed;totals.inserted+=j.inserted;totals.updated+=j.updated;totals.failed+=j.failed;totals.errors.push(...(j.errors||[]).map(x=>({...x,row:x.row+i})));}setResult(totals)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const download=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([template(type)],{type:'text/csv'}));a.download=`anaira-${type}-template.csv`;a.click();URL.revokeObjectURL(a.href)};
 if(session===undefined)return <AppShell><div className="notice">Connecting to CRM…</div></AppShell>;if(!session)return <AppShell><div className="auth-card"><h1>Sign in required</h1><a className="btn primary" href="/login">Open CRM Login</a></div></AppShell>;
 return <AppShell active="/import-export"><Header eyebrow="DATA OPERATIONS" title="CRM Data Import" subtitle="Add real customers and CRM records manually through existing modules, or bulk-import validated CSV data with tenant-safe server processing." actions={<a className="btn" href="/customer-360">Open Customer 360</a>}/>
 <Section title="1. Choose what you are importing"><div className="card admin-form"><label><span>Data Type</span><select value={type} onChange={e=>{setType(e.target.value);setRows([]);setResult(null)}}>{Object.keys(fields).map(x=><option key={x} value={x}>{x.replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase())}</option>)}</select></label><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn" onClick={download}>Download CSV Template</button><label className="btn"><input type="file" accept=".csv,text/csv" onChange={onFile} style={{display:'none'}}/>Choose CSV File</label></div></div></Section>
 {error&&<div className="notice error">{error}</div>}
 <Section title="2. Preview & Import" meta={`${validRows.length} rows ready`}><div className="notice">Allowed fields are enforced server-side. Existing customers are matched by email or phone; corporate accounts by company name; partners by name; Google/provider reviews by external review ID when available. No demo records are inserted.</div>{validRows.length>0&&<><div style={{overflow:'auto',maxHeight:420}}><table className="data-table"><thead><tr>{fields[type].map(f=><th key={f}>{f}</th>)}</tr></thead><tbody>{validRows.slice(0,25).map((r,i)=><tr key={i}>{fields[type].map(f=><td key={f}>{String(r[f]??'').slice(0,80)}</td>)}</tr>)}</tbody></table></div><button className="btn primary" onClick={importNow} disabled={busy||!validRows.length} style={{marginTop:12}}>{busy?'Importing…':`Import ${validRows.length} Rows`}</button></>}</Section>
 {result&&<Section title="Import Result"><div className="grid kpis"><div className="kpi"><small>Processed</small><b>{result.processed}</b></div><div className="kpi"><small>Inserted</small><b>{result.inserted}</b></div><div className="kpi"><small>Updated</small><b>{result.updated}</b></div><div className="kpi"><small>Failed</small><b>{result.failed}</b></div></div>{result.errors?.length>0&&<pre className="card" style={{whiteSpace:'pre-wrap',overflow:'auto'}}>{JSON.stringify(result.errors,null,2)}</pre>}</Section>}
 <Section title="How you add data in Anaira"><div className="mini-grid"><div className="mini"><b>Single customer</b><span>Customer 360 → + New Record</span></div><div className="mini"><b>Bulk customers</b><span>Download Customers CSV → fill → import</span></div><div className="mini"><b>Google reviews</b><span>Do not type them manually; connect Google and sync</span></div><div className="mini"><b>Operational data</b><span>Use the canonical Hotel/POS/Restaurant modules so CRM can consume their events</span></div></div></Section>
 </AppShell>}
