import {db,open,googleToken} from '../../../../lib/server/provider';
import {requireTenant} from '../../../../lib/server/auth';
import {assertReviewPlugin} from '../../../../lib/server/review-config';

export async function GET(req){try{const {searchParams}=new URL(req.url);const tenantId=searchParams.get('tenantId');await requireTenant(req,tenantId);await assertReviewPlugin(tenantId);const {data,error}=await db().from('crm_review_google_connections').select('id,tenant_id,account_id,scope,connected_by,connected_at,pubsub_topic,pubsub_enabled,reply_automation_consent,reply_automation_consent_at,status,last_sync_at,last_error,created_at,updated_at').eq('tenant_id',tenantId).maybeSingle();if(error)throw error;return Response.json({ok:true,connection:data||null})}catch(e){return Response.json({ok:false,error:e.message},{status:400})}}

export async function POST(req){try{
 const {tenantId,replyAutomationConsent,pubsubTopic,pubsubEnabled}=await req.json();const {user}=await requireTenant(req,tenantId);await assertReviewPlugin(tenantId);const s=db();const {data:row}=await s.from('crm_review_google_connections').select('*').eq('tenant_id',tenantId).maybeSingle();if(!row)throw new Error('Connect Google Business Profile first');
 let nextTopic=pubsubTopic??row.pubsub_topic,nextEnabled=pubsubEnabled??row.pubsub_enabled;
 const int=await s.from('crm_seo_integrations').select('settings').eq('tenant_id',tenantId).eq('provider','google_business_profile').maybeSingle();const refresh=int.data?.settings?.refresh_token||row.refresh_token;
 if(pubsubEnabled===true){if(!nextTopic)throw new Error('pubsubTopic is required');if(!refresh)throw new Error('Google OAuth refresh token is missing');const token=await googleToken(open(refresh));const accountId=row.account_id||int.data?.settings?.account_id;if(!accountId)throw new Error('Google account id is missing');const rr=await fetch(`https://mybusinessnotifications.googleapis.com/v1/accounts/${accountId}/notificationSetting?updateMask=pubsubTopic`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({pubsubTopic:nextTopic})});const jj=await rr.json();if(!rr.ok)throw new Error(jj.error?.message||'Google notification configuration failed');nextEnabled=true;}
 if(pubsubEnabled===false&&refresh&&row.account_id){const token=await googleToken(open(refresh));const rr=await fetch(`https://mybusinessnotifications.googleapis.com/v1/accounts/${row.account_id}/notificationSetting?updateMask=pubsubTopic`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({pubsubTopic:''})});if(!rr.ok){const jj=await rr.json().catch(()=>({}));throw new Error(jj.error?.message||'Google notification disconnect failed');}nextEnabled=false;}
 const consent=replyAutomationConsent===true;const {data,error}=await s.from('crm_review_google_connections').update({reply_automation_consent:consent,reply_automation_consent_at:consent?new Date().toISOString():null,pubsub_topic:nextTopic,pubsub_enabled:nextEnabled,updated_at:new Date().toISOString(),status:'connected',last_error:null}).eq('tenant_id',tenantId).select('id,reply_automation_consent,reply_automation_consent_at,pubsub_topic,pubsub_enabled,status').single();if(error)throw error;return Response.json({ok:true,connection:data,actor:user.id});
}catch(e){return Response.json({ok:false,error:e.message},{status:400})}}

export async function DELETE(req){try{const {tenantId}=await req.json();await requireTenant(req,tenantId);const s=db();const {data:row}=await s.from('crm_review_google_connections').select('*').eq('tenant_id',tenantId).maybeSingle();const {data:int}=await s.from('crm_seo_integrations').select('settings').eq('tenant_id',tenantId).eq('provider','google_business_profile').maybeSingle();const refresh=int?.settings?.refresh_token||row?.refresh_token;if(refresh&&row?.account_id){try{const token=await googleToken(open(refresh));await fetch(`https://mybusinessnotifications.googleapis.com/v1/accounts/${row.account_id}/notificationSetting?updateMask=pubsubTopic`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({pubsubTopic:''})});}catch{}}
 await s.from('crm_review_sources').update({active:false,api_enabled:false}).eq('tenant_id',tenantId).eq('source','google');await s.from('crm_review_google_connections').delete().eq('tenant_id',tenantId);await s.from('crm_seo_integrations').delete().eq('tenant_id',tenantId).eq('provider','google_business_profile');return Response.json({ok:true,disconnected:true});}catch(e){return Response.json({ok:false,error:e.message},{status:400})}}
