'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {AppShell,Header,Section} from '../../components';
import {supabase} from '../../../lib/supabase';
import MarketplaceImageUpload from '../MarketplaceImageUpload';

const defaults={
 marketplace_enabled:true,require_listing_approval:true,default_commission_percent:0,featured_listings_enabled:true,settlements_enabled:true,marketplace_payment_mode:'platform',
 restaurant_home_title:'Good food. Great restaurants.',restaurant_home_subtitle:'Discover live menus, offers, delivery, pickup and dine-in from restaurants on Anaira.',restaurant_home_theme:'forest',
 restaurant_home_show_search:true,restaurant_home_show_popular:true,restaurant_home_show_offers:true,restaurant_home_show_modes:true,restaurant_home_show_banners:true,restaurant_home_show_restaurants:true,
 restaurant_home_hero_image:'',restaurant_home_hero_mobile_image:'',restaurant_home_hero_overlay:'0.58',restaurant_home_hero_cta:'Explore restaurants',restaurant_home_hero_cta_url:'#restaurants',
 restaurant_home_primary_color:'#073b2b',restaurant_home_accent_color:'#d4aa4c',restaurant_home_surface_color:'#ffffff',restaurant_home_background_color:'#f7f7f5',restaurant_home_text_color:'#17352a',
 restaurant_home_container_width:1240,restaurant_home_restaurant_columns:3,restaurant_home_dish_columns:4,restaurant_home_banner_columns:3,restaurant_home_card_radius:20,
 restaurant_home_show_footer:true,restaurant_home_footer_text:'Anaira Food — discover restaurants, order food and enjoy local dining.',restaurant_home_meta_title:'Anaira Food | Restaurant Marketplace',restaurant_home_meta_description:'Discover restaurants, menus, offers, delivery, pickup and dine-in on Anaira Food.'
};
const blank={title:'',subtitle:'',image_url:'',mobile_image_url:'',cta_label:'Explore restaurants',cta_url:'#restaurants',display_order:0,active:true};
const field=(label,key,type='text',extra={})=>({label,key,type,...extra});
export default function MarketplaceSettings(){
 const [form,setForm]=useState(defaults),[banners,setBanners]=useState([]),[banner,setBanner]=useState(blank),[store,setStore]=useState(null),[msg,setMsg]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState('design'),[saving,setSaving]=useState(false);
 useEffect(()=>{(async()=>{const {data,error}=await supabase.from('anaira_platform_settings').select('key,value').in('key',Object.keys(defaults));if(error){setError(error.message);return}const x={...defaults};(data||[]).forEach(r=>x[r.key]=r.value?.value??r.value);setForm(x);const {data:s}=await supabase.from('anaira_platform_stores').select('id,store_name').eq('store_type','restaurant').maybeSingle();setStore(s||null);if(s){const {data:b}=await supabase.from('anaira_store_banners').select('*').eq('store_id',s.id).order('display_order');setBanners(b||[])}})()},[]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function save(e){e?.preventDefault();setSaving(true);setMsg('');setError('');const user=(await supabase.auth.getUser()).data.user?.id;for(const [key,value] of Object.entries(form)){const q=await supabase.from('anaira_platform_settings').upsert({key,value:{value},updated_by:user},{onConflict:'key'});if(q.error){setError(q.error.message);setSaving(false);return}}setMsg('Global Restaurant Store settings saved.');setSaving(false);}
 async function addBanner(e){e.preventDefault();setError('');if(!store||!banner.title||!banner.image_url){setError('Banner title and desktop image are required.');return}const {data,error}=await supabase.from('anaira_store_banners').insert({...banner,store_id:store.id,restaurant_id:null,display_order:Number(banner.display_order)||0}).select('*').single();if(error){setError(error.message);return}setBanners(x=>[...x,data].sort((a,b)=>(a.display_order||0)-(b.display_order||0)));setBanner(blank);setMsg('Global homepage banner added.');}
 async function toggleBanner(b){const {error}=await supabase.from('anaira_store_banners').update({active:!b.active,updated_at:new Date().toISOString()}).eq('id',b.id);if(error){setError(error.message);return}setBanners(x=>x.map(i=>i.id===b.id?{...i,active:!b.active}:i));}
 async function deleteBanner(id){const {error}=await supabase.from('anaira_store_banners').delete().eq('id',id);if(error){setError(error.message);return}setBanners(x=>x.filter(i=>i.id!==id));}
 const tabs=[['design','🎨 Store Design'],['hero','🖼 Hero & Banners'],['sections','🧩 Home Sections'],['business','⚙ Marketplace Rules'],['seo','🔎 SEO & Footer']];
 return <AppShell active="/super-admin/marketplace-settings">
  <Header eyebrow="SUPER ADMIN • GLOBAL RESTAURANT STORE" title="Restaurant Store Control Center" subtitle="This is the GLOBAL Anaira Restaurant Marketplace store. Super Admin owns its branding, layout, homepage, banners, sections, marketplace rules and publishing. Business Admin controls only their own restaurant or hotel store." actions={<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link className="btn" href="/store" target="_blank">Open Global Store ↗</Link><button className="btn primary" onClick={()=>save()} disabled={saving}>{saving?'Saving…':'Save All Changes'}</button></div>}/>
  <div className="store-control-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {msg&&<div className="notice success" style={{marginBottom:16}}>{msg}</div>}{error&&<div className="notice error" style={{marginBottom:16}}>{error}</div>}
  {tab==='design'&&<>
   <Section title="Global Store Identity & Visual System" meta="Everything here belongs to the Super Admin-owned Restaurant Marketplace. It affects the global /store experience, not an individual restaurant store."><div className="card store-settings-grid">
    <label><span>Homepage title</span><input value={form.restaurant_home_title} onChange={e=>set('restaurant_home_title',e.target.value)}/></label>
    <label><span>Homepage subtitle</span><input value={form.restaurant_home_subtitle} onChange={e=>set('restaurant_home_subtitle',e.target.value)}/></label>
    <label><span>Theme preset</span><select value={form.restaurant_home_theme} onChange={e=>set('restaurant_home_theme',e.target.value)}><option value="forest">Forest Premium</option><option value="light">Luxury Light</option><option value="dark">Midnight</option></select></label>
    <label><span>Primary / header color</span><input type="color" value={form.restaurant_home_primary_color} onChange={e=>set('restaurant_home_primary_color',e.target.value)}/></label>
    <label><span>Accent / CTA color</span><input type="color" value={form.restaurant_home_accent_color} onChange={e=>set('restaurant_home_accent_color',e.target.value)}/></label>
    <label><span>Page background</span><input type="color" value={form.restaurant_home_background_color} onChange={e=>set('restaurant_home_background_color',e.target.value)}/></label>
    <label><span>Card / surface color</span><input type="color" value={form.restaurant_home_surface_color} onChange={e=>set('restaurant_home_surface_color',e.target.value)}/></label>
    <label><span>Text color</span><input type="color" value={form.restaurant_home_text_color} onChange={e=>set('restaurant_home_text_color',e.target.value)}/></label>
    <label><span>Content max width (px)</span><input type="number" min="980" max="1600" value={form.restaurant_home_container_width} onChange={e=>set('restaurant_home_container_width',Number(e.target.value))}/></label>
    <label><span>Restaurant cards per row</span><select value={form.restaurant_home_restaurant_columns} onChange={e=>set('restaurant_home_restaurant_columns',Number(e.target.value))}><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></label>
    <label><span>Popular dish cards per row</span><select value={form.restaurant_home_dish_columns} onChange={e=>set('restaurant_home_dish_columns',Number(e.target.value))}><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></label>
    <label><span>Banner cards per row</span><select value={form.restaurant_home_banner_columns} onChange={e=>set('restaurant_home_banner_columns',Number(e.target.value))}><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></label>
    <label><span>Card corner radius (px)</span><input type="number" min="8" max="40" value={form.restaurant_home_card_radius} onChange={e=>set('restaurant_home_card_radius',Number(e.target.value))}/></label>
   </div></Section>
   <Section title="Live Preview Controls" meta="Choose which sections are available on the global homepage."><div className="card store-toggle-grid">{[['restaurant_home_show_search','Search'],['restaurant_home_show_modes','Delivery / Pickup / Dine-in'],['restaurant_home_show_banners','Hero / promotional banners'],['restaurant_home_show_offers','Offers'],['restaurant_home_show_restaurants','Restaurant listings'],['restaurant_home_show_popular','Popular dishes'],['restaurant_home_show_footer','Footer']].map(([k,l])=><label key={k} className="check-field"><input type="checkbox" checked={!!form[k]} onChange={e=>set(k,e.target.checked)}/><span>{l}</span></label>)}</div></Section>
  </>}
  {tab==='hero'&&<>
   <Section title="Ultra-Premium Hero" meta="Set the global homepage hero exactly from Super Admin. Use a separate mobile crop for better phone composition."><div className="card store-settings-grid">
    <MarketplaceImageUpload label="Desktop hero image" value={form.restaurant_home_hero_image} onChange={v=>set('restaurant_home_hero_image',v)} folder="marketplace/restaurants/hero"/>
    <MarketplaceImageUpload label="Mobile hero image" value={form.restaurant_home_hero_mobile_image} onChange={v=>set('restaurant_home_hero_mobile_image',v)} folder="marketplace/restaurants/hero-mobile"/>
    <label><span>Hero overlay strength</span><input type="number" min="0" max="0.9" step="0.05" value={form.restaurant_home_hero_overlay} onChange={e=>set('restaurant_home_hero_overlay',e.target.value)}/></label>
    <label><span>Hero CTA label</span><input value={form.restaurant_home_hero_cta} onChange={e=>set('restaurant_home_hero_cta',e.target.value)}/></label>
    <label className="full"><span>Hero CTA URL</span><input value={form.restaurant_home_hero_cta_url} onChange={e=>set('restaurant_home_hero_cta_url',e.target.value)}/></label>
   </div></Section>
   <Section title="Restaurant Marketplace Home — Homepage Promotional Banners" meta="Global banners belong to Super Admin. Restaurant admins cannot edit these banners."><div className="card"><form className="store-settings-grid" onSubmit={addBanner}>
    <label><span>Banner title</span><input value={banner.title} onChange={e=>setBanner({...banner,title:e.target.value})} placeholder="Weekend Food Festival"/></label><label><span>Subtitle</span><input value={banner.subtitle} onChange={e=>setBanner({...banner,subtitle:e.target.value})}/></label>
    <MarketplaceImageUpload label="Desktop banner image" value={banner.image_url} onChange={v=>setBanner({...banner,image_url:v})} folder="marketplace/restaurants/banners"/>
    <MarketplaceImageUpload label="Mobile banner image" value={banner.mobile_image_url} onChange={v=>setBanner({...banner,mobile_image_url:v})} folder="marketplace/restaurants/banners-mobile"/><label><span>CTA label</span><input value={banner.cta_label} onChange={e=>setBanner({...banner,cta_label:e.target.value})}/></label><label><span>CTA URL</span><input value={banner.cta_url} onChange={e=>setBanner({...banner,cta_url:e.target.value})}/></label><label><span>Display order</span><input type="number" value={banner.display_order} onChange={e=>setBanner({...banner,display_order:e.target.value})}/></label><div className="full"><button className="btn primary">Add Global Banner</button></div>
   </form><div className="banner-admin-list">{banners.map(b=><article key={b.id}><img src={b.image_url} alt=""/><div><b>{b.title}</b><p>{b.subtitle||'No subtitle'} · order {b.display_order}</p><small>{b.active?'LIVE':'DISABLED'}</small></div><div><button className="btn" onClick={()=>toggleBanner(b)}>{b.active?'Disable':'Enable'}</button><button className="btn" onClick={()=>deleteBanner(b.id)}>Delete</button></div></article>)}</div></div></Section>
  </>}
  {tab==='sections'&&<Section title="Homepage Section Layout" meta="Control the global ordering and density without changing Restaurant SaaS catalog data."><div className="card store-section-layout"><div className="layout-preview"><div className="lp-hero">HERO / SEARCH / CTA</div><div className="lp-row"><div>OFFERS</div><div>PROMOTIONS</div></div><div className="lp-restaurants">RESTAURANT DISCOVERY GRID</div><div className="lp-dishes">POPULAR DISHES</div></div><div className="store-settings-grid"><label><span>Restaurant grid</span><select value={form.restaurant_home_restaurant_columns} onChange={e=>set('restaurant_home_restaurant_columns',Number(e.target.value))}><option value="2">2 columns</option><option value="3">3 columns</option><option value="4">4 columns</option></select></label><label><span>Dish grid</span><select value={form.restaurant_home_dish_columns} onChange={e=>set('restaurant_home_dish_columns',Number(e.target.value))}><option value="3">3 columns</option><option value="4">4 columns</option><option value="5">5 columns</option></select></label><label><span>Banner grid</span><select value={form.restaurant_home_banner_columns} onChange={e=>set('restaurant_home_banner_columns',Number(e.target.value))}><option value="1">1 column</option><option value="2">2 columns</option><option value="3">3 columns</option></select></label><label><span>Card radius</span><input type="number" min="8" max="40" value={form.restaurant_home_card_radius} onChange={e=>set('restaurant_home_card_radius',Number(e.target.value))}/></label></div></div></Section>}
  {tab==='business'&&<Section title="Marketplace Business Rules" meta="Global policy only. Individual restaurant content remains inside its own Business Admin store builder."><form className="card store-settings-grid" onSubmit={save}><label className="check-field"><input type="checkbox" checked={!!form.marketplace_enabled} onChange={e=>set('marketplace_enabled',e.target.checked)}/><span>Restaurant Marketplace enabled</span></label><label className="check-field"><input type="checkbox" checked={!!form.require_listing_approval} onChange={e=>set('require_listing_approval',e.target.checked)}/><span>Require listing approval</span></label><label><span>Default commission %</span><input type="number" min="0" max="100" step="0.01" value={form.default_commission_percent} onChange={e=>set('default_commission_percent',Number(e.target.value))}/></label><label className="check-field"><input type="checkbox" checked={!!form.featured_listings_enabled} onChange={e=>set('featured_listings_enabled',e.target.checked)}/><span>Featured listings enabled</span></label><label className="check-field"><input type="checkbox" checked={!!form.settlements_enabled} onChange={e=>set('settlements_enabled',e.target.checked)}/><span>Marketplace settlements enabled</span></label><label><span>Marketplace payment mode</span><select value={form.marketplace_payment_mode} onChange={e=>set('marketplace_payment_mode',e.target.value)}><option value="platform">Platform</option><option value="direct">Direct to business</option><option value="hybrid">Hybrid</option></select></label></form></Section>}
  {tab==='seo'&&<Section title="SEO, Footer & Discovery" meta="Global Restaurant Marketplace metadata controlled by Super Admin."><div className="card store-settings-grid"><label><span>SEO title</span><input value={form.restaurant_home_meta_title} onChange={e=>set('restaurant_home_meta_title',e.target.value)}/></label><label><span>Footer text</span><input value={form.restaurant_home_footer_text} onChange={e=>set('restaurant_home_footer_text',e.target.value)}/></label><label className="full"><span>SEO description</span><textarea value={form.restaurant_home_meta_description} onChange={e=>set('restaurant_home_meta_description',e.target.value)} rows={4}/></label></div></Section>}
  <div className="store-control-footer"><b>Ownership boundary:</b> Super Admin owns the global Restaurant Marketplace store. Business Admin owns only their own restaurant/hotel store. Restaurant SaaS remains the operational catalog and order source of truth. <Link href="/store" target="_blank">Preview global store ↗</Link></div>
 </AppShell>
}
