'use client';
import {useEffect,useState} from 'react';
import {AppShell,Header,Section} from '../../components';
import {supabase} from '../../../lib/supabase';

const defaults={marketplace_enabled:true,require_listing_approval:true,default_commission_percent:0,featured_listings_enabled:true,settlements_enabled:true,marketplace_payment_mode:'platform'};
export default function MarketplaceSettings(){
 const [form,setForm]=useState(defaults),[msg,setMsg]=useState(''),[error,setError]=useState('');
 useEffect(()=>{(async()=>{const {data,error}=await supabase.from('anaira_platform_settings').select('key,value').in('key',Object.keys(defaults));if(error){setError(error.message);return}const x={...defaults};(data||[]).forEach(r=>x[r.key]=r.value?.value??r.value);setForm(x)})()},[]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function save(e){e.preventDefault();setMsg('');setError('');const user=(await supabase.auth.getUser()).data.user?.id;for(const [key,value] of Object.entries(form)){const q=await supabase.from('anaira_platform_settings').upsert({key,value:{value},updated_by:user},{onConflict:'key'});if(q.error){setError(q.error.message);return}}setMsg('Marketplace platform settings saved.');}
 return <AppShell active="/super-admin/marketplace-settings"><Header eyebrow="SUPER ADMIN • MARKETPLACE" title="Marketplace Settings" subtitle="Global marketplace policy, approval, commission and settlement controls. Business Admin cannot access this module."/><Section title="Platform Marketplace Configuration" meta="Super Admin only"><form className="card admin-form" onSubmit={save}><label className="check-field"><input type="checkbox" checked={!!form.marketplace_enabled} onChange={e=>set('marketplace_enabled',e.target.checked)}/><span>Marketplace enabled</span></label><label className="check-field"><input type="checkbox" checked={!!form.require_listing_approval} onChange={e=>set('require_listing_approval',e.target.checked)}/><span>Require listing approval</span></label><label><span>Default commission %</span><input type="number" min="0" max="100" step="0.01" value={form.default_commission_percent} onChange={e=>set('default_commission_percent',Number(e.target.value))}/></label><label className="check-field"><input type="checkbox" checked={!!form.featured_listings_enabled} onChange={e=>set('featured_listings_enabled',e.target.checked)}/><span>Featured listings enabled</span></label><label className="check-field"><input type="checkbox" checked={!!form.settlements_enabled} onChange={e=>set('settlements_enabled',e.target.checked)}/><span>Marketplace settlements enabled</span></label><label><span>Marketplace payment mode</span><select value={form.marketplace_payment_mode} onChange={e=>set('marketplace_payment_mode',e.target.value)}><option value="platform">Platform</option><option value="direct">Direct to business</option><option value="hybrid">Hybrid</option></select></label><div className="full"><button className="btn primary">Save Marketplace Settings</button>{msg&&<span style={{marginLeft:10}}>{msg}</span>}{error&&<div className="notice error">{error}</div>}</div></form></Section></AppShell>;
}
