'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {AppShell,Header,Section} from '../../components';
import {supabase} from '../../../lib/supabase';
import MarketplaceImageUpload from '../MarketplaceImageUpload';

const defaultFeatures=[{icon:'🍽️',title:'Fresh Food',text:'Quality dishes from connected kitchens'},{icon:'🚴',title:'Fast Delivery',text:'Direct ordering from restaurants'},{icon:'🥬',title:'Hygienic Kitchens',text:'Freshly prepared with care'},{icon:'💳',title:'Secure Payments',text:'Multiple payment options'},{icon:'🎁',title:'Exclusive Offers',text:'Restaurant-specific deals'},{icon:'📞',title:'24/7 Support',text:'Help when you need it'}];
const defaults={
 marketplace_enabled:true,require_listing_approval:true,default_commission_percent:0,featured_listings_enabled:true,settlements_enabled:true,marketplace_payment_mode:'platform',
 restaurant_home_title:'Good food. Great restaurants.',restaurant_home_subtitle:'Discover live menus, offers, delivery, pickup and dine-in from restaurants on Anaira.',restaurant_home_theme:'forest',
 restaurant_home_show_search:true,restaurant_home_show_popular:true,restaurant_home_show_offers:true,restaurant_home_show_modes:true,restaurant_home_show_banners:true,restaurant_home_show_restaurants:true,
 restaurant_home_hero_image:'',restaurant_home_hero_mobile_image:'',restaurant_home_hero_overlay:'0.58',restaurant_home_hero_cta:'Explore restaurants',restaurant_home_hero_cta_url:'#restaurants',
 restaurant_home_primary_color:'#073b2b',restaurant_home_accent_color:'#d4aa4c',restaurant_home_surface_color:'#ffffff',restaurant_home_background_color:'#f7f7f5',restaurant_home_text_color:'#17352a',
 restaurant_home_container_width:1240,restaurant_home_restaurant_columns:3,restaurant_home_dish_columns:4,restaurant_home_banner_columns:3,restaurant_home_card_radius:20,
 restaurant_home_show_footer:true,restaurant_home_footer_text:'Anaira Food — discover restaurants, order food and enjoy local dining.',restaurant_home_meta_title:'Anaira Food | Restaurant Marketplace',restaurant_home_meta_description:'Discover restaurants, menus, offers, delivery, pickup and dine-in on Anaira Food.',
 restaurant_home_feature_icons:defaultFeatures,
 restaurant_home_categories:[{name:'North Indian',icon:'🍛'},{name:'Chinese',icon:'🥡'},{name:'Fast Food',icon:'🍔'},{name:'Tandoori',icon:'🔥'},{name:'Pizza',icon:'🍕'},{name:'Burgers',icon:'🍔'},{name:'Momos',icon:'🥟'},{name:'Thali',icon:'🍱'},{name:'Beverages',icon:'☕'},{name:'Desserts',icon:'🍰'}]
};
const blank={title:'',subtitle:'',image_url:'',mobile_image_url:'',cta_label:'Explore restaurants',cta_url:'#restaurants',display_order:0,active:true};
const field=(label,key,type='text',extra={})=>({label,key,type,...extra});


function RestaurantStoreExperienceManager({store}){
 const blankPc={why_label:'WHY CHOOSE US',why_title:'A better food experience for everyone',why_choose:[],how_label:'HOW IT WORKS',how_title:'Order your favourite food in a few simple steps',how_it_works:[],flavor_banner:{eyebrow:'DISCOVER OUR FLAVOURS',title:'Taste the flavours of our kitchen',text:'Authentic food, warm hospitality and memorable dining.',image_url:'',cta_label:'Explore Menu',cta_url:'#menu'},app_promo:{eyebrow:'ORDER ON THE GO',title:'Download our app',text:'A faster way to discover menus and place orders.',image_url:'',cta_label:'Order Now',cta_url:'#menu',points:[]},reservation:{title:'Plan Your Visit',text:'Reserve your table for a delightful dining experience.',cta_label:'Book Now'},footer:{text:'Bringing great food and warm hospitality to your doorstep.'}};
 const [restaurants,setRestaurants]=useState([]),[rid,setRid]=useState(''),[membership,setMembership]=useState(null),[pc,setPc]=useState(blankPc),[features,setFeatures]=useState([]),[gallery,setGallery]=useState([]),[banners,setBanners]=useState([]),[banner,setBanner]=useState({title:'',subtitle:'',image_url:'',mobile_image_url:'',cta_label:'Order Now',cta_url:'#menu',display_order:0,active:true}),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[error,setError]=useState('');
 useEffect(()=>{(async()=>{const {data}=await supabase.from('restaurants').select('id,name,city').order('name').limit(500);setRestaurants(data||[])})()},[]);
 async function load(id){if(!id||!store)return;setLoading(true);setMsg('');setError('');const [{data:m,error:me},{data:b,error:be}]=await Promise.all([supabase.from('anaira_store_memberships').select('*').eq('restaurant_id',id).eq('store_id',store.id).maybeSingle(),supabase.from('anaira_store_banners').select('*').eq('restaurant_id',id).eq('store_id',store.id).order('display_order')]);if(me){setError(me.message);setLoading(false);return}setMembership(m||null);const sc=m?.store_config||{}, p=m?.store_config?.page_content||{};setPc({...blankPc,...p});setFeatures(Array.isArray(sc.feature_icons)?sc.feature_icons:[]);setGallery(Array.isArray(m?.listing_override?.gallery)?m.listing_override.gallery:[]);setBanners(b||[]);setLoading(false)}
 useEffect(()=>{load(rid)},[rid,store?.id]);
 const updateArr=(key,index,patch)=>setPc(x=>({...x,[key]:(x[key]||[]).map((v,i)=>i===index?{...v,...patch}:v)}));
 async function saveAll(){if(!membership)return;setSaving(true);setMsg('');setError('');const old=membership.store_config||{};const store_config={...old,feature_icons:features,page_content:pc};const listing_override={...(membership.listing_override||{}),gallery};const {data,error}=await supabase.from('anaira_store_memberships').update({store_config,listing_override,updated_at:new Date().toISOString()}).eq('id',membership.id).select('*').single();if(error)setError(error.message);else{setMembership(data);setMsg('Restaurant Store experience saved.');}setSaving(false)}
 async function addBanner(e){e.preventDefault();if(!membership||!banner.image_url){setError('Select a restaurant and upload a hero image first.');return}const {data,error}=await supabase.from('anaira_store_banners').insert({...banner,store_id:store.id,restaurant_id:rid,display_order:Number(banner.display_order)||0}).select('*').single();if(error)setError(error.message);else{setBanners(x=>[...x,data].sort((a,b)=>(a.display_order||0)-(b.display_order||0)));setBanner({title:'',subtitle:'',image_url:'',mobile_image_url:'',cta_label:'Order Now',cta_url:'#menu',display_order:banners.length+1,active:true})}}
 async function toggleBanner(b){const {error}=await supabase.from('anaira_store_banners').update({active:!b.active,updated_at:new Date().toISOString()}).eq('id',b.id);if(error)setError(error.message);else setBanners(x=>x.map(a=>a.id===b.id?{...a,active:!b.active}:a))}
 async function deleteBanner(id){const {error}=await supabase.from('anaira_store_banners').delete().eq('id',id);if(error)setError(error.message);else setBanners(x=>x.filter(a=>a.id!==id))}
 const addWhy=()=>setPc(x=>({...x,why_choose:[...(x.why_choose||[]),{icon:'✦',title:'Great Experience',text:'Made for our guests',action_type:'menu',action_value:''}]}));
 const addHow=()=>setPc(x=>({...x,how_it_works:[...(x.how_it_works||[]),{icon:String((x.how_it_works||[]).length+1),title:'Choose your food',text:'Browse the live restaurant menu.'}]}));
 const addTest=()=>setPc(x=>({...x,testimonials:[...(x.testimonials||[]),{name:'Guest',rating:5,text:'Amazing food and service.',meta:'Verified guest'}]}));
 const addFeature=()=>setFeatures(x=>[...x,{icon:'✦',title:'Restaurant Experience',text:'A memorable experience for every guest',action_type:'menu',action_value:''}]);
 return <div className="amp-store-experience"><div className="card"><div className="store-settings-grid"><label className="full"><span>Select Restaurant Store</span><select value={rid} onChange={e=>setRid(e.target.value)}><option value="">Select restaurant…</option>{restaurants.map(r=><option key={r.id} value={r.id}>{r.name}{r.city?` · ${r.city}`:''}</option>)}</select></label></div>{loading&&<p>Loading restaurant experience…</p>}{rid&&!loading&&<>
   <div className="experience-toolbar"><b>Restaurant Store Experience</b><button className="btn primary" onClick={saveAll} disabled={saving}>{saving?'Saving…':'Save All Restaurant Content'}</button></div>
   <Section title="Hero Slider — Restaurant Specific" meta="These slides appear only on this restaurant's /store/[id] page. Upload, edit, enable/disable and delete them here."><form className="store-settings-grid" onSubmit={addBanner}><label><span>Title</span><input value={banner.title} onChange={e=>setBanner({...banner,title:e.target.value})}/></label><label><span>Subtitle</span><input value={banner.subtitle} onChange={e=>setBanner({...banner,subtitle:e.target.value})}/></label><MarketplaceImageUpload label="Desktop image" value={banner.image_url} onChange={v=>setBanner({...banner,image_url:v})} folder={`marketplace/restaurants/${rid}/hero`}/><MarketplaceImageUpload label="Mobile image" value={banner.mobile_image_url} onChange={v=>setBanner({...banner,mobile_image_url:v})} folder={`marketplace/restaurants/${rid}/hero-mobile`}/><label><span>CTA</span><input value={banner.cta_label} onChange={e=>setBanner({...banner,cta_label:e.target.value})}/></label><label><span>CTA URL</span><input value={banner.cta_url} onChange={e=>setBanner({...banner,cta_url:e.target.value})}/></label><label><span>Order</span><input type="number" value={banner.display_order} onChange={e=>setBanner({...banner,display_order:e.target.value})}/></label><div className="full"><button className="btn primary">+ Add Hero Slide</button></div></form><div className="banner-admin-list">{banners.map(b=><article key={b.id}><img src={b.image_url} alt=""/><div><b>{b.title||'Restaurant Hero'}</b><p>{b.subtitle||''}</p><small>{b.active?'LIVE':'DISABLED'}</small></div><div><button className="btn" onClick={()=>toggleBanner(b)}>{b.active?'Disable':'Enable'}</button><button className="btn" onClick={()=>deleteBanner(b.id)}>Delete</button></div></article>)}</div></Section>
   <Section title="Premium Feature / Highlight Buttons" meta="Every icon is clickable. Use Menu, Category, Dish, Offers, Gallery, About, Reservation or URL actions."><div className="sb-feature-editor">{features.map((f,i)=><div className="sb-feature-rich" key={i}><input value={f.icon||''} onChange={e=>setFeatures(a=>a.map((x,n)=>n===i?{...x,icon:e.target.value}:x))} placeholder="🍽️"/><input value={f.title||''} onChange={e=>setFeatures(a=>a.map((x,n)=>n===i?{...x,title:e.target.value}:x))} placeholder="Fresh Food"/><input value={f.text||''} onChange={e=>setFeatures(a=>a.map((x,n)=>n===i?{...x,text:e.target.value}:x))} placeholder="Description"/><select value={f.action_type||'menu'} onChange={e=>setFeatures(a=>a.map((x,n)=>n===i?{...x,action_type:e.target.value,action_value:''}:x))}><option value="menu">Menu</option><option value="category">Category</option><option value="item">Dish</option><option value="offers">Offers</option><option value="gallery">Gallery</option><option value="about">About</option><option value="reservation">Reservation</option><option value="url">URL</option></select><input value={f.action_value||''} onChange={e=>setFeatures(a=>a.map((x,n)=>n===i?{...x,action_value:e.target.value}:x))} placeholder="Target ID / URL"/><button className="btn" onClick={()=>setFeatures(a=>a.filter((_,n)=>n!==i))}>Delete</button></div>)}<button className="btn" onClick={addFeature}>+ Add Highlight</button></div></Section>
   <Section title="Why Choose Us" meta="The six/eight premium icon boxes shown on the restaurant page."><div className="store-settings-grid"><label><span>Eyebrow</span><input value={pc.why_label||''} onChange={e=>setPc(x=>({...x,why_label:e.target.value}))}/></label><label><span>Heading</span><input value={pc.why_title||''} onChange={e=>setPc(x=>({...x,why_title:e.target.value}))}/></label></div><div className="sb-content-grid">{(pc.why_choose||[]).map((x,i)=><div className="content-card" key={i}><input value={x.icon||''} onChange={e=>updateArr('why_choose',i,{icon:e.target.value})}/><input value={x.title||''} onChange={e=>updateArr('why_choose',i,{title:e.target.value})}/><textarea value={x.text||''} onChange={e=>updateArr('why_choose',i,{text:e.target.value})}/><button className="btn" onClick={()=>setPc(a=>({...a,why_choose:a.why_choose.filter((_,n)=>n!==i)}))}>Delete</button></div>)}</div><button className="btn" onClick={addWhy}>+ Add Benefit</button></Section>
   <Section title="Flavour / Destination Banner" meta="Premium image banner between About and Gallery."><div className="store-settings-grid"><label><span>Eyebrow</span><input value={pc.flavor_banner.eyebrow||''} onChange={e=>setPc(x=>({...x,flavor_banner:{...x.flavor_banner,eyebrow:e.target.value}}))}/></label><label><span>Title</span><input value={pc.flavor_banner.title||''} onChange={e=>setPc(x=>({...x,flavor_banner:{...x.flavor_banner,title:e.target.value}}))}/></label><label className="full"><span>Description</span><textarea value={pc.flavor_banner.text||''} onChange={e=>setPc(x=>({...x,flavor_banner:{...x.flavor_banner,text:e.target.value}}))}/></label><MarketplaceImageUpload label="Banner image" value={pc.flavor_banner.image_url||''} onChange={v=>setPc(x=>({...x,flavor_banner:{...x.flavor_banner,image_url:v}}))} folder={`marketplace/restaurants/${rid}/flavour`}/><label><span>Button text</span><input value={pc.flavor_banner.cta_label||''} onChange={e=>setPc(x=>({...x,flavor_banner:{...x.flavor_banner,cta_label:e.target.value}}))}/></label><label><span>Button URL</span><input value={pc.flavor_banner.cta_url||''} onChange={e=>setPc(x=>({...x,flavor_banner:{...x.flavor_banner,cta_url:e.target.value}}))}/></label></div></Section>
   <Section title="How It Works" meta="Four step cards shown on the public store."><div className="store-settings-grid"><label><span>Eyebrow</span><input value={pc.how_label||''} onChange={e=>setPc(x=>({...x,how_label:e.target.value}))}/></label><label><span>Heading</span><input value={pc.how_title||''} onChange={e=>setPc(x=>({...x,how_title:e.target.value}))}/></label></div><div className="sb-content-grid">{(pc.how_it_works||[]).map((x,i)=><div className="content-card" key={i}><input value={x.icon||''} onChange={e=>updateArr('how_it_works',i,{icon:e.target.value})}/><input value={x.title||''} onChange={e=>updateArr('how_it_works',i,{title:e.target.value})}/><textarea value={x.text||''} onChange={e=>updateArr('how_it_works',i,{text:e.target.value})}/><button className="btn" onClick={()=>setPc(a=>({...a,how_it_works:a.how_it_works.filter((_,n)=>n!==i)}))}>Delete</button></div>)}</div><button className="btn" onClick={addHow}>+ Add Step</button></Section>
   <Section title="App Promotion" meta="Optional red premium banner like the reference design."><div className="store-settings-grid"><label><span>Eyebrow</span><input value={pc.app_promo.eyebrow||''} onChange={e=>setPc(x=>({...x,app_promo:{...x.app_promo,eyebrow:e.target.value}}))}/></label><label><span>Title</span><input value={pc.app_promo.title||''} onChange={e=>setPc(x=>({...x,app_promo:{...x.app_promo,title:e.target.value}}))}/></label><label className="full"><span>Text</span><textarea value={pc.app_promo.text||''} onChange={e=>setPc(x=>({...x,app_promo:{...x.app_promo,text:e.target.value}}))}/></label><MarketplaceImageUpload label="Promotion image" value={pc.app_promo.image_url||''} onChange={v=>setPc(x=>({...x,app_promo:{...x.app_promo,image_url:v}}))} folder={`marketplace/restaurants/${rid}/app`}/><label><span>CTA label</span><input value={pc.app_promo.cta_label||''} onChange={e=>setPc(x=>({...x,app_promo:{...x.app_promo,cta_label:e.target.value}}))}/></label><label><span>CTA URL</span><input value={pc.app_promo.cta_url||''} onChange={e=>setPc(x=>({...x,app_promo:{...x.app_promo,cta_url:e.target.value}}))}/></label></div></Section>
   <Section title="Customer Reviews"><div className="sb-content-grid">{(pc.testimonials||[]).map((x,i)=><div className="content-card" key={i}><input value={x.name||''} onChange={e=>updateArr('testimonials',i,{name:e.target.value})}/><input value={x.rating||5} type="number" min="1" max="5" onChange={e=>updateArr('testimonials',i,{rating:Number(e.target.value)})}/><input value={x.meta||''} onChange={e=>updateArr('testimonials',i,{meta:e.target.value})}/><textarea value={x.text||''} onChange={e=>updateArr('testimonials',i,{text:e.target.value})}/><button className="btn" onClick={()=>setPc(a=>({...a,testimonials:a.testimonials.filter((_,n)=>n!==i)}))}>Delete</button></div>)}</div><button className="btn" onClick={addTest}>+ Add Review</button></Section>
   <Section title="Reservation & Footer"><div className="store-settings-grid"><label><span>Reservation title</span><input value={pc.reservation.title||''} onChange={e=>setPc(x=>({...x,reservation:{...x.reservation,title:e.target.value}}))}/></label><label><span>Reservation CTA</span><input value={pc.reservation.cta_label||''} onChange={e=>setPc(x=>({...x,reservation:{...x.reservation,cta_label:e.target.value}}))}/></label><label className="full"><span>Reservation text</span><textarea value={pc.reservation.text||''} onChange={e=>setPc(x=>({...x,reservation:{...x.reservation,text:e.target.value}}))}/></label><label className="full"><span>Footer premium text</span><textarea value={pc.footer.text||''} onChange={e=>setPc(x=>({...x,footer:{...x.footer,text:e.target.value}}))}/></label></div></Section>
   <Section title="Restaurant Gallery"><div className="sb-content-grid">{gallery.map((u,i)=><div className="content-card" key={i}><img src={u} alt="" style={{width:'100%',height:110,objectFit:'cover',borderRadius:10}}/><button className="btn" onClick={()=>setGallery(a=>a.filter((_,n)=>n!==i))}>Delete</button></div>)}</div><div className="gallery-add-row"><MarketplaceImageUpload label="Add gallery image" value="" onChange={v=>v&&setGallery(a=>[...a,v])} folder={`marketplace/restaurants/${rid}/gallery`}/></div></Section>
 </>}</div></div>
}

function RestaurantFeaturedManager({store}){
 const [restaurants,setRestaurants]=useState([]),[rid,setRid]=useState(''),[menu,setMenu]=useState([]),[selected,setSelected]=useState([]),[loading,setLoading]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{(async()=>{const {data}=await supabase.from('restaurants').select('id,name,city').order('name').limit(500);setRestaurants(data||[])})()},[]);
 async function load(){if(!rid||!store)return;setLoading(true);const [{data:m},{data:f}]=await Promise.all([supabase.from('anaira_marketplace_menu_items').select('id,item_name,name,price,discount_price,image_url,image,category_name').eq('restaurant_id',rid).eq('active',true).order('display_order').limit(200),supabase.from('anaira_marketplace_featured_items').select('*').eq('restaurant_id',rid).eq('store_id',store.id)]);setMenu(m||[]);setSelected(f||[]);setLoading(false)}
 useEffect(()=>{load()},[rid,store?.id]);
 async function toggle(i){if(!store)return;const ex=selected.find(x=>String(x.external_item_id)===String(i.id));if(ex){await supabase.from('anaira_marketplace_featured_items').update({active:!ex.active,updated_at:new Date().toISOString()}).eq('id',ex.id);setSelected(x=>x.map(a=>a.id===ex.id?{...a,active:!ex.active}:a));return}const {data,error}=await supabase.from('anaira_marketplace_featured_items').insert({store_id:store.id,restaurant_id:rid,external_item_id:String(i.id),title_override:null,image_override:i.image_url||i.image||null,badge:'Popular',display_order:selected.length,active:true}).select('*').single();if(!error&&data)setSelected(x=>[...x,data])}
 return <div className="amp-admin-feature-manager"><select value={rid} onChange={e=>setRid(e.target.value)}><option value="">Select restaurant…</option>{restaurants.map(r=><option key={r.id} value={r.id}>{r.name}{r.city?` · ${r.city}`:''}</option>)}</select>{loading?<p>Loading menu…</p>:<div className="amp-admin-menu-pick">{menu.map(i=>{const active=selected.some(x=>String(x.external_item_id)===String(i.id)&&x.active);return <button type="button" key={i.id} className={active?'active':''} onClick={()=>toggle(i)}><span>{i.image_url||i.image?<img src={i.image_url||i.image} alt=""/>:<i>🍽️</i>}</span><b>{i.item_name||i.name}</b><small>₹{i.discount_price??i.price}</small></button>})}</div>}<small>{msg}</small></div>
}

export default function MarketplaceSettings(){
 const [form,setForm]=useState(defaults),[banners,setBanners]=useState([]),[banner,setBanner]=useState(blank),[store,setStore]=useState(null),[msg,setMsg]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState('design'),[saving,setSaving]=useState(false);
 useEffect(()=>{(async()=>{const {data,error}=await supabase.from('anaira_platform_settings').select('key,value').in('key',Object.keys(defaults));if(error){setError(error.message);return}const x={...defaults};(data||[]).forEach(r=>x[r.key]=r.value?.value??r.value);setForm(x);const {data:s}=await supabase.from('anaira_platform_stores').select('id,store_name').eq('store_type','restaurant').maybeSingle();setStore(s||null);if(s){const {data:b}=await supabase.from('anaira_store_banners').select('*').eq('store_id',s.id).order('display_order');setBanners(b||[])}})()},[]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function save(e){e?.preventDefault();setSaving(true);setMsg('');setError('');const user=(await supabase.auth.getUser()).data.user?.id;for(const [key,value] of Object.entries(form)){const q=await supabase.from('anaira_platform_settings').upsert({key,value:{value},updated_by:user},{onConflict:'key'});if(q.error){setError(q.error.message);setSaving(false);return}}setMsg('Global Restaurant Store settings saved.');setSaving(false);}
 async function addBanner(e){e.preventDefault();setError('');if(!store||!banner.title||!banner.image_url){setError('Banner title and desktop image are required.');return}const {data,error}=await supabase.from('anaira_store_banners').insert({...banner,store_id:store.id,restaurant_id:null,display_order:Number(banner.display_order)||0}).select('*').single();if(error){setError(error.message);return}setBanners(x=>[...x,data].sort((a,b)=>(a.display_order||0)-(b.display_order||0)));setBanner(blank);setMsg('Global homepage banner added.');}
 async function toggleBanner(b){const {error}=await supabase.from('anaira_store_banners').update({active:!b.active,updated_at:new Date().toISOString()}).eq('id',b.id);if(error){setError(error.message);return}setBanners(x=>x.map(i=>i.id===b.id?{...i,active:!b.active}:i));}
 async function deleteBanner(id){const {error}=await supabase.from('anaira_store_banners').delete().eq('id',id);if(error){setError(error.message);return}setBanners(x=>x.filter(i=>i.id!==id));}
 async function editBanner(b){const title=window.prompt('Banner title',b.title||'');if(title===null)return;const subtitle=window.prompt('Banner subtitle',b.subtitle||'');if(subtitle===null)return;const cta=window.prompt('CTA label',b.cta_label||'');if(cta===null)return;const {data,error}=await supabase.from('anaira_store_banners').update({title,subtitle,cta_label:cta,updated_at:new Date().toISOString()}).eq('id',b.id).select('*').single();if(error){setError(error.message);return}setBanners(x=>x.map(i=>i.id===b.id?data:i));setMsg('Banner updated.');}
 const tabs=[['design','🎨 Store Design'],['hero','🖼 Hero & Banners'],['restaurant-store','🍽 Restaurant Store Page'],['sections','🧩 Home Sections'],['business','⚙ Marketplace Rules'],['seo','🔎 SEO & Footer']];
 return <AppShell active="/super-admin/marketplace-settings">
  <Header eyebrow="SUPER ADMIN • GLOBAL RESTAURANT STORE" title="Restaurant Store Control Center" subtitle="This is the GLOBAL Anaira Restaurant Marketplace store. Super Admin owns its branding, layout, homepage, banners, sections, marketplace rules and publishing. Business Admin controls only their own restaurant or hotel store." actions={<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><Link className="btn" href="/store" target="_blank">Open Global Store ↗</Link><button className="btn primary" onClick={()=>save()} disabled={saving}>{saving?'Saving…':'Save All Changes'}</button></div>}/>
  <div className="store-control-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {msg&&<div className="notice success" style={{marginBottom:16}}>{msg}</div>}{error&&<div className="notice error" style={{marginBottom:16}}>{error}</div>}
  {tab==='restaurant-store'&&<RestaurantStoreExperienceManager store={store}/>}
  {tab==='design'&&<>
   <Section title="Global Store Identity & Visual System" meta="Everything here belongs to the Super Admin-owned Restaurant Marketplace. It affects the global /store experience, not an individual restaurant store."><div className="card store-settings-grid">
    <label><span>Homepage title</span><input value={form.restaurant_home_title} onChange={e=>set('restaurant_home_title',e.target.value)}/></label>
    <label><span>Homepage subtitle</span><input value={form.restaurant_home_subtitle} onChange={e=>set('restaurant_home_subtitle',e.target.value)}/></label>
    <label><span>Theme preset</span><select value={form.restaurant_home_theme} onChange={e=>set('restaurant_home_theme',e.target.value)}><option value="forest">Forest Premium</option><option value="light">Luxury Light</option><option value="dark">Midnight</option></select></label>
    <label><span>Primary / header color</span><input type="color" value={form.restaurant_home_primary_color} onChange={e=>set('restaurant_home_primary_color',e.target.value)}/></label>
    <label><span>Accent / CTA color</span><input type="color" value={form.restaurant_home_accent_color} onChange={e=>set('restaurant_home_accent_color',e.target.value)}/></label>
    <label><span>Page background</span><input type="color" value={form.restaurant_home_background_color} onChange={e=>set('restaurant_home_background_color',e.target.value)}/></label>
    <label><span>Card / surface color</span><input type="color" value={form.restaurant_home_surface_color} onChange={e=>set('restaurant_home_surface_color',e.target.value)}/></label>
    <label><span>Text color</span><input type="color" value={form.restaurant_home_text_color} onChange={e=>set('restaurant_home_text_color',e.target.value)}/></label>
    <label><span>Content max width (px)</span><input type="number" min="980" max="1600" value={form.restaurant_home_container_width} onChange={e=>set('restaurant_home_container_width',Number(e.target.value))}/></label>
    <label><span>Restaurant cards per row</span><select value={form.restaurant_home_restaurant_columns} onChange={e=>set('restaurant_home_restaurant_columns',Number(e.target.value))}><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></label>
    <label><span>Popular dish cards per row</span><select value={form.restaurant_home_dish_columns} onChange={e=>set('restaurant_home_dish_columns',Number(e.target.value))}><option value="3">3</option><option value="4">4</option><option value="5">5</option></select></label>
    <label><span>Banner cards per row</span><select value={form.restaurant_home_banner_columns} onChange={e=>set('restaurant_home_banner_columns',Number(e.target.value))}><option value="1">1</option><option value="2">2</option><option value="3">3</option></select></label>
    <label><span>Card corner radius (px)</span><input type="number" min="8" max="40" value={form.restaurant_home_card_radius} onChange={e=>set('restaurant_home_card_radius',Number(e.target.value))}/></label>
   </div></Section>
   <Section title="Live Preview Controls" meta="Choose which sections are available on the global homepage."><div className="card store-toggle-grid">{[['restaurant_home_show_search','Search'],['restaurant_home_show_modes','Delivery / Pickup / Dine-in'],['restaurant_home_show_banners','Hero / promotional banners'],['restaurant_home_show_offers','Offers'],['restaurant_home_show_restaurants','Restaurant listings'],['restaurant_home_show_popular','Popular dishes'],['restaurant_home_show_footer','Footer']].map(([k,l])=><label key={k} className="check-field"><input type="checkbox" checked={!!form[k]} onChange={e=>set(k,e.target.checked)}/><span>{l}</span></label>)}</div></Section>
  </>}
  {tab==='hero'&&<>
   <Section title="Ultra-Premium Hero" meta="Set the global homepage hero exactly from Super Admin. Use a separate mobile crop for better phone composition."><div className="card store-settings-grid">
    <MarketplaceImageUpload label="Desktop hero image" value={form.restaurant_home_hero_image} onChange={v=>set('restaurant_home_hero_image',v)} folder="marketplace/restaurants/hero"/>
    <MarketplaceImageUpload label="Mobile hero image" value={form.restaurant_home_hero_mobile_image} onChange={v=>set('restaurant_home_hero_mobile_image',v)} folder="marketplace/restaurants/hero-mobile"/>
    <label><span>Hero overlay strength</span><input type="number" min="0" max="0.9" step="0.05" value={form.restaurant_home_hero_overlay} onChange={e=>set('restaurant_home_hero_overlay',e.target.value)}/></label>
    <label><span>Hero CTA label</span><input value={form.restaurant_home_hero_cta} onChange={e=>set('restaurant_home_hero_cta',e.target.value)}/></label>
    <label className="full"><span>Hero CTA URL</span><input value={form.restaurant_home_hero_cta_url} onChange={e=>set('restaurant_home_hero_cta_url',e.target.value)}/></label>
   </div></Section>
   <Section title="Restaurant Marketplace Home — Homepage Promotional Banners" meta="Global banners belong to Super Admin. Restaurant admins cannot edit these banners."><div className="card"><form className="store-settings-grid" onSubmit={addBanner}>
    <label><span>Banner title</span><input value={banner.title} onChange={e=>setBanner({...banner,title:e.target.value})} placeholder="Weekend Food Festival"/></label><label><span>Subtitle</span><input value={banner.subtitle} onChange={e=>setBanner({...banner,subtitle:e.target.value})}/></label>
    <MarketplaceImageUpload label="Desktop banner image" value={banner.image_url} onChange={v=>setBanner({...banner,image_url:v})} folder="marketplace/restaurants/banners"/>
    <MarketplaceImageUpload label="Mobile banner image" value={banner.mobile_image_url} onChange={v=>setBanner({...banner,mobile_image_url:v})} folder="marketplace/restaurants/banners-mobile"/><label><span>CTA label</span><input value={banner.cta_label} onChange={e=>setBanner({...banner,cta_label:e.target.value})}/></label><label><span>CTA URL</span><input value={banner.cta_url} onChange={e=>setBanner({...banner,cta_url:e.target.value})}/></label><label><span>Display order</span><input type="number" value={banner.display_order} onChange={e=>setBanner({...banner,display_order:e.target.value})}/></label><div className="full"><button className="btn primary">Add Global Banner</button></div>
   </form><div className="banner-admin-list">{banners.map(b=><article key={b.id}><img src={b.image_url} alt=""/><div><b>{b.title}</b><p>{b.subtitle||'No subtitle'} · order {b.display_order}</p><small>{b.active?'LIVE':'DISABLED'}</small></div><div><button className="btn" onClick={()=>editBanner(b)}>Edit</button><button className="btn" onClick={()=>toggleBanner(b)}>{b.active?'Disable':'Enable'}</button><button className="btn" onClick={()=>deleteBanner(b.id)}>Delete</button></div></article>)}</div></div></Section>
  </>}
  {tab==='sections'&&<Section title="Homepage Section Layout" meta="Control the global ordering and density without changing Restaurant SaaS catalog data."><div className="card store-section-layout"><div className="layout-preview"><div className="lp-hero">HERO / SEARCH / CTA</div><div className="lp-row"><div>OFFERS</div><div>PROMOTIONS</div></div><div className="lp-restaurants">RESTAURANT DISCOVERY GRID</div><div className="lp-dishes">POPULAR DISHES</div></div><div className="store-settings-grid"><label><span>Restaurant grid</span><select value={form.restaurant_home_restaurant_columns} onChange={e=>set('restaurant_home_restaurant_columns',Number(e.target.value))}><option value="2">2 columns</option><option value="3">3 columns</option><option value="4">4 columns</option></select></label><label><span>Dish grid</span><select value={form.restaurant_home_dish_columns} onChange={e=>set('restaurant_home_dish_columns',Number(e.target.value))}><option value="3">3 columns</option><option value="4">4 columns</option><option value="5">5 columns</option></select></label><label><span>Banner grid</span><select value={form.restaurant_home_banner_columns} onChange={e=>set('restaurant_home_banner_columns',Number(e.target.value))}><option value="1">1 column</option><option value="2">2 columns</option><option value="3">3 columns</option></select></label><label><span>Card radius</span><input type="number" min="8" max="40" value={form.restaurant_home_card_radius} onChange={e=>set('restaurant_home_card_radius',Number(e.target.value))}/></label></div></div></Section>}
  {tab==='sections'&&<Section title="Marketplace Cuisine Categories" meta="These category icons appear in the global marketplace. Configure the presentation without changing Restaurant SaaS menu data."><div className="card"><div className="amp-admin-category-grid">{(Array.isArray(form.restaurant_home_categories)?form.restaurant_home_categories:[]).map((c,i)=><div key={i}><input value={c.icon||''} onChange={e=>{const a=[...(form.restaurant_home_categories||[])];a[i]={...a[i],icon:e.target.value};set('restaurant_home_categories',a)}}/><input value={c.name||''} onChange={e=>{const a=[...(form.restaurant_home_categories||[])];a[i]={...a[i],name:e.target.value};set('restaurant_home_categories',a)}}/><button type="button" className="btn" onClick={()=>{const a=[...(form.restaurant_home_categories||[])];a.splice(i,1);set('restaurant_home_categories',a)}}>Delete</button></div>)}</div><button className="btn" type="button" onClick={()=>set('restaurant_home_categories',[...(form.restaurant_home_categories||[]),{name:'New Category',icon:'🍽️'}])}>+ Add Category</button></div></Section>}
  {tab==='sections'&&<Section title="Restaurant-Specific Popular Dishes" meta="Super Admin can curate popular dishes for any published restaurant. Restaurant Admin can curate the same section from Store Builder."><div className="card"><RestaurantFeaturedManager store={store} /></div></Section>}
  {tab==='business'&&<Section title="Marketplace Business Rules" meta="Global policy only. Individual restaurant content remains inside its own Business Admin store builder."><form className="card store-settings-grid" onSubmit={save}><label className="check-field"><input type="checkbox" checked={!!form.marketplace_enabled} onChange={e=>set('marketplace_enabled',e.target.checked)}/><span>Restaurant Marketplace enabled</span></label><label className="check-field"><input type="checkbox" checked={!!form.require_listing_approval} onChange={e=>set('require_listing_approval',e.target.checked)}/><span>Require listing approval</span></label><label><span>Default commission %</span><input type="number" min="0" max="100" step="0.01" value={form.default_commission_percent} onChange={e=>set('default_commission_percent',Number(e.target.value))}/></label><label className="check-field"><input type="checkbox" checked={!!form.featured_listings_enabled} onChange={e=>set('featured_listings_enabled',e.target.checked)}/><span>Featured listings enabled</span></label><label className="check-field"><input type="checkbox" checked={!!form.settlements_enabled} onChange={e=>set('settlements_enabled',e.target.checked)}/><span>Marketplace settlements enabled</span></label><label><span>Marketplace payment mode</span><select value={form.marketplace_payment_mode} onChange={e=>set('marketplace_payment_mode',e.target.value)}><option value="platform">Platform</option><option value="direct">Direct to business</option><option value="hybrid">Hybrid</option></select></label></form></Section>}
  {tab==='sections'&&<Section title="Food Icon Boxes & Marketplace Highlights" meta="These icon boxes appear across the Restaurant Marketplace. Configure them once from Super Admin."><div className="card"><div className="amp-admin-icon-grid">{(Array.isArray(form.restaurant_home_feature_icons)?form.restaurant_home_feature_icons:JSON.parse(form.restaurant_home_feature_icons||'[]')).map((f,i)=><div key={i} className="amp-admin-icon-card"><input value={f.icon||''} onChange={e=>{const a=[...(Array.isArray(form.restaurant_home_feature_icons)?form.restaurant_home_feature_icons:JSON.parse(form.restaurant_home_feature_icons||'[]'))];a[i]={...a[i],icon:e.target.value};set('restaurant_home_feature_icons',a)}} placeholder="🍽️"/><input value={f.title||''} onChange={e=>{const a=[...(Array.isArray(form.restaurant_home_feature_icons)?form.restaurant_home_feature_icons:JSON.parse(form.restaurant_home_feature_icons||'[]'))];a[i]={...a[i],title:e.target.value};set('restaurant_home_feature_icons',a)}} placeholder="Title"/><input value={f.text||''} onChange={e=>{const a=[...(Array.isArray(form.restaurant_home_feature_icons)?form.restaurant_home_feature_icons:JSON.parse(form.restaurant_home_feature_icons||'[]'))];a[i]={...a[i],text:e.target.value};set('restaurant_home_feature_icons',a)}} placeholder="Short text"/><button className="btn" type="button" onClick={()=>{const a=[...(Array.isArray(form.restaurant_home_feature_icons)?form.restaurant_home_feature_icons:JSON.parse(form.restaurant_home_feature_icons||'[]'))];a.splice(i,1);set('restaurant_home_feature_icons',a)}}>Remove</button></div>)}</div><button className="btn" type="button" onClick={()=>{const a=[...(Array.isArray(form.restaurant_home_feature_icons)?form.restaurant_home_feature_icons:JSON.parse(form.restaurant_home_feature_icons||'[]')),{icon:'✦',title:'New Feature',text:'Marketplace benefit'}];set('restaurant_home_feature_icons',a)}}>+ Add Icon Box</button><button className="btn primary" type="button" onClick={()=>save()}>Save Icon Boxes</button></div></Section>}
  {tab==='seo'&&<Section title="SEO, Footer & Discovery" meta="Global Restaurant Marketplace metadata controlled by Super Admin."><div className="card store-settings-grid"><label><span>SEO title</span><input value={form.restaurant_home_meta_title} onChange={e=>set('restaurant_home_meta_title',e.target.value)}/></label><label><span>Footer text</span><input value={form.restaurant_home_footer_text} onChange={e=>set('restaurant_home_footer_text',e.target.value)}/></label><label className="full"><span>SEO description</span><textarea value={form.restaurant_home_meta_description} onChange={e=>set('restaurant_home_meta_description',e.target.value)} rows={4}/></label></div></Section>}
  <div className="store-control-footer"><b>Ownership boundary:</b> Super Admin owns the global Restaurant Marketplace store. Business Admin owns only their own restaurant/hotel store. Restaurant SaaS remains the operational catalog and order source of truth. <Link href="/store" target="_blank">Preview global store ↗</Link></div>
 <style jsx global>{`.amp-store-experience{display:grid;gap:16px}.experience-toolbar{display:flex;justify-content:space-between;align-items:center;padding:14px 0}.sb-feature-editor{display:grid;gap:10px}.sb-feature-rich{display:grid;grid-template-columns:45px 1fr 1.2fr 150px 1fr auto;gap:8px;align-items:center}.sb-feature-rich input,.sb-feature-rich select,.content-card input,.content-card textarea{width:100%;border:1px solid #ddd6c8;border-radius:10px;padding:10px;background:#fff}.sb-content-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:12px 0}.content-card{border:1px solid #e7dfd2;border-radius:14px;padding:12px;background:#fff;display:grid;gap:8px}.gallery-add-row{margin-top:12px}@media(max-width:1000px){.sb-feature-rich{grid-template-columns:45px 1fr}.sb-feature-rich select,.sb-feature-rich input:nth-of-type(2),.sb-feature-rich input:nth-of-type(3),.sb-feature-rich button{grid-column:1/-1}.sb-content-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.sb-content-grid{grid-template-columns:1fr}.experience-toolbar{display:grid;gap:10px}}`}</style></AppShell>
}
