'use client';
import {useEffect,useState} from 'react';
import {supabase} from '../../../lib/supabase';
import MarketplaceImageUpload from '../MarketplaceImageUpload';

const defaults={
 categories:[{name:'North Indian',icon:'🍛'},{name:'Chinese',icon:'🥡'},{name:'Fast Food',icon:'🍔'},{name:'Tandoori',icon:'🔥'},{name:'Pizza',icon:'🍕'},{name:'Burgers',icon:'🍔'},{name:'Momos',icon:'🥟'},{name:'Thali',icon:'🍱'},{name:'Beverages',icon:'☕'},{name:'Desserts',icon:'🍰'}],
 why:[{icon:'🍽️',title:'Multiple Restaurants',text:'Choose from the best local restaurants'},{icon:'🥬',title:'Fresh & Hygienic Food',text:'Quality food, prepared with care'},{icon:'🚴',title:'Fast Delivery',text:'Hot & fresh food at your doorstep'},{icon:'💳',title:'Secure Payments',text:'Multiple safe payment options'},{icon:'🎁',title:'Exclusive Offers',text:'Best deals and discounts'},{icon:'📞',title:'24/7 Support',text:'We are always here to help'}],
 how:[{icon:'📍',title:'Choose Location',text:'Select your delivery address'},{icon:'🍽️',title:'Find a Restaurant',text:'Explore multiple restaurants near you'},{icon:'🛍️',title:'Place Your Order',text:'Add items & make payment'},{icon:'🛵',title:'Get It Delivered',text:'Enjoy your delicious food'}],
 promotions:[{eyebrow:'SPECIAL OFFER',title:'Get 10% OFF',text:'On your first order',badge:'Use Code: FIRST10',cta:'Order Now',url:'#restaurants',image_url:''},{eyebrow:'SPECIAL OFFER',title:'Special Thali Meals',text:'Starting at ₹120',badge:'Traditional Taste of Himachal',cta:'View Menu',url:'#dishes',image_url:''}],
 app:{eyebrow:'ORDER ON THE GO',title:'Download Our App',text:'Get the best food delivery experience with our mobile app.',image_url:'',points:[{icon:'🎁',text:'Exclusive App Offers'},{icon:'⚡',text:'Faster Ordering'},{icon:'📍',text:'Live Order Tracking'},{icon:'↻',text:'Easy Reordering'}]},
 landscape:{eyebrow:'TASTE THE FLAVOURS',title:'Flavours of Himachal',text:'From local favourites to global cuisines, explore a world of flavours at one place.',image_url:'',cta:'Explore Restaurants',url:'#restaurants'},
 reviews:[{name:'Rohit Sharma',avatar:'👨🏻',rating:5,text:'Amazing food quality and super fast delivery. Best food experience in Manali!'},{name:'Priya Verma',avatar:'👩🏻',rating:5,text:'Loved the variety of restaurants and local Himachali cuisine.'},{name:'Amit Negi',avatar:'👨🏻',rating:5,text:'Fresh food, great taste and friendly support. Makes food ordering so easy!'}],
 footer:{brand:'ANAIRA',subtitle:'FOOD MARKETPLACE',text:'Bringing the best restaurants, local flavours and delicious food to your doorstep.',copyright:'© 2026 Anaira Food Marketplace. All Rights Reserved.',made:'Made with ♥ in Himachal'}
};
const keys={categories:'restaurant_home_categories',why:'restaurant_home_why_choose',how:'restaurant_home_how_it_works',promotions:'restaurant_home_promotions',app:'restaurant_home_app_promo',landscape:'restaurant_home_landscape',reviews:'restaurant_home_reviews',footer:'restaurant_home_footer'};
const clone=o=>JSON.parse(JSON.stringify(o));
export default function ReferenceStoreContentManager(){
 const [data,setData]=useState(clone(defaults)),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[error,setError]=useState('');
 useEffect(()=>{(async()=>{const {data:rows,error:e}=await supabase.from('anaira_platform_settings').select('key,value').in('key',Object.values(keys));if(e){setError(e.message);setLoading(false);return}const next=clone(defaults);(rows||[]).forEach(r=>{const v=r.value?.value??r.value;const k=Object.keys(keys).find(x=>keys[x]===r.key);if(k&&v!==undefined)next[k]=v});setData(next);setLoading(false)})()},[]);
 const set=(k,v)=>setData(d=>({...d,[k]:v}));
 const update=(k,i,p)=>set(k,data[k].map((x,n)=>n===i?{...x,...p}:x));
 const add=(k,item)=>set(k,[...(data[k]||[]),item]);
 const remove=(k,i)=>set(k,data[k].filter((_,n)=>n!==i));
 async function save(){setSaving(true);setMsg('');setError('');const user=(await supabase.auth.getUser()).data.user?.id;for(const [k,key] of Object.entries(keys)){const {error:e}=await supabase.from('anaira_platform_settings').upsert({key,value:{value:data[k]},updated_by:user},{onConflict:'key'});if(e){setError(e.message);setSaving(false);return}}setMsg('Reference Store content saved.');setSaving(false)}
 if(loading)return <div className="card">Loading Reference Store content…</div>;
 return <div className="reference-store-manager">
  <div className="experience-toolbar"><div><b>Reference Store — Complete Content Control</b><p className="muted">This controls the public <code>/store</code> layout. Restaurant <code>/store/[id]</code> is intentionally not changed here.</p></div><button className="btn primary" onClick={save} disabled={saving}>{saving?'Saving…':'Save Reference Store'}</button></div>
  <Section title="Food Category Strip" desc="Same 10-icon strip shown below the hero. Add, edit or delete." ><div className="ref-grid">{data.categories.map((x,i)=><div className="ref-card" key={i}><input value={x.icon||''} onChange={e=>update('categories',i,{icon:e.target.value})}/><input value={x.name||''} onChange={e=>update('categories',i,{name:e.target.value})}/><button className="btn danger" onClick={()=>remove('categories',i)}>Delete</button></div>)}</div><button className="btn" onClick={()=>add('categories',{name:'New Category',icon:'🍽️'})}>+ Add Category</button></Section>
  <Section title="Why Choose Us" desc="Six premium icon buttons. Each can be edited here; the public Store renders them as clickable feature buttons."><div className="ref-grid">{data.why.map((x,i)=><div className="ref-card wide" key={i}><input value={x.icon||''} onChange={e=>update('why',i,{icon:e.target.value})}/><input value={x.title||''} onChange={e=>update('why',i,{title:e.target.value})}/><input value={x.text||''} onChange={e=>update('why',i,{text:e.target.value})}/><button className="btn danger" onClick={()=>remove('why',i)}>Delete</button></div>)}</div><button className="btn" onClick={()=>add('why',{icon:'✦',title:'New Benefit',text:'Marketplace benefit'})}>+ Add Benefit</button></Section>
  <Section title="How It Works" desc="Four steps exactly like the reference Store page."><div className="ref-grid">{data.how.map((x,i)=><div className="ref-card wide" key={i}><input value={x.icon||''} onChange={e=>update('how',i,{icon:e.target.value})}/><input value={x.title||''} onChange={e=>update('how',i,{title:e.target.value})}/><input value={x.text||''} onChange={e=>update('how',i,{text:e.target.value})}/><button className="btn danger" onClick={()=>remove('how',i)}>Delete</button></div>)}</div><button className="btn" onClick={()=>add('how',{icon:'✦',title:'New Step',text:'Step description'})}>+ Add Step</button></Section>
  <Section title="Promotional Cards" desc="The two cards between Top Rated Restaurants and Popular Dishes. Upload images, edit text, CTA and delete/add cards."><div className="ref-promo-grid">{data.promotions.map((x,i)=><div className="ref-card promo" key={i}><MarketplaceImageUpload label="Promotion image" value={x.image_url||''} onChange={v=>update('promotions',i,{image_url:v})} folder="marketplace/store/promotions"/><input value={x.eyebrow||''} onChange={e=>update('promotions',i,{eyebrow:e.target.value})} placeholder="Eyebrow"/><input value={x.title||''} onChange={e=>update('promotions',i,{title:e.target.value})} placeholder="Title"/><input value={x.text||''} onChange={e=>update('promotions',i,{text:e.target.value})} placeholder="Text"/><input value={x.badge||''} onChange={e=>update('promotions',i,{badge:e.target.value})} placeholder="Badge"/><input value={x.cta||''} onChange={e=>update('promotions',i,{cta:e.target.value})} placeholder="CTA"/><input value={x.url||''} onChange={e=>update('promotions',i,{url:e.target.value})} placeholder="CTA URL"/><button className="btn danger" onClick={()=>remove('promotions',i)}>Delete</button></div>)}</div><button className="btn" onClick={()=>add('promotions',{eyebrow:'SPECIAL OFFER',title:'New Offer',text:'Offer description',badge:'Special offer',cta:'Order Now',url:'#restaurants',image_url:''})}>+ Add Promotion</button></Section>
  <Section title="Himachal Landscape Banner" desc="The full-width image section after Why Choose Us."><div className="ref-form"><input value={data.landscape.eyebrow||''} onChange={e=>set('landscape',{...data.landscape,eyebrow:e.target.value})} placeholder="Eyebrow"/><input value={data.landscape.title||''} onChange={e=>set('landscape',{...data.landscape,title:e.target.value})} placeholder="Title"/><input value={data.landscape.text||''} onChange={e=>set('landscape',{...data.landscape,text:e.target.value})} placeholder="Text"/><input value={data.landscape.cta||''} onChange={e=>set('landscape',{...data.landscape,cta:e.target.value})} placeholder="CTA"/><input value={data.landscape.url||''} onChange={e=>set('landscape',{...data.landscape,url:e.target.value})} placeholder="CTA URL"/><MarketplaceImageUpload label="Landscape image" value={data.landscape.image_url||''} onChange={v=>set('landscape',{...data.landscape,image_url:v})} folder="marketplace/store/landscape"/></div></Section>
  <Section title="App Promotion" desc="The red app section with phone visual and four feature points."><div className="ref-form"><input value={data.app.eyebrow||''} onChange={e=>set('app',{...data.app,eyebrow:e.target.value})}/><input value={data.app.title||''} onChange={e=>set('app',{...data.app,title:e.target.value})}/><input value={data.app.text||''} onChange={e=>set('app',{...data.app,text:e.target.value})}/><MarketplaceImageUpload label="App background / visual" value={data.app.image_url||''} onChange={v=>set('app',{...data.app,image_url:v})} folder="marketplace/store/app"/></div><div className="ref-grid">{(data.app.points||[]).map((x,i)=><div className="ref-card wide" key={i}><input value={x.icon||''} onChange={e=>set('app',{...data.app,points:data.app.points.map((p,n)=>n===i?{...p,icon:e.target.value}:p)})}/><input value={x.text||''} onChange={e=>set('app',{...data.app,points:data.app.points.map((p,n)=>n===i?{...p,text:e.target.value}:p)})}/><button className="btn danger" onClick={()=>set('app',{...data.app,points:data.app.points.filter((_,n)=>n!==i)})}>Delete</button></div>)}</div><button className="btn" onClick={()=>set('app',{...data.app,points:[...(data.app.points||[]),{icon:'✦',text:'New App Benefit'}]})}>+ Add App Point</button></Section>
  <Section title="Customer Reviews" desc="Reference Store review cards. Add/edit/delete here."><div className="ref-grid">{data.reviews.map((x,i)=><div className="ref-card wide" key={i}><input value={x.avatar||''} onChange={e=>update('reviews',i,{avatar:e.target.value})}/><input value={x.name||''} onChange={e=>update('reviews',i,{name:e.target.value})}/><input type="number" min="1" max="5" value={x.rating||5} onChange={e=>update('reviews',i,{rating:Number(e.target.value)})}/><textarea value={x.text||''} onChange={e=>update('reviews',i,{text:e.target.value})}/><button className="btn danger" onClick={()=>remove('reviews',i)}>Delete</button></div>)}</div><button className="btn" onClick={()=>add('reviews',{name:'Guest',avatar:'👤',rating:5,text:'Amazing food and service.'})}>+ Add Review</button></Section>
  <Section title="Footer Content" desc="Footer brand, text, copyright and Made in Himachal line."><div className="ref-form"><input value={data.footer.brand||''} onChange={e=>set('footer',{...data.footer,brand:e.target.value})}/><input value={data.footer.subtitle||''} onChange={e=>set('footer',{...data.footer,subtitle:e.target.value})}/><textarea value={data.footer.text||''} onChange={e=>set('footer',{...data.footer,text:e.target.value})}/><input value={data.footer.copyright||''} onChange={e=>set('footer',{...data.footer,copyright:e.target.value})}/><input value={data.footer.made||''} onChange={e=>set('footer',{...data.footer,made:e.target.value})}/></div></Section>
  {msg&&<div className="notice success">{msg}</div>}{error&&<div className="notice error">{error}</div>}
  <style jsx global>{`.reference-store-manager{display:grid;gap:16px}.ref-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin:12px 0}.ref-card{display:grid;grid-template-columns:60px 1fr auto;gap:8px;align-items:center;border:1px solid #e7dfd2;border-radius:12px;padding:10px;background:#fff}.ref-card.wide{grid-template-columns:60px 1fr 1.5fr auto}.ref-card.promo{grid-template-columns:1fr}.ref-card input,.ref-card textarea,.ref-form input,.ref-form textarea{width:100%;border:1px solid #ddd6c8;border-radius:9px;padding:10px;background:#fff}.ref-form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ref-form textarea{min-height:90px}.ref-form>*:last-child{grid-column:1/-1}.muted{color:#777;font-size:12px;margin:4px 0}.ref-promo-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}@media(max-width:800px){.ref-grid,.ref-promo-grid,.ref-form{grid-template-columns:1fr}.ref-card,.ref-card.wide{grid-template-columns:1fr}}`}</style>
 </div>;
}
function Section({title,desc,children}){return <section className="card"><h3 style={{margin:'0 0 5px'}}>{title}</h3><p className="muted">{desc}</p>{children}</section>}
