'use client';
import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import {AppShell,Header,Section,Table,Pill} from '../../../components';
import {supabase} from '../../../../lib/supabase';
const META={hotel:['Hotel','Hotel'],camp:['Camping','Camp / Tent'],homestay:['Homestay','Accommodation'],guest_house:['Guest House','Accommodation'],cottage:['Cottage','Cottage']};
const isHotel=t=>t==='hotel_resort'||t==='hotel_restaurant';
const isRestaurant=t=>t==='restaurant_cafe'||t==='hotel_restaurant';
const BUSINESS_LABEL={hotel_resort:'🏨 Hotel / Resort',hotel_restaurant:'🏨🍽️ Hotel + Restaurant',restaurant_cafe:'🍽️ Restaurant / Cafe',salon:'💇 Salon',barber_shop:'💈 Barber Shop',spa_wellness:'💆 Spa',clinic_hospital:'🏥 Clinic / Hospital',dentist_doctor:'🦷 Dentist / Doctor',pharmacy:'💊 Pharmacy',gym_yoga:'🏋️ Gym / Yoga',retail_grocery:'🛍️ Retail / Grocery',fashion:'👗 Fashion',jewellery:'💎 Jewellery',electronics_mobile:'📱 Electronics / Mobile',automotive:'🚗 Automotive',real_estate:'🏠 Real Estate',travel:'✈️ Travel',education_coaching:'🎓 Education / Coaching',legal:'⚖️ Legal',ca_accounting_tax:'📊 CA / Accounting / Tax',it_agency:'💻 IT / Agency',repair_maintenance:'🔧 Repair / Maintenance',cleaning:'🧹 Cleaning',veterinary:'🐕 Veterinary',photography:'📸 Photography',events:'🎉 Events',coworking:'🏢 Coworking',logistics:'🚚 Logistics',construction_home_services:'🏗️ Construction / Home Services',ecommerce:'🛒 E-commerce',saas_subscription:'☁️ SaaS / Subscription',creator_personal_brand:'👤 Creator / Personal Brand',non_profit:'🤝 Non-profit',other:'• Other'};
export default function PropertyManage(){
 const {id}=useParams(); const [r,setR]=useState(null),[plugins,setPlugins]=useState([]),[error,setError]=useState('');
 useEffect(()=>{if(!id)return;(async()=>{const [a,b]=await Promise.all([supabase.from('restaurants').select('*').eq('id',id).maybeSingle(),supabase.from('restaurant_plugins').select('plugin_code,enabled,updated_at').eq('restaurant_id',id)]);if(a.error||b.error)setError(a.error?.message||b.error?.message);setR(a.data);setPlugins(b.data||[])})()},[id]);
 if(error)return <AppShell><div className="notice error">{error}</div></AppShell>; if(!r)return <AppShell><div className="notice">Loading business…</div></AppShell>;
 const bt=r.business_type||''; const hospitalityLabel=META[r.hospitality_type]?.[0]||null; const businessLabel=BUSINESS_LABEL[bt]||bt||'Business type not selected'; const showHotel=isHotel(bt); const restaurantPluginEnabled=plugins.some(x=>x.enabled && ['restaurant-management','restaurant-core','restaurant-store'].includes(x.plugin_code)); const showRestaurant=isRestaurant(bt)&&restaurantPluginEnabled; const q=`?property=${id}`;
 return <AppShell active="/properties"><Header eyebrow="BUSINESS / TENANT MANAGEMENT" title={r.name||'Business'} subtitle={`${businessLabel}${hospitalityLabel?` · ${hospitalityLabel}`:''}`} actions={<><a className="btn primary" href={'/properties?edit='+id}>Edit Business</a><a className="btn" href="/properties">Back to Properties</a></>}/>
 <Section title="Business Master" meta="Universal tenant identity"><div className="mini-grid">{[['Business Type',businessLabel],['Hospitality Type',showHotel?(hospitalityLabel||'Not selected'):'Not applicable'],['Legal Name',r.legal_name],['Phone',r.phone],['Email',r.email],['Address',r.address],['Location',[r.city,r.state,r.postal_code].filter(Boolean).join(', ')],['Status',r.status]].map(([k,v])=><div className="mini" key={k}><span className="kpi-label">{k}</span><b>{v||'—'}</b></div>)}</div></Section>
 {showHotel&&<Section title={`${hospitalityLabel||'Hotel'} Management Setup`} meta="Enabled because Business Type is Hotel / Resort or Hotel + Restaurant"><div className="module-grid"><a className="module-card" href={`/hotel-management/setup${q}`}><h3>{hospitalityLabel||'Hotel'} Profile</h3><p>Property identity, policies, tax, timings, media and marketplace settings.</p></a><a className="module-card" href={`/hotel-management/room-types${q}`}><h3>{hospitalityLabel==='Camping'?'Camp / Tent':'Room'} Types</h3><p>Create sellable accommodation categories, capacity, images and amenities.</p></a><a className="module-card" href={`/hotel-management/rooms${q}`}><h3>{hospitalityLabel==='Camping'?'Camp / Tent Units':'Rooms'}</h3><p>Create physical sellable units and live inventory.</p></a><a className="module-card" href={`/hotel-management/rates${q}`}><h3>Rate Plans</h3><p>Per-unit or per-person pricing, seasonal and stay rules.</p></a><a className="module-card" href={`/hotel-management/inventory${q}`}><h3>Auto Inventory</h3><p>Date-wise inventory generated from units and reservations.</p></a><a className="module-card" href={`/booking${q}`}><h3>Reservations</h3><p>Reservation, payment, confirmation and operational lifecycle.</p></a></div></Section>}
 {showRestaurant&&<Section title="Restaurant Management Setup" meta="Enabled because a Restaurant module plugin is active"><div className="module-grid"><a className="module-card" href={`/restaurant-setup?property=${id}`}><h3>Restaurant Setup</h3><p>Restaurant identity, timings, taxes, service modes and marketplace settings.</p></a><a className="module-card" href={`/pos?property=${id}`}><h3>POS</h3><p>Orders, billing, tables and restaurant operations.</p></a><a className="module-card" href={`/menu?property=${id}`}><h3>Menu</h3><p>Categories, items, modifiers and pricing.</p></a><a className="module-card" href={`/restaurant-reservations?property=${id}`}><h3>Reservations</h3><p>Table reservations and guest lifecycle.</p></a></div></Section>}
 {!showHotel&&!showRestaurant&&<Section title={`${businessLabel} Workspace`} meta="Dedicated business engine"><div className="notice">This tenant is configured as <b>{businessLabel}</b>. Hotel and Restaurant engines are hidden. Its dedicated landing page and setup are available below.</div><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:12}}><a className="btn primary" href={`/business/${bt}`}>Open {businessLabel.replace(/^[^ ]+ /,'')} Landing →</a><a className="btn" href={`/business/${bt}/setup`}>Open {businessLabel.replace(/^[^ ]+ /,'')} Setup →</a><a className="btn" href="/plugins">Plugin Control Center →</a></div></Section>}
 <Section title="Activated Plugins" meta={`${plugins.filter(x=>x.enabled).length} active`}><Table columns={['Plugin','Status','Updated']} rows={plugins.map(x=>[x.plugin_code,<Pill tone={x.enabled?'success':'muted'}>{x.enabled?'Active':'Disabled'}</Pill>,x.updated_at||'—'])}/></Section>
 </AppShell>;
}
