'use client';
import {useEffect,useMemo,useState} from 'react';
import {AppShell,Header,Section,Table,Pill,Kpi,Progress} from './components';
import {supabase} from '../lib/supabase';

const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const fmt=v=>v?new Date(v).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—';
const MODULES={
 crm:{title:'CRM Master',eyebrow:'CRM MASTER',table:'crm_customers',subtitle:'Canonical customer master with value, lifecycle, service, loyalty and relationship controls.',fields:['full_name','customer_type','phone','email','vip'],actions:['Refresh Value','Open Customer 360','Find Duplicates','Export Data']},
 identity:{title:'Identity Resolution',eyebrow:'CUSTOMER 360',table:'crm_customer_identity_links',subtitle:'Duplicate detection, evidence comparison and transaction-safe canonical customer merge.',fields:['source_type','source_id','match_key','confidence','verified'],actions:['Find Duplicates','Merge Selected']},
 leads:{title:'Leads & Sales',eyebrow:'SALES CRM',table:'crm_leads',subtitle:'Lead inbox, qualification, assignment, follow-up and conversion into measurable revenue.',fields:['lead_type','source','stage','estimated_value','next_follow_up','notes'],actions:['Qualify','Convert','Follow-up','Mark Lost']},
 pipeline:{title:'Sales Pipeline',eyebrow:'SALES CRM',table:'crm_opportunities',subtitle:'Opportunity pipeline with value, probability, owner, expected close and stage history.',fields:['name','value','probability','expected_close_at','source','status','notes'],actions:['Open','Move Stage','Mark Won','Mark Lost']},
 corporate:{title:'Corporate CRM',eyebrow:'B2B CRM',table:'crm_corporate_accounts',subtitle:'Corporate accounts, contacts, negotiated rates, credit, contracts, bookings, invoicing, revenue and renewal control.',fields:['company_name','contact_name','phone','email','payment_terms','credit_limit','credit_used','account_manager_id','contract_expiry','negotiated_rates','notes','active'],actions:['Create Contract','Approve Contract','Renew Contract','Record Credit','Create Rate Agreement','Create Booking','Create Invoice','Generate Statement','Record Revenue','View Ledger','View Contacts','Add Contact','Assign Account Manager','Renewal Review','Open Account','Open Corporate Portal']},
 partners:{title:'Partners & Agents',eyebrow:'PARTNER CRM',table:'crm_partners',subtitle:'Partner onboarding, KYC, contracts, commission rules, attributed bookings, settlements, payouts, statements and reconciliation.',fields:['partner_type','name','contact_name','phone','email','commission_percent','kyc_status','contract_status','contract_expiry','account_manager_id','active'],actions:['Onboard','Create Contract','Approve Contract','Renew Contract','Calculate Commission','Create Booking','Create Settlement','Approve Settlement','Payout Settlement','Generate Statement','Reconcile Settlement','Open Partner Portal']},
 quotes:{title:'Quotes',eyebrow:'SALES CRM',table:'crm_quotes',subtitle:'Quote builder and lifecycle from draft through approval, acceptance and booking conversion.',fields:['quote_number','lead_id','status','subtotal','discount','tax','total','valid_until'],actions:['Approve','Accept','Reject','Convert to Booking']},
 partnerBookings:{title:'Partner Bookings',eyebrow:'PARTNER CRM',table:'crm_partner_bookings',subtitle:'Partner-sourced booking lifecycle with commission and settlement controls.',fields:['booking_reference','partner_id','customer_id','booking_amount','commission_amount','status'],actions:['Complete','Cancel','Prepare Settlement']},
 guestRelations:{title:'Guest Relations & Service Recovery',eyebrow:'SERVICE RECOVERY',table:'crm_complaints',subtitle:'Complaint, guest request and recovery queue with SLA, ownership, resolution and audit.',fields:['title','priority','status','root_cause','assigned_to','compensation_amount','resolution'],actions:['Assign','Start SLA','Escalate','Resolve','Create Recovery']},serviceRecovery:{title:'Service Recovery',eyebrow:'SERVICE RECOVERY',table:'crm_service_recovery_cases',subtitle:'Compensation and recovery lifecycle linked to complaints and guests with approval, outcome and audit.',fields:['complaint_id','customer_id','status','recovery_type','compensation_amount','approved_by','outcome','notes'],actions:['Approve Recovery','Complete Recovery','Cancel Recovery','Create Timeline']},
 loyalty:{title:'Loyalty & Rewards',eyebrow:'LOYALTY ENGINE',table:'crm_loyalty_accounts',subtitle:'Canonical loyalty ledger, earn, redeem, reverse, tier and reward controls.',fields:['customer_id','tier','points_balance','lifetime_points'],actions:['Issue Points','Redeem Reward','Reverse Transaction','Refresh Tier']},
 segments:{title:'Segments',eyebrow:'CUSTOMER INTELLIGENCE',table:'crm_segments',subtitle:'Dynamic customer audiences with rule preview, recalculation, scheduling and history.',fields:['name','active','definition'],actions:['Preview Audience','Recalculate','Activate','Deactivate']},
 offers:{title:'Offers & Coupons',eyebrow:'GROWTH ENGINE',table:'crm_coupon_definitions',subtitle:'Eligibility, limits, date windows, redemption and cancellation-safe coupon management.',fields:['code','name','discount_type','discount_value','max_redemptions','per_customer_limit','starts_at','ends_at','active'],actions:['Validate Coupon','Deactivate','View Redemptions']},
 campaigns:{title:'Campaign Studio',eyebrow:'MARKETING AUTOMATION',table:'crm_campaigns',subtitle:'Audience, channel, template, scheduling, delivery, engagement, conversion and revenue attribution.',fields:['name','channel','segment_id','status','scheduled_at','offer_code'],actions:['Run Audience','Launch','Pause','View Attribution']},
 whatsapp:{title:'WhatsApp CRM',eyebrow:'OMNICHANNEL CRM',table:'crm_message_log',subtitle:'Conversation log, templates, delivery states, retry queue, consent and provider health.',fields:['customer_id','channel','direction','provider_message_id','status','sent_at'],actions:['Open Conversation','Send WhatsApp','Retry Failed','Mark Read','Create Template','Opt Out']},
 workflows:{title:'Workflow Automation',eyebrow:'AUTOMATION ENGINE',table:'crm_workflows',subtitle:'Trigger → conditions → branch → action → delay → goal workflow builder with runs and retry/DLQ.',fields:['name','trigger_type','active','definition'],actions:['Start Workflow','Clone','Activate','Deactivate']},
 analytics:{title:'CRM Analytics',eyebrow:'BUSINESS INTELLIGENCE',table:'crm_analytics_daily',subtitle:'Customer, revenue, retention, marketing, service, loyalty and sales reporting from live CRM data.',fields:['metric_date','new_customers','active_customers','repeat_customers','hotel_revenue','restaurant_revenue','total_revenue','complaints','campaign_conversions'],actions:['Refresh Metrics','Export Report']},
 advancedAnalytics:{title:'Advanced Analytics',eyebrow:'ADVANCED INTELLIGENCE',table:'crm_analytics_daily',subtitle:'RFM, cohorts, retention, LTV, funnels, attribution, campaign ROI and property comparison.',fields:['metric_date','new_customers','active_customers','repeat_customers','total_revenue','campaign_conversions'],actions:['Refresh Metrics','Compare Periods','Open Cohorts','Export Report']},
 relationship:{title:'Relationship Manager',eyebrow:'RELATIONSHIP MANAGEMENT',table:'crm_relationship_assignments',subtitle:'Customer portfolios, owner assignment, workload, capacity, reassignment, SLA and performance.',fields:['customer_id','staff_id','assigned_at','active'],actions:['Assign Owner','Reassign','Rebalance Workload','Escalate SLA']},
 ai:{title:'AI CRM',eyebrow:'AI DECISION INTELLIGENCE',table:'crm_ai_insights',subtitle:'Explainable customer summaries, next-best-actions, churn, upsell and retention recommendations with human approval.',fields:['customer_id','insight_type','summary','recommendation','confidence','model_name','model_version'],actions:['Generate Summary','Next Best Action','Run Insight','Approve Action']},
 revenue:{title:'Revenue Management',eyebrow:'REVENUE INTELLIGENCE',table:'crm_revenue_forecasts',subtitle:'Occupancy, booking pace, ADR, RevPAR, seasonality, demand and competitor-informed rate recommendations.',fields:['forecast_date','occupancy_forecast','adr_forecast','revpar_forecast','demand_index','confidence','model_version'],actions:['Generate Recommendation','Approve Rate','Override Rate','Publish Rate']},
 forecasting:{title:'Revenue Forecasting',eyebrow:'REVENUE FORECASTING',table:'crm_revenue_forecasts',subtitle:'Forecast occupancy, ADR, RevPAR, revenue and booking pace with actual-vs-forecast accuracy.',fields:['forecast_date','occupancy_forecast','adr_forecast','revpar_forecast','demand_index','confidence','model_version'],actions:['Generate Forecast','Refresh Forecast','Compare Accuracy','Approve Forecast']},
 competitors:{title:'Competitor Intelligence',eyebrow:'COMPETITOR INTELLIGENCE',table:'crm_competitor_rates',subtitle:'Configured provider collection, normalization, parity, history and rate-position alerts.',fields:['competitor_name','stay_date','room_type_label','rate','currency'],actions:['Collect Rates','Normalize Rates','Run Parity','Create Alert']},
 timeline:{title:'Timeline / Interactions',eyebrow:'OMNICHANNEL TIMELINE',table:'crm_timeline_events',subtitle:'Unified chronological customer journey across booking, PMS, POS, restaurant, messaging, service, loyalty and AI.',fields:['customer_id','event_type','source_system','title','occurred_at','amount'],actions:['Rebuild Timeline','Filter Source']},
 consent:{title:'Consent & Privacy',eyebrow:'PRIVACY & GOVERNANCE',table:'crm_consents',subtitle:'Channel consent, opt-in/out, data export, deletion requests and audit controls.',fields:['customer_id','channel','status','source','policy_version','consented_at'],actions:['Grant Consent','Withdraw Consent','Export Data','Delete Request']},
 service:{title:'Service Tickets',eyebrow:'SERVICE CRM',table:'crm_service_tickets',subtitle:'Unified service queue with priority, assignment, SLA, resolution and CSAT.',fields:['customer_id','subject','channel','priority','status','assigned_to','sla_due_at','csat','resolution'],actions:['Assign','Start SLA','Escalate','Resolve']},
 restaurant:{title:'Restaurant CRM',eyebrow:'RESTAURANT CRM',table:'crm_restaurant_visits',subtitle:'Restaurant visits, spending, reservations, preferences, complaints, offers and loyalty linked to canonical customers.',fields:['customer_id','visit_at','table_number','guest_count','amount','payment_method'],actions:['Refresh Visit Metrics','Refresh Preferences','Open Customer 360']},
 events:{title:'Events & Upselling',eyebrow:'EVENT CRM',table:'crm_events',subtitle:'Event lead, proposal, quote, deposit, attendees, follow-up, upsell and revenue lifecycle.',fields:['name','event_type','venue','event_date','expected_guests','stage','estimated_value','owner_id','notes'],actions:['Create Quote','Approve Proposal','Schedule Follow-up','Record Deposit']},
 vip:{title:'VIP Management',eyebrow:'VIP MANAGEMENT',table:'crm_customers',subtitle:'Automatic VIP qualification, benefits, manager assignment, priority service and property-scoped history.',fields:['full_name','customer_type','total_hotel_revenue','total_stays','vip'],actions:['Qualify VIP','Assign Manager','Add Amenity','Open Customer 360']},
 churn:{title:'Churn & Retention',eyebrow:'RETENTION INTELLIGENCE',table:'crm_churn_scores',subtitle:'Customer churn risk, factors, recommended retention actions and outcome attribution.',fields:['customer_id','score','risk_level','factors','calculated_at'],actions:['Recompute Churn','View Factors','Create Retention Action']},
 upselling:{title:'Upselling',eyebrow:'REVENUE GROWTH',table:'crm_upsell_events',subtitle:'Eligible guest offers, acceptance, fulfilment, payment and revenue attribution.',fields:['customer_id','offer_id','status','amount','created_at'],actions:['Find Eligible Guests','Create Offer','Send Offer','Record Acceptance','Record Payment','Fulfil Offer','Cancel Offer']},
 crossSelling:{title:'Cross-selling',eyebrow:'REVENUE GROWTH',table:'crm_hotel_cross_sell_opportunities',subtitle:'Restaurant, activities, transport and hotel service cross-sell opportunities with fulfilment attribution.',fields:['customer_id','property_id','status','offer_id','created_at'],actions:['Preview Matches','Generate Offers','Create Offer','Send Offers','Record Payment','Fulfil Offer','View Attribution']},
 reputation:{title:'Reputation',eyebrow:'REPUTATION MANAGEMENT',table:'crm_reviews',subtitle:'Review inbox, sentiment, response SLA, approval, publishing and service recovery linkage.',fields:['customer_id','source','rating','review_text','reply_status','created_at'],actions:['Generate Reply','Approve Reply','Publish Reply','Create Recovery']}
};

const routeMap={
'/crm':'crm','/identity-resolution':'identity','/leads':'leads','/sales-pipeline':'pipeline','/corporate':'corporate','/corporate-crm':'corporate','/corporate-portal':'corporate','/partners':'partners','/partner-crm':'partners','/quotes':'quotes','/partner-bookings':'partnerBookings','/guest-relations':'guestRelations','/complaints':'guestRelations','/loyalty':'loyalty','/segments':'segments','/segmentation':'segments','/offers-coupons':'offers','/campaigns':'campaigns','/marketing':'offers','/whatsapp-crm':'whatsapp','/workflows':'workflows','/analytics':'analytics','/advanced-analytics':'advancedAnalytics','/relationship-manager':'relationship','/ai':'ai','/ai-crm':'ai','/revenue':'revenue','/revenue-management':'revenue','/forecasting':'forecasting','/revenue-forecasting':'forecasting','/competitors':'competitors','/competitor-intelligence':'competitors','/timeline':'timeline','/omnichannel-timeline':'timeline','/consent-privacy':'consent','/service-tickets':'service','/restaurant':'restaurant','/restaurant-crm':'restaurant','/events':'events','/vip':'vip','/churn':'churn','/upselling':'upselling','/cross-selling':'crossSelling','/reputation':'reputation','/customer-intelligence':'ai','/customer-ltv':'crm','/followups':'service','/guest-requests':'guestRelations','/service-recovery':'serviceRecovery','/customer-360':'crm'
};

async function sessionTenant(){const {data:{session}}=await supabase.auth.getSession();if(!session)return {session:null,tenant:'',profile:null};const {data:p}=await supabase.from('anaira_my_profile').select('restaurant_id,is_super_admin,role,full_name').eq('id',session.user.id).maybeSingle();return {session,tenant:p?.restaurant_id||'',profile:p||null};}

export default function CrmEnterprisePage({module,route}){
 const key=module||routeMap[route]||'crm'; const cfg=MODULES[key]||MODULES.crm;
 const [corporateData,setCorporateData]=useState({contacts:[],contracts:[],rates:[],bookings:[],invoices:[],statements:[],revenue:[],ledger:[]});
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null),[tenant,setTenant]=useState(''),[properties,setProperties]=useState([]),[propertyId,setPropertyId]=useState(''),[rows,setRows]=useState([]),[selected,setSelected]=useState(null),[query,setQuery]=useState(''),[msg,setMsg]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState({}),[extra,setExtra]=useState({}),[tab,setTab]=useState('workspace');
 const selectedProperty=useMemo(()=>properties.find(p=>p.id===propertyId)||null,[properties,propertyId]);
 const load=async()=>{if(!tenant||!propertyId)return;setBusy(true);setError('');let q=supabase.from(cfg.table).select('*').eq('tenant_id',tenant).eq('property_id',propertyId).limit(500);if(key==='analytics'||key==='advancedAnalytics'||key==='forecasting'||key==='revenue')q=q.order('forecast_date',{ascending:false});else if(key==='timeline')q=q.order('occurred_at',{ascending:false});else if(key==='relationship')q=q.order('assigned_at',{ascending:false});else q=q.order('created_at',{ascending:false});const r=await q;if(r.error)setError(r.error.message);else setRows(r.data||[]);if(key==='corporate'&&r.data?.length){const a=r.data[0];const [contacts,contracts,rates,bookings,invoices,statements,revenue,ledger]=await Promise.all([supabase.from('crm_corporate_contacts').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).eq('corporate_account_id',a.id).limit(100),supabase.from('crm_corporate_contracts').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).eq('corporate_account_id',a.id).order('end_date',{ascending:false}),supabase.from('crm_corporate_rate_agreements').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).eq('corporate_account_id',a.id).order('valid_from',{ascending:false}),supabase.from('crm_corporate_bookings').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).eq('corporate_account_id',a.id).order('created_at',{ascending:false}),supabase.from('crm_corporate_invoices').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).eq('corporate_account_id',a.id).order('issue_date',{ascending:false}),supabase.from('crm_corporate_statements').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).eq('corporate_account_id',a.id).order('period_to',{ascending:false}),supabase.from('crm_corporate_revenue_attribution').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).eq('corporate_account_id',a.id).order('revenue_date',{ascending:false}),supabase.from('crm_corporate_ledger').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).eq('corporate_account_id',a.id).order('created_at',{ascending:false})]);setCorporateData({contacts:contacts.data||[],contracts:contracts.data||[],rates:rates.data||[],bookings:bookings.data||[],invoices:invoices.data||[],statements:statements.data||[],revenue:revenue.data||[],ledger:ledger.data||[]});}setBusy(false)};
 useEffect(()=>{(async()=>{const x=await sessionTenant();setSession(x.session);setProfile(x.profile);if(!x.session)return;let propQuery=supabase.from('anaira_hospitality_properties_master').select('id,tenant_id,property_type,name,destination,city,state,country,active').order('name',{ascending:true});if(!(x.profile?.is_super_admin===true||x.profile?.role==='super_admin'))propQuery=propQuery.eq('tenant_id',x.tenant);const {data:props,error:pe}=await propQuery;if(pe){setError(pe.message);setTenant(x.tenant);return;}const list=props||[];setProperties(list);const requested=new URLSearchParams(window.location.search).get('property');const requestedProp=list.find(p=>p.id===requested);const profileProp=list.find(p=>p.tenant_id===x.tenant);const chosen=requestedProp||profileProp||list[0]||null;if(chosen){setPropertyId(chosen.id);setTenant(chosen.tenant_id||'');}else setTenant(x.tenant);})()},[]); useEffect(()=>{if(tenant)load()},[tenant,key,propertyId]);
 const switchProperty=(id)=>{const p=properties.find(x=>x.id===id);if(!p)return;setPropertyId(id);setTenant(p.tenant_id||'');setSelected(null);setRows([]);setForm({});const u=new URL(window.location.href);u.searchParams.set('property',id);window.history.replaceState({},'',u);setMsg(`CRM property switched to ${p.name}.`)};
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q))},[rows,query]);
 const metrics=useMemo(()=>({total:rows.length,active:rows.filter(r=>r.active===true||r.status==='active'||r.status==='open'||r.stage==='open').length,value:rows.reduce((n,r)=>n+Number(r.total_revenue||r.total||r.value||r.booking_amount||r.points_balance||r.revpar_forecast||0),0),high:rows.filter(r=>r.risk_level==='high'||r.priority==='high').length}),[rows]);
 const audit=async(action,entityId,payload={})=>{const {data,error}=await supabase.rpc('anaira_crm_record_action',{p_tenant_id:tenant,p_property_id:propertyId,p_entity_type:cfg.table,p_entity_id:entityId||null,p_action:action,p_payload:payload||{}});if(error)throw error;return data};
 const timeline=async(customerId,title,eventType='crm_action',payload={})=>{if(!customerId)return null;const {data,error}=await supabase.rpc('anaira_record_crm_timeline',{p_tenant_id:tenant,p_customer_id:customerId,p_event_type:eventType,p_source_system:'crm',p_source_id:cfg.table,p_title:title,p_description:JSON.stringify(payload||{}),p_amount:Number(payload.amount||0)||null,p_metadata:payload||{},p_occurred_at:new Date().toISOString()});if(error)throw error;return data};
 const save=async()=>{setBusy(true);setError('');const payload={...form,tenant_id:tenant,property_id:propertyId};Object.keys(payload).forEach(k=>{if(payload[k]==='')payload[k]=null});if(key==='quotes'){payload.total=Number(payload.subtotal||0)-Number(payload.discount||0)+Number(payload.tax||0);payload.quote_number=payload.quote_number||`QT-${Date.now()}`;}if(key==='partners')payload.commission_percent=Number(payload.commission_percent||0);if(key==='leads')payload.estimated_value=Number(payload.estimated_value||0);if(key==='analytics')delete payload.id;const r=await supabase.from(cfg.table).insert(payload).select().single();if(r.error)setError(r.error.message);else{setMsg('Live CRM record created.');await audit('create',r.data.id,r.data);await timeline(r.data.customer_id,`${cfg.title}: record created`,'crm_created',r.data);setForm({});await load()}setBusy(false)};
 const updateStatus=async(next)=>{if(!selected)return;setBusy(true);const field=['leads','pipeline'].includes(key)?(key==='leads'?'stage':'status'):(cfg.fields.includes('status')?'status':cfg.fields.includes('active')?'active':null);if(!field){setError('This module uses a dedicated action instead of a simple status field.');setBusy(false);return}const value=field==='active'?next===true:next;const r=await supabase.from(cfg.table).update({[field]:value}).eq('tenant_id',tenant).eq('property_id',propertyId).eq('id',selected.id).select().single();if(r.error)setError(r.error.message);else{setMsg(`${cfg.title}: ${field} updated.`);await audit(`status:${value}`,selected.id,r.data);await timeline(r.data.customer_id,`${cfg.title}: ${value}`,'crm_status_change',{status:value});await load();setSelected(r.data)}setBusy(false)};
 const pluginAction=async(pluginKey,actionId,recordKey={},payload={})=>{const token=(await supabase.auth.getSession()).data.session?.access_token||'';const r=await fetch(`/api/plugins/${pluginKey}/action`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({pluginKey,tenantId:tenant,actionId,recordKey,payload})});const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error||`${pluginKey}/${actionId} failed`);return j};
 const action=async(name)=>{if(!selected&&['Refresh Value','Refresh Metrics','Generate Forecast','Collect Rates','Rebuild Timeline'].indexOf(name)<0){setError('Select a record first.');return}setBusy(true);setError('');try{
  if(name==='Refresh Value'&&selected?.id){const token=(await supabase.auth.getSession()).data.session?.access_token||'';const r=await fetch('/api/plugins/crm/action',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({pluginKey:'crm',tenantId:tenant,actionId:'refresh_value',recordKey:{id:selected.id},payload:{propertyId}})});const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error||'Customer value refresh failed');setMsg('Customer value refreshed.');}
  else if(name==='Find Duplicates'){const {data:c}=await supabase.from('crm_customers').select('id,full_name,email,phone').eq('tenant_id',tenant).limit(500);const dup=(c||[]).filter((x,i,a)=>a.some((y,j)=>j!==i&&((x.email&&y.email&&x.email.toLowerCase()===y.email.toLowerCase())||(x.phone&&y.phone&&x.phone===y.phone))));setExtra({duplicates:dup});setTab('duplicates');setMsg(`${dup.length} duplicate candidates found.`);}
  else if(name==='Merge Selected'&&selected){const dupId=selected.duplicate_customer_id||selected.merged_customer_id;if(!dupId)throw new Error('Select an identity link containing duplicate_customer_id/merged_customer_id.');const survivor=selected.customer_id||selected.survivor_customer_id;const r=await supabase.rpc('anaira_merge_crm_customer_enterprise',{p_survivor:survivor,p_duplicate:dupId,p_reason:'CRM Identity Resolution',p_evidence:{source:'crm-ui'}});if(r.error)throw r.error;setMsg('Customer merge completed and audited.');}
  else if(name==='Open Customer 360'){location.href=`/customer-360?customer=${selected?.id||''}`;}
  else if(name==='Convert'){if(!selected?.customer_id){const r=await supabase.from('crm_customers').insert({tenant_id:tenant,property_id:propertyId,full_name:selected?.lead_type||'Converted Lead',customer_type:'lead',lifecycle_status:'active'}).select().single();if(r.error)throw r.error;await supabase.from('crm_leads').update({customer_id:r.data.id,stage:'converted'}).eq('tenant_id',tenant).eq('id',selected.id);setMsg('Lead converted into canonical CRM customer.')}else await updateStatus('converted');}
  else if(name==='Follow-up'){const r=await supabase.from('crm_followup_events').insert({tenant_id:tenant,property_id:propertyId,customer_id:selected.customer_id||null,lead_id:selected.id||null,scheduled_at:new Date(Date.now()+24*3600000).toISOString(),status:'pending'}).select().single();if(r.error)throw r.error;setMsg('Follow-up scheduled for 24 hours.');}
  else if(name==='Create Contract'){const r=await supabase.rpc('anaira_corporate_contract_action',{p_account_id:selected.id,p_action:'create_contract',p_end_date:new Date(Date.now()+365*86400000).toISOString().slice(0,10)});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Corporate contract created as draft and audited.');}
  else if(name==='Approve Contract'){const r=await supabase.rpc('anaira_corporate_contract_action',{p_account_id:selected.id,p_action:'approve_contract'});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Corporate contract approved and activated.');}
  else if(name==='Renew Contract'){const r=await supabase.rpc('anaira_corporate_contract_action',{p_account_id:selected.id,p_action:'renew_contract',p_end_date:new Date(Date.now()+365*86400000).toISOString().slice(0,10)});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Corporate contract renewed and audited.');}
  else if(name==='Record Credit'){const amount=Number(prompt('Credit/debit amount. Use negative for payment/credit reduction','0')||0);if(!Number.isFinite(amount)||amount===0)throw new Error('Enter a non-zero amount.');const r=await supabase.rpc('anaira_corporate_record_ledger',{p_account_id:selected.id,p_entry_type:amount>0?'charge':'payment',p_amount:amount,p_reference_number:`CRM-${Date.now()}`,p_description:'Corporate CRM credit control'});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Corporate ledger entry posted; credit utilization updated transactionally.');}
  else if(name==='Create Rate Agreement'){const rate=Number(prompt('Negotiated room rate','0')||0);if(!(rate>0))throw new Error('Enter a valid negotiated rate.');const r=await supabase.from('crm_corporate_rate_agreements').insert({tenant_id:tenant,property_id:propertyId,corporate_account_id:selected.id,rate,currency:'INR',valid_from:new Date().toISOString().slice(0,10),terms:{source:'corporate-crm'}}).select().single();if(r.error)throw r.error;setMsg('Negotiated rate agreement saved and scoped to this property.');}
  else if(name==='Create Booking'){const amount=Number(prompt('Corporate booking amount','0')||0);if(!(amount>=0))throw new Error('Valid booking amount required.');const roomType=prompt('Room type UUID (optional)','')||null;const room=prompt('Room UUID (optional)','')||null;const checkIn=prompt('Check-in (YYYY-MM-DD, optional)','')||null;const checkOut=prompt('Check-out (YYYY-MM-DD, optional)','')||null;const ref=`CORP-BKG-${Date.now()}`;const r=await supabase.from('crm_corporate_bookings').insert({tenant_id:tenant,property_id:propertyId,corporate_account_id:selected.id,booking_reference:ref,amount,status:'draft',room_type_id:roomType,room_id:room,check_in:checkIn,check_out:checkOut,room_allocation:{source:'corporate-crm',property_id:propertyId,room_type_id:roomType,room_id:room,check_in:checkIn,check_out:checkOut}}).select().single();if(r.error)throw r.error;if(amount>0){const l=await supabase.rpc('anaira_corporate_record_ledger',{p_account_id:selected.id,p_entry_type:'booking',p_amount:amount,p_reference_number:ref,p_description:'Corporate booking charge'});if(l.error)throw l.error;}setMsg('Corporate booking created with persisted room-allocation payload and ledger linkage.');}
  else if(name==='Create Invoice'){const subtotal=Number(prompt('Invoice subtotal','0')||0);const tax=Number(prompt('Tax','0')||0);if(!(subtotal>=0&&tax>=0))throw new Error('Valid invoice amounts required.');const total=subtotal+tax;const ref=`INV-CORP-${Date.now()}`;const r=await supabase.from('crm_corporate_invoices').insert({tenant_id:tenant,property_id:propertyId,corporate_account_id:selected.id,invoice_number:ref,subtotal,tax,total,status:'open'}).select().single();if(r.error)throw r.error;const l=await supabase.rpc('anaira_corporate_record_ledger',{p_account_id:selected.id,p_entry_type:'invoice',p_amount:total,p_reference_number:ref,p_description:'Corporate invoice'});if(l.error)throw l.error;const rv=await supabase.rpc('anaira_corporate_record_revenue',{p_account_id:selected.id,p_invoice_id:r.data.id,p_gross:total});if(rv.error)throw rv.error;setMsg('Corporate invoice created, ledger posted and revenue attributed.');}
  else if(name==='Generate Statement'){const from=prompt('Statement from (YYYY-MM-DD)',new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10));const to=prompt('Statement to (YYYY-MM-DD)',new Date().toISOString().slice(0,10));if(!from||!to)throw new Error('Statement dates required.');const r=await supabase.rpc('anaira_corporate_generate_statement',{p_account_id:selected.id,p_from:from,p_to:to});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Corporate statement generated from the canonical ledger.');}
  else if(name==='Record Revenue'){const amount=Number(prompt('Revenue amount','0')||0);if(!(amount>0))throw new Error('Valid revenue amount required.');const r=await supabase.rpc('anaira_corporate_record_revenue',{p_account_id:selected.id,p_gross:amount,p_net:amount});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Corporate revenue attribution persisted.');}
  else if(name==='View Ledger'){setExtra({ledger:corporateData.ledger});setTab('results');}
  else if(name==='View Contacts'){setExtra({contacts:corporateData.contacts});setTab('results');}
  else if(name==='Add Contact'){const name=prompt('Contact name');if(!name)throw new Error('Contact name required.');const email=prompt('Contact email','')||null;const phone=prompt('Contact phone','')||null;const role=prompt('Role / designation','')||null;const r=await supabase.from('crm_corporate_contacts').insert({tenant_id:tenant,property_id:propertyId,corporate_account_id:selected.id,contact_name:name,email,phone,role_title:role,primary_contact:corporateData.contacts.length===0}).select().single();if(r.error)throw r.error;setMsg(`Corporate contact ${name} saved.`);}
  else if(name==='Assign Account Manager'){const staff=prompt('Account manager user UUID',selected.account_manager_id||'');if(!staff)throw new Error('Account manager UUID required.');const r=await supabase.from('crm_corporate_accounts').update({account_manager_id:staff}).eq('tenant_id',tenant).eq('property_id',propertyId).eq('id',selected.id).select().single();if(r.error)throw r.error;setSelected(r.data);setMsg('Corporate account manager assigned and persisted.');}
  else if(name==='Renewal Review'){const r=await supabase.from('crm_notifications').insert({tenant_id:tenant,property_id:propertyId,notification_type:'corporate_renewal',title:'Corporate renewal review',body:`Review ${selected.company_name||selected.id}`,severity:'info',action_url:'/corporate-crm'}).select().single();if(r.error)throw r.error;setMsg('Renewal review notification persisted.');}
  else if(name==='Open Corporate Portal'){location.href=`/corporate-portal?property=${propertyId}&account=${selected.id}`;}
  else if(name==='Onboard'){const r=await supabase.rpc('anaira_partner_onboard',{p_partner_id:selected.id,p_kyc_status:'approved'});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Partner onboarding/KYC state updated through canonical RPC.');await load();}
  else if(name==='Create Contract'){const r=await supabase.rpc('anaira_partner_contract_action',{p_partner_id:selected.id,p_action:'create',p_end_date:new Date(Date.now()+365*86400000).toISOString().slice(0,10)});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Partner contract created as draft.');}
  else if(name==='Approve Contract'){const r=await supabase.rpc('anaira_partner_contract_action',{p_partner_id:selected.id,p_action:'approve'});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Partner contract approved and activated.');await load();}
  else if(name==='Renew Contract'){const r=await supabase.rpc('anaira_partner_contract_action',{p_partner_id:selected.id,p_action:'renew',p_end_date:new Date(Date.now()+365*86400000).toISOString().slice(0,10)});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Partner contract renewed.');await load();}
  else if(name==='Calculate Commission'){const r=await supabase.rpc('anaira_partner_calculate_commission',{p_booking_id:selected.id,p_cancelled:selected.status==='cancelled',p_cancellation_amount:Number(selected.cancellation_amount||0)});if(r.error)throw r.error;setExtra(r.data||{});setTab('results');setMsg('Partner commission calculated through canonical commission runtime.');}
  else if(name==='Create Booking'){const amount=Number(prompt('Booking amount','0')||0);if(!(amount>=0))throw new Error('Valid booking amount required.');const ref=prompt('Booking reference',`PARTNER-${Date.now()}`)||`PARTNER-${Date.now()}`;const customer=prompt('Customer UUID (optional)','')||null;const idem=`partner-${selected.id}-${ref}`;const r=await supabase.rpc('anaira_partner_upsert_booking',{p_partner_id:selected.id,p_booking_reference:ref,p_booking_amount:amount,p_customer_id:customer,p_property_id:propertyId,p_idempotency_key:idem});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Partner booking attributed with idempotent commission calculation.');}
  else if(name==='Create Settlement'){const from=new Date(Date.now()-30*86400000).toISOString().slice(0,10),to=new Date().toISOString().slice(0,10);const r=await supabase.rpc('anaira_partner_create_settlement',{p_partner_id:selected.id,p_from:from,p_to:to});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Partner settlement created through canonical settlement runtime.');}
  else if(name==='Approve Settlement'){const r=await supabase.rpc('anaira_partner_settlement_action',{p_settlement_id:selected.id,p_action:'approve'});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Partner settlement approved.');}
  else if(name==='Payout Settlement'){const ref=prompt('Payout reference',`PAYOUT-${Date.now()}`)||`PAYOUT-${Date.now()}`;const r=await supabase.rpc('anaira_partner_settlement_action',{p_settlement_id:selected.id,p_action:'payout',p_reference:ref});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Partner payout recorded.');}
  else if(name==='Generate Statement'){const from=prompt('Statement from (YYYY-MM-DD)',new Date(new Date().getFullYear(),new Date().getMonth(),1).toISOString().slice(0,10));const to=prompt('Statement to (YYYY-MM-DD)',new Date().toISOString().slice(0,10));const r=await supabase.rpc('anaira_partner_generate_statement',{p_partner_id:selected.id,p_from:from,p_to:to});if(r.error)throw r.error;setExtra(r.data||{});setTab('results');setMsg('Partner statement generated.');}
  else if(name==='Reconcile Settlement'){const actual=Number(prompt('Actual commission paid','0')||0);if(!(actual>=0))throw new Error('Valid actual commission required.');const r=await supabase.rpc('anaira_partner_reconcile',{p_settlement_id:selected.id,p_actual:actual});if(r.error)throw r.error;setExtra(r.data||{});setTab('results');setMsg('Partner settlement reconciliation persisted.');}
  else if(name==='Open Partner Portal'){location.href=`/partner-portal?property=${propertyId}&partner=${selected.id}`;}
  else if(name==='Prepare Settlement'){const partnerId=selected.partner_id;const {data:b}=await supabase.from('crm_partner_bookings').select('booking_amount,commission_amount').eq('tenant_id',tenant).eq('partner_id',partnerId).eq('status','completed');const gross=(b||[]).reduce((n,x)=>n+Number(x.booking_amount||0),0),commission=(b||[]).reduce((n,x)=>n+Number(x.commission_amount||0),0);const r=await supabase.from('crm_partner_settlements').insert({tenant_id:tenant,property_id:propertyId,partner_id:partnerId,period_start:new Date(Date.now()-30*86400000).toISOString().slice(0,10),period_end:new Date().toISOString().slice(0,10),gross_amount:gross,commission_amount:commission,status:'pending'}).select().single();if(r.error)throw r.error;setMsg('Settlement prepared.');}
  else if(name==='Qualify')await updateStatus('qualified');
  else if(name==='Refresh Visit Metrics'){const {data:v}=await supabase.from('crm_restaurant_visits').select('customer_id,amount,visit_at').eq('tenant_id',tenant).limit(5000);const groups={};for(const x of v||[]){if(!x.customer_id)continue;(groups[x.customer_id] ||= {visits:0,spend:0,last:null});groups[x.customer_id].visits++;groups[x.customer_id].spend+=Number(x.amount||0);if(!groups[x.customer_id].last||new Date(x.visit_at)>new Date(groups[x.customer_id].last))groups[x.customer_id].last=x.visit_at;}for(const [customer_id,g] of Object.entries(groups))await supabase.from('crm_restaurant_customer_metrics').upsert({tenant_id:tenant,customer_id,total_visits:g.visits,lifetime_spend:g.spend,average_bill:g.visits?g.spend/g.visits:0,last_visit_at:g.last,updated_at:new Date().toISOString()},{onConflict:'tenant_id,customer_id'});setMsg('Restaurant customer metrics refreshed from live visits.');}
  else if(name==='Refresh Preferences'){const r=await pluginAction('restaurant_crm','refresh_preferences',{id:selected?.id,customer_id:selected?.customer_id});setExtra({preferences:r.result||r});setTab('results');}
  else if(name==='Qualify VIP'){const c=selected;const level=Number(c.total_hotel_revenue||0)+Number(c.total_restaurant_revenue||0)>=100000?'platinum':Number(c.total_stays||0)>=5?'gold':'vip';const r=await supabase.from('crm_vip_profiles').upsert({tenant_id:tenant,property_id:propertyId,customer_id:c.id,vip_level:level,notes:'Qualified from CRM VIP rules'},{onConflict:'customer_id'}).select().single();if(r.error)throw r.error;await supabase.from('crm_customers').update({vip:true}).eq('tenant_id',tenant).eq('id',c.id);setMsg(`VIP qualified as ${level}.`);}
  else if(name==='Assign Manager'||name==='Add Amenity'){const manager=prompt('Manager user UUID',selected?.dedicated_manager||'');if(name==='Assign Manager'&&manager){const r=await supabase.from('crm_vip_profiles').upsert({tenant_id:tenant,property_id:propertyId,customer_id:selected.id,dedicated_manager:manager,vip_level:selected.vip_level||'vip'},{onConflict:'customer_id'});if(r.error)throw r.error;setMsg('VIP manager assigned.')}else if(name==='Add Amenity'){const amenity=prompt('Amenity');if(amenity){const r=await supabase.from('crm_vip_profiles').select('welcome_amenities').eq('tenant_id',tenant).eq('customer_id',selected.id).maybeSingle();const arr=Array.isArray(r.data?.welcome_amenities)?r.data.welcome_amenities:[];const u=await supabase.from('crm_vip_profiles').upsert({tenant_id:tenant,property_id:propertyId,customer_id:selected.id,vip_level:selected.vip_level||'vip',welcome_amenities:[...arr,amenity]},{onConflict:'customer_id'});if(u.error)throw u.error;setMsg('VIP amenity added.')}}}
  else if(name==='Recompute Churn'){const r=await pluginAction('churn','recompute_churn',{id:selected.id},{customerId:selected.customer_id||selected.id});setExtra({churn:r.result||r});setTab('results');setMsg('Churn score recomputed.');}
  else if(name==='View Factors'){setExtra({factors:selected.factors||[]});setTab('results');}
  else if(name==='Create Retention Action'){const r=await pluginAction('churn','create_retention',{id:selected.id},{customerId:selected.customer_id||selected.id});setExtra({retention:r.result||r});setTab('results');setMsg('Retention action created.');}
  else if(name==='Create Offer'&&key==='upselling'){const r=await supabase.from('crm_commercial_offers').insert({tenant_id:tenant,property_id:propertyId,customer_id:selected.customer_id,offer_type:'upsell',title:selected.title||'CRM Upsell Offer',price:Number(selected.amount||0),inventory_ref:selected.offer_id?String(selected.offer_id):null,status:'offered',metadata:{source:'crm_upselling',source_record:selected.id}}).select().single();if(r.error)throw r.error;setExtra({offer:r.data});setTab('results');await audit('create_commercial_offer',r.data.id,r.data);setMsg('Commercial upsell offer created.')}
  else if(name==='Create Offer'&&key==='crossSelling'){const r=await supabase.from('crm_commercial_offers').insert({tenant_id:tenant,property_id:propertyId,customer_id:selected.customer_id,offer_type:'cross_sell',title:selected.title||'CRM Cross-sell Offer',price:Number(selected.amount||0),inventory_ref:selected.offer_id?String(selected.offer_id):null,status:'offered',metadata:{source:'crm_cross_selling',source_record:selected.id}}).select().single();if(r.error)throw r.error;setExtra({offer:r.data});setTab('results');await audit('create_commercial_offer',r.data.id,r.data);setMsg('Commercial cross-sell offer created.')}
  else if(name==='Record Payment'&&['upselling','crossSelling'].includes(key)){const r=await supabase.from('crm_commercial_offers').update({status:'paid',paid_at:new Date().toISOString()}).eq('tenant_id',tenant).eq('property_id',propertyId).eq('id',selected.id).select().single();if(r.error)throw r.error;setSelected(r.data);await audit('offer_payment',r.data.id,selected,r.data);setMsg('Offer payment recorded.')}
  else if(name==='Fulfil Offer'&&['upselling','crossSelling'].includes(key)){const r=await supabase.from('crm_commercial_offers').update({status:'fulfilled',fulfilled_at:new Date().toISOString(),revenue:Number(selected.price||0)}).eq('tenant_id',tenant).eq('property_id',propertyId).eq('id',selected.id).select().single();if(r.error)throw r.error;setSelected(r.data);await audit('offer_fulfilment',r.data.id,selected,r.data);if(selected.customer_id)await timeline(selected.customer_id,'Commercial offer fulfilled','commercial_offer',{offer_id:r.data.id,amount:r.data.revenue});setMsg('Offer fulfilment recorded and attributed.')}
  else if(name==='Find Eligible Guests'||name==='Send Offer'||name==='Record Acceptance'||name==='Cancel Offer'){const map={'Find Eligible Guests':'find_eligible','Send Offer':'send_offer','Record Acceptance':'record_acceptance','Cancel Offer':'cancel_offer'};const r=await pluginAction('upselling',map[name],{id:selected.id},{customerId:selected.customer_id});setExtra({upsell:r.result||r});setTab('results');}
  else if(name==='Preview Matches'||name==='Generate Offers'||name==='Send Offers'){const map={'Preview Matches':'preview_matches','Generate Offers':'generate_offers','Send Offers':'send_offers'};const r=await pluginAction('cross_selling',map[name],{id:selected.id},{customerId:selected.customer_id});setExtra({crossSell:r.result||r});setTab('results');}else if(name==='View Attribution'){const {data:r}=await supabase.from('crm_upsell_events').select('*').eq('tenant_id',tenant).eq('reference_id',selected.id).limit(500);setExtra({attribution:r||[]});setTab('results');}
  else if(name==='Create Quote'){const r=await supabase.from('crm_quotes').insert({tenant_id:tenant,quote_number:`EV-${Date.now()}`,status:'draft',subtotal:Number(selected?.estimated_value||0),discount:0,tax:0,total:Number(selected?.estimated_value||0)}).select().single();if(r.error)throw r.error;const x=await supabase.from('crm_event_quotes').insert({event_id:selected.id,quote_id:r.data.id,package_definition:{source:'event-crm'}});if(x.error)throw x.error;setMsg('Event quote created and linked.');}
  else if(name==='Approve Proposal'){const r=await supabase.from('crm_events').update({stage:'proposal_approved'}).eq('tenant_id',tenant).eq('property_id',propertyId).eq('id',selected.id).select().single();if(r.error)throw r.error;setMsg('Event proposal approved.');}
  else if(name==='Schedule Follow-up'){const r=await supabase.from('crm_followup_events').insert({tenant_id:tenant,lead_id:null,customer_id:selected.customer_id||null,scheduled_at:new Date(Date.now()+24*3600000).toISOString(),status:'pending'}).select().single();if(r.error)throw r.error;setMsg('Event follow-up scheduled.');}
  else if(name==='Record Deposit'){const amount=Number(prompt('Deposit amount',selected?.estimated_value||0)||0);const r=await supabase.from('crm_timeline_events').insert({tenant_id:tenant,property_id:propertyId,customer_id:selected.customer_id||null,event_type:'event_deposit',source_system:'event_crm',source_id:selected.id,title:`Deposit for ${selected.name}`,description:`Deposit ${amount}`,amount,occurred_at:new Date().toISOString()});if(r.error)throw r.error;setMsg('Deposit event recorded in timeline.');}
  else if(name==='Mark Lost')await updateStatus('lost');
  else if(name==='Mark Won')await updateStatus('won');
  else if(name==='Approve'||name==='Accept'||name==='Reject')await updateStatus(name.toLowerCase());
  else if(name==='Complete')await updateStatus('completed');
  else if(name==='Cancel')await updateStatus('cancelled');
  else if(name==='Activate')await updateStatus(true);
  else if(name==='Deactivate')await updateStatus(false);
  else if(name==='Issue Points'){const pts=Number(prompt('Points to issue', '100')||0);if(pts<=0)throw new Error('Points must be positive');const r=await supabase.rpc('anaira_loyalty_post',{p_tenant_id:tenant,p_customer_id:selected.customer_id,p_domain:'crm',p_amount:pts,p_reference_type:'manual_issue',p_reference_id:selected.id});if(r.error)throw r.error;setMsg('Loyalty points posted through canonical ledger.');}
  else if(name==='Redeem Reward'){const pts=Number(prompt('Points to redeem','100')||0);if(pts<=0)throw new Error('Points must be positive');const r=await supabase.rpc('anaira_loyalty_redeem',{p_tenant_id:tenant,p_customer_id:selected.customer_id,p_reward_id:selected.reward_id||null,p_reference_id:selected.id});if(r.error)throw r.error;setMsg('Reward redemption executed through loyalty engine.');}
  else if(name==='Reverse Transaction'){const r=await supabase.rpc('anaira_reverse_loyalty_transaction',{p_transaction_id:selected.id,p_reason:'CRM reversal'});if(r.error)throw r.error;setMsg('Loyalty transaction reversed.');}
  else if(name==='Preview Audience'){const r=await supabase.rpc('anaira_preview_segment',{p_segment:selected.id});if(r.error)throw r.error;setExtra({preview:r.data});setTab('results');setMsg('Segment preview calculated.');}
  else if(name==='Recalculate'){const r=await supabase.rpc('anaira_recalculate_segment',{p_segment:selected.id});if(r.error)throw r.error;setExtra({recalculated:r.data});setTab('results');setMsg('Segment membership recalculated.');}
  else if(name==='Validate Coupon'){const code=prompt('Coupon code',selected?.code||'');const r=await supabase.rpc('anaira_validate_coupon',{p_tenant_id:tenant,p_code:code,p_customer_id:selected?.customer_id||null,p_order_amount:Number(prompt('Order amount','0')||0)});if(r.error)throw r.error;setExtra({coupon:r.data});setTab('results');}
  else if(name==='Run Audience'){const r=await supabase.from('crm_campaign_recipients').select('id',{count:'exact',head:true}).eq('campaign_id',selected.id);if(r.error)throw r.error;setExtra({audienceCount:r.count||0});setTab('results');}
  else if(name==='Launch'){await updateStatus('active');}
  else if(name==='Pause'){await updateStatus('paused');}
  else if(name==='Start Workflow'){const r=await supabase.rpc('anaira_start_workflow',{p_workflow_id:selected.id,p_context:{source:'crm_ui'}});if(r.error)throw r.error;setExtra({run:r.data});setTab('results');setMsg('Workflow run queued.');}
  else if(name==='Refresh Metrics'){const r=await supabase.rpc('anaira_refresh_crm_analytics',{p_tenant_id:tenant,p_metric_date:new Date().toISOString().slice(0,10)});if(r.error)throw r.error;setMsg('Analytics metrics refreshed.');}
  else if(name==='Generate Forecast'||name==='Refresh Forecast'){const r=await fetch('/api/plugins/revenue_forecasting/action',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${(await supabase.auth.getSession()).data.session?.access_token||''}`},body:JSON.stringify({pluginKey:'revenue_forecasting',tenantId:tenant,actionId:'generate_forecast',recordKey:{},payload:{horizonDays:30}})});const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error||'Forecast action failed');setMsg('Forecast generated from live analytics baseline.');}
  else if(name==='Collect Rates'){setMsg('Competitor provider is not connected. Configure COMPETITOR_RATES_API_URL/provider credentials before live collection.');setTab('results');}
  else if(name==='Rebuild Timeline'){const r=await supabase.from('crm_integration_event_inbox').select('*').eq('tenant_id',tenant).order('created_at',{ascending:false}).limit(500);if(r.error)throw r.error;setExtra({eventInbox:r.data||[]});setTab('results');setMsg('Event inbox loaded for timeline reconciliation.');}
  else if(name==='Grant Consent'||name==='Withdraw Consent'){await updateStatus(name==='Grant Consent'?'granted':'withdrawn');}
  else if(name==='Export Data'){const customerId=selected?.customer_id||selected?.id;const r=await supabase.from('crm_data_requests').insert({tenant_id:tenant,property_id:propertyId,customer_id:customerId,request_type:'export',status:'queued',requested_at:new Date().toISOString()}).select().single();if(r.error)throw r.error;setMsg('Data export request queued.');}
  else if(name==='Delete Request'){const customerId=selected?.customer_id||selected?.id;const r=await supabase.from('crm_data_requests').insert({tenant_id:tenant,property_id:propertyId,customer_id:customerId,request_type:'delete',status:'queued',requested_at:new Date().toISOString()}).select().single();if(r.error)throw r.error;setMsg('Deletion request queued for authorized processing.');}
  else if(name==='Create Template'){setTab('template');}
  else if(name==='Retry Failed'){const ins=await supabase.from('crm_whatsapp_jobs').insert({tenant_id:tenant,property_id:propertyId,message_id:selected.id,job_type:'send',status:'queued',next_attempt_at:new Date().toISOString()}).select().single();if(ins.error)throw ins.error;setMsg('WhatsApp message retry queued through canonical job runtime.');}
  else if(name==='Mark Read'){if(!selected.provider_message_id)throw new Error('Provider message ID is required for read acknowledgement.');const r=await supabase.rpc('anaira_whatsapp_apply_status',{p_provider_message_id:selected.provider_message_id,p_status:'read',p_payload:{source:'crm_ui'}});if(r.error)throw r.error;setMsg('WhatsApp provider status recorded as read.');}
  else if(name==='Send WhatsApp'){const body=prompt('WhatsApp message','Hello')||'';if(!body)throw new Error('Message body required.');const customerId=selected.customer_id||selected.id;const r=await supabase.rpc('anaira_whatsapp_enqueue',{p_customer_id:customerId,p_phone:selected.phone||'',p_body:body,p_message_type:'text',p_template_id:null,p_property_id:propertyId,p_idempotency_key:`crm-wa-${customerId}-${Date.now()}`});if(r.error)throw r.error;let delivery=r.data||{};if(delivery.provider_connected&&delivery.message_id){const token=(await supabase.auth.getSession()).data.session?.access_token||'';const sr=await fetch('/api/crm/whatsapp/send',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({tenantId:tenant,messageId:delivery.message_id,phone:selected.phone||''})});delivery={...delivery,provider_send:await sr.json()};}setExtra(delivery);setTab('results');setMsg(delivery.provider_connected?'WhatsApp provider send attempted and provider response persisted.':'WhatsApp provider is NOT CONNECTED; message state persisted without fake delivery.');}
  else if(name==='Opt Out'){const r=await supabase.rpc('anaira_whatsapp_optout',{p_customer_id:selected.customer_id||selected.id,p_phone:selected.phone||null,p_reason:'CRM WhatsApp opt-out',p_property_id:propertyId});if(r.error)throw r.error;setExtra(r.data||{});setTab('results');setMsg('WhatsApp opt-out persisted.');}
  else if(name==='Generate Summary'||name==='Next Best Action'||name==='Run Insight'){const mode=name==='Generate Summary'?'summary':name==='Next Best Action'?'next_best_action':'insight';const r=await fetch('/api/plugins/ai_crm/action',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${(await supabase.auth.getSession()).data.session?.access_token||''}`},body:JSON.stringify({pluginKey:'ai_crm',tenantId:tenant,actionId:name==='Generate Summary'?'generate_summary':name==='Next Best Action'?'next_best_action':'run_insight',recordKey:{id:selected.id},payload:{customerId:selected.customer_id||selected.id,mode,propertyId}})});const j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error||'AI action failed');setMsg('AI action completed and stored.');}
  else if(name==='Approve Action')await updateStatus('approved');
  else if(name==='Rebalance Workload'){const {data:a}=await supabase.from('crm_relationship_assignments').select('staff_id,customer_id').eq('tenant_id',tenant).eq('active',true);const workload={};for(const x of a||[]){workload[x.staff_id]=(workload[x.staff_id]||0)+1}setExtra({assignments:(a||[]).length,workload});setTab('results');await supabase.from('crm_notifications').insert({tenant_id:tenant,notification_type:'relationship_rebalance',title:'Relationship workload analysed',body:`${(a||[]).length} active assignments analysed.`,severity:'info',action_url:'/relationship-manager'});setMsg('Relationship workload analysed and manager notification queued.');}
  else if(name==='Assign Owner'||name==='Reassign'){const staff=prompt('Staff user UUID');if(!staff)throw new Error('Staff user UUID required');const r=await supabase.from('crm_relationship_assignments').update({staff_id:staff,active:true}).eq('tenant_id',tenant).eq('property_id',propertyId).eq('id',selected.id).select().single();if(r.error)throw r.error;setMsg('Relationship assignment updated.');}
  else if(name==='Generate Recommendation'){
 const f=selected||{}; const oldRate=Number(f.adr_forecast||0);
 const demand=Number(f.demand_index||1); const occ=Number(f.occupancy_forecast||0);
 const recommended=Math.max(0,Math.round(oldRate*(1+Math.max(-0.2,Math.min(0.5,(demand-1)*0.35+(occ-70)/300)))));
 const r=await supabase.from('crm_rate_decisions').insert({tenant_id:tenant,property_id:propertyId,forecast_id:f.id||null,room_type_id:f.room_type_id||null,rate_plan_id:f.rate_plan_id||null,decision_type:'recommendation',old_rate:oldRate,recommended_rate:recommended,status:'pending_approval',rationale:{source:'crm_revenue_engine',demand_index:demand,occupancy_forecast:occ}}).select().single();
 if(r.error)throw r.error;setExtra({rateDecision:r.data});setTab('results');setMsg('Rate recommendation generated and persisted for approval.');
}
else if(name==='Approve Rate'){
 const r=await supabase.from('crm_rate_decisions').update({status:'approved',approved_by:(await supabase.auth.getUser()).data.user?.id||null,approved_at:new Date().toISOString()}).eq('tenant_id',tenant).eq('property_id',propertyId).eq('id',selected.id).select().single();
 if(r.error)throw r.error;setSelected(r.data);setMsg('Rate recommendation approved.');
}
else if(name==='Override Rate'){
 const rate=Number(prompt('Override published/recommended rate',selected?.recommended_rate||selected?.old_rate||0)||0);if(!(rate>0))throw new Error('Valid override rate required');
 const r=await supabase.from('crm_rate_decisions').update({recommended_rate:rate,decision_type:'override',status:'pending_approval',rationale:{source:'manual_override',previous:selected?.recommended_rate||null}}).eq('tenant_id',tenant).eq('property_id',propertyId).eq('id',selected.id).select().single();
 if(r.error)throw r.error;setSelected(r.data);setMsg('Rate override saved for approval.');
}
else if(name==='Publish Rate'){
 if(selected?.status!=='approved')throw new Error('Rate decision must be approved before publish.');
 if(!selected?.rate_plan_id)throw new Error('Rate decision has no rate plan.');
 const rate=Number(selected.published_rate||selected.recommended_rate||0);if(!(rate>0))throw new Error('No publishable rate.');
 const rp=await supabase.from('hms_rate_plans').update({rate}).eq('id',selected.rate_plan_id).eq('restaurant_id',tenant).select().single();
 if(rp.error)throw rp.error;
 const r=await supabase.from('crm_rate_decisions').update({published_rate:rate,status:'published',published_at:new Date().toISOString()}).eq('tenant_id',tenant).eq('property_id',propertyId).eq('id',selected.id).select().single();
 if(r.error)throw r.error;setSelected(r.data);setMsg('Approved rate published to the linked rate plan and audited.');
}
  else if(name==='Create Recovery'){const customerId=selected?.customer_id||null;const r=await supabase.from('crm_service_recovery_cases').insert({tenant_id:tenant,property_id:propertyId,customer_id:customerId,complaint_id:selected?.id||null,recovery_type:'service_recovery',compensation_amount:Number(selected?.compensation_amount||selected?.compensation||0),status:'open',notes:'Created from complaint recovery workspace'}).select().single();if(r.error)throw r.error;setMsg('Service recovery case created.');}
  else if(name==='Open Account'){location.href=`/corporate?property=${propertyId}&account=${selected.id}`;}

  else if(name==='Convert to Booking'){if(selected?.status!=='accepted')throw new Error('Quote must be accepted before conversion.');const r=await supabase.from('crm_booking_transactions').insert({tenant_id:tenant,customer_id:selected.customer_id||null,state:'draft',idempotency_key:`crm-quote-${selected.id}-${Date.now()}`,amount:Number(selected.total||0),payload:{quote_id:selected.id,quote_number:selected.quote_number,property_id:propertyId,source:'crm_quote_conversion'}}).select().single();if(r.error)throw r.error;await supabase.from('crm_quotes').update({status:'converted'}).eq('tenant_id',tenant).eq('property_id',propertyId).eq('id',selected.id);setExtra({bookingTransaction:r.data});setTab('results');setMsg('Quote converted into a booking transaction; final inventory/payment confirmation remains in the booking engine.');}
  else if(name==='Escalate SLA'){await updateStatus('escalated');}
  else if(name==='Refresh Tier'){const a=selected;const pts=Number(a.lifetime_points||a.points_balance||0);const tier=pts>=50000?'platinum':pts>=20000?'gold':pts>=5000?'silver':'bronze';const r=await supabase.from('crm_loyalty_accounts').update({tier}).eq('tenant_id',tenant).eq('property_id',propertyId).eq('id',selected.id).select().single();if(r.error)throw r.error;setSelected(r.data);setMsg(`Loyalty tier recalculated: ${tier}.`);}
  else if(name==='Export Report'){const rows=filtered||[];setExtra({exported_at:new Date().toISOString(),rows});setTab('results');setMsg(`${rows.length} live records prepared for export.`);}
  else if(name==='Compare Periods'||name==='Open Cohorts'||name==='Compare Accuracy'){const rows=filtered||[];setExtra({action:name,records:rows,period:new Date().toISOString().slice(0,10)});setTab('results');}
  else if(name==='Approve Forecast'){await updateStatus('approved');}
  else if(name==='Normalize Rates'){const rows=filtered||[];const normalized=rows.map(x=>({...x,normalized_rate:Number(x.rate||0)}));setExtra({normalized});setTab('results');setMsg('Competitor rates normalized from stored provider records.');}
  else if(name==='Run Parity'){const rows=filtered||[];const grouped={};for(const x of rows){const k=x.stay_date||'unknown';(grouped[k] ||= []).push(Number(x.rate||0));}const parity=Object.fromEntries(Object.entries(grouped).map(([d,v])=>[d,{min:Math.min(...v),max:Math.max(...v),spread:Math.max(...v)-Math.min(...v)}]));setExtra({parity});setTab('results');}
  else if(name==='Create Alert'){const r=await supabase.from('crm_notifications').insert({tenant_id:tenant,property_id:propertyId,notification_type:'competitor_parity',title:'Competitor rate alert',body:`Parity review requested for ${selected?.stay_date||'selected date'}`,severity:'warning',action_url:'/competitors'}).select().single();if(r.error)throw r.error;setMsg('Competitor parity alert created.');}
  else if(name==='Generate Reply'){const text=selected?.review_text||'';const reply=`Thank you for sharing your feedback${selected?.customer_id?' with us':''}. We appreciate your review and are reviewing your experience carefully.`;const r=await supabase.from('crm_reviews').update({reply_draft:reply,reply_status:'draft'}).eq('tenant_id',tenant).eq('property_id',propertyId).eq('id',selected.id).select().single();if(r.error)throw r.error;setSelected(r.data);setMsg('AI-safe reply draft generated for human review.');}
  else if(name==='Approve Reply'){const r=await supabase.from('crm_reviews').update({reply_status:'approved'}).eq('tenant_id',tenant).eq('property_id',propertyId).eq('id',selected.id).select().single();if(r.error)throw r.error;setSelected(r.data);setMsg('Reply approved; publishing remains provider-gated.');}
  else if(name==='Publish Reply'){if(selected?.reply_status!=='approved')throw new Error('Reply must be approved before publishing.');throw new Error('NOT CONNECTED: Review provider credentials/webhook are required before publishing. The approved reply remains persisted as provider-ready.');}
  else if(name==='Approve Recovery'){const r=await supabase.rpc('anaira_service_recovery_action',{p_recovery_id:selected.id,p_action:'approve',p_outcome:null,p_csat:null,p_nps:null});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Recovery approved through canonical recovery runtime.');}
  else if(name==='Complete Recovery'){const outcome=prompt('Recovery outcome','resolved');const r=await supabase.rpc('anaira_service_recovery_action',{p_recovery_id:selected.id,p_action:'complete',p_outcome:outcome,p_csat:null,p_nps:null});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Recovery completed through canonical recovery runtime.');}
  else if(name==='Cancel Recovery'){const r=await supabase.rpc('anaira_service_recovery_action',{p_recovery_id:selected.id,p_action:'cancel',p_outcome:'cancelled',p_csat:null,p_nps:null});if(r.error)throw r.error;setExtra(r.data||{});setMsg('Recovery cancelled through canonical recovery runtime.');}
  else if(name==='Create Timeline'){const r=await supabase.from('crm_timeline_events').insert({tenant_id:tenant,property_id:propertyId,customer_id:selected?.customer_id||null,event_type:'service_recovery',source_system:'crm_service_recovery',source_id:selected.id,title:'Service recovery update',description:selected?.outcome||selected?.notes||'Recovery case updated',amount:Number(selected?.compensation_amount||0),occurred_at:new Date().toISOString()}).select().single();if(r.error)throw r.error;setMsg('Service recovery event added to customer timeline.');}
  else if(name==='Assign'||name==='Start SLA'||name==='Escalate'||name==='Resolve'){const map={Assign:'assign', 'Start SLA':'start', Escalate:'escalate', Resolve:'resolve'};if(key==='guestRelations'){const r=await supabase.rpc('anaira_complaint_action',{p_complaint_id:selected.id,p_action:map[name],p_resolution:name==='Resolve'?(prompt('Resolution','Resolved')||'Resolved'):null,p_csat:null,p_nps:null,p_recovery_cost:null,p_recovery_outcome:null});if(r.error)throw r.error;setExtra(r.data||{});setMsg(`Guest Relations: ${name} completed through canonical complaint runtime.`);}else await updateStatus(name==='Resolve'?'resolved':name==='Escalate'?'escalated':name==='Start SLA'?'in_progress':'assigned');}
  await audit(name,selected?.id,{module:key});await load();
 }catch(e){setError(e.message||String(e))}finally{setBusy(false)}};
 if(!session)return <AppShell><div className="auth-card"><h1>Sign in required</h1><a className="btn primary" href="/login">Open CRM Login</a></div></AppShell>;
 const isProvider=key==='whatsapp'||key==='competitors';
 return <AppShell active={route||'/crm'}><Header eyebrow={cfg.eyebrow} title={cfg.title} subtitle={cfg.subtitle} actions={<><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search live CRM records…"/><button className="btn" onClick={load} disabled={busy}>Refresh</button></>}/>
  <Section title="CRM Property Scope" meta="Super Admin / property-wise live CRM control"><div className="card" style={{display:'flex',gap:12,alignItems:'center',flexWrap:'wrap'}}><label style={{minWidth:320,flex:1}}><span style={{display:'block',fontWeight:700,marginBottom:6}}>Select Property</span><select className="input" value={propertyId} onChange={e=>switchProperty(e.target.value)} disabled={!properties.length}><option value="">Select property</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name} · {p.property_type||'property'}{p.destination?` · ${p.destination}`:''}</option>)}</select></label>{selectedProperty&&<div className="notice" style={{margin:0,flex:1}}><b>{selectedProperty.name}</b><br/>{selectedProperty.property_type||'property'} · {selectedProperty.city||selectedProperty.destination||'—'} · {selectedProperty.active?'Active':'Inactive'}<br/><small>All create/read/action operations on this CRM workspace use tenant {String(selectedProperty.tenant_id||'').slice(0,8)}…</small></div>}<a className="btn" href="/properties">Add / Manage Properties</a></div></Section>
  {error&&<div className="notice error">{error}</div>}{msg&&<div className="notice success">{msg}</div>}
  {isProvider&&<div className="notice">Provider state is explicit. <b>NOT CONNECTED</b> is shown until the relevant provider credentials/webhook are configured; no fake delivery or rate data is generated.</div>}
  <div className="grid kpis"><Kpi label="Records" value={metrics.total} delta="Live Supabase"/><Kpi label="Active / Open" value={metrics.active}/><Kpi label="Value / Revenue" value={money(metrics.value)}/><Kpi label="High Priority / Risk" value={metrics.high}/></div>
  <div className="tabs"><button className={'btn '+(tab==='workspace'?'primary':'')} onClick={()=>setTab('workspace')}>Workspace</button><button className={'btn '+(tab==='results'?'primary':'')} onClick={()=>setTab('results')}>Action Results</button>{(key==='crm'||key==='identity')&&<button className={'btn '+(tab==='duplicates'?'primary':'')} onClick={()=>setTab('duplicates')}>Identity</button>}</div>
  {tab==='workspace'&&<>
   <Section title="Operational Actions" meta="Actions write real records/events; select a row first where required"><div className="actions" style={{display:'flex',gap:8,flexWrap:'wrap'}}>{cfg.actions.map(a=><button key={a} className="btn" disabled={busy} onClick={()=>action(a)}>{busy?'Working…':a}</button>)}</div></Section>
   {key==='corporate'&&selected&&<Section title="Corporate Operational Workspace" meta="Contacts · contracts · negotiated rates · bookings · invoices · credit ledger · renewals"><div className="grid kpis"><Kpi label="Credit Used" value={money(selected.credit_used)}/><Kpi label="Credit Limit" value={money(selected.credit_limit)}/><Kpi label="Contracts" value={corporateData.contracts.length}/><Kpi label="Bookings" value={corporateData.bookings.length}/><Kpi label="Invoices" value={corporateData.invoices.length}/><Kpi label="Revenue" value={money(corporateData.revenue.reduce((n,x)=>n+Number(x.net_amount||0),0))}/></div><div className="grid" style={{gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))'}}><div className="card"><b>Contracts</b>{corporateData.contracts.map(c=><div key={c.id} className="notice">{c.contract_number} · {c.status} · {c.end_date||'—'}</div>)}</div><div className="card"><b>Negotiated Rates</b>{corporateData.rates.map(r=><div key={r.id} className="notice">₹{Number(r.rate||0).toLocaleString('en-IN')} · {r.valid_from} → {r.valid_to||'open'}</div>)}</div><div className="card"><b>Recent Ledger</b>{corporateData.ledger.slice(0,5).map(l=><div key={l.id} className="notice">{l.entry_type} · ₹{Number(l.amount||0).toLocaleString('en-IN')} · balance ₹{Number(l.balance_after||0).toLocaleString('en-IN')}</div>)}</div></div></Section>}
  {key==='workflows'&&<Section title="Visual Workflow Builder" meta="Trigger → conditions → action → delay → goal"><div className="card admin-form"><label><span>Trigger</span><select value={form.trigger_type||'customer.created'} onChange={e=>setForm({...form,trigger_type:e.target.value})}><option>customer.created</option><option>lead.created</option><option>booking.created</option><option>checkin.completed</option><option>checkout.completed</option><option>complaint.created</option><option>review.created</option><option>loyalty.changed</option><option>churn.high</option><option>vip.changed</option><option>payment.completed</option></select></label><label><span>Conditions JSON</span><textarea value={JSON.stringify(form.definition?.conditions||[],null,2)} onChange={e=>{try{setForm({...form,definition:{...(form.definition||{}),conditions:JSON.parse(e.target.value)}})}catch{}}}/></label><label><span>Actions JSON</span><textarea value={JSON.stringify(form.definition?.actions||[{type:'create_task',config:{}}],null,2)} onChange={e=>{try{setForm({...form,definition:{...(form.definition||{}),actions:JSON.parse(e.target.value)}})}catch{}}}/></label><label><span>Goal JSON</span><textarea value={JSON.stringify(form.definition?.goal||{},null,2)} onChange={e=>{try{setForm({...form,definition:{...(form.definition||{}),goal:JSON.parse(e.target.value)}})}catch{}}}/></label><div className="notice">The workflow definition is persisted in <b>crm_workflows.definition</b>; execution uses the existing workflow engine and queue.</div></div></Section>}
   {key==='campaigns'&&<Section title="Campaign Studio Builder" meta="Audience → channel → schedule → delivery → conversion"><div className="card admin-form"><label><span>Audience Segment</span><input placeholder="Segment UUID" value={form.segment_id||''} onChange={e=>setForm({...form,segment_id:e.target.value})}/></label><label><span>Channel</span><select value={form.channel||'whatsapp'} onChange={e=>setForm({...form,channel:e.target.value})}><option>whatsapp</option><option>email</option><option>sms</option></select></label><label><span>Schedule</span><input type="datetime-local" value={form.scheduled_at||''} onChange={e=>setForm({...form,scheduled_at:e.target.value})}/></label><div className="notice">After creating the campaign, select it and use Run Audience/Launch. Delivery remains provider-gated and every queue item is persisted.</div></div></Section>}
   <Section title="Create Live Record" meta={selectedProperty?`Property-scoped write · ${selectedProperty.name}`:"Select a property first"}><div className="card admin-form">{cfg.fields.slice(0,10).map(f=><label key={f}><span>{f.replaceAll('_',' ')}</span>{f==='active'||f==='verified'?<select value={form[f]??true} onChange={e=>setForm({...form,[f]:e.target.value==='true'})}><option value="true">Yes</option><option value="false">No</option></select>:f==='definition'?<textarea value={typeof form[f]==='string'?form[f]:JSON.stringify(form[f]||{},null,2)} onChange={e=>{try{setForm({...form,[f]:JSON.parse(e.target.value)})}catch{setForm({...form,[f]:e.target.value})}}}/>:f==='notes'||f==='resolution'||f==='summary'||f==='recommendation'?<textarea value={form[f]||''} onChange={e=>setForm({...form,[f]:e.target.value})}/>:<input value={form[f]??''} onChange={e=>setForm({...form,[f]:e.target.value})}/>}</label>)}<button className="btn primary" disabled={busy||!tenant||!propertyId} onClick={save}>Create Live Record</button></div></Section>
   <Section title="Live Records" meta={`${filtered.length} records`}><div className="table-wrap"><Table columns={['ID',...cfg.fields.slice(0,7),'Actions']} rows={filtered.map(r=>[String(r.id||'').slice(0,8),...cfg.fields.slice(0,7).map(f=>{const v=r[f];if(v===null||v===undefined||v==='')return '—';if(typeof v==='object')return JSON.stringify(v).slice(0,90);if(f.includes('amount')||f.includes('value')||f.includes('revenue')||f.includes('points'))return money(v);if(['active','verified'].includes(f))return <Pill tone={v?'success':'muted'}>{v?'Yes':'No'}</Pill>;return String(v).slice(0,90)}),<button className="btn" onClick={()=>setSelected(r)}>Select</button>])}/></div></Section>
  </>}
  {tab==='results'&&<Section title="Action Results" meta="Live output from CRM engines"><pre className="card" style={{whiteSpace:'pre-wrap',overflow:'auto'}}>{JSON.stringify(extra,null,2)||'No action result yet.'}</pre></Section>}
  {tab==='duplicates'&&<Section title="Identity Resolution" meta="Duplicate candidates and canonical merge"><Table columns={['Customer','Email','Phone','ID','Action']} rows={(extra.duplicates||[]).map(r=>[r.full_name,r.email||'—',r.phone||'—',r.id,<button className="btn" onClick={()=>setSelected(r)}>Select</button>])}/><div className="notice">For a real merge, select an identity-link record containing the survivor and duplicate IDs, then use Merge Selected. Destructive merge executes the canonical enterprise RPC.</div></Section>}
  {tab==='template'&&<Section title="Message Template" meta="Persist template metadata; provider delivery remains explicit"><div className="card admin-form"><input placeholder="Template key" id="crm-tpl-key"/><select id="crm-tpl-channel"><option>whatsapp</option><option>email</option><option>sms</option></select><textarea placeholder="Template body" id="crm-tpl-body"/><button className="btn primary" onClick={async()=>{const keyv=document.getElementById('crm-tpl-key').value;const ch=document.getElementById('crm-tpl-channel').value;const body=document.getElementById('crm-tpl-body').value;const r=await supabase.from('crm_message_templates').insert({tenant_id:tenant,property_id:propertyId,channel:ch,template_key:keyv,body,variables:[]}).select().single();if(r.error)setError(r.error.message);else{setMsg('Template saved. Provider approval/delivery remains separate.');setTab('workspace');load()}}}>Save Template</button></div></Section>}
  {selected&&key==='campaigns'&&<Section title="Campaign Steps" meta="Persist real campaign sequence steps"><div className="card admin-form"><input id="campaign-step-template" placeholder="Template name"/><select id="campaign-step-channel"><option>whatsapp</option><option>email</option><option>sms</option></select><input id="campaign-step-delay" type="number" min="0" defaultValue="0" placeholder="Delay minutes"/><button className="btn primary" onClick={async()=>{const template=document.getElementById('campaign-step-template').value;const channel=document.getElementById('campaign-step-channel').value;const delay=Number(document.getElementById('campaign-step-delay').value||0);const {data:steps}=await supabase.from('crm_campaign_steps').select('step_order').eq('campaign_id',selected.id).order('step_order',{ascending:false}).limit(1);const next=(steps?.[0]?.step_order||0)+1;const r=await supabase.from('crm_campaign_steps').insert({tenant_id:tenant,property_id:propertyId,campaign_id:selected.id,step_order:next,channel,template_name:template,delay_minutes:delay,content:{source:'campaign-studio'}}).select().single();if(r.error)setError(r.error.message);else setMsg('Campaign step added and persisted.')}}>Add Step</button></div></Section>}
  {selected&&<Section title="Selected Record" meta="Actions operate on this record"><pre style={{whiteSpace:'pre-wrap',maxHeight:240,overflow:'auto'}}>{JSON.stringify(selected,null,2)}</pre></Section>}
 </AppShell>
}
