'use client';
import {useEffect,useMemo,useState} from 'react';
import {AppShell,Header,Section,Table,Pill} from './components';
import {supabase} from '../lib/supabase';

const labelize=k=>k.replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
const inputType=k=>{if(/(amount|price|rate|value|percent|points|count|number|confidence|credit|revenue|total|tax|discount|commission|score|priority_order)/i.test(k))return 'number';if(/(date|at|time)$/i.test(k)||k==='scheduled_at'||k==='due_at'||k==='occurred_at'||k==='valid_until'||k==='stay_date')return k.includes('at')||k.includes('time')?'datetime-local':'date';if(/email/i.test(k))return 'email';if(/(description|notes|comment|resolution|definition|body|summary|recommendation|eligibility|factors|payload|package_definition|metadata|address)/i.test(k))return 'textarea';return 'text'};
const isBool=k=>/^(active|vip|published|verified|preferred|allowed|approved|enabled|no_show|production_rls_verified|primary_contact|marketplace_visible|hotel_booking_enabled|food_ordering_enabled|restaurant_reservation_enabled|delivery_enabled|pickup_enabled|dine_in_enabled)$/i.test(k);
const hidden=['id','created_at','updated_at','tenant_id','restaurant_id','owner_id','actor_id','assigned_to'];
function normalize(v,k){if(v===null||v===undefined)return '';if(typeof v==='object')return JSON.stringify(v,null,2);if(typeof v==='boolean')return v;return v}
function payloadFrom(form,fields){const p={};for(const f of fields){if(hidden.includes(f))continue;let v=form[f];if(v==='')v=null;if(isBool(f))v=!!v;if(inputType(f)==='number'&&v!==null)v=Number(v);if(inputType(f)==='date'&&v instanceof Date) v=v.toISOString().slice(0,10);if(inputType(f)==='textarea'&&typeof v==='string'&&/^(\[|\{)/.test(v.trim())){try{v=JSON.parse(v)}catch{}}p[f]=v}return p}
function Field({name,value,onChange}){const t=inputType(name);if(isBool(name))return <label className="check-field"><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/><span>{labelize(name)}</span></label>;return <label><span>{labelize(name)}</span>{t==='textarea'?<textarea rows={3} value={value??''} onChange={e=>onChange(e.target.value)}/>:<input type={t} value={value??''} onChange={e=>onChange(e.target.value)}/>}</label>}
export default function CrudPage({config}){
 const source=config.source; const fields=source?.editable||source?.fields||[];
 const [session,setSession]=useState(undefined),[profile,setProfile]=useState(null),[properties,setProperties]=useState([]),[rid,setRid]=useState(''),[rows,setRows]=useState([]),[editing,setEditing]=useState(null),[form,setForm]=useState({}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState('');
 useEffect(()=>{if(!supabase){setSession(null);return}let alive=true;(async()=>{const {data}=await supabase.auth.getSession();if(alive)setSession(data.session);if(data.session){const {data:p}=await supabase.from('anaira_my_profile').select('restaurant_id,is_super_admin,role,full_name').eq('id',data.session.user.id).maybeSingle();if(alive){setProfile(p||null);if(p?.is_super_admin){const {data:rs}=await supabase.from('restaurants').select('id,name,status').order('name');setProperties(rs||[])}else setRid(p?.restaurant_id||'')}}})();return()=>{alive=false}},[]);
 useEffect(()=>{if(profile?.is_super_admin&&properties.length&&!rid)setRid(properties[0].id)},[profile,properties,rid]);
 const load=async()=>{if(!source||!supabase||!session)return;setLoading(true);setError('');let q=supabase.from(source.table).select('*').order(source.orderBy||'created_at',{ascending:false}).limit(200);if(source.tenantColumn&&rid)q=q.eq(source.tenantColumn,rid);const r=await q;if(r.error){setError(r.error.message);setRows([])}else setRows(r.data||[]);setLoading(false)};
 useEffect(()=>{load()},[source?.table,source?.orderBy,source?.tenantColumn,rid,session]);
 const shown=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return rows;return rows.filter(r=>source.fields.some(f=>String(r[f]??'').toLowerCase().includes(q)))},[rows,query,source]);
 const startNew=()=>{setEditing(null);const x={};fields.forEach(f=>{if(isBool(f))x[f]=false;else if(f==='status')x[f]='open';else x[f]=''});setForm(x);setError('')};
 const editRow=r=>{setEditing(r.id);const x={};fields.forEach(f=>x[f]=normalize(r[f],f));setForm(x);setError('');window.scrollTo({top:0,behavior:'smooth'})};
 const save=async e=>{e.preventDefault();if(!session)return;setSaving(true);setError('');let p=payloadFrom(form,fields);if(source.tenantColumn&&!p[source.tenantColumn]&&rid)p[source.tenantColumn]=rid; if(source.autoDefaults)Object.assign(p,source.autoDefaults);let q;if(editing)q=await supabase.from(source.table).update(p).eq('id',editing);else q=await supabase.from(source.table).insert(p);if(q.error)setError(q.error.message);else{setForm({});setEditing(null);await load()}setSaving(false)};
 const del=async r=>{if(!confirm(`Delete ${source.title||source.table} record?`))return;setSaving(true);const q=await supabase.from(source.table).delete().eq('id',r.id);if(q.error)setError(q.error.message);else await load();setSaving(false)};
 if(!source)return <AppShell><div className="notice error">No data source configured.</div></AppShell>;
 if(!supabase)return <AppShell><div className="auth-card"><h1>Supabase is not configured</h1></div></AppShell>;
 if(session===undefined)return <AppShell><div className="notice">Connecting to Supabase Auth…</div></AppShell>;
 if(!session)return <AppShell><div className="auth-card"><h1>Sign in required</h1><a className="btn primary" href="/login">Open CRM Login</a></div></AppShell>;
 return <AppShell active={config.active}><Header eyebrow={config.eyebrow||'ANAIRA CRM'} title={config.title} subtitle={config.subtitle} actions={<><button className="btn primary" onClick={startNew}>+ New Record</button>{profile?.is_super_admin&&source.tenantColumn&&<select value={rid} onChange={e=>setRid(e.target.value)} style={{padding:'10px',borderRadius:10}}><option value="">Select property</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}</>}/>
 <div className="live-bar"><span className="status-dot ok"></span><b>LIVE SUPABASE CRUD</b><span>{source.table}</span><span>{shown.length} records</span></div>
 {error&&<div className="notice error">{error}</div>}
 <Section title={editing?'Edit Record':'Create / Edit'} meta={editing?'Editing existing record':'Use the form below to create a live database record'}><form className="card admin-form" onSubmit={save}>{fields.filter(f=>!hidden.includes(f)).map(f=><Field key={f} name={f} value={form[f]} onChange={v=>setForm(x=>({...x,[f]:v}))}/>)}<div className="full"><button className="btn primary" disabled={saving}>{saving?'Saving…':editing?'Update Record':'Create Record'}</button>{editing&&<button type="button" className="btn" onClick={()=>{setEditing(null);setForm({})}}>Cancel</button>}</div></form></Section>
 <Section title={source.title||'Live Records'} meta={loading?'Syncing…':`${shown.length} of ${rows.length} records`}><div className="filters"><input placeholder="Search live records…" value={query} onChange={e=>setQuery(e.target.value)}/><button className="btn" onClick={load}>Refresh</button></div>{loading?<div className="notice">Loading…</div>:!shown.length?<div className="notice">No records found. Use <b>+ New Record</b> to create one.</div>:<Table columns={[...source.headers,'Actions']} rows={shown.map(r=>[...source.fields.map(f=>{const v=r[f];if(v===null||v===undefined||v==='')return '—';if(typeof v==='boolean')return <Pill tone={v?'success':'muted'}>{v?'Yes':'No'}</Pill>;if(typeof v==='object')return JSON.stringify(v);return String(v).slice(0,100)}),<><button className="btn" onClick={()=>editRow(r)}>Edit</button> <button className="btn" onClick={()=>del(r)} disabled={saving}>Delete</button></>])}/>}</Section>
 <Section title="Module Contract" meta="Real data ownership"><div className="notice">This page performs authenticated Supabase CRUD against <b>{source.table}</b>. Tenant scoping is enforced by RLS; tenant identifiers are automatically attached where this module uses <b>{source.tenantColumn}</b>. Cross-plugin ownership remains unchanged.</div></Section>
 </AppShell>
}
