'use client';
import {useEffect,useMemo,useState} from 'react';
import {AppShell,Header,Section,Kpi,Pill} from './components';
import {supabase} from '../lib/supabase';
const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:0})}`;
const STAGES=['new','contacted','qualified','opportunity','quote','negotiation','won','lost'];
async function ctx(){const {data:{session}}=await supabase.auth.getSession();if(!session)return {session:null,tenant:''};const {data:p}=await supabase.from('anaira_my_profile').select('restaurant_id').eq('id',session.user.id).maybeSingle();return {session,tenant:p?.restaurant_id||''}}
export default function LeadsSalesWorkspace(){
 const [session,setSession]=useState(null),[tenant,setTenant]=useState(''),[properties,setProperties]=useState([]),[propertyId,setPropertyId]=useState(''),[leads,setLeads]=useState([]),[opps,setOpps]=useState([]),[quotes,setQuotes]=useState([]),[selected,setSelected]=useState(null),[msg,setMsg]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[q,setQ]=useState(''),[analytics,setAnalytics]=useState(null);
 const property=properties.find(x=>x.id===propertyId);
 const load=async()=>{if(!tenant||!propertyId)return;setBusy(true);setError('');const [l,o,qt]=await Promise.all([supabase.from('crm_leads').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('created_at',{ascending:false}).limit(500),supabase.from('crm_opportunities').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('updated_at',{ascending:false}).limit(500),supabase.from('crm_quotes').select('*').eq('tenant_id',tenant).eq('property_id',propertyId).order('created_at',{ascending:false}).limit(500)]);if(l.error||o.error||qt.error)setError(l.error?.message||o.error?.message||qt.error?.message||'Unable to load sales data');setLeads(l.data||[]);setOpps(o.data||[]);setQuotes(qt.data||[]);setBusy(false)};
 useEffect(()=>{(async()=>{const c=await ctx();setSession(c.session);if(!c.session)return;const r=await supabase.from('anaira_hospitality_properties_master').select('id,tenant_id,name,property_type,city,active').eq('active',true).order('name');if(r.error){setError(r.error.message);return}setProperties(r.data||[]);const pick=(r.data||[]).find(x=>x.tenant_id===c.tenant)||(r.data||[])[0];if(pick){setPropertyId(pick.id);setTenant(pick.tenant_id)}})()},[]);useEffect(()=>{load()},[tenant,propertyId]);
 const filtered=useMemo(()=>{const x=q.toLowerCase().trim();return x?leads.filter(r=>JSON.stringify(r).toLowerCase().includes(x)):leads},[leads,q]);
 const call=async(name,args)=>{setBusy(true);setError('');setMsg('');try{const {data,error:e}=await supabase.rpc(name,args);if(e)throw e;setMsg(`${name}: completed`);await load();return data}catch(e){setError(e.message||String(e))}finally{setBusy(false)}};
 const score=()=>selected?.kind==='lead'&&call('anaira_score_lead',{p_lead_id:selected.id});
 const assign=()=>{const id=window.prompt('Owner user UUID');if(id)call('anaira_assign_lead',{p_lead_id:selected.id,p_owner_id:id})};
 const opportunity=()=>selected?.kind==='lead'&&call('anaira_create_opportunity_from_lead',{p_lead_id:selected.id,p_name:`Opportunity - ${selected.lead_type||'Lead'}`});
 const oppStage=(id,stage)=>call('anaira_opportunity_transition',{p_opportunity_id:id,p_to_stage:stage,p_reason:'Kanban transition'});
 const forecast=()=>call('anaira_generate_sales_forecast',{p_tenant_id:tenant,p_property_id:propertyId});
 const analyticsSummary=useMemo(()=>{const qualified=leads.filter(x=>x.stage==='qualified').length;const won=opps.filter(x=>(x.stage||x.status)==='won');const accepted=quotes.filter(x=>x.status==='accepted').length;return {leadQualified:leads.length?Math.round(qualified*10000/leads.length)/100:0,oppWin:opps.length?Math.round(won.length*10000/opps.length)/100:0,quoteAccept:quotes.length?Math.round(accepted*10000/quotes.length)/100:0,wonValue:won.reduce((n,x)=>n+Number(x.value||0),0)}} , [leads,opps,quotes]);
 const createQuote=id=>call('anaira_create_quote_from_opportunity',{p_opportunity_id:id});
 const analyticsLoad=async()=>{setAnalytics(analyticsSummary);};
 const cards=STAGES.map(s=>({stage:s,items:opps.filter(o=>(o.stage||o.status||'new')===s)}));
 return <AppShell><Header eyebrow="SALES CRM" title="Leads & Sales" subtitle="Lead scoring → ownership → opportunity → quote → negotiation → won/lost → revenue attribution → forecast" actions={<><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search leads…"/><button className="btn" onClick={load} disabled={busy}>Refresh</button></>}/>
 <Section title="Property Scope"><div className="card"><select value={propertyId} onChange={e=>{const p=properties.find(x=>x.id===e.target.value);setPropertyId(e.target.value);setTenant(p?.tenant_id||tenant)}}><option value="">Select property</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name} · {p.property_type||'property'}</option>)}</select>{property&&<span className="notice">{property.name} · {property.city||'—'}</span>}</div></Section>
 {error&&<div className="notice error">{error}</div>}{msg&&<div className="notice success">{msg}</div>}
 <div className="grid kpis"><Kpi label="Leads" value={leads.length}/><Kpi label="Open Pipeline" value={money(opps.filter(o=>!['won','lost'].includes(o.stage||o.status)).reduce((n,o)=>n+Number(o.value||0),0))}/><Kpi label="Weighted" value={money(opps.filter(o=>!['won','lost'].includes(o.stage||o.status)).reduce((n,o)=>n+Number(o.weighted_value||Number(o.value||0)*Number(o.probability||0)/100),0))}/><Kpi label="Quotes" value={quotes.length}/></div>
 <Section title="Lead Inbox" meta="Real lead scoring, owner assignment, lifecycle and opportunity creation"><div className="card" style={{overflowX:'auto'}}><table><thead><tr><th>Lead</th><th>Stage</th><th>Score</th><th>Value</th><th>Owner</th><th>Follow-up</th><th>Actions</th></tr></thead><tbody>{filtered.map(l=><tr key={l.id}><td>{l.lead_type||l.name||l.id.slice(0,8)}</td><td><Pill>{l.stage}</Pill></td><td>{Number(l.lead_score||0)}</td><td>{money(l.estimated_value)}</td><td>{l.owner_id?String(l.owner_id).slice(0,8):'Unassigned'}</td><td>{l.next_follow_up?new Date(l.next_follow_up).toLocaleString('en-IN'): '—'}</td><td><button className="btn" onClick={()=>setSelected({...l,kind:'lead'})}>Select</button></td></tr>)}</tbody></table></div></Section>
 {selected?.kind==='lead'&&<Section title="Selected Lead Actions"><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn" onClick={score} disabled={busy}>Recalculate Score</button><button className="btn" onClick={assign} disabled={busy}>Assign Owner</button><button className="btn" onClick={opportunity} disabled={busy}>Create Opportunity</button><button className="btn" onClick={()=>call('anaira_lead_transition',{p_lead_id:selected.id,p_to_stage:'qualified',p_reason:'Qualified in Sales CRM'})} disabled={busy}>Qualify</button><button className="btn" onClick={()=>call('anaira_lead_transition',{p_lead_id:selected.id,p_to_stage:'lost',p_reason:window.prompt('Loss reason')||'Lost'})} disabled={busy}>Mark Lost</button></div></Section>}
 <Section title="Sales Pipeline / Kanban" meta="Stage transitions persist to opportunity history and Customer 360 timeline"><div className="grid" style={{gridTemplateColumns:'repeat(4,minmax(180px,1fr))'}}>{cards.map(c=><div className="card" key={c.stage} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/opportunity-id');if(id)oppStage(id,c.stage)}}><strong>{c.stage.toUpperCase()}</strong><div style={{marginTop:10}}>{c.items.map(o=><div className="card" key={o.id} style={{marginBottom:8}}><div>{o.name||o.id.slice(0,8)}</div><b>{money(o.value)}</b><div>Probability {Number(o.probability||0)}%</div><div draggable onDragStart={e=>e.dataTransfer.setData('text/opportunity-id',o.id)} style={{cursor:'grab'}}><small>Owner: {o.owner_id?String(o.owner_id).slice(0,8):'Unassigned'} · Close: {o.expected_close_at?new Date(o.expected_close_at).toLocaleDateString('en-IN'):'—'}</small></div><button className="btn" onClick={()=>createQuote(o.id)} disabled={busy}>Create / Link Quote</button></div>)}</div></div>)}</div></Section>
 <Section title="Sales Forecast & Conversion Analytics"><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="btn primary" onClick={forecast} disabled={busy}>Generate Forecast Snapshot</button><button className="btn" onClick={analyticsLoad} disabled={busy}>Refresh Conversion Analytics</button></div>{analytics&&<div className="grid kpis" style={{marginTop:12}}><Kpi label="Lead→Qualified" value={`${analytics.leadQualified||0}%`}/><Kpi label="Opportunity Win" value={`${analytics.oppWin||0}%`}/><Kpi label="Quote Accept" value={`${analytics.quoteAccept||0}%`}/><Kpi label="Won Revenue" value={money(analytics.wonValue)}/></div>}<span className="notice">Forecast uses live opportunity value × probability plus won revenue. Kanban cards support drag/drop with persisted stage transition.</span></Section>
 </AppShell>
}
