'use client';
import {useEffect,useState} from 'react';
import {AppShell,Header,Kpi,Section,Table,Progress,ModuleCards} from './components';
import {supabase} from '../lib/supabase';
const modules=[['◉','Customer 360','Unified profile, value, preferences and history','/customer-360'],['⌂','Hotel Guest CRM','Bookings, stays, requests and VIP service','/hotel-guest-crm'],['♨','Restaurant CRM','Visits, spend, tables and food preferences','/restaurant'],['◆','Leads & Sales','Pipeline, quotations, tasks and conversion','/leads'],['▣','Corporate CRM','Companies, contracts, credit and negotiated rates','/corporate'],['♢','Partners','Agents, OTAs, planners and commissions','/partners'],['★','Loyalty','Tiers, points, rewards and referrals','/loyalty'],['◇','Offers','Coupons, eligibility and redemption','/marketing'],['✉','Campaigns','WhatsApp, SMS, email and journeys','/campaigns'],['◌','WhatsApp CRM','Templates, delivery and conversations','/integrations'],['⚠','Guest Relations','Complaints, SLA and service recovery','/guest-relations'],['₹','Revenue Manager','Dynamic rates, forecasts and demand','/revenue'],['▤','Analytics','LTV, retention, campaign and revenue BI','/analytics'],['✦','Event CRM','Wedding, banquet and corporate events','/events'],['✧','AI Insights','Next-best-action and churn intelligence','/ai'],['⚙','Integrations','PMS, POS, OTA and accounting connections','/integrations']];
export default function Dashboard(){
 const [session,setSession]=useState(undefined),[stats,setStats]=useState(null),[error,setError]=useState('');
 useEffect(()=>{if(!supabase){setSession(null);return}let mounted=true;let subscription;(async()=>{const {data}=await supabase.auth.getSession();if(mounted)setSession(data.session);const res=supabase.auth.onAuthStateChange((_e,s)=>mounted&&setSession(s));subscription=res.data.subscription})();return()=>{mounted=false;subscription?.unsubscribe()}},[]);
 useEffect(()=>{if(!session||!supabase)return;let mounted=true;(async()=>{const tables=['crm_customers','crm_guest_stays','crm_restaurant_visits','crm_leads','crm_complaints'];const results=await Promise.all(tables.map(t=>supabase.from(t).select('*',{count:'exact',head:true})));const bad=results.find(r=>r.error);if(bad){setError(bad.error.message);return}if(mounted)setStats(Object.fromEntries(tables.map((t,i)=>[t,results[i].count||0])));})();return()=>{mounted=false}},[session]);
 if(!supabase)return <AppShell active="/"><div className="auth-card"><h1>Supabase is not configured</h1><p>Add your Supabase URL and publishable/anon key to <b>.env.local</b>, then restart.</p></div></AppShell>;
 if(session===undefined)return <AppShell active="/"><div className="notice">Connecting to Supabase Auth…</div></AppShell>;
 if(!session)return <AppShell active="/"><div className="auth-card"><div className="eyebrow">ANAIRA CRM</div><h1>CRM Command Center</h1><p>Sign in to load live CRM data from Supabase.</p><a className="btn primary" href="/login">Sign in</a></div></AppShell>;
 const n=t=>stats?.[t]??0;
 return <AppShell active="/"><Header eyebrow="ANAIRA ENTERPRISE CRM" title="Hotel & Restaurant Command Center" subtitle="Live Customer 360, guest relationships, sales, loyalty, marketing and revenue intelligence powered by Supabase." actions={<><a className="btn" href="/analytics">Reports</a><a className="btn primary" href="/customer-360">Customer 360</a></>}/><div className="live-bar"><span className="status-dot ok"></span><b>LIVE SUPABASE</b><span>Authenticated</span><span>CRM database connected</span></div><div className="grid kpis"><Kpi label="Customers" value={n('crm_customers').toLocaleString('en-IN')} delta="crm_customers"/><Kpi label="Guest Stays" value={n('crm_guest_stays').toLocaleString('en-IN')} delta="crm_guest_stays"/><Kpi label="Restaurant Visits" value={n('crm_restaurant_visits').toLocaleString('en-IN')} delta="crm_restaurant_visits"/><Kpi label="Open Leads" value={n('crm_leads').toLocaleString('en-IN')} delta="crm_leads"/><Kpi label="Complaints" value={n('crm_complaints').toLocaleString('en-IN')} delta="crm_complaints"/></div>{error&&<div className="notice error">{error}</div>}<Section title="Live CRM Snapshot" meta="Canonical Supabase tables"><Table columns={['Module','Table','Live Records','Open in CRM']} rows={[["Customer 360",'crm_customers',n('crm_customers'),<a href="/customer-360">Open</a>],["Hotel Guest CRM",'crm_guest_stays',n('crm_guest_stays'),<a href="/hotel-guest-crm">Open</a>],["Restaurant CRM",'crm_restaurant_visits',n('crm_restaurant_visits'),<a href="/restaurant">Open</a>],["Sales",'crm_leads',n('crm_leads'),<a href="/leads">Open</a>],["Guest Relations",'crm_complaints',n('crm_complaints'),<a href="/complaints">Open</a>]]}/></Section><Section title="Data Health" meta="Connectivity"><Progress label="Supabase connection" value={100} display="Connected"/><Progress label="Authenticated RLS" value={100} display="Protected"/><Progress label="Demo writes" value={0} display="None"/></Section><section className="section"><div className="section-head"><h2>Enterprise Modules</h2><span>Each module reads its own canonical CRM table</span></div><ModuleCards items={modules}/></section></AppShell>
}
