'use client';
import {useEffect,useMemo,useState} from 'react';
import {AppShell,Header,Section,Table,Pill,Kpi} from './components';
import {supabase} from '../lib/supabase';
import {pluginCatalog} from './pluginCatalog';
import {getPluginDefinition} from './pluginEngine';

const labelize=k=>k.replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
const val=v=>{if(v===null||v===undefined||v==='')return '—';if(typeof v==='boolean')return v?'Yes':'No';if(typeof v==='object')return JSON.stringify(v);return String(v).slice(0,140)};
const inputType=(f,v)=>{if(typeof v==='boolean'||['active','published','vip'].includes(f))return 'boolean';if(['date','stay_date','reservation_date','check_in_date','check_out_date','check_in','check_out','forecast_date'].includes(f))return 'date';if(f.endsWith('_at')||f==='scheduled_at'||f==='reservation_time')return f==='reservation_time'?'time':'datetime-local';if(['amount','total','total_amount','estimated_value','price','rate','discount_value','credit_limit','commission_percent','confidence','score','recommended_rate','current_rate','occupancy_pct','horizon_days','expected_guests'].includes(f)||f.includes('count')||f.includes('points')||f.includes('revenue')||f.includes('spend'))return 'number';return 'text'};
function Field({field,value,onChange}){const type=inputType(field,value);if(type==='boolean')return <label className="check-field"><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/><span>{labelize(field)}</span></label>;return <label><span>{labelize(field)}</span><input type={type} value={value??''} onChange={e=>onChange(type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)}/></label>}

function writeDefaults(pluginKey,tenantId,payload){
 const p={...payload};
 if(['crm','customer_360','customer_intelligence','hotel_guest_crm','restaurant_crm','customer_ltv','lead_management','followups','corporate_crm','partner_crm','loyalty','offers_coupons','marketing_automation','whatsapp_crm','reputation','guest_relations','segmentation','churn','vip','revenue_management','upselling','cross_selling','event_crm','omnichannel_timeline','consent_privacy','relationship_manager','advanced_analytics','ai_crm','revenue_forecasting','competitor_intelligence','seo-system','ai-review-system','crm'].includes(pluginKey))p.tenant_id=p.tenant_id||tenantId;
 if(['hotel-management-suite','hotel-pms','restaurant-reservation','food-delivery','restaurant-store','anaira-pos','channel-manager'].includes(pluginKey))p.restaurant_id=p.restaurant_id||tenantId;
 if(pluginKey==='anaira-pos'){p.business_id=p.business_id||tenantId;p.restaurant_id=tenantId;}
 if(pluginKey==='hotel-booking'&&!p.idempotency_key)p.idempotency_key=`plugin:${tenantId}:${Date.now()}:${Math.random().toString(36).slice(2)}`;
 if(pluginKey==='restaurant-reservation'&&!p.reservation_code)p.reservation_code=`RES-${Date.now()}`;
 if(pluginKey==='omnichannel_timeline'&&!p.source_system)p.source_system='anaira-crm';
 if(pluginKey==='revenue_forecasting')p.property_id=p.property_id||tenantId;
 return p;
}
function rowKey(row,def){const out={};for(const k of def.primaryKey||['id'])out[k]=row?.[k];return out}

const promptMap={
 issue_points:['amount','Points calculation amount'], redeem_reward:['rewardId','Reward ID'], assign_owner:['staffId','Staff User ID'], assign_manager:['staffId','Staff User ID'], add_amenity:['amenity','Amenity'], override_rate:['rate','Override Rate'], room_move:['roomId','Target Room ID'], check_in:['roomId','Check-in Room ID'], record_deposit:['amount','Deposit Amount'], create_guest_request:['requestType','Request Type'], export_request:['requestReason','Export Request Note'], delete_request:['requestReason','Deletion Request Note'], generate_forecast:['horizonDays','Forecast Horizon Days']
};

export default function PluginPage({pluginKey}){
 const plugin=pluginCatalog.find(x=>x.key===pluginKey),def=getPluginDefinition(pluginKey);
 const [session,setSession]=useState(undefined),[profile,setProfile]=useState(null),[rid,setRid]=useState(''),[properties,setProperties]=useState([]),[enabled,setEnabled]=useState(false),[settings,setSettings]=useState({}),[rows,setRows]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState({}),[tab,setTab]=useState('overview'),[search,setSearch]=useState(''),[error,setError]=useState(''),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[actionBusy,setActionBusy]=useState(''),[actionResult,setActionResult]=useState(null);
 const isSuper=profile?.is_super_admin===true||profile?.role==='super_admin';
 const load=async()=>{if(!rid||!def?.dataTable||!enabled)return;setLoading(true);setError('');const cols=[...new Set(['id',...(def.primaryKey||[]),...(def.fields||[])])];let q=supabase.from(def.dataTable).select(cols.join(',')).limit(250);if(def.tenantColumn)q=q.eq(def.tenantColumn,rid);const r=await q;if(r.error){setError(r.error.message);setRows([])}else setRows(r.data||[]);setLoading(false)};
 const loadState=async()=>{if(!rid||!pluginKey)return;const [a,b]=await Promise.all([supabase.from('restaurant_plugins').select('enabled,config').eq('restaurant_id',rid).eq('plugin_code',pluginKey).maybeSingle(),supabase.from('plugin_settings').select('config,custom_settings').eq('restaurant_id',rid).eq('plugin_code',pluginKey).maybeSingle()]);if(a.error)setError(a.error.message);const cfg={...(a.data?.config?.settings||{}),...(b.data?.config?.settings||{}),...(b.data?.custom_settings||{})};setEnabled(a.data?.enabled===true);setSettings(cfg)};
 useEffect(()=>{let alive=true;(async()=>{if(!supabase){setSession(null);return}const {data}=await supabase.auth.getSession();if(!alive)return;setSession(data.session);if(!data.session)return;const p=await supabase.from('anaira_my_profile').select('restaurant_id,is_super_admin,role').eq('id',data.session.user.id).maybeSingle();if(!alive)return;setProfile(p.data||null);if(p.data?.is_super_admin===true||p.data?.role==='super_admin'){const q=await supabase.from('restaurants').select('id,name,status').order('name');setProperties(q.data||[])}else setRid(p.data?.restaurant_id||'')})();return()=>{alive=false}},[]);
 useEffect(()=>{if(!rid)return;loadState()},[rid,pluginKey]);
 useEffect(()=>{load()},[rid,enabled,pluginKey]);
 const filtered=useMemo(()=>{const s=search.trim().toLowerCase();if(!s)return rows;return rows.filter(r=>(def?.fields||[]).some(f=>String(r[f]??'').toLowerCase().includes(s)))},[rows,search,def]);
 const headers=[...(def?.fields||[]).map(labelize),'Actions'];
 const toggle=async()=>{if(!rid){setError('Select a property first.');return}const next=!enabled;const payload={restaurant_id:rid,plugin_code:pluginKey,plugin_slug:pluginKey,display_name:plugin.name,category:plugin.category,description:plugin.description,feature_kind:'feature',enabled:next,activated_by:session.user.id,activated_at:next?new Date().toISOString():null,disabled_at:next?null:new Date().toISOString(),config:{schema_version:1,settings}};let q=await supabase.from('restaurant_plugins').upsert(payload,{onConflict:'restaurant_id,plugin_code'});if(q.error){setError(q.error.message);return}if(next&&['hotel-booking','hotel-pms','channel-manager'].includes(pluginKey)){const h={restaurant_id:rid,plugin_code:'hotel-management-suite',plugin_slug:'hotel-management-suite',display_name:'Anaira Hotel Management System',category:'Hotel',description:'Canonical hotel master data and operations',feature_kind:'feature',enabled:true,activated_by:session.user.id,activated_at:new Date().toISOString(),disabled_at:null,config:{schema_version:1,settings:{}}};const hr=await supabase.from('restaurant_plugins').upsert(h,{onConflict:'restaurant_id,plugin_code'});if(hr.error){setError(hr.error.message);return}}setEnabled(next)};
 const save=async()=>{if(!rid||!def?.dataTable){setError('No tenant/data owner configured.');return}setSaving(true);setError('');setMsg('');let payload=writeDefaults(pluginKey,rid,{...form});for(const k of Object.keys(payload))if(payload[k]==='')delete payload[k];if(selected){payload=writeDefaults(pluginKey,rid,{...form});for(const k of def.primaryKey||['id'])delete payload[k];let q=supabase.from(def.dataTable).update(payload);q=q.eq(def.tenantColumn,rid);for(const k of def.primaryKey||['id'])q=q.eq(k,selected[k]);const r=await q; if(r.error)setError(r.error.message);else{setMsg('Record updated successfully.');setSelected(null);setForm({});setTab('records');await load()}}
 else{const r=await supabase.from(def.dataTable).insert(payload);if(r.error)setError(r.error.message);else{setMsg('Record created successfully.');setForm({});setTab('records');await load()}}setSaving(false)};
 const remove=async(row)=>{if(!row||!confirm('Delete this record permanently?'))return;let q=supabase.from(def.dataTable).delete();if(def.tenantColumn)q=q.eq(def.tenantColumn,rid);for(const k of def.primaryKey||['id'])q=q.eq(k,row[k]);const r=await q;if(r.error)setError(r.error.message);else{setMsg('Record deleted.');await load()}};
 const edit=row=>{setSelected(row);setForm(Object.fromEntries((def.createFields||[]).map(f=>[f,row[f]??''])));setTab('create')};
 const runAction=async(action,row=null)=>{setError('');setMsg('');setActionResult(null);setActionBusy(action.id);let payload={};const pm=promptMap[action.id]||({check_availability:['checkIn','Check-in (YYYY-MM-DD)'],create_hold:['roomTypeId','Room Type ID']});if(pm){const v=window.prompt(pm[1],action.id==='generate_forecast'?'30':'');if(v===null){setActionBusy('');return}payload[pm[0]]=action.id==='generate_forecast'||action.id==='issue_points'||action.id==='record_deposit'||action.id==='override_rate'?Number(v):v}
 try{const res=await fetch(`/api/plugins/${pluginKey}/action`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${session.access_token}`},body:JSON.stringify({pluginKey,tenantId:rid,actionId:action.id,recordKey:row?rowKey(row,def):null,payload})});const j=await res.json();if(!res.ok||j.ok===false)throw new Error(j.error||'Plugin action failed');setActionResult(j.result||j);if(j.navigateTo)location.href=j.navigateTo;else setMsg(`${action.name} completed.`);await load()}catch(e){setError(e.message)}finally{setActionBusy('')}};
 const exportCsv=()=>{const cols=def?.fields||[];const esc=x=>`"${String(x??'').replaceAll('"','""')}"`;const csv=[cols.map(esc).join(','),...filtered.map(r=>cols.map(f=>esc(r[f])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`${pluginKey}-records.csv`;a.click();URL.revokeObjectURL(a.href)};
 if(!plugin||!def)return <AppShell><div className="notice error">Plugin manifest not found.</div></AppShell>;
 if(session===undefined)return <AppShell><div className="notice">Connecting to Supabase Auth…</div></AppShell>;
 if(!session)return <AppShell><div className="auth-card"><h1>Sign in required</h1><a className="btn primary" href="/login">Open CRM Login</a></div></AppShell>;
 return <AppShell active={def.route}>
  <Header eyebrow={def.category} title={def.name} subtitle={def.description} actions={<><select value={rid} onChange={e=>setRid(e.target.value)} disabled={!isSuper} style={{minWidth:220,padding:10,borderRadius:10}}><option value="">{isSuper?'Select property':'Current property'}</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className={'btn '+(enabled?'danger':'primary')} onClick={toggle}>{enabled?'Disable':'Enable'} Plugin</button><a className="btn" href={`/plugins/${pluginKey}/settings`}>Settings</a></>}/>
  {!enabled?<Section title="Plugin disabled" meta="Runtime is gated by tenant activation"><div className="notice">This plugin is disabled for the selected property. No plugin runtime reads or writes are executed.</div></Section>:<>
   <div className="tabs" style={{display:'flex',gap:7,flexWrap:'wrap',marginBottom:14}}>{[['overview','Dashboard'],['records','Records'],['create',selected?'Edit Record':'Create Record'],['workflow','Workflow'],['analytics','Analytics']].map(([k,l])=><button key={k} className={'btn '+(tab===k?'primary':'')} onClick={()=>setTab(k)}>{l}</button>)}</div>
   {error&&<div className="notice error">{error}</div>}{msg&&<div className="notice">{msg}</div>}{actionResult&&<Section title="Action Result" meta="Live result"><pre className="card" style={{whiteSpace:'pre-wrap',overflow:'auto'}}>{JSON.stringify(actionResult,null,2)}</pre></Section>}
   {tab==='overview'&&<><div className="grid kpis"><Kpi label="Live Records" value={rows.length} delta={loading?'Loading…':def.dataTable}/><Kpi label="Search Results" value={filtered.length} delta="Current filter"/><Kpi label="Settings" value={def.settingsSchema.length} delta="Effective configuration"/><Kpi label="Domain Actions" value={def.actions.length} delta="Executable / provider-gated"/></div><Section title="Domain Workflow"><div className="mini-grid">{def.actions.map(a=><div className="mini" key={a.id}><b>{a.name}</b><span>{a.kind==='provider'?'Real provider adapter; credentials/config required when applicable.':a.kind==='navigate'?'Opens canonical module.':'Executes through the plugin action API.'}</span></div>)}</div></Section><Section title="Runtime Configuration"><div className="mini-grid"><div className="mini"><span className="kpi-label">Data Owner</span><b>{def.dataTable}</b></div><div className="mini"><span className="kpi-label">Tenant Key</span><b>{def.tenantColumn||'None'}</b></div><div className="mini"><span className="kpi-label">Primary Key</span><b>{def.primaryKey.join(', ')}</b></div><div className="mini"><span className="kpi-label">Settings Loaded</span><b>{Object.keys(settings).length}</b></div></div></Section></>}
   {tab==='records'&&<Section title="Live Records" meta={`${filtered.length} shown`}><div style={{display:'flex',gap:8,marginBottom:12,flexWrap:'wrap'}}><input placeholder="Search records…" value={search} onChange={e=>setSearch(e.target.value)} style={{flex:1,minWidth:240}}/><button className="btn" onClick={load}>Refresh</button><button className="btn" onClick={exportCsv}>Export CSV</button>{pluginKey!=='hotel-booking'&&<button className="btn primary" onClick={()=>{setSelected(null);setForm({});setTab('create')}}>+ New</button>}</div>{loading?<div className="notice">Loading live records…</div>:!filtered.length?<div className="notice">No live records yet. No demo/sample rows are inserted.</div>:<Table columns={headers} rows={filtered.map(r=>[...(def.fields||[]).map(f=>val(r[f])),<div style={{display:'flex',gap:5,flexWrap:'wrap'}}><button className="btn" onClick={()=>edit(r)}>Edit</button>{def.actions.filter(a=>a.kind!=='navigate').slice(0,4).map(a=><button key={a.id} className="btn" disabled={!!actionBusy} onClick={()=>runAction(a,r)}>{actionBusy===a.id?'…':a.name}</button>)}{pluginKey!=='hotel-booking'&&<button className="btn danger" onClick={()=>remove(r)}>Delete</button>}</div>])}/>}</Section>}
   {tab==='create'&&<Section title={selected?'Edit Record':'Create Record'} meta="Writes to the canonical plugin-owned data owner"><div className="card admin-form">{def.createFields.length?def.createFields.map(f=><Field key={f} field={f} value={form[f]} onChange={v=>setForm(x=>({...x,[f]:v}))}/>):<div className="notice">This plugin's canonical table is workflow-controlled. Use the Workflow tab for domain transactions.</div>}<div style={{display:'flex',gap:8}}><button className="btn primary" onClick={save} disabled={saving||!def.createFields.length}>{saving?'Saving…':selected?'Update Record':'Create Record'}</button><button className="btn" onClick={()=>{setSelected(null);setForm({});setTab('records')}}>Cancel</button></div></div></Section>}
   {tab==='workflow'&&<Section title="Workflow Center" meta="Every displayed action is backed by an API handler or explicit provider gate"><div className="grid two">{def.actions.map(a=><div className="mini" key={a.id}><b>{a.name}</b><span>{a.kind==='provider'?'Provider/API integration required when applicable.':a.kind==='navigate'?'Canonical navigation action.':'Server-side domain action handler.'}</span><button className="btn primary" disabled={!!actionBusy} onClick={()=>runAction(a,selected||filtered[0]||null)}>{actionBusy===a.id?'Running…':'Run'}</button></div>)}</div></Section>}
   {tab==='analytics'&&<Section title="Operational Analytics" meta="Computed from current live rows"><div className="grid kpis"><Kpi label="Total" value={rows.length} delta="Live records"/><Kpi label="Status-bearing" value={def.statusField?rows.filter(r=>r[def.statusField]!=null).length:0} delta={def.statusField||'No status field'}/><Kpi label="Active / Published" value={rows.filter(r=>r.active===true||r.enabled===true||r.published===true).length} delta="Current rows"/><Kpi label="Recent" value={rows.filter(r=>{const d=r.created_at||r.updated_at||r.captured_at;return d&&Date.now()-new Date(d).getTime()<30*86400000}).length} delta="Last 30 days"/></div></Section>}
  </>}
 </AppShell>;
}
