const b=(key,label,def=true)=>({key,label,type:'boolean',default:def});
const n=(key,label,def=1,min=0,max=100000)=>({key,label,type:'number',default:def,min,max});
const s=(key,label,def='',options)=>({key,label,type:options?'select':'text',default:def,...(options?{options}: {})});

const common={
  manager_access:b('manager_access','Manager Access',true),
  staff_access:b('staff_access','Staff Access',false),
  notifications_enabled:b('notifications_enabled','Notifications Enabled',true),
  audit_logging:b('audit_logging','Audit Logging',true),
  automation_enabled:b('automation_enabled','Automation Enabled',true),
  retry_attempts:n('retry_attempts','Retry Attempts',3,0,10),
  email_notifications:b('email_notifications','Email Notifications',true),
  whatsapp_notifications:b('whatsapp_notifications','WhatsApp Notifications',false),
  sms_notifications:b('sms_notifications','SMS Notifications',false),
};

const ext={
  crm:[b('duplicate_detection','Duplicate Detection'),b('customer_timeline','Customer Timeline'),b('auto_tagging','Automatic Customer Tags'),b('lead_scoring','Lead Scoring'),n('ltv_refresh_hours','LTV Refresh Hours',24,1,168),n('duplicate_match_threshold','Duplicate Match Threshold',90,50,100),s('default_customer_type','Default Customer Type','guest',['guest','diner','corporate','vip']),b('auto_relationship_sync','Automatic Relationship Sync'),b('auto_value_refresh','Automatic Customer Value Refresh')],
  customer_360:[b('unified_timeline','Unified Timeline'),b('hotel_history','Hotel History'),b('restaurant_history','Restaurant History'),b('communication_history','Communication History'),b('profile_enrichment','Profile Enrichment'),b('loyalty_history','Loyalty History'),b('complaint_history','Complaint History'),b('review_history','Review History'),b('campaign_history','Campaign History'),b('consent_history','Consent History'),n('timeline_page_size','Timeline Page Size',100,20,500)],
  customer_intelligence:[b('preference_learning','Preference Learning'),b('affinity_scoring','Affinity Scoring'),b('behavior_scoring','Behavior Scoring'),n('refresh_hours','Refresh Hours',24,1,168),b('hotel_signals','Hotel Behaviour Signals'),b('restaurant_signals','Restaurant Behaviour Signals'),b('purchase_patterns','Purchase Pattern Analysis'),b('visit_patterns','Visit Pattern Analysis'),n('minimum_confidence','Minimum Insight Confidence',0.55,0,1),n('insight_retention_days','Insight Retention Days',90,7,730)],
  hotel_guest_crm:[b('prearrival','Pre-arrival Automation'),b('stay_lifecycle','Stay Lifecycle'),b('guest_requests','Guest Requests'),b('upsell_offers','Upsell Offers'),n('prearrival_days','Pre-arrival Trigger Days',7,0,30),b('post_stay_review_request','Post-stay Review Request'),b('checkout_followup','Checkout Follow-up'),b('service_recovery_link','Service Recovery Link'),b('loyalty_link','Loyalty Link')],
  restaurant_crm:[b('visit_metrics','Visit Metrics'),b('food_preferences','Food Preferences'),b('auto_tags','Automatic Tags'),b('restaurant_ltv','Restaurant LTV'),b('favorite_items','Favorite Items'),b('favorite_categories','Favorite Categories'),b('reservation_behavior','Reservation Behaviour'),b('ordering_behavior','Ordering Behaviour'),b('birthday_automation','Birthday Automation'),b('anniversary_automation','Anniversary Automation'),b('review_journey','Review Journey')],
  customer_ltv:[b('hotel_revenue','Hotel Revenue'),b('restaurant_revenue','Restaurant Revenue'),b('event_revenue','Event Revenue'),b('ancillary_revenue','Ancillary Revenue'),n('refresh_frequency_hours','Refresh Frequency Hours',24,1,720),s('ltv_method','LTV Method','historical',['historical','cohort','hybrid']),n('forecast_horizon_months','Forecast Horizon Months',12,1,60),b('margin_adjustment','Margin Adjustment'),n('margin_percent','Margin Percent',100,0,100)],
  lead_management:[b('pipeline_enabled','Pipeline Enabled'),b('lead_scoring','Lead Scoring'),b('source_tracking','Source Tracking'),b('auto_assignment','Automatic Assignment'),b('qualification_rules','Qualification Rules'),b('conversion_tracking','Conversion Tracking'),b('quote_link','Quotation Link'),n('stale_lead_days','Stale Lead Days',7,1,90),b('lost_reason_required','Lost Reason Required'),b('source_roi','Source ROI')],
  followups:[b('task_reminders','Task Reminders'),b('sequence_automation','Sequence Automation'),b('owner_required','Owner Required'),n('reminder_hours_before','Reminder Hours Before',24,0,168),b('overdue_escalation','Overdue Escalation'),b('channel_execution','Channel Execution'),b('retry_failed_steps','Retry Failed Steps'),n('max_sequence_steps','Max Sequence Steps',20,1,100),b('completion_analytics','Completion Analytics')],
  corporate_crm:[b('contracts','Contracts'),b('negotiated_rates','Negotiated Rates'),b('credit_control','Credit Control'),b('account_reviews','Account Reviews'),b('contacts','Corporate Contacts'),b('booking_attribution','Booking Attribution'),b('invoice_terms','Invoice / Payment Terms'),n('review_interval_months','Account Review Interval Months',3,1,24),b('renewal_alerts','Renewal Alerts'),b('credit_limit_guard','Credit Limit Guard')],
  partner_crm:[b('commission_tracking','Commission Tracking'),b('partner_bookings','Partner Bookings'),b('settlement_tracking','Settlement Tracking'),b('partner_scoring','Partner Scoring'),b('onboarding_workflow','Partner Onboarding'),b('contract_management','Contract Management'),b('payout_reconciliation','Payout Reconciliation'),n('settlement_cycle_days','Settlement Cycle Days',30,1,180),b('booking_attribution','Booking Attribution')],
  loyalty:[b('earn_rules','Earn Rules'),b('redeem_rules','Redeem Rules'),b('tier_rules','Tier Rules'),b('referrals','Referrals'),b('reverse_transactions','Reverse Transactions'),n('points_expiry_days','Points Expiry Days',365,0,3650),b('tier_downgrade','Tier Downgrade'),b('fraud_controls','Fraud / Abuse Controls'),b('customer_notifications','Customer Notifications'),b('loyalty_statement','Loyalty Statement')],
  offers_coupons:[b('eligibility_rules','Eligibility Rules'),n('redemption_limit','Redemption Limit',0,0,1000000),b('expiry_enforcement','Expiry Enforcement'),b('customer_attribution','Customer Attribution'),b('booking_discount','Booking Discount'),b('order_discount','Order Discount'),b('refund_reversal','Refund / Reversal'),b('stacking_control','Stacking Control'),n('conversion_window_days','Conversion Window Days',30,1,365)],
  marketing_automation:[b('trigger_engine','Trigger Engine'),b('journeys','Journeys'),b('campaign_scheduling','Campaign Scheduling'),b('attribution','Attribution'),b('visual_journey','Visual Journey Builder'),b('wait_steps','Wait / Delay Steps'),b('branching','Branching'),b('unsubscribe','Unsubscribe Handling'),b('retry','Retry'),b('roi_tracking','Campaign ROI'),n('max_journey_steps','Max Journey Steps',50,1,200)],
  whatsapp_crm:[b('template_management','Template Management'),b('inbound_logging','Inbound Logging'),b('outbound_logging','Outbound Logging'),b('delivery_status','Delivery Status'),b('conversation_inbox','Conversation Inbox'),b('assignment','Conversation Assignment'),b('media','Media Messages'),b('webhook_processing','Webhook Processing'),b('read_receipts','Read Receipts'),b('consent_enforcement','Consent Enforcement'),n('conversation_retention_days','Conversation Retention Days',365,30,3650)],
  reputation:[b('multi_source','Multi-source Reviews'),b('sentiment','Sentiment Analysis'),b('response_workflow','Response Workflow'),b('review_requests','Review Requests'),b('rating_trend','Rating Trend'),b('source_comparison','Source Comparison'),b('topic_trend','Topic Trend'),b('response_analytics','Response Analytics'),b('recovery_analytics','Recovery Analytics'),b('competitor_benchmark','Competitor Benchmark')],
  guest_relations:[b('complaints','Complaints'),b('service_recovery','Service Recovery'),b('sla','SLA'),b('manager_escalation','Manager Escalation'),b('assignment','Assignment'),b('customer_notification','Customer Notification'),b('closure_required','Closure Required'),n('default_sla_minutes','Default SLA Minutes',120,15,10080),b('root_cause','Root Cause Tracking'),b('compensation','Compensation Tracking')],
  segmentation:[b('dynamic_segments','Dynamic Segments'),b('auto_membership','Automatic Membership'),n('segment_refresh_hours','Segment Refresh Hours',24,1,168),b('engagement_filters','Engagement Filters'),b('visual_rule_builder','Visual Rule Builder'),b('and_or_groups','AND / OR Groups'),b('live_audience_count','Live Audience Count'),b('campaign_activation','Campaign Activation'),b('segment_history','Segment History'),b('performance_tracking','Performance Tracking')],
  churn:[b('score_enabled','Churn Scoring'),n('risk_threshold','Risk Threshold',0.65,0,1),b('retention_actions','Retention Actions'),n('recompute_hours','Recompute Hours',24,1,720),b('feature_pipeline','Feature Pipeline'),b('reason_factors','Reason Factors'),b('intervention_tracking','Intervention Tracking'),b('outcome_measurement','Outcome Measurement'),s('model_type','Model Type','rule-v1',['rule-v1','external-model']),b('accuracy_tracking','Accuracy Tracking')],
  vip:[b('vip_levels','VIP Levels'),b('amenity_tracking','Amenity Tracking'),b('dedicated_manager','Dedicated Manager'),b('vip_history','VIP History'),b('automatic_qualification','Automatic Qualification'),b('ltv_rules','LTV Qualification Rules'),b('vip_approval','VIP Approval'),b('benefit_enforcement','Benefit Enforcement'),b('vip_alerts','VIP Alerts'),b('workload_analytics','Manager Workload Analytics')],
  revenue_management:[b('occupancy_signal','Occupancy Signal'),b('booking_pace','Booking Pace'),b('competitor_signal','Competitor Signal'),b('approval_required','Approval Required'),b('min_rate_guard','Minimum Rate Guard'),b('demand_calculation','Demand Calculation'),b('pickup_analysis','Pickup Analysis'),b('pricing_calendar','Pricing Calendar'),b('restrictions','Rate Restrictions'),b('override_tracking','Override Tracking'),b('performance_feedback','Performance Feedback'),s('recommendation_method','Recommendation Method','rule-v1',['rule-v1','hybrid'])],
  upselling:[b('prearrival_offers','Pre-arrival Offers'),b('in_stay_offers','In-stay Offers'),b('ancillary_catalog','Ancillary Catalog'),b('approval_required','Approval Required'),b('eligibility_engine','Eligibility Engine'),b('recommendation_engine','Recommendation Engine'),b('delivery','Offer Delivery'),b('acceptance_tracking','Acceptance Tracking'),b('revenue_attribution','Revenue Attribution'),b('cancellation_refund','Cancellation / Refund'),n('cooldown_hours','Offer Cooldown Hours',24,0,720)],
  cross_selling:[b('hotel_to_restaurant','Hotel → Restaurant'),b('restaurant_to_hotel','Restaurant → Hotel'),b('activity_cross_sell','Activity Cross-sell'),b('customer_eligibility','Customer Eligibility'),s('recommendation_strategy','Recommendation Strategy','rule-based',['rule-based','affinity','value-based']),n('priority','Priority',100,1,1000),n('minimum_ltv','Minimum LTV',0,0,100000000),s('validity_hours','Offer Validity Hours','24',['6','12','24','48','72']),n('frequency_cap','Frequency Cap',3,1,30),n('cooldown_hours','Cooldown Hours',24,0,720),b('approval','Approval'),b('attribution','Attribution'),n('conversion_window_days','Conversion Window Days',30,1,365),b('logging','Decision Logging')],
  event_crm:[b('lead_pipeline','Lead Pipeline'),b('quotes','Quotes'),b('followups','Follow-ups'),b('deposit_tracking','Deposit Tracking'),b('package_builder','Package Builder'),b('venue_management','Venue Management'),b('proposal_approval','Proposal Approval'),b('payment_schedule','Payment Schedule'),b('task_planning','Task Planning'),b('event_execution','Event Execution'),b('post_event_followup','Post-event Follow-up'),n('default_deposit_percent','Default Deposit %',25,0,100)],
  omnichannel_timeline:[b('hotel_events','Hotel Events'),b('restaurant_events','Restaurant Events'),b('messages','Messages'),b('reviews','Reviews'),b('bookings','Bookings'),b('orders','Orders'),b('complaints','Complaints'),b('campaigns','Campaigns'),n('timeline_retention_days','Timeline Retention Days',730,30,3650),b('dedupe_events','Dedupe Events')],
  consent_privacy:[b('marketing_consent','Marketing Consent'),b('channel_preferences','Channel Preferences'),b('data_requests','Data Requests'),b('audit_trail','Consent Audit Trail'),b('consent_capture','Consent Capture'),b('versioning','Consent Versioning'),b('withdrawal','Withdrawal'),b('retention_policy','Retention Policy'),b('processor_history','Processor History'),b('access_controls','Access Controls'),n('retention_days','Default Retention Days',730,30,3650)],
  relationship_manager:[b('portfolio_assignment','Portfolio Assignment'),b('ownership_required','Ownership Required'),b('workload_limits','Workload Limits'),b('reassignment_audit','Reassignment Audit'),b('auto_assignment','Automatic Assignment'),b('sla','Relationship SLA'),b('relationship_history','Relationship History'),b('manager_performance','Manager Performance'),n('max_accounts_per_manager','Max Accounts / Manager',200,1,5000),b('workload_rebalance','Workload Rebalance')],
  advanced_analytics:[b('retention','Retention Analytics'),b('ltv','LTV Analytics'),b('campaign_roi','Campaign ROI'),b('guest_analytics','Guest Analytics'),b('cohort_analysis','Cohort Analysis'),b('date_filters','Date Filters'),b('drilldowns','Drilldowns'),b('channel_contribution','Channel Contribution'),b('export','Export Reports'),b('period_comparison','Period Comparison'),n('default_period_days','Default Period Days',30,7,365)],
  ai_crm:[b('summaries','Customer Summaries'),b('next_best_action','Next Best Action'),b('ai_insights','AI Insights'),b('human_approval','Human Approval'),b('model_invocation','Model Invocation'),b('context_aggregation','Customer Context Aggregation'),b('tool_actions','Tool / Action Layer'),b('structured_output','Structured Output'),b('inference_logging','Inference Logging'),b('cost_tracking','Cost Tracking'),b('failure_handling','Failure Handling'),s('model','AI Model','configured',['configured','openai'])],
  revenue_forecasting:[b('occupancy_forecast','Occupancy Forecast'),b('adr_forecast','ADR Forecast'),b('revpar_forecast','RevPAR Forecast'),b('demand_forecast','Demand Forecast'),b('approval_required','Approval Required'),b('historical_dataset','Historical Dataset'),b('feature_pipeline','Feature Pipeline'),b('scheduled_inference','Scheduled Inference'),b('confidence','Confidence Intervals'),b('accuracy_tracking','Accuracy Tracking'),b('model_versioning','Model Versioning'),n('horizon_days','Forecast Horizon Days',30,1,90)],
  competitor_intelligence:[b('live_collection','Live Collection'),b('rate_parity','Rate Parity'),b('competitor_alerts','Competitor Alerts'),n('collection_interval_hours','Collection Interval Hours',6,1,168),b('source_registry','Source Registry'),b('normalization','Rate Normalization'),b('room_mapping','Room Mapping'),b('price_comparison','Price Comparison'),b('history','Collection History'),b('dashboard','Competitive Dashboard'),b('provider_required','External Provider Required',true)],
  'hotel-booking':[b('direct_booking','Direct Booking'),b('payment_required','Payment Required'),b('confirmation_required','Booking Confirmation Required'),n('cancellation_window_hours','Cancellation Window Hours',24,0,720),n('inventory_hold_minutes','Inventory Hold Minutes',15,1,120),b('prearrival_automation','Pre-arrival Automation'),b('tax_enabled','Tax Calculation'),b('idempotency','Idempotent Transactions'),b('refunds','Refund Processing'),b('webhook_verification','Payment Webhook Verification'),b('pms_sync','PMS Synchronization'),b('crm_sync','CRM Synchronization')],
  'hotel-management-suite':[b('front_desk','Front Desk'),b('housekeeping','Housekeeping'),b('folios','Folios'),b('inventory','Inventory'),b('night_audit','Night Audit'),b('maintenance','Maintenance'),b('room_status','Room Status'),b('guest_lifecycle','Guest Lifecycle'),b('document_management','Guest Documents'),b('deposit_management','Deposits'),b('restaurant_charges','Restaurant Charges'),b('room_inspection','Room Inspection')],
  'hotel-pms':[b('front_desk','Front Desk'),b('housekeeping','Housekeeping'),b('auto_room_status','Automatic Room Status'),b('overbooking_guard','Overbooking Guard'),b('folio_management','Folio Management'),b('walk_in','Walk-in Reservations'),b('modification','Reservation Modification'),b('early_check_in','Early Check-in'),b('late_checkout','Late Check-out'),b('upgrade_downgrade','Upgrade / Downgrade'),b('deposit','Deposits'),b('partial_payment','Partial Payments'),b('refund','Refunds'),b('restaurant_charge_posting','Restaurant Charge Posting'),b('night_audit','Night Audit')],
  'restaurant-reservation':[b('online_reservations','Online Reservations'),b('waitlist','Waitlist'),b('auto_assignment','Automatic Table Assignment'),n('default_slot_minutes','Default Slot Minutes',90,15,300),s('no_show_policy','No-show Policy','mark',['mark','release','charge']),b('capacity_management','Capacity Management'),b('confirmation','Confirmation'),b('reminders','Reminders'),b('seating','Seating'),b('table_move','Table Move'),n('default_covers','Default Covers',2,1,50)],
  'food-delivery':[b('online_orders','Online Orders'),b('cod','Cash on Delivery'),b('auto_accept','Auto Accept'),n('delivery_radius_km','Delivery Radius KM',10,1,100),n('minimum_order','Minimum Order',0,0,100000),s('dispatch_mode','Dispatch Mode','manual',['manual','automatic']),b('status_notifications','Status Notifications'),b('rider_assignment','Rider Assignment'),b('settlement','Settlement'),b('refunds','Refunds'),b('pos_bridge','POS Bridge')],
  'restaurant-store':[b('published','Published'),b('online_ordering','Online Ordering'),b('custom_domain','Custom Domain'),b('show_reviews','Show Reviews'),b('tax_enabled','Tax Enabled'),b('cart','Cart'),b('checkout','Checkout'),b('payment_gateway','Payment Gateway'),b('pos_bridge','POS Bridge'),b('kot','KOT'),b('kds','KDS'),b('delivery','Delivery'),b('refunds','Refunds')],
  'anaira-pos':[b('kot_enabled','KOT Enabled'),b('kds_enabled','KDS Enabled'),b('thermal_printing','Thermal Printing'),b('customer_sync','Customer Sync'),b('delivery_sync','Delivery Sync'),b('order_bridge','Order Bridge'),b('payment_sync','Payment Sync'),b('refund_sync','Refund Sync'),b('inventory_sync','Inventory Sync'),b('crm_events','CRM Events')],
  'channel-manager':[b('rate_sync','Rate Sync'),b('inventory_sync','Inventory Sync'),b('reservation_sync','Reservation Sync'),b('parity_alerts','Parity Alerts'),n('sync_interval_minutes','Sync Interval Minutes',15,5,1440),s('conflict_strategy','Conflict Strategy','latest',['latest','source-priority','manual']),b('provider_adapters','Provider Adapters'),b('acknowledgement','Acknowledgement'),b('retry','Retry / Backoff'),b('mapping_validation','Mapping Validation'),b('sync_history','Sync History')],
  'seo-system':[b('sitemap_enabled','Sitemap Enabled'),b('robots_enabled','Robots Enabled'),b('respect_robots','Respect Robots'),b('scheduled_crawl','Scheduled Crawl'),n('crawl_max_pages','Crawl Max Pages',500,1,10000),b('browser_rendering','Browser Rendering'),b('gsc_enabled','GSC Enabled'),b('ga4_enabled','GA4 Enabled'),b('rank_tracking_enabled','Rank Tracking'),b('ai_content_enabled','AI Content'),b('internal_links_enabled','Internal Links'),b('schema_enabled','Schema'),b('redirects_enabled','Redirect Management'),b('technical_issues','Technical Issue Tracking'),b('backlinks_enabled','Backlink Intelligence'),b('local_seo_enabled','Local SEO / GBP'),b('geo_visibility_enabled','AI / GEO Visibility'),b('competitor_intelligence_enabled','Competitor Intelligence'),b('reports_enabled','SEO Reports'),b('keyword_research_enabled','Keyword Research'),n('crawl_delay_ms','Crawl Delay (ms)',100,0,5000)],

  'ai-review-system':[b('google_sync','Google Sync'),b('review_requests','Review Requests'),b('ai_classification','AI Classification'),b('ai_reply_drafts','AI Reply Drafts'),b('human_approval','Human Approval'),b('auto_publish','Auto Publish'),b('service_recovery','Service Recovery'),b('sla_enabled','SLA Enabled'),b('whatsapp_enabled','WhatsApp'),b('sms_enabled','SMS'),b('email_enabled','Email'),n('request_delay_hours','Request Delay Hours',24,1,720),b('source_deduplication','Source Deduplication'),b('negative_review_escalation','Negative Review Escalation')]
};

export function getEnhancedSettings(pluginKey, base=[]) {
  const seen=new Set();
  const out=[];
  for(const item of [...base,...Object.values(common),...(ext[pluginKey]||[])]){
    if(!item||seen.has(item.key))continue;seen.add(item.key);out.push(item);
  }
  return out;
}

export const pluginSettingExtensions=ext;
