'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import AnairaShell from '@/components/anaira/AnairaShell';
import {Hotel,Utensils,Search,MapPin,ArrowRight} from 'lucide-react';
import {supabase} from '../../lib/supabase';
export default function Marketplace(){
 const [stores,setStores]=useState([]),[hotel,setHotel]=useState([]),[restaurant,setRestaurant]=useState([]);
 useEffect(()=>{(async()=>{const {data:s}=await supabase.from('anaira_platform_stores').select('*').eq('enabled',true).eq('published',true).order('store_type');setStores(s||[]); for(const x of (s||[])){const {data:m}=await supabase.from('anaira_store_memberships').select('restaurant_id,listing_override,restaurants(id,name,city,address,logo,cover_image,cuisine)').eq('store_id',x.id).eq('enabled',true).order('sort_order'); if(x.store_type==='hotel')setHotel(m||[]); if(x.store_type==='restaurant')setRestaurant(m||[]);}})()},[]);
 const h=stores.find(x=>x.store_type==='hotel'), r=stores.find(x=>x.store_type==='restaurant');
 return <AnairaShell title="ANAIRA Marketplace"><div className="anaira-hero"><h2>One account. Two ANAIRA stores.</h2><p>Hotels ke liye unified booking marketplace aur restaurants ke liye unified ordering marketplace. Dono ek hi ANAIRA customer identity, CRM aur operational contracts se connected hain.</p><div style={{display:'flex',gap:10,marginTop:18}}><Link className="anaira-btn" href="/anaira/hotels"><Hotel size={17}/> {h?.store_name||'ANAIRA Hotels'} <ArrowRight size={15}/></Link><Link className="anaira-btn" href="/anaira/food"><Utensils size={17}/> {r?.store_name||'ANAIRA Restaurants'} <ArrowRight size={15}/></Link></div></div><div className="anaira-section"><h2><Hotel size={20}/> {h?.store_name||'ANAIRA Hotels'}</h2><div className="anaira-grid">{hotel.map(x=><div className="anaira-card" key={x.restaurant_id}><div className="anaira-muted"><MapPin size={14}/> {x.restaurants?.city||x.restaurants?.address||''}</div><h3>{x.restaurants?.name}</h3><p>{x.restaurants?.address||''}</p><Link href={`/anaira/hotels?hotel=${x.restaurant_id}`}>View rooms →</Link></div>)}</div></div><div className="anaira-section"><h2><Utensils size={20}/> {r?.store_name||'ANAIRA Restaurants'}</h2><div className="anaira-grid">{restaurant.map(x=><div className="anaira-card" key={x.restaurant_id}><div className="anaira-muted"><MapPin size={14}/> {x.restaurants?.city||x.restaurants?.address||''}</div><h3>{x.restaurants?.name}</h3><p>{x.restaurants?.cuisine||'Restaurant'} • Delivery / Pickup / Dine-in</p><Link href={`/anaira/food?restaurant=${x.restaurant_id}`}>View menu →</Link></div>)}</div></div></AnairaShell>
}
