import {NextResponse} from 'next/server'
import crypto from 'node:crypto'
import {db} from '../../../../lib/server/provider'
import {requireTenant} from '../../../../lib/server/auth'
const seal=v=>{const s=process.env.ANAIRA_SECRET_KEY||process.env.ANAIRA_SECRET;if(!s)throw new Error('ANAIRA_SECRET_KEY is required');const k=crypto.createHash('sha256').update(s).digest(),iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',k,iv);const enc=Buffer.concat([c.update(String(v),'utf8'),c.final()]);return [iv.toString('base64'),c.getAuthTag().toString('base64'),enc.toString('base64')].join('.')}
const open=v=>{const s=process.env.ANAIRA_SECRET_KEY||process.env.ANAIRA_SECRET;if(!s)throw new Error('ANAIRA_SECRET_KEY is required');const k=crypto.createHash('sha256').update(s).digest(),[i,t,e]=String(v).split('.'),d=crypto.createDecipheriv('aes-256-gcm',k,Buffer.from(i,'base64'));d.setAuthTag(Buffer.from(t,'base64'));return Buffer.concat([d.update(Buffer.from(e,'base64')),d.final()]).toString('utf8')}
async function ctx(req,tenantId){const x=await requireTenant(req,tenantId);if(req.method==='POST' && !(x.profile?.is_super_admin||x.profile?.role==='super_admin')) throw new Error('Super Admin integration settings required');return {user:x.user,tenantId,db:db()}}
export async function GET(req){try{const tenantId=new URL(req.url).searchParams.get('tenantId');const {db:s}=await ctx(req,tenantId);const {data,error}=await s.from('anaira_restaurant_connections').select('id,tenant_id,restaurant_id,restaurant_api_base_url,status,capabilities,last_sync_at,last_error,created_at,updated_at').eq('tenant_id',tenantId).maybeSingle();if(error)throw error;return NextResponse.json({ok:true,connection:data||null})}catch(e){return NextResponse.json({ok:false,error:e.message},{status:400})}}
export async function POST(req){try{const b=await req.json();const tenantId=String(b.tenantId||'');const {db:s}=await ctx(req,tenantId);const action=String(b.action||'connect');if(action==='disconnect'){await s.from('anaira_restaurant_connections').update({status:'disconnected',updated_at:new Date().toISOString()}).eq('tenant_id',tenantId);await s.from('anaira_store_memberships').update({catalog_source:'anaira_pos',integration_connection_id:null,sync_status:'disconnected'}).eq('restaurant_id',tenantId);return NextResponse.json({ok:true,status:'disconnected'})}const base=String(b.restaurant_api_base_url||'').trim().replace(/\/$/,'');const key=String(b.restaurant_api_key||'').trim();if(!/^https?:\/\//i.test(base))throw new Error('Valid Restaurant SaaS base URL is required');if(!key)throw new Error('Restaurant integration key is required');const {data:restaurant,error:re}=await s.from('restaurants').select('id').eq('id',tenantId).single();if(re)throw re;const payload={tenant_id:tenantId,restaurant_id:restaurant.id,restaurant_api_base_url:base,restaurant_api_key:seal(key),status:'connected',capabilities:b.capabilities||undefined,last_error:null,updated_at:new Date().toISOString()};const {data,error}=await s.from('anaira_restaurant_connections').upsert(payload,{onConflict:'tenant_id,restaurant_id'}).select('id,tenant_id,restaurant_id,restaurant_api_base_url,status,capabilities,last_sync_at,last_error').single();if(error)throw error;await s.from('anaira_store_memberships').update({catalog_source:'restaurant_saas',integration_connection_id:data.id,sync_status:'connected',last_sync_at:new Date().toISOString()}).eq('restaurant_id',tenantId);return NextResponse.json({ok:true,connection:data})}catch(e){return NextResponse.json({ok:false,error:e.message},{status:400})}}
