'use client';
import {useEffect,useState} from 'react';
import {AppShell,Header,Section} from '../../components';
import {supabase} from '../../../lib/supabase';

const defaults={global_booking_engine_enabled:true,global_booking_rules:{},global_payment_provider:'platform',global_notifications_enabled:true,global_cancellation_policy:'',marketplace_booking_enabled:true};
export default function GlobalBookingEngine(){
 const [form,setForm]=useState(defaults),[msg,setMsg]=useState(''),[error,setError]=useState('');
 useEffect(()=>{(async()=>{const {data,error}=await supabase.from('anaira_platform_settings').select('key,value').in('key',Object.keys(defaults));if(error){setError(error.message);return}const x={...defaults};(data||[]).forEach(r=>x[r.key]=r.value?.value??r.value);setForm(x)})()},[]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function save(e){e.preventDefault();setMsg('');setError('');const user=(await supabase.auth.getUser()).data.user?.id;for(const [key,value] of Object.entries(form)){const q=await supabase.from('anaira_platform_settings').upsert({key,value:{value},updated_by:user},{onConflict:'key'});if(q.error){setError(q.error.message);return}}setMsg('Global booking engine settings saved.');}
 return <AppShell active="/super-admin/booking-engine"><Header eyebrow="SUPER ADMIN • BOOKING ENGINE" title="Global Booking Engine" subtitle="Platform defaults and global controls. Room types, rooms, rates and inventory remain canonical in Hotel Management."/><Section title="Global Booking Engine Configuration" meta="Super Admin only"><form className="card admin-form" onSubmit={save}><label className="check-field"><input type="checkbox" checked={!!form.global_booking_engine_enabled} onChange={e=>set('global_booking_engine_enabled',e.target.checked)}/><span>Global booking engine enabled</span></label><label className="check-field"><input type="checkbox" checked={!!form.marketplace_booking_enabled} onChange={e=>set('marketplace_booking_enabled',e.target.checked)}/><span>Marketplace booking enabled</span></label><label className="check-field"><input type="checkbox" checked={!!form.global_notifications_enabled} onChange={e=>set('global_notifications_enabled',e.target.checked)}/><span>Global booking notifications enabled</span></label><label><span>Global payment provider</span><input value={form.global_payment_provider||''} onChange={e=>set('global_payment_provider',e.target.value)} placeholder="Provider key / platform account"/></label><label className="full"><span>Global cancellation policy</span><textarea rows="4" value={form.global_cancellation_policy||''} onChange={e=>set('global_cancellation_policy',e.target.value)}/></label><div className="notice">Business Admin configures only its own hotel selling options. HMS remains the source of truth for Room Types, Rooms, Rates and Inventory.</div><div className="full"><button className="btn primary">Save Global Booking Engine Settings</button>{msg&&<span style={{marginLeft:10}}>{msg}</span>}{error&&<div className="notice error">{error}</div>}</div></form></Section></AppShell>;
}
