'use client';
import {useEffect,useState} from 'react';
import {SetupShell,SetupHeader,useTenantProperty,ensureSelected,SelectField,Section,Table,Pill,hospitalityMeta} from '../setup-components';
import {supabase} from '../../../lib/supabase';
const STATES=['pending','in_progress','completed','inspected'];
export default function Housekeeping(){
 const ctx=useTenantProperty(); const[rid,setRid]=useState(null),[rows,setRows]=useState([]),[filter,setFilter]=useState('all'),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false); const id=ensureSelected(ctx,rid); const m=hospitalityMeta(ctx.hospitalityType);
 async function load(){if(!id)return;const q=await supabase.from('hms_housekeeping_tasks').select('*,hms_rooms(room_number,status,housekeeping_status,hospitality_type)').eq('restaurant_id',id).order('due_at',{ascending:true});if(q.error)setMsg(q.error.message);else setRows((q.data||[]).filter(x=>(x.hms_rooms?.hospitality_type||ctx.hospitalityType||'hotel')===(ctx.hospitalityType||'hotel')))}
 useEffect(()=>{load()},[id]);
 async function transition(t,action){setBusy(true);setMsg('');const q=await supabase.rpc('anaira_housekeeping_transition',{p_restaurant_id:id,p_task_id:t.id,p_action:action,p_notes:null});setMsg(q.error?.message||`${action.replaceAll('_',' ')} completed.`);if(!q.error)await load();setBusy(false)}
 const shown=rows.filter(x=>filter==='all'||x.status===filter);return <SetupShell active="/hotel-management" title={`${m.label} Housekeeping`} subtitle={`${m.unit} board, cleaning, inspections and maintenance tasks.`} ctx={ctx}><SetupHeader title={`${m.label} Housekeeping`} subtitle="Operational unit readiness" ctx={ctx} rid={rid} setRid={setRid}/>{id?<><Section title="Room Board" meta={`${shown.length} tasks`}><div className="card"><SelectField label="Status" value={filter} onChange={setFilter} options={[['all','All'],...STATES]}/></div><Table columns={[m.unit,'Task','Priority','Status','Due','Actions']} rows={shown.map(t=>[<b>{t.hms_rooms?.room_number||'—'}</b>,t.task_type,<Pill>{t.priority}</Pill>,<Pill>{t.status}</Pill>,t.due_at?new Date(t.due_at).toLocaleString():'—',<div style={{display:'flex',gap:5,flexWrap:'wrap'}}>{t.status==='pending'&&<button className="btn" disabled={busy} onClick={()=>transition(t,'start')}>Start</button>}{t.status==='in_progress'&&<button className="btn" disabled={busy} onClick={()=>transition(t,'complete')}>Complete</button>}{t.status==='completed'&&<button className="btn" disabled={busy} onClick={()=>transition(t,'inspect')}>Inspect</button>}{['completed','inspected'].includes(t.status)&&<button className="btn" disabled={busy} onClick={()=>transition(t,'reopen')}>Reopen</button>}</div>])}/></Section>{msg&&<div className="notice">{msg}</div>}</>:<div className="notice">Select a property first.</div>}</SetupShell>}
