'use client';
import {useEffect,useMemo,useState} from 'react';
import {AppShell,Header,Section,Kpi,Table,Pill} from '../components';
import {supabase} from '../../lib/supabase';
const tabs=['Dashboard','Room Catalog','Reservations','Availability','Rates','Promotions','Packages','Add-ons','Engine Design','Policies','Reports'];
const money=v=>`₹${Number(v||0).toLocaleString('en-IN')}`;
function Field({label,children}){return <label><span>{label}</span>{children}</label>}
function Text({label,value,setValue,type='text'}){return <Field label={label}><input type={type} value={value??''} onChange={e=>setValue(e.target.value)}/></Field>}
export default function Page(){
 const [session,setSession]=useState(undefined),[profile,setProfile]=useState(null),[properties,setProperties]=useState([]),[rid,setRid]=useState(''),[tab,setTab]=useState('Dashboard'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [rooms,setRooms]=useState([]),[rates,setRates]=useState([]),[inventory,setInventory]=useState([]),[reservations,setReservations]=useState([]),[addons,setAddons]=useState([]),[promos,setPromos]=useState([]),[packages,setPackages]=useState([]);
 const [rateForm,setRateForm]=useState({name:'',code:'',room_type_id:'',board_type:'room_only',rate:0,cancellation_policy:'',active:true,min_stay:1});
 const [addonForm,setAddonForm]=useState({name:'',description:'',price:0,addon_type:'service',active:true});
 const [promoForm,setPromoForm]=useState({code:'',name:'',discount_type:'percent',discount_value:0,min_nights:1,active:true});
 const [pkgForm,setPkgForm]=useState({name:'',code:'',description:'',price:0,active:true});
 const [engine,setEngine]=useState({template:'anaira-premium',locale:'en-IN',currency:'INR',multi_currency:false,multi_language:false,payment_mode:'pay_at_hotel',pay_at_hotel_enabled:true,bank_transfer_enabled:true,qr_upi_enabled:true,bank_name:'',bank_account_name:'',bank_account_number:'',bank_ifsc:'',bank_branch:'',bank_upi_id:'',payment_qr_url:'',whatsapp_booking_enabled:true,whatsapp_number:'',direct_booking_enabled:true,packages_enabled:true,addons_enabled:true,promo_enabled:true});
 useEffect(()=>{(async()=>{if(!supabase){setSession(null);return}const {data}=await supabase.auth.getSession();setSession(data.session);if(data.session){const {data:p}=await supabase.from('anaira_my_profile').select('restaurant_id,is_super_admin,role').eq('id',data.session.user.id).maybeSingle();setProfile(p||{});if(p?.is_super_admin){const {data:rs}=await supabase.from('restaurants').select('id,name,status').order('name');setProperties(rs||[])}else setRid(p?.restaurant_id||'')}})()},[]);
 useEffect(()=>{if(profile?.is_super_admin&&properties.length&&!rid)setRid(properties[0].id)},[profile,properties,rid]);
 const load=async()=>{if(!rid)return;const qs=await Promise.all([supabase.from('hms_room_types').select('*').eq('restaurant_id',rid).order('created_at',{ascending:false}),supabase.from('hms_rate_plans').select('*,hms_room_types(name)').eq('restaurant_id',rid).order('created_at',{ascending:false}),supabase.from('hms_inventory').select('*').eq('restaurant_id',rid).order('stay_date').limit(100),supabase.from('hms_reservations').select('*,hms_guests(full_name,phone,email)').eq('restaurant_id',rid).order('created_at',{ascending:false}).limit(100),supabase.from('booking_addons').select('*').eq('restaurant_id',rid).order('created_at',{ascending:false}),supabase.from('booking_promotions').select('*').eq('restaurant_id',rid).order('created_at',{ascending:false}),supabase.from('booking_packages').select('*').eq('restaurant_id',rid).order('created_at',{ascending:false}),supabase.from('booking_engine_settings').select('*').eq('restaurant_id',rid).maybeSingle()]);const [a,b,c,d,e,f,g,h]=qs;const bad=qs.find(x=>x.error&&!/does not exist/i.test(x.error.message));if(bad)setError(bad.error.message);setRooms(a.data||[]);setRates(b.data||[]);setInventory(c.data||[]);setReservations(d.data||[]);setAddons(e.data||[]);setPromos(f.data||[]);setPackages(g.data||[]);if(h.data)setEngine(h.data)};
 useEffect(()=>{load()},[rid]);
 const stats=useMemo(()=>{const today=new Date().toISOString().slice(0,10);return {rooms:rooms.length,rates:rates.length,bookings:reservations.length,today:reservations.filter(x=>x.check_in===today).length,revenue:reservations.reduce((s,x)=>s+Number(x.total_amount||0),0)}},[rooms,rates,reservations]);
 const insert=async(table,form,reset)=>{setBusy(true);setError('');const r=await supabase.from(table).insert({...form,restaurant_id:rid});if(r.error)setError(r.error.message);else{reset();await load()}setBusy(false)};
 async function uploadQR(file){if(!file||!rid)return;setBusy(true);const ext=(file.name.split('.').pop()||'png').toLowerCase();const path=`hotel-payment-qr/${rid}/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const up=await supabase.storage.from('anaira-media').upload(path,file,{upsert:false,contentType:file.type||'image/png'});if(up.error)setError(up.error.message);else{const {data}=supabase.storage.from('anaira-media').getPublicUrl(path);setEngine({...engine,payment_qr_url:data.publicUrl});}setBusy(false)}
 const saveEngine=async()=>{setBusy(true);const r=await supabase.from('booking_engine_settings').upsert({...engine,restaurant_id:rid},{onConflict:'restaurant_id'});if(r.error)setError(r.error.message);else await load();setBusy(false)};
 const updateInventory=async(row,field,value)=>{const r=await supabase.from('hms_inventory').update({[field]:Number(value)}).eq('id',row.id);if(r.error)setError(r.error.message);else load()};
 if(session===undefined)return <div className="notice">Connecting…</div>;
 if(!session)return <AppShell><div className="auth-card"><h1>Sign in required</h1><a className="btn primary" href="/login">Open CRM Login</a></div></AppShell>;
 return <AppShell active="/booking"><Header eyebrow="DIRECT CONNECT • RESERVATION & REVENUE" title="Anaira Hotel Booking Engine" subtitle="Direct booking control center for inventory, rates, reservations, promotions, packages, stay enrichments, payment mode and engine presentation." actions={<><select value={rid} onChange={e=>setRid(e.target.value)} disabled={!profile?.is_super_admin} style={{padding:10,borderRadius:10}}><option value="">Select property</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><a className="btn" href="/booking">Plugin Dashboard</a></>}/>
 <div className="tabs">{tabs.map(t=><button key={t} className={'btn '+(tab===t?'primary':'')} onClick={()=>setTab(t)}>{t}</button>)}</div>{error&&<div className="notice error">{error}</div>}{!rid?<div className="notice">Select a property to manage its booking engine.</div>:<>
 {tab==='Dashboard'&&<><div className="grid kpis"><Kpi label="Room Types" value={stats.rooms} delta="Direct inventory"/><Kpi label="Rate Plans" value={stats.rates} delta="Sellable rates"/><Kpi label="Reservations" value={stats.bookings} delta="Live records"/><Kpi label="Today's Arrivals" value={stats.today} delta="Check-in date"/><Kpi label="Gross Booking Value" value={money(stats.revenue)} delta="Reservations"/></div><Section title="Direct Revenue Engine" meta="Anaira Direct Connect"><div className="mini-grid"><div className="mini"><b>Responsive booking</b><span>Mobile-first direct sales.</span></div><div className="mini"><b>Packages</b><span>Room + experience bundles.</span></div><div className="mini"><b>Stay enrichments</b><span>Airport transfer, meals and services.</span></div><div className="mini"><b>Promotions</b><span>Promo/coupon rules feed the transactional quote.</span></div><div className="mini"><b>Payments</b><span>Payment intent + verification/webhook state machine.</span></div><div className="mini"><b>Multi-currency/language</b><span>Engine configuration controls.</span></div></div></Section><Section title="Recent Reservations" meta="Live Supabase"><Table columns={['Code','Guest','Check-in','Check-out','Status','Payment','Total']} rows={reservations.slice(0,10).map(r=>[r.reservation_code,r.hms_guests?.full_name||'Guest',r.check_in,r.check_out,<Pill>{r.status}</Pill>,<Pill>{r.payment_status||'pending'}</Pill>,money(r.total_amount)])}/></Section></>}
 {tab==='Room Catalog'&&<Section title="Room Catalog" meta="HMS master • read only"><div className="grid cards">{rooms.map(r=>{const inv=inventory.filter(i=>i.room_type_id===r.id);const available=inv.length?Math.max(0,Math.min(...inv.map(i=>Number(i.total_rooms||0)-Number(i.sold_rooms||0)-Number(i.blocked_rooms||0)))):0;return <div className="card" key={r.id}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><h3 style={{margin:'0 0 6px'}}>{r.name}</h3><div className="muted">{r.short_description||r.description||'Hotel room'}</div></div><Pill tone={r.active?'success':'muted'}>{r.active?'Active':'Inactive'}</Pill></div><div className="mini-grid" style={{marginTop:12}}><div className="mini"><b>Capacity</b><span>{r.max_adults||0} adults · {r.max_children||0} children</span></div><div className="mini"><b>Bed</b><span>{r.bed_type||'—'} · {r.number_of_beds||1}</span></div><div className="mini"><b>Rate</b><span>{money(r.base_rate)} / night</span></div><div className="mini"><b>Availability</b><span>{available} rooms</span></div></div><div style={{marginTop:12,display:'flex',gap:8}}><a className="btn" href={`/hotel-management/room-types?room_type=${r.id}`}>Manage in HMS →</a><a className="btn primary" href={`/book?room_type=${r.id}`}>View / Book</a></div></div>})}</div>{!rooms.length&&<div className="notice">No active HMS room types found. Create the room type in Hotel Management → Room Types.</div>}</Section>}
 {tab==='Reservations'&&<Section title="Reservation Control Center" meta="Direct bookings"><Table columns={['Code','Guest','Dates','Guests','Source','Status','Payment','Total']} rows={reservations.map(r=>[r.reservation_code,r.hms_guests?.full_name||'Guest',`${r.check_in} → ${r.check_out}`,`${r.adults}/${r.children}`,r.source,<Pill>{r.status}</Pill>,<Pill>{r.payment_status||'pending'}</Pill>,money(r.total_amount)])}/></Section>}
 {tab==='Availability'&&<Section title="Availability Control" meta="Live inventory"><Table columns={['Date','Room Type','Total','Sold','Blocked','Available','Closed']} rows={inventory.map(r=>[r.stay_date,r.room_type_id,r.total_rooms,<input className="compact-input" type="number" value={r.sold_rooms||0} onChange={e=>updateInventory(r,'sold_rooms',e.target.value)}/>,<input className="compact-input" type="number" value={r.blocked_rooms||0} onChange={e=>updateInventory(r,'blocked_rooms',e.target.value)}/>,Math.max(0,Number(r.total_rooms||0)-Number(r.sold_rooms||0)-Number(r.blocked_rooms||0)),<button className="btn" onClick={async()=>{const q=await supabase.from('hms_inventory').update({closed:!r.closed}).eq('id',r.id);if(q.error)setError(q.error.message);else load()}}>{r.closed?'Open':'Close'}</button>])}/></Section>}
 {tab==='Rates'&&<><Section title="Create Rate Plan" meta="EP / CP / MAP / AP"><form className="card admin-form"><Text label="Name" value={rateForm.name} setValue={v=>setRateForm({...rateForm,name:v})}/><Text label="Code" value={rateForm.code} setValue={v=>setRateForm({...rateForm,code:v})}/><Field label="Room Type"><select value={rateForm.room_type_id} onChange={e=>setRateForm({...rateForm,room_type_id:e.target.value})}><option value="">Select room type</option>{rooms.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><Text label="Rate" type="number" value={rateForm.rate} setValue={v=>setRateForm({...rateForm,rate:v})}/><Text label="Weekend Rate" type="number" value={rateForm.weekend_rate||0} setValue={v=>setRateForm({...rateForm,weekend_rate:v})}/><Field label="Board Type"><select value={rateForm.board_type} onChange={e=>setRateForm({...rateForm,board_type:e.target.value})}><option value="room_only">Room Only / EP</option><option value="breakfast">Breakfast / CP</option><option value="half_board">MAP</option><option value="full_board">AP</option></select></Field><Text label="Cancellation Policy" value={rateForm.cancellation_policy} setValue={v=>setRateForm({...rateForm,cancellation_policy:v})}/><div className="full"><button className="btn primary" type="button" disabled={busy} onClick={()=>insert('hms_rate_plans',rateForm,()=>setRateForm({name:'',code:'',room_type_id:'',board_type:'room_only',rate:0,cancellation_policy:'',active:true,min_stay:1}))}>Create Rate Plan</button></div></form></Section><Section title="Rate Plans" meta={`${rates.length} live`}><Table columns={['Name','Code','Room Type','Board','Rate','Active']} rows={rates.map(r=>[r.name,r.code,r.hms_room_types?.name||r.room_type_id||'Flexible',r.board_type,money(r.rate),r.active?'Yes':'No'])}/></Section></>}
 {tab==='Add-ons'&&<><Section title="Create Stay Enrichment" meta="Paid extras"><form className="card admin-form"><Text label="Name" value={addonForm.name} setValue={v=>setAddonForm({...addonForm,name:v})}/><Text label="Description" value={addonForm.description} setValue={v=>setAddonForm({...addonForm,description:v})}/><Text label="Price" type="number" value={addonForm.price} setValue={v=>setAddonForm({...addonForm,price:v})}/><Text label="Type" value={addonForm.addon_type} setValue={v=>setAddonForm({...addonForm,addon_type:v})}/><div className="full"><button className="btn primary" type="button" onClick={()=>insert('booking_addons',addonForm,()=>setAddonForm({name:'',description:'',price:0,addon_type:'service',active:true}))}>Create Add-on</button></div></form></Section><Section title="Stay Enrichments" meta="Live"><Table columns={['Name','Type','Price','Active']} rows={addons.map(a=>[a.name,a.addon_type,money(a.price),a.active?'Yes':'No'])}/></Section></>}
 {tab==='Promotions'&&<><Section title="Create Promotion" meta="Direct-booking offers"><form className="card admin-form"><Text label="Code" value={promoForm.code} setValue={v=>setPromoForm({...promoForm,code:v.toUpperCase()})}/><Text label="Name" value={promoForm.name} setValue={v=>setPromoForm({...promoForm,name:v})}/><Field label="Discount Type"><select value={promoForm.discount_type} onChange={e=>setPromoForm({...promoForm,discount_type:e.target.value})}><option value="percent">Percent</option><option value="fixed">Fixed Amount</option></select></Field><Text label="Discount Value" type="number" value={promoForm.discount_value} setValue={v=>setPromoForm({...promoForm,discount_value:v})}/><div className="full"><button className="btn primary" type="button" onClick={()=>insert('booking_promotions',promoForm,()=>setPromoForm({code:'',name:'',discount_type:'percent',discount_value:0,min_nights:1,active:true}))}>Create Promotion</button></div></form></Section><Section title="Promotions" meta="Live"><Table columns={['Code','Name','Type','Value','Active']} rows={promos.map(p=>[p.code,p.name,p.discount_type,p.discount_type==='percent'?`${p.discount_value}%`:money(p.discount_value),p.active?'Yes':'No'])}/></Section></>}
 {tab==='Packages'&&<><Section title="Create Package" meta="Room + experience bundles"><form className="card admin-form"><Text label="Name" value={pkgForm.name} setValue={v=>setPkgForm({...pkgForm,name:v})}/><Text label="Code" value={pkgForm.code} setValue={v=>setPkgForm({...pkgForm,code:v})}/><Text label="Description" value={pkgForm.description} setValue={v=>setPkgForm({...pkgForm,description:v})}/><Text label="Price" type="number" value={pkgForm.price} setValue={v=>setPkgForm({...pkgForm,price:v})}/><div className="full"><button className="btn primary" type="button" onClick={()=>insert('booking_packages',pkgForm,()=>setPkgForm({name:'',code:'',description:'',price:0,active:true}))}>Create Package</button></div></form></Section><Section title="Packages" meta="Live"><Table columns={['Name','Code','Price','Active']} rows={packages.map(p=>[p.name,p.code,money(p.price),p.active?'Yes':'No'])}/></Section></>}
 {tab==='Engine Design'&&<Section title="Booking Engine Design & Configuration" meta="Direct Connect"><div className="card admin-form"><Field label="Template"><select value={engine.template||'anaira-premium'} onChange={e=>setEngine({...engine,template:e.target.value})}><option value="anaira-premium">Anaira Premium</option><option value="anaira-minimal">Anaira Minimal</option><option value="anaira-boutique">Anaira Boutique</option></select></Field><Text label="Locale" value={engine.locale||'en-IN'} setValue={v=>setEngine({...engine,locale:v})}/><Text label="Currency" value={engine.currency||'INR'} setValue={v=>setEngine({...engine,currency:v})}/><Field label="Payment Mode"><select value={engine.payment_mode||'pay_at_hotel'} onChange={e=>setEngine({...engine,payment_mode:e.target.value})}><option value="pay_at_hotel">Pay at Hotel</option><option value="gateway">Online Payment Gateway</option><option value="both">Both</option></select></Field>{[['multi_currency','Multi-currency'],['multi_language','Multi-language'],['packages_enabled','Packages'],['addons_enabled','Stay Enrichments'],['promo_enabled','Promotions'],['direct_booking_enabled','Direct Booking'],['pay_at_hotel_enabled','Pay at Hotel'],['bank_transfer_enabled','Bank Transfer'],['qr_upi_enabled','QR / UPI'],['whatsapp_booking_enabled','WhatsApp Booking']].map(([k,l])=><label className="check-field" key={k}><input type="checkbox" checked={!!engine[k]} onChange={e=>setEngine({...engine,[k]:e.target.checked})}/><span>{l}</span></label>)}<div className="full payment-config"><h3>Hotel Payment & WhatsApp</h3><div className="form-grid"><Text label="Bank Name" value={engine.bank_name||''} setValue={v=>setEngine({...engine,bank_name:v})}/><Text label="Account Name" value={engine.bank_account_name||''} setValue={v=>setEngine({...engine,bank_account_name:v})}/><Text label="Account Number" value={engine.bank_account_number||''} setValue={v=>setEngine({...engine,bank_account_number:v})}/><Text label="IFSC" value={engine.bank_ifsc||''} setValue={v=>setEngine({...engine,bank_ifsc:v})}/><Text label="Branch" value={engine.bank_branch||''} setValue={v=>setEngine({...engine,bank_branch:v})}/><Text label="UPI ID" value={engine.bank_upi_id||''} setValue={v=>setEngine({...engine,bank_upi_id:v})}/><Text label="Payment QR Image URL" value={engine.payment_qr_url||''} setValue={v=>setEngine({...engine,payment_qr_url:v})}/><label className="field-label">Upload Payment QR<input type="file" accept="image/*" onChange={e=>uploadQR(e.target.files?.[0])}/></label><Text label="WhatsApp Number" value={engine.whatsapp_number||''} setValue={v=>setEngine({...engine,whatsapp_number:v})}/></div></div><div className="full"><button className="btn primary" onClick={saveEngine} disabled={busy}>Save Engine Settings</button></div></div></Section>}
 {tab==='Policies'&&<Section title="Booking Policy Control" meta="Business rules"><div className="mini-grid"><div className="mini"><b>Cancellation</b><span>Configured per rate plan.</span></div><div className="mini"><b>Minimum stay</b><span>Configured per rate plan.</span></div><div className="mini"><b>Check-in/out</b><span>Inherited from hotel settings.</span></div><div className="mini"><b>Taxes</b><span>Inherited from hotel profile.</span></div></div></Section>}
 {tab==='Reports'&&<Section title="Booking Revenue Report" meta="Live aggregation"><Table columns={['Metric','Value']} rows={[["Reservations",reservations.length],["Gross Booking Value",money(stats.revenue)],["Paid",money(reservations.filter(x=>x.payment_status==='paid').reduce((s,x)=>s+Number(x.total_amount||0),0))],["Pending Payment",money(reservations.filter(x=>x.payment_status!=='paid').reduce((s,x)=>s+Number(x.total_amount||0),0))],["Cancelled",reservations.filter(x=>x.status==='cancelled').length]]}/></Section>}
 </>}</AppShell>;
}
