'use client';
import {useEffect,useMemo,useState} from 'react';
import {Section,Pill} from '../../components';
import {useTenantProperty,SetupHeader,SetupShell,Field,SelectField,SetupNav,ensureSelected,hospitalityMeta} from '../setup-components';
import {supabase} from '../../../lib/supabase';

const BOARDS=[['room_only','EP','Room Only'],['breakfast','CP','Breakfast'],['half_board','MAP','Half Board'],['full_board','AP','Full Board']];
const pad=n=>String(n).padStart(2,'0');
const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const addDays=(s,n)=>{const d=new Date(`${s}T00:00:00`);d.setDate(d.getDate()+n);return iso(d)};
const fmt=s=>new Date(`${s}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
const daysBetween=(a,b)=>{const out=[];for(let x=a;x<=b;x=addDays(x,1))out.push(x);return out};

export default function RateCalendar(){
 const ctx=useTenantProperty(); const[rid,setRid]=useState(null); const id=ensureSelected(ctx,rid); const m=hospitalityMeta(ctx.hospitalityType||'hotel');
 const [types,setTypes]=useState([]),[plans,setPlans]=useState([]),[selectedType,setSelectedType]=useState(''),[dates,setDates]=useState([]),[rates,setRates]=useState({}),[modal,setModal]=useState(null),[form,setForm]=useState({single:0,double:0,triple:0,quad:0,extraAdult:0,extraChild:0,closed:false}),[base,setBase]=useState(3500),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const today=iso(new Date());
 const [from,setFrom]=useState(today),[to,setTo]=useState(addDays(today,14));
 const roomPlans=useMemo(()=>plans.filter(x=>!selectedType||x.room_type_id===selectedType),[plans,selectedType]);
 async function load(){if(!id)return; const [a,b]=await Promise.all([supabase.from('hms_room_types').select('id,name').eq('restaurant_id',id).eq('hospitality_type',ctx.hospitalityType||'hotel').eq('active',true).order('name'),supabase.from('hms_rate_plans').select('id,name,code,board_type,room_type_id,rate,occupancy,pricing_mode,active').eq('restaurant_id',id).eq('hospitality_type',ctx.hospitalityType||'hotel').eq('active',true).order('name')]); setTypes(a.data||[]);setPlans(b.data||[]);if(!selectedType&&a.data?.[0])setSelectedType(a.data[0].id)}
 useEffect(()=>{load()},[id,ctx.hospitalityType]);
 useEffect(()=>{setDates(daysBetween(from,to))},[from,to]);
 async function ensureBoardPlans(){
  if(!id||!selectedType)return [];
  const existing=roomPlans; const made=[];
  for(const [board,code,label] of BOARDS){let p=existing.find(x=>x.board_type===board); if(!p){const ins=await supabase.from('hms_rate_plans').insert({restaurant_id:id,hospitality_type:ctx.hospitalityType||'hotel',room_type_id:selectedType,name:`${types.find(t=>t.id===selectedType)?.name||'Room'} - ${code}`,code:`${code}-${String(types.find(t=>t.id===selectedType)?.name||'ROOM').replace(/\W+/g,'').slice(0,8).toUpperCase()}`,description:`${label} daily rate calendar`,board_type:board,pricing_mode:'per_unit',rate:Number(base||0),occupancy:2,extra_adult:0,extra_child:0,min_stay:1,active:true}).select('id,name,code,board_type,room_type_id,rate,occupancy,pricing_mode,active').single();if(ins.error)throw ins.error;p=ins.data;made.push(p)}}
  if(made.length){setPlans(x=>[...x,...made]);return [...existing,...made]} return existing;
 }
 async function initialize(){setBusy(true);setMsg('');try{const ps=await ensureBoardPlans();for(const p of ps.filter(x=>BOARDS.some(b=>b[0]===x.board_type))){await supabase.rpc('anaira_seed_daily_rate_calendar',{p_restaurant_id:id,p_rate_plan_id:p.id,p_from:from,p_to:to})}await loadRates(ps);setMsg('EP / CP / MAP / AP initialized with the same base rate. You can now edit each day separately.')}catch(e){setMsg(e.message||'Initialization failed')}finally{setBusy(false)}}
 async function loadRates(ps=roomPlans){if(!id)return;const ids=ps.map(x=>x.id);if(!ids.length)return;const q=await supabase.from('hms_daily_rate_calendar').select('*').in('rate_plan_id',ids).gte('stay_date',from).lte('stay_date',to).order('stay_date');const map={};(q.data||[]).forEach(r=>{map[`${r.rate_plan_id}:${r.stay_date}`]=r});setRates(map)}
 useEffect(()=>{if(roomPlans.length)loadRates()},[from,to,roomPlans.map(x=>x.id).join(',')]);
 function openEditor(plan,date){const r=rates[`${plan.id}:${date}`];setModal({plan,date});setForm({single:r?.single_rate??plan.rate??0,double:r?.double_rate??plan.rate??0,triple:r?.triple_rate??plan.rate??0,quad:r?.quad_rate??plan.rate??0,extraAdult:r?.extra_adult??plan.extra_adult??0,extraChild:r?.extra_child??plan.extra_child??0,closed:!!r?.closed})}
 async function saveDay(){if(!modal)return;setBusy(true);const p=modal.plan;const r=await supabase.rpc('anaira_set_daily_rate',{p_restaurant_id:id,p_rate_plan_id:p.id,p_stay_date:modal.date,p_single:Number(form.single||0),p_double:Number(form.double||0),p_triple:Number(form.triple||0),p_quad:Number(form.quad||0),p_extra_adult:Number(form.extraAdult||0),p_extra_child:Number(form.extraChild||0),p_closed:!!form.closed});setBusy(false);if(r.error){setMsg(r.error.message);return}setModal(null);await loadRates();setMsg(`${BOARDS.find(b=>b[0]===p.board_type)?.[1]||p.name} · ${fmt(modal.date)} saved.`)}
 return <SetupShell active="/hotel-management/rate-calendar" title="Daily Rate Calendar" subtitle={`date-wise ${m.unit.toLowerCase()} pricing for EP, CP, MAP and AP.`} ctx={ctx}>
  <SetupHeader title="Daily Rate Calendar" subtitle="A premium Anaira control center for EP, CP, MAP and AP daily pricing." ctx={ctx} rid={rid} setRid={setRid}/>
  {id?<>
   <div className="rate-hero">
    <div><div className="eyebrow">ANAIRA REVENUE CONTROL</div><h2>Daily Rate Calendar</h2><p>Initialize one common rate, then fine-tune every occupancy, meal plan and date independently.</p></div>
    <div className="hero-status"><span className="status-dot"></span>Live pricing workspace</div>
   </div>
   <div className="rate-toolbar card">
    <div className="toolbar-grid">
      <SelectField label={m.unitType} value={selectedType} onChange={setSelectedType} options={types.map(x=>[x.id,x.name])}/>
      <Field label="From" type="date" value={from} onChange={setFrom}/><Field label="To" type="date" value={to} onChange={setTo}/><Field label="Base Rate" type="number" value={base} onChange={setBase}/>
      <button className="btn primary rate-init" disabled={busy||!selectedType} onClick={initialize}>{busy?'Saving…':'Initialize EP / CP / MAP / AP'}</button>
    </div>
    <div className="toolbar-hint"><span>₹ Base rate</span><span>→</span><span>4 meal plans</span><span>→</span><span>{dates.length} daily dates</span><span>→</span><span>Edit independently</span></div>
   </div>
   {msg&&<div className="rate-message notice">{msg}</div>}
   <div className="rate-kpis">
    <div className="rate-kpi"><span className="kpi-label">ROOM TYPE</span><strong>{types.find(x=>x.id===selectedType)?.name||'Select room type'}</strong><small>{m.unitType}</small></div>
    <div className="rate-kpi"><span className="kpi-label">DATE WINDOW</span><strong>{dates.length} days</strong><small>{fmt(from)} → {fmt(to)}</small></div>
    <div className="rate-kpi"><span className="kpi-label">RATE PLANS</span><strong>4</strong><small>EP · CP · MAP · AP</small></div>
    <div className="rate-kpi accent"><span className="kpi-label">BASE RATE</span><strong>₹{Number(base||0).toLocaleString('en-IN')}</strong><small>Starting daily rate</small></div>
   </div>
   <Section title="Rate Plan Calendars" meta="Same initial rate → edit any date independently">
    <div className="plan-stack">{BOARDS.map(([board,short,label])=>{const plan=roomPlans.find(x=>x.board_type===board);return <div key={board} className="plan-card">
      <div className="plan-head">
       <div className="plan-identity"><div className={`plan-icon plan-${short.toLowerCase()}`}>{short}</div><div><div className="plan-title">{label}</div><div className="plan-sub">{plan?plan.name:'Not initialized'} · {plan?'Active rate plan':'Ready to initialize'}</div></div></div>
       <div className="plan-actions"><span className={`plan-state ${plan?'live':'pending'}`}>{plan?'● Active':'○ Pending'}</span><button className="btn" disabled={!plan} onClick={()=>plan&&openEditor(plan,from)}>Edit {short}</button></div>
      </div>
      <div className="calendar-scroll"><table className="rate-table"><thead><tr><th className="occupancy-head">OCCUPANCY</th>{dates.map(d=><th key={d} className={d===today?'today-head':''}>{new Date(`${d}T00:00:00`).toLocaleDateString('en-IN',{weekday:'short'})}<br/><b>{new Date(`${d}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}</b>{d===today&&<span className="today-tag">TODAY</span>}</th>)}</tr></thead><tbody>{['single_rate','double_rate','triple_rate','quad_rate'].map((field,i)=><tr key={field}><td className="occupancy-cell"><span className="occ-number">{i+1}</span><span>{['Single','Double','Triple','Quad'][i]}</span></td>{dates.map(d=>{const r=plan&&rates[`${plan.id}:${d}`];const val=r?.[field]??plan?.rate??0;return <td key={d} className={d===today?'today-col':''}><button className={`rate-cell ${r?.closed?'closed':''}`} disabled={!plan} onClick={()=>plan&&openEditor(plan,d)}><span>₹{Number(val).toLocaleString('en-IN')}</span>{r?.closed&&<em>STOP SELL</em>}<i>✎</i></button></td>})}</tr>)}</tbody></table></div>
      <div className="plan-footer"><span>Click any daily rate to edit Single / Double / Triple / Quad, extra guest pricing and Stop Sell.</span><span>{dates.length} dates</span></div>
    </div>})}</div>
   </Section>
   <div className="workflow-card"><div className="workflow-title"><span>ANAIRA RATE WORKFLOW</span><b>Controlled daily pricing</b></div><div className="workflow-steps"><div><b>01</b><span>Set Base Rate</span></div><i>→</i><div><b>02</b><span>Initialize Plans</span></div><i>→</i><div><b>03</b><span>Review Daily Grid</span></div><i>→</i><div><b>04</b><span>Edit & Save</span></div></div></div>
   <SetupNav hospitalityType={ctx.hospitalityType}/>
  </>:<div className="notice">Select a property first.</div>}
  {modal&&<div className="rate-modal" onClick={()=>setModal(null)}><div className="rate-modal-card" onClick={e=>e.stopPropagation()}><div style={{display:'flex',justifyContent:'space-between',alignItems:'start'}}><div><div className="eyebrow">DAILY RATE EDITOR</div><h2 style={{fontFamily:'Georgia,serif',margin:'4px 0'}}>{BOARDS.find(b=>b[0]===modal.plan.board_type)?.[1]} · {fmt(modal.date)}</h2><p style={{fontSize:12,color:'#756b62'}}>{modal.plan.name}</p></div><button className="btn" onClick={()=>setModal(null)}>×</button></div><div className="rate-grid"><Field label="Single" type="number" value={form.single} onChange={v=>setForm(x=>({...x,single:v}))}/><Field label="Double" type="number" value={form.double} onChange={v=>setForm(x=>({...x,double:v}))}/><Field label="Triple" type="number" value={form.triple} onChange={v=>setForm(x=>({...x,triple:v}))}/><Field label="Quad" type="number" value={form.quad} onChange={v=>setForm(x=>({...x,quad:v}))}/><Field label="Extra Adult" type="number" value={form.extraAdult} onChange={v=>setForm(x=>({...x,extraAdult:v}))}/><Field label="Extra Child" type="number" value={form.extraChild} onChange={v=>setForm(x=>({...x,extraChild:v}))}/></div><label style={{display:'flex',gap:8,alignItems:'center',marginTop:12,fontSize:12,fontWeight:700}}><input type="checkbox" checked={form.closed} onChange={e=>setForm(x=>({...x,closed:e.target.checked}))}/> Stop Sell this date</label><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:20}}><button className="btn" onClick={()=>setModal(null)}>Cancel</button><button className="btn primary" disabled={busy} onClick={saveDay}>{busy?'Saving…':'Save Rate'}</button></div></div></div>}
  <style jsx global>{`
   .rate-hero{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:24px 26px;margin-bottom:14px;border-radius:18px;background:linear-gradient(135deg,#063d2b,#0b523b 55%,#163f33);color:#fff;box-shadow:0 12px 35px rgba(3,45,31,.16)}
   .rate-hero h2{margin:4px 0 5px;font:700 30px Georgia,serif;letter-spacing:-.5px}.rate-hero p{margin:0;color:#cfe4da;font-size:12px}.eyebrow{font-size:10px;letter-spacing:2px;font-weight:800;color:#d4ab4c}.hero-status{font-size:11px;border:1px solid rgba(255,255,255,.2);padding:9px 12px;border-radius:999px;background:rgba(255,255,255,.07);white-space:nowrap}.status-dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:#d4ab4c;margin-right:7px}
   .rate-toolbar{padding:18px;margin-bottom:14px;border:1px solid #eadfce;box-shadow:0 8px 24px rgba(50,35,15,.05)}.toolbar-grid{display:grid;grid-template-columns:1.25fr .85fr .85fr .85fr auto;gap:12px;align-items:end}.rate-init{height:40px;white-space:nowrap}.toolbar-hint{display:flex;gap:9px;align-items:center;margin-top:12px;padding-top:12px;border-top:1px solid #eee5d8;color:#766b60;font-size:11px}.toolbar-hint span:nth-child(odd){font-weight:700}.rate-message{margin-bottom:14px}
   .rate-kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:16px}.rate-kpi{padding:16px 18px;border:1px solid #eadfce;border-radius:14px;background:#fff;box-shadow:0 7px 20px rgba(50,35,15,.045)}.rate-kpi.accent{background:linear-gradient(135deg,#fffaf0,#fff);border-color:#e0c98d}.kpi-label{display:block;font-size:9px;letter-spacing:1.4px;font-weight:800;color:#92794a;margin-bottom:6px}.rate-kpi strong{display:block;font-size:20px;color:#123b2e}.rate-kpi small{display:block;margin-top:4px;font-size:10px;color:#83786d}
   .plan-stack{display:grid;gap:16px}.plan-card{border:1px solid #e8dece;border-radius:16px;background:#fff;overflow:hidden;box-shadow:0 8px 24px rgba(50,35,15,.045)}.plan-head{display:flex;justify-content:space-between;align-items:center;padding:15px 17px;background:linear-gradient(180deg,#fffdf9,#faf7f0);border-bottom:1px solid #eee4d7}.plan-identity{display:flex;align-items:center;gap:12px}.plan-icon{width:42px;height:42px;border-radius:12px;display:grid;place-items:center;font-size:12px;font-weight:900;color:#fff;background:#0b4a35;box-shadow:inset 0 -3px 0 rgba(0,0,0,.1)}.plan-cp{background:#8a6a2c}.plan-map{background:#6b4d2f}.plan-ap{background:#4c3d35}.plan-title{font-size:16px;font-weight:800;color:#183b30}.plan-sub{font-size:10px;color:#81766b;margin-top:3px}.plan-actions{display:flex;align-items:center;gap:10px}.plan-state{font-size:9px;letter-spacing:.8px;font-weight:800;padding:7px 9px;border-radius:999px}.plan-state.live{background:#e8f6ef;color:#16724a}.plan-state.pending{background:#f5efe4;color:#876d42}
   .calendar-scroll{overflow-x:auto}.rate-table{width:100%;min-width:980px;border-collapse:separate;border-spacing:0}.rate-table th{padding:10px 8px;text-align:center;font-size:9px;color:#7b7167;background:#faf7f1;border-bottom:1px solid #eee5d9;position:relative}.rate-table th:first-child{position:sticky;left:0;z-index:2;background:#faf7f1}.rate-table td{padding:7px 6px;border-bottom:1px solid #f1eadf;text-align:center}.occupancy-head,.occupancy-cell{width:105px;text-align:left!important;position:sticky;left:0;z-index:1;background:#fff}.occupancy-cell{font-size:11px;font-weight:800;color:#29483d}.occ-number{display:inline-grid;place-items:center;width:22px;height:22px;border-radius:7px;background:#f4eee3;color:#806738;margin-right:6px;font-size:10px}.rate-cell{width:100%;min-width:82px;min-height:42px;border:1px solid #e2d7c7;background:#fff;border-radius:9px;padding:6px 7px;font-weight:800;color:#183b30;cursor:pointer;position:relative;transition:.15s}.rate-cell:hover{border-color:#b58a3a;background:#fffaf0;transform:translateY(-1px);box-shadow:0 4px 10px rgba(50,35,15,.08)}.rate-cell i{display:block;font-style:normal;font-size:8px;color:#b09568;opacity:0;margin-top:2px}.rate-cell:hover i{opacity:1}.rate-cell.closed{background:#fff0ed;border-color:#efc2b8;color:#a43e31}.rate-cell em{display:block;font-style:normal;font-size:7px;letter-spacing:.5px;color:#b34739;margin-top:2px}.today-head{background:#f6eedb!important;color:#7b5b1f!important}.today-col{background:#fffcf4}.today-tag{display:block;font-size:6px;letter-spacing:1px;color:#b1842d;margin-top:2px}
   .plan-footer{display:flex;justify-content:space-between;gap:12px;padding:9px 14px;font-size:9px;color:#887c70;background:#fcfaf6}.workflow-card{margin-top:16px;padding:17px 18px;border:1px solid #e8dece;border-radius:15px;background:linear-gradient(135deg,#fbf8f0,#fff);box-shadow:0 8px 22px rgba(50,35,15,.04)}.workflow-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.workflow-title span{font-size:9px;letter-spacing:1.5px;color:#a17b32;font-weight:900}.workflow-title b{font-size:12px;color:#234538}.workflow-steps{display:grid;grid-template-columns:1fr auto 1fr auto 1fr auto 1fr;align-items:center;gap:9px}.workflow-steps div{display:flex;align-items:center;gap:8px;padding:10px;border-radius:10px;background:#fff;border:1px solid #eee3d3}.workflow-steps b{width:24px;height:24px;display:grid;place-items:center;border-radius:7px;background:#0b4a35;color:#fff;font-size:9px}.workflow-steps span{font-size:10px;font-weight:700;color:#4e514d}.workflow-steps i{color:#b18a43;font-style:normal}
   @media(max-width:1000px){.toolbar-grid{grid-template-columns:1fr 1fr}.rate-kpis{grid-template-columns:1fr 1fr}.rate-init{width:100%}.workflow-steps{grid-template-columns:1fr}.workflow-steps i{display:none}}
   @media(max-width:650px){.rate-hero{align-items:flex-start;flex-direction:column}.rate-kpis{grid-template-columns:1fr}.toolbar-grid{grid-template-columns:1fr}.toolbar-hint{flex-wrap:wrap}}
   .rate-modal{position:fixed;inset:0;background:rgba(20,15,8,.58);backdrop-filter:blur(5px);display:grid;place-items:center;padding:20px;z-index:1000}.rate-modal-card{width:min(700px,100%);background:#fffdf9;border:1px solid #eadfce;border-radius:18px;padding:24px;box-shadow:0 25px 80px rgba(0,0,0,.3)}.rate-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:16px}@media(max-width:800px){.rate-grid{grid-template-columns:1fr}}
  `}</style>
 </SetupShell>
}
