'use client';
import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import {supabase} from '../../../lib/supabase';
export default function RestaurantOrder(){
 const {id}=useParams();const [r,setR]=useState(null),[items,setItems]=useState([]),[cart,setCart]=useState([]),[f,setF]=useState({name:'',phone:'',address:''}),[msg,setMsg]=useState('');
 useEffect(()=>{if(!id)return;(async()=>{const b=await supabase.rpc('anaira_marketplace_business',{p_restaurant_id:id});setR(b.data?.[0]||null);const m=await supabase.from('menu_items').select('id,name,price,category,image,description').eq('restaurant_id',id).eq('active',true).limit(200);setItems(m.data||[])})()},[id]);
 async function checkout(){if(!cart.length)return setMsg('Cart is empty.');const {data,error}=await supabase.rpc('anaira_create_public_delivery_order_by_id',{p_restaurant_id:id,p_customer_name:f.name,p_customer_phone:f.phone,p_address:{text:f.address},p_items:cart.map(x=>({name:x.name,quantity:x.quantity||1,unit_price:x.price,modifiers:{}})),p_source:'anaira_marketplace'});setMsg(error?error.message:`Order ${data?.[0]?.order_code||''} created. Payment gateway can be attached to this order.`)}
 return <main className="public-shell"><header><div className="eyebrow">ANAIRA FOOD MARKETPLACE</div><h1>{r?.name||'Restaurant'}</h1><p>{r?.cuisine||''} · {r?.address||''}</p></header><div className="public-columns"><section><h2>Menu</h2>{items.map(i=><article className="card" key={i.id}><b>{i.name}</b><p>{i.description||''}</p><strong>₹{i.price}</strong><button className="btn" onClick={()=>setCart(c=>[...c,{...i,quantity:1}])}>Add</button></article>)}</section><aside className="card"><h2>Cart</h2>{cart.map((i,n)=><div key={n}>{i.name} × {i.quantity} — ₹{i.price}</div>)}<hr/><b>Total ₹{cart.reduce((s,i)=>s+Number(i.price||0)*(i.quantity||1),0)}</b><input placeholder="Name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input placeholder="Phone" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/><textarea placeholder="Delivery address" value={f.address} onChange={e=>setF({...f,address:e.target.value})}/><button className="btn primary" onClick={checkout}>Place Order</button>{msg&&<p>{msg}</p>}</aside></div><a className="btn" href="/marketplace">← Back to Marketplace</a></main>
}