'use client';
import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import {supabase} from '../../../lib/supabase';
export default function RestaurantOrder(){
 const {id}=useParams();const [r,setR]=useState(null),[items,setItems]=useState([]),[cart,setCart]=useState([]),[f,setF]=useState({name:'',phone:'',address:''}),[msg,setMsg]=useState(''),[pay,setPay]=useState('manual'),[payBusy,setPayBusy]=useState(false);
 useEffect(()=>{if(!id)return;(async()=>{const b=await supabase.rpc('anaira_marketplace_business',{p_restaurant_id:id});setR(b.data?.[0]||null);const m=await supabase.from('menu_items').select('id,name,price,category,image,description').eq('restaurant_id',id).eq('active',true).limit(200);setItems(m.data||[])})()},[id]);
 async function checkout(){if(!cart.length)return setMsg('Cart is empty.');if(!f.name.trim()||!f.phone.trim()||!f.address.trim())return setMsg('Name, phone and delivery address are required.');setPayBusy(true);const {data,error}=await supabase.rpc('anaira_create_public_delivery_order_by_id',{p_restaurant_id:id,p_customer_name:f.name,p_customer_phone:f.phone,p_address:{text:f.address},p_items:cart.map(x=>({name:x.name,quantity:x.quantity||1,unit_price:x.price,modifiers:{}})),p_source:'anaira_marketplace'});if(error){setMsg(error.message);setPayBusy(false);return}const order=data?.[0];if(!order){setMsg('Order was not created.');setPayBusy(false);return}if(pay==='manual'){setMsg(`Order ${order.order_code} created. Payment mode: Pay on delivery.`);setCart([]);setPayBusy(false);return}const total=Number(order.total_amount||cart.reduce((s,i)=>s+Number(i.price||0)*(i.quantity||1),0));const pr=await fetch('/api/payments/create',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({restaurant_id:id,reference_type:'delivery_order',reference_id:order.id,amount:total,currency:'INR',provider:pay,idempotency_key:`delivery:${order.id}`})});const pj=await pr.json();if(!pr.ok){setMsg(pj.error||'Payment initialization failed.');setPayBusy(false);return}if(pay==='razorpay'&&pj.provider?.order_id){if(!window.Razorpay){const sc=document.createElement('script');sc.src='https://checkout.razorpay.com/v1/checkout.js';sc.onload=()=>openRazor(pj,order,total);document.body.appendChild(sc)}else openRazor(pj,order,total)}else{setMsg('Payment initialized. Complete it using the returned provider flow.');setPayBusy(false)}}
 function openRazor(pj,order,total){const rz=new window.Razorpay({key:pj.provider.key_id,amount:pj.provider.amount,currency:pj.provider.currency,order_id:pj.provider.order_id,name:r?.name||'Anaira Marketplace',description:`Order ${order.order_code}`,prefill:{name:f.name,contact:f.phone},handler:async(resp)=>{const vr=await fetch('/api/payments/razorpay/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({payment_intent_id:pj.payment.id,razorpay_order_id:resp.razorpay_order_id,razorpay_payment_id:resp.razorpay_payment_id,razorpay_signature:resp.razorpay_signature})});const vj=await vr.json();setMsg(vr.ok?`Order ${order.order_code} confirmed and payment verified.`:(vj.error||'Payment verification failed.'));setPayBusy(false);if(vr.ok)setCart([])},modal:{ondismiss:()=>setPayBusy(false)}});rz.open()}
 return <main className="public-shell"><header><div className="eyebrow">ANAIRA FOOD MARKETPLACE</div><h1>{r?.name||'Restaurant'}</h1><p>{r?.cuisine||''} · {r?.address||''}</p></header><div className="public-columns"><section><h2>Menu</h2>{items.map(i=><article className="card" key={i.id}><b>{i.name}</b><p>{i.description||''}</p><strong>₹{i.price}</strong><button className="btn" onClick={()=>setCart(c=>[...c,{...i,quantity:1}])}>Add</button></article>)}</section><aside className="card"><h2>Cart</h2>{cart.map((i,n)=><div key={n}>{i.name} × {i.quantity} — ₹{i.price}</div>)}<hr/><b>Total ₹{cart.reduce((s,i)=>s+Number(i.price||0)*(i.quantity||1),0)}</b><input placeholder="Name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input placeholder="Phone" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/><textarea placeholder="Delivery address" value={f.address} onChange={e=>setF({...f,address:e.target.value})}/><select value={pay} onChange={e=>setPay(e.target.value)}><option value="manual">Pay on delivery</option><option value="razorpay">Pay online · Razorpay</option><option value="stripe">Pay online · Stripe</option></select><button className="btn primary" disabled={payBusy} onClick={checkout}>{payBusy?'Processing…':'Place Order & Pay'}</button>{msg&&<p>{msg}</p>}</aside></div><a className="btn" href="/marketplace">← Back to Marketplace</a></main>
}