'use client';
import {useEffect,useMemo,useState} from 'react';
import {useParams} from 'next/navigation';
import {AppShell,Header,Section,Pill} from '../../../components';
import {supabase} from '../../../../lib/supabase';
import {pluginCatalog} from '../../../pluginCatalog';
import {getPluginDefinition} from '../../../pluginEngine';
const labelize=k=>k.replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
function Input({item,value,onChange}){if(item.type==='boolean')return <label><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/> <span>{item.label}</span></label>; if(item.type==='number')return <label><span>{item.label}</span><input type="number" min={item.min} max={item.max} value={value??''} onChange={e=>onChange(e.target.value===''?'':Number(e.target.value))}/></label>; if(item.type==='select')return <label><span>{item.label}</span><select value={value??item.default??''} onChange={e=>onChange(e.target.value)}>{(item.options||[]).map(x=><option key={x} value={x}>{labelize(x)}</option>)}</select></label>; return <label><span>{item.label}</span><input value={value??''} onChange={e=>onChange(e.target.value)}/></label>}
export default function PluginSettings(){const {pluginKey}=useParams();const plugin=pluginCatalog.find(x=>x.key===pluginKey),reg=getPluginDefinition(pluginKey);const [session,setSession]=useState(undefined),[rid,setRid]=useState(''),[properties,setProperties]=useState([]),[enabled,setEnabled]=useState(false),[form,setForm]=useState({}),[custom,setCustom]=useState({}),[newKey,setNewKey]=useState(''),[newType,setNewType]=useState('text'),[newValue,setNewValue]=useState(''),[msg,setMsg]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const defaults=useMemo(()=>Object.fromEntries((reg?.settingsSchema||[]).map(x=>[x.key,x.default])),[reg]);
 useEffect(()=>{(async()=>{if(!supabase){setSession(null);return}const {data}=await supabase.auth.getSession();setSession(data.session);if(!data.session)return;const p=await supabase.from('anaira_my_profile').select('restaurant_id,is_super_admin,role').eq('id',data.session.user.id).maybeSingle();if(p.data?.is_super_admin===true||p.data?.role==='super_admin'){const rs=await supabase.from('restaurants').select('id,name').order('name');setProperties(rs.data||[])}else setRid(p.data?.restaurant_id||'')})()},[]);
 useEffect(()=>{if(!rid||!pluginKey||!reg)return;(async()=>{const q=await supabase.from('restaurant_plugins').select('enabled,config').eq('restaurant_id',rid).eq('plugin_code',pluginKey).maybeSingle();if(q.error){setError(q.error.message);return}const cfg=q.data?.config||{};setEnabled(q.data?.enabled===true);setForm({...defaults,...(cfg.settings||cfg)});setCustom(cfg.custom_settings||{})})()},[rid,pluginKey,reg,defaults]);
 async function save(e){e.preventDefault();if(!rid||!plugin||!reg||!session){setError('Select a property first.');return}setSaving(true);setError('');setMsg('');const config={schema_version:1,settings:form,custom_settings:custom};const q=await supabase.from('restaurant_plugins').upsert({restaurant_id:rid,plugin_code:pluginKey,plugin_slug:pluginKey,display_name:plugin.name,category:plugin.category,description:plugin.description,feature_kind:'feature',enabled,config,activated_by:session.user.id,activated_at:enabled?new Date().toISOString():null,disabled_at:enabled?null:new Date().toISOString()},{onConflict:'restaurant_id,plugin_code'});if(q.error)setError(q.error.message);else{const ps=await supabase.from('plugin_settings').upsert({restaurant_id:rid,plugin_code:pluginKey,config,schema_version:1,custom_settings:custom,updated_by:session.user.id},{onConflict:'restaurant_id,plugin_code'});if(ps.error){setError(ps.error.message);setSaving(false);return}setMsg('Saved to live tenant configuration.')}setSaving(false)}
 function addCustom(){const k=newKey.trim().replace(/[^a-zA-Z0-9_\-]/g,'_');if(!k)return;let v=newValue;if(newType==='boolean')v=newValue==='true';if(newType==='number')v=Number(newValue||0);setCustom(x=>({...x,[k]:v}));setNewKey('');setNewValue('')}
 if(!plugin||!reg)return <AppShell><div className="notice error">Unknown plugin or manifest.</div></AppShell>;
 if(session===undefined)return <AppShell><div className="notice">Loading authentication…</div></AppShell>;
 if(!session)return <AppShell><div className="auth-card"><h1>Sign in required</h1><a className="btn primary" href="/login">Login</a></div></AppShell>;
 return <AppShell active="/plugins"><Header eyebrow="PLUGIN CONFIGURATION" title={`${plugin.name} — Complete Settings`} subtitle="Every plugin has its own explicit settings schema, permissions, dependencies and auditable tenant configuration. Provider secrets belong in secure server-side integration infrastructure." actions={<a className="btn" href={`/plugins/${pluginKey}`}>Back to Plugin</a>}/>
 <Section title="Property & Activation" meta="Tenant-scoped"><select value={rid} onChange={e=>setRid(e.target.value)} disabled={properties.length===0} style={{minWidth:320,padding:12,borderRadius:10}}><option value="">{properties.length?'Select property':'Current property'}</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select> <Pill tone={enabled?'success':'muted'}>{enabled?'Activated':'Disabled'}</Pill></Section>
 {error&&<div className="notice error">{error}</div>}
 <Section title="Core Settings" meta={`${reg.settingsSchema.length} explicit settings`}><form className="card admin-form" onSubmit={save}>{reg.settingsSchema.map(item=><Input key={item.key} item={item} value={form[item.key]} onChange={v=>setForm(x=>({...x,[item.key]:v}))}/>)}</form></Section>
 <Section title="Custom Settings" meta="Plugin-local extension point"><div className="notice">Add non-secret plugin settings without changing application code. API keys, OAuth refresh tokens and passwords must not be stored here.</div><div className="admin-form"><label>Setting Key<input value={newKey} onChange={e=>setNewKey(e.target.value)} placeholder="example: default_followup_days"/></label><label>Type<select value={newType} onChange={e=>setNewType(e.target.value)}><option value="text">Text</option><option value="number">Number</option><option value="boolean">Boolean</option></select></label><label>Value<input value={newValue} onChange={e=>setNewValue(e.target.value)}/></label><div><button type="button" className="btn" onClick={addCustom}>+ Add Setting</button></div></div><div className="grid two" style={{marginTop:12}}>{Object.entries(custom).map(([k,v])=><div className="mini" key={k}><b>{k}</b><span>{String(v)}</span><button className="btn" type="button" onClick={()=>setCustom(x=>{const n={...x};delete n[k];return n})}>Remove</button></div>)}</div></Section>
 <Section title="Permissions & Dependencies" meta="Independent plugin contract"><div className="mini-grid"><div className="mini"><span className="kpi-label">Permissions</span><b>{reg.permissions.join(', ')}</b></div><div className="mini"><span className="kpi-label">Dependencies</span><b>{reg.dependencies.length?reg.dependencies.join(', '):'None'}</b></div><div className="mini"><span className="kpi-label">Data Owner</span><b>{reg.dataTable||'No direct operational table'}</b></div><div className="mini"><span className="kpi-label">Published Events</span><b>{reg.events.publishes.join(', ')}</b></div></div></Section>
 <div className="card" style={{position:'sticky',bottom:16,display:'flex',gap:12,alignItems:'center'}}><button className="btn primary" onClick={save} disabled={saving}>{saving?'Saving…':'Save Complete Configuration'}</button>{msg&&<span>{msg}</span>}</div>
 </AppShell>}
