'use client';
import {useEffect,useMemo,useState} from 'react';
import {AppShell,Header,Section,Table,Pill} from '../components';
import {supabase} from '../../lib/supabase';

export default function Roles(){
 const [roles,setRoles]=useState([]),[profiles,setProfiles]=useState([]),[perms,setPerms]=useState([]),[profilePerms,setProfilePerms]=useState([]),[selected,setSelected]=useState('business_admin'),[error,setError]=useState(''),[saving,setSaving]=useState(''),[isSuper,setIsSuper]=useState(false);
 const load=async()=>{setError('');const {data:{session}}=await supabase.auth.getSession();if(session){const {data:me}=await supabase.from('anaira_my_profile').select('is_super_admin').eq('id',session.user.id).maybeSingle();setIsSuper(me?.is_super_admin===true)}const [a,b,c,d]=await Promise.all([supabase.from('anaira_roles').select('role_key,name,scope,description').order('role_key'),supabase.from('anaira_permission_profiles').select('profile_key,name,role_key,description').order('role_key').order('name'),supabase.from('anaira_permissions').select('permission_key,name,module,description').order('module').order('permission_key'),supabase.from('anaira_profile_permissions').select('profile_key,permission_key')]);const bad=[a,b,c,d].find(x=>x.error);if(bad){setError(bad.error.message);return}setRoles(a.data||[]);setProfiles(b.data||[]);setPerms(c.data||[]);setProfilePerms(d.data||[])};
 useEffect(()=>{load()},[]);
 const active=profiles.find(x=>x.profile_key===selected); const activeSet=useMemo(()=>new Set(profilePerms.filter(x=>x.profile_key===selected).map(x=>x.permission_key)),[profilePerms,selected]);
 const toggle=async(k)=>{setSaving(k);const next=!activeSet.has(k);const {error}=await supabase.rpc('anaira_set_profile_permission',{p_profile_key:selected,p_permission_key:k,p_allowed:next});if(error)setError(error.message);else setProfilePerms(x=>next?[...x,{profile_key:selected,permission_key:k}]:x.filter(y=>!(y.profile_key===selected&&y.permission_key===k)));setSaving('')};
 const grouped={}; perms.forEach(p=>(grouped[p.module]??=[]).push(p));
 return <AppShell active="/roles"><Header eyebrow="ACCESS CONTROL" title="Roles & Permission Profiles" subtitle="Role = hierarchy/scope. Profile = job function. Permission = actual action."/><Section title="Base Roles" meta={`${roles.length} roles`}><Table columns={['Role','Name','Scope','Description']} rows={roles.map(r=>[r.role_key,r.name,r.scope,r.description||'—'])}/></Section>{error&&<div className="notice error">{error}</div>}<Section title="Job Profiles" meta={`${profiles.length} profiles`}><div className="module-grid">{profiles.map(p=><button className="module-card" key={p.profile_key} onClick={()=>setSelected(p.profile_key)} style={{textAlign:'left',border:selected===p.profile_key?'2px solid #0d6d48':undefined}}><div className="module-icon">{p.role_key==='staff'?'👤':p.role_key==='manager'?'👔':'🏢'}</div><h3>{p.name}</h3><p>{p.description}</p><Pill>{p.role_key}</Pill></button>)}</div></Section><Section title={active?`${active.name} — Permission Matrix`:'Permission Matrix'} meta={active?`Role: ${active.role_key}`:'Select a profile'}>{active&&Object.entries(grouped).map(([module,list])=><div key={module} className="card" style={{marginBottom:12}}><div className="section-head"><h2>{module}</h2><span>{list.filter(x=>activeSet.has(x.permission_key)).length}/{list.length} enabled</span></div><Table columns={['Permission','Description','Access']} rows={list.map(x=>[x.permission_key,x.description||x.name,<button className={'btn '+(activeSet.has(x.permission_key)?'primary':'')} onClick={()=>toggle(x.permission_key)} disabled={!isSuper||saving===x.permission_key}>{activeSet.has(x.permission_key)?'Enabled':'Disabled'}</button>])}/></div>)}</Section><div className="notice">Profile templates are platform-wide. {isSuper?'You can edit the global profile template here.':'Business Admin can assign profiles and user-specific permission overrides; only Super Admin edits global profile templates.'} Super Admin bypasses tenant permission filtering. Business Admin receives the full tenant administration profile. Manager and Staff access is narrowed by profile + permission overrides. Refund, delete, launch, assignment and other sensitive actions remain separately permissioned.</div></AppShell>
}
