'use client';
import {useEffect,useState} from 'react';
import {AppShell,Header,Section,Kpi,Table,Pill} from '../components';
import {supabase} from '../../lib/supabase';
const money=v=>`₹${Number(v||0).toLocaleString('en-IN')}`;
const datePlus=(d,n)=>{const x=new Date(`${d}T00:00:00`);x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)};
function Field({label,children}){return <label><span>{label}</span>{children}</label>}
export default function CampingBookingEngine(){
 const [session,setSession]=useState(undefined),[profile,setProfile]=useState(null),[properties,setProperties]=useState([]),[rid,setRid]=useState(''),[tab,setTab]=useState('Dashboard'),[error,setError]=useState(''),[msg,setMsg]=useState('');
 const [camp,setCamp]=useState({name:'',short_name:'',description:'',destination:'',address:'',city:'',state:'Himachal Pradesh',country:'India',cover_image_url:'',logo_url:'',active:true,marketplace_visible:true,check_in_time:'12:00',check_out_time:'11:00'});
 const [units,setUnits]=useState([]),[rates,setRates]=useState([]),[inventory,setInventory]=useState([]),[reservations,setReservations]=useState([]);
 const [unitForm,setUnitForm]=useState({name:'',code:'',description:'',max_guests:1,max_adults:1,max_children:0,unit_count:1,base_rate:0,image_urls:[],amenities:[],active:true});
 const [rateForm,setRateForm]=useState({name:'',code:'',unit_type_id:'',pricing_mode:'per_person',rate:0,weekend_rate:0,seasonal_multiplier:1,refundable:true,deposit_percent:0,min_stay:1,active:true});
 const [invForm,setInvForm]=useState({unit_type_id:'',from:datePlus(new Date().toISOString().slice(0,10),1),to:datePlus(new Date().toISOString().slice(0,10),30),total_units:1});
 useEffect(()=>{const q=new URLSearchParams(window.location.search); if(q.get('tab'))setTab(q.get('tab'));},[]);useEffect(()=>{(async()=>{if(!supabase){setSession(null);return}const {data}=await supabase.auth.getSession();setSession(data.session);if(data.session){const {data:p}=await supabase.from('anaira_my_profile').select('restaurant_id,is_super_admin,role').eq('id',data.session.user.id).maybeSingle();setProfile(p||{});if(p?.is_super_admin){const {data:rs}=await supabase.from('restaurants').select('id,name,status').order('name');setProperties(rs||[])}else setRid(p?.restaurant_id||'')}})()},[]);
 useEffect(()=>{if(profile?.is_super_admin&&properties.length&&!rid)setRid(properties[0].id)},[profile,properties,rid]);
 async function load(){if(!rid)return;const [c,u,r,i,b]=await Promise.all([supabase.from('camp_properties').select('*').eq('restaurant_id',rid).maybeSingle(),supabase.from('camp_unit_types').select('*').eq('restaurant_id',rid).order('created_at',{ascending:false}),supabase.from('camp_rate_plans').select('*,camp_unit_types(name)').eq('restaurant_id',rid).order('created_at',{ascending:false}),supabase.from('camp_inventory').select('*').eq('restaurant_id',rid).order('stay_date').limit(200),supabase.from('camp_reservations').select('*').eq('restaurant_id',rid).order('created_at',{ascending:false}).limit(100)]);setCamp(c.data||{...camp});setUnits(u.data||[]);setRates(r.data||[]);setInventory(i.data||[]);setReservations(b.data||[]);const bad=[c,u,r,i,b].find(x=>x.error&&!/does not exist/i.test(x.error.message));if(bad)setError(bad.error.message)}
 useEffect(()=>{load()},[rid]);
 async function saveCamp(e){e.preventDefault();setError('');const q=await supabase.from('camp_properties').upsert({...camp,restaurant_id:rid},{onConflict:'restaurant_id'});if(q.error)setError(q.error.message);else{setMsg('Camping property saved.');load()}}
 async function addUnit(e){e.preventDefault();const q=await supabase.from('camp_unit_types').insert({...unitForm,restaurant_id:rid,image_urls:unitForm.image_urls||[],amenities:unitForm.amenities||[]});if(q.error)setError(q.error.message);else{setMsg('Camp unit added.');setUnitForm({name:'',code:'',description:'',max_guests:1,max_adults:1,max_children:0,unit_count:1,base_rate:0,image_urls:[],amenities:[],active:true});load()}}
 async function addRate(e){e.preventDefault();const q=await supabase.from('camp_rate_plans').insert({...rateForm,restaurant_id:rid});if(q.error)setError(q.error.message);else{setMsg('Camping rate plan added.');setRateForm({...rateForm,name:'',code:'',rate:0,weekend_rate:0});load()}}
 async function generateInventory(e){e.preventDefault();const rows=[];let d=invForm.from;while(d<invForm.to){rows.push({restaurant_id:rid,unit_type_id:invForm.unit_type_id,stay_date:d,total_units:Number(invForm.total_units)||0});d=datePlus(d,1)}if(!rows.length){setError('Select a valid inventory date range.');return}const q=await supabase.from('camp_inventory').upsert(rows,{onConflict:'unit_type_id,stay_date'});if(q.error)setError(q.error.message);else{setMsg(`${rows.length} camping inventory days saved.`);load()}}
 const revenue=reservations.reduce((s,x)=>s+Number(x.total_amount||0),0);
 if(session===undefined)return <div className="notice">Connecting…</div>;
 if(!session)return <AppShell><div className="auth-card"><h1>Sign in required</h1><a className="btn primary" href="/login">Open CRM Login</a></div></AppShell>;
 return <AppShell active="/booking"><div className="booking-engine-admin-shell"><Header eyebrow="ANAIRA CAMPING BOOKING ENGINE" title="Camping Booking Engine" subtitle="Manage camping properties, tents, per-person pricing, live inventory and the same guest-to-confirmation journey used by hotels." actions={<><select value={rid} onChange={e=>setRid(e.target.value)} disabled={!profile?.is_super_admin} style={{padding:10,borderRadius:10}}><option value="">Select property</option>{properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><a className="btn" href="/hotel-management/setup">Property Profile / Type</a><a className="btn" href="/booking">Hotel Booking Engine</a><a className="btn" href="/booking-engine/stays">Homestay / Guest House / Cottage</a></>}/><div className="tabs">{['Dashboard','Camp Property','Camp Units','Rates','Availability','Reservations','Policies'].map(t=><button key={t} className={'btn '+(tab===t?'primary':'')} onClick={()=>setTab(t)}>{t}</button>)}</div>{error&&<div className="notice error">{error}</div>}{msg&&<div className="notice">{msg}</div>}{!rid?<div className="notice">Select a property to manage camping.</div>:<>
 {tab==='Dashboard'&&<><div className="grid kpis"><Kpi label="Camp Units" value={units.length}/><Kpi label="Rate Plans" value={rates.length}/><Kpi label="Reservations" value={reservations.length}/><Kpi label="Gross Booking Value" value={money(revenue)}/></div><Section title="Camping Engine" meta="Same booking architecture as hotels"><div className="mini-grid"><div className="mini"><b>Single person</b><span>Per-person pricing supports 1 guest.</span></div><div className="mini"><b>Live inventory</b><span>Camp/tent availability by date.</span></div><div className="mini"><b>Guest verification</b><span>Phone or email OTP before booking.</span></div><div className="mini"><b>Payment</b><span>Pay at camp, bank transfer or QR proof.</span></div></div></Section></>}
 {tab==='Camp Property'&&<Section title="Camping Property" meta="Marketplace master"><form className="card admin-form" onSubmit={saveCamp}><Field label="Camp Name"><input value={camp.name||''} onChange={e=>setCamp({...camp,name:e.target.value})}/></Field><Field label="Short Name"><input value={camp.short_name||''} onChange={e=>setCamp({...camp,short_name:e.target.value})}/></Field><Field label="Destination"><input value={camp.destination||''} onChange={e=>setCamp({...camp,destination:e.target.value})} placeholder="Manali / Jalori Jot / Saryolsar"/></Field><Field label="City"><input value={camp.city||''} onChange={e=>setCamp({...camp,city:e.target.value})}/></Field><Field label="State"><input value={camp.state||''} onChange={e=>setCamp({...camp,state:e.target.value})}/></Field><Field label="Address"><input value={camp.address||''} onChange={e=>setCamp({...camp,address:e.target.value})}/></Field><Field label="Desktop / Cover Image URL"><input value={camp.cover_image_url||''} onChange={e=>setCamp({...camp,cover_image_url:e.target.value})}/></Field><Field label="Logo URL"><input value={camp.logo_url||''} onChange={e=>setCamp({...camp,logo_url:e.target.value})}/></Field><Field label="Description"><textarea value={camp.description||''} onChange={e=>setCamp({...camp,description:e.target.value})}/></Field><Field label="Check-in"><input value={camp.check_in_time||''} onChange={e=>setCamp({...camp,check_in_time:e.target.value})}/></Field><Field label="Check-out"><input value={camp.check_out_time||''} onChange={e=>setCamp({...camp,check_out_time:e.target.value})}/></Field><label className="check-field"><input type="checkbox" checked={!!camp.active} onChange={e=>setCamp({...camp,active:e.target.checked})}/><span>Active</span></label><label className="check-field"><input type="checkbox" checked={!!camp.marketplace_visible} onChange={e=>setCamp({...camp,marketplace_visible:e.target.checked})}/><span>Marketplace Visible</span></label><div className="full"><button className="btn primary">Save Camping Property</button></div></form></Section>}
 {tab==='Camp Units'&&<><Section title="Add Camp / Tent Type" meta="Single-person supported"><form className="card admin-form" onSubmit={addUnit}><Field label="Camp / Tent Name"><input required value={unitForm.name} onChange={e=>setUnitForm({...unitForm,name:e.target.value})}/></Field><Field label="Code"><input value={unitForm.code} onChange={e=>setUnitForm({...unitForm,code:e.target.value})}/></Field><Field label="Max Guests"><input type="number" min="1" value={unitForm.max_guests} onChange={e=>setUnitForm({...unitForm,max_guests:Math.max(1,Number(e.target.value)||1)})}/></Field><Field label="Max Adults"><input type="number" min="1" value={unitForm.max_adults} onChange={e=>setUnitForm({...unitForm,max_adults:Math.max(1,Number(e.target.value)||1)})}/></Field><Field label="Max Children"><input type="number" min="0" value={unitForm.max_children} onChange={e=>setUnitForm({...unitForm,max_children:Math.max(0,Number(e.target.value)||0)})}/></Field><Field label="Number of Camps"><input type="number" min="0" value={unitForm.unit_count} onChange={e=>setUnitForm({...unitForm,unit_count:Math.max(0,Number(e.target.value)||0)})}/></Field><Field label="Base Per-person Rate"><input type="number" min="0" value={unitForm.base_rate} onChange={e=>setUnitForm({...unitForm,base_rate:Math.max(0,Number(e.target.value)||0)})}/></Field><Field label="Image URL"><input value={unitForm.image_urls?.[0]||''} onChange={e=>setUnitForm({...unitForm,image_urls:e.target.value?[e.target.value]:[]})}/></Field><Field label="Description"><textarea value={unitForm.description} onChange={e=>setUnitForm({...unitForm,description:e.target.value})}/></Field><div className="full"><button className="btn primary">Add Camp / Tent</button></div></form></Section><Section title="Camp Catalog" meta={`${units.length} units`}><Table columns={['Name','Capacity','Units','Base Rate','Active']} rows={units.map(u=>[u.name,`${u.max_adults} adults · ${u.max_children} children`,u.unit_count,money(u.base_rate),u.active?'Yes':'No'])}/></Section></>}
 {tab==='Rates'&&<><Section title="Create Camping Rate Plan" meta="Per-person is the default; per-unit remains available when a camp sells the whole tent/unit."><form className="card admin-form" onSubmit={addRate}><Field label="Name"><input required value={rateForm.name} onChange={e=>setRateForm({...rateForm,name:e.target.value})}/></Field><Field label="Code"><input value={rateForm.code} onChange={e=>setRateForm({...rateForm,code:e.target.value})}/></Field><Field label="Camp / Tent"><select value={rateForm.unit_type_id} onChange={e=>setRateForm({...rateForm,unit_type_id:e.target.value})}><option value="">Select camp</option>{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="Pricing Mode"><select value={rateForm.pricing_mode} onChange={e=>setRateForm({...rateForm,pricing_mode:e.target.value})}><option value="per_person">Per Person</option><option value="per_unit">Per Camp / Unit</option></select></Field><Field label="Rate"><input type="number" min="0" value={rateForm.rate} onChange={e=>setRateForm({...rateForm,rate:Number(e.target.value)||0})}/></Field><Field label="Weekend Rate"><input type="number" min="0" value={rateForm.weekend_rate} onChange={e=>setRateForm({...rateForm,weekend_rate:Number(e.target.value)||0})}/></Field><Field label="Season Multiplier"><input type="number" min="0.01" step="0.01" value={rateForm.seasonal_multiplier} onChange={e=>setRateForm({...rateForm,seasonal_multiplier:Number(e.target.value)||1})}/></Field><Field label="Minimum Stay"><input type="number" min="1" value={rateForm.min_stay} onChange={e=>setRateForm({...rateForm,min_stay:Math.max(1,Number(e.target.value)||1)})}/></Field><div className="full"><button className="btn primary">Create Rate Plan</button></div></form></Section><Section title="Camping Rates" meta={`${rates.length} live`}><Table columns={['Name','Camp','Mode','Rate','Weekend','Active']} rows={rates.map(r=>[r.name,r.camp_unit_types?.name||r.unit_type_id,r.pricing_mode,money(r.rate),money(r.weekend_rate),r.active?'Yes':'No'])}/></Section></>}
 {tab==='Availability'&&<><Section title="Generate Live Camping Inventory" meta="Date-wise tent/camp inventory"><form className="card admin-form" onSubmit={generateInventory}><Field label="Camp / Tent"><select required value={invForm.unit_type_id} onChange={e=>setInvForm({...invForm,unit_type_id:e.target.value})}><option value="">Select camp</option>{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field><Field label="From"><input type="date" value={invForm.from} onChange={e=>setInvForm({...invForm,from:e.target.value})}/></Field><Field label="To"><input type="date" value={invForm.to} onChange={e=>setInvForm({...invForm,to:e.target.value})}/></Field><Field label="Total Camps per Day"><input type="number" min="0" value={invForm.total_units} onChange={e=>setInvForm({...invForm,total_units:Number(e.target.value)||0})}/></Field><div><button className="btn primary">Generate Inventory</button></div></form></Section><Section title="Camping Inventory" meta="Live dates"><Table columns={['Date','Camp','Total','Sold','Held','Blocked','Available']} rows={inventory.map(i=>{const u=units.find(x=>x.id===i.unit_type_id);return [i.stay_date,u?.name||i.unit_type_id,i.total_units,i.sold_units,i.held_units,i.blocked_units,Math.max(0,Number(i.total_units||0)-Number(i.sold_units||0)-Number(i.held_units||0)-Number(i.blocked_units||0))]})}/></Section></>}
 {tab==='Reservations'&&<Section title="Camping Reservation Control Center" meta="Live bookings"><Table columns={['Code','Guest','Dates','Guests','Camp','Status','Payment','Total']} rows={reservations.map(r=>[r.reservation_code,r.guest_name,`${r.check_in} → ${r.check_out}`,`${r.adults}/${r.children}`,units.find(u=>u.id===r.unit_type_id)?.name||r.unit_type_id,<Pill>{r.status}</Pill>,<Pill>{r.payment_status}</Pill>,money(r.total_amount)])}/></Section>}
 {tab==='Policies'&&<Section title="Camping Booking Policies" meta="Business rules"><div className="mini-grid"><div className="mini"><b>Single guest</b><span>Minimum 1 adult; per-person rates can calculate for exactly one guest.</span></div><div className="mini"><b>Availability</b><span>Inventory is checked for every night before a booking hold.</span></div><div className="mini"><b>Payment</b><span>Pay at camp, bank transfer and QR proof are supported.</span></div><div className="mini"><b>Confirmation</b><span>OTP verification → hold → payment choice → confirmation.</span></div></div></Section>}
 </>}</div><style jsx global>{`.booking-engine-admin-shell .tabs{position:sticky;top:0;z-index:8;background:var(--bg,#f7f5ef);padding:10px 0;overflow-x:auto;display:flex;gap:7px}.booking-engine-admin-shell .tabs .btn{white-space:nowrap;flex:0 0 auto}.booking-engine-admin-shell .admin-form{min-width:0}.booking-engine-admin-shell textarea{min-height:90px;resize:vertical}.booking-engine-admin-shell table{min-width:760px}@media(max-width:900px){.booking-engine-admin-shell .kpis{grid-template-columns:repeat(2,minmax(0,1fr))}.booking-engine-admin-shell .admin-form{grid-template-columns:1fr 1fr}}@media(max-width:600px){.booking-engine-admin-shell .kpis{grid-template-columns:1fr}.booking-engine-admin-shell .tabs{margin:0 -12px;padding:8px 12px}.booking-engine-admin-shell .tabs .btn{font-size:11px;padding:8px 10px}.booking-engine-admin-shell .admin-form{grid-template-columns:1fr!important}.booking-engine-admin-shell .mini-grid{grid-template-columns:1fr!important}}`}</style></AppShell>
}
