create or replace function public.anaira_can_access_tenant(p_tenant_id uuid)
returns boolean language sql stable security definer set search_path=public as $$
select exists(select 1 from public.profiles p where p.id=auth.uid() and (p.is_super_admin=true or p.restaurant_id=p_tenant_id));
$$;
revoke all on function public.anaira_can_access_tenant(uuid) from public;
grant execute on function public.anaira_can_access_tenant(uuid) to authenticated;
create table if not exists public.anaira_roles(role_key text primary key,name text not null,scope text not null default 'tenant',description text,created_at timestamptz not null default now());
create table if not exists public.anaira_permissions(permission_key text primary key,name text not null,module text not null,description text,created_at timestamptz not null default now());
create table if not exists public.anaira_role_permissions(role_key text not null references public.anaira_roles(role_key) on delete cascade,permission_key text not null references public.anaira_permissions(permission_key) on delete cascade,primary key(role_key,permission_key));
create table if not exists public.anaira_user_permissions(user_id uuid not null references auth.users(id) on delete cascade,restaurant_id uuid not null references public.restaurants(id) on delete cascade,permission_key text not null references public.anaira_permissions(permission_key) on delete cascade,allowed boolean not null default true,created_at timestamptz not null default now(),primary key(user_id,restaurant_id,permission_key));
insert into public.anaira_roles(role_key,name,scope,description) values ('super_admin','Super Admin','platform','Anaira platform owner with cross-tenant control'),('admin','Business Admin','tenant','Full operational administration for the assigned hotel or restaurant'),('manager','Manager','tenant','Operational management within assigned business'),('staff','Staff','tenant','Restricted day-to-day operational access') on conflict(role_key) do update set name=excluded.name,scope=excluded.scope,description=excluded.description;
insert into public.anaira_permissions(permission_key,name,module,description) values ('business.view','View business','core','Access assigned business dashboard'),('business.settings','Manage business settings','core','Edit business settings'),('staff.manage','Manage staff','core','Create and manage business users'),('crm.view','View CRM','crm','Access CRM customer and relationship data'),('crm.manage','Manage CRM','crm','Create/update CRM records'),('booking.view','View bookings','hotel-booking','Access hotel bookings'),('booking.manage','Manage bookings','hotel-booking','Create/update/cancel hotel bookings'),('pms.manage','Manage PMS','hotel-pms','Manage rooms, stays and housekeeping'),('reservation.manage','Manage restaurant reservations','restaurant-reservation','Manage tables and reservations'),('pos.manage','Manage POS','anaira-pos','Operate restaurant POS'),('delivery.manage','Manage delivery','food-delivery','Manage delivery orders and riders'),('store.manage','Manage restaurant store','restaurant-store','Manage storefront'),('ota.manage','Manage OTA','channel-manager','Manage channel distribution'),('reports.view','View reports','analytics','View operational and financial reports') on conflict(permission_key) do update set name=excluded.name,module=excluded.module,description=excluded.description;
insert into public.anaira_role_permissions(role_key,permission_key) select 'admin',permission_key from public.anaira_permissions on conflict do nothing;
insert into public.anaira_role_permissions(role_key,permission_key) select 'manager',permission_key from public.anaira_permissions where permission_key in ('business.view','crm.view','crm.manage','booking.view','booking.manage','pms.manage','reservation.manage','pos.manage','delivery.manage','store.manage','ota.manage','reports.view') on conflict do nothing;
insert into public.anaira_role_permissions(role_key,permission_key) select 'staff',permission_key from public.anaira_permissions where permission_key in ('business.view','crm.view','booking.view') on conflict do nothing;
alter table public.anaira_roles enable row level security; alter table public.anaira_permissions enable row level security; alter table public.anaira_role_permissions enable row level security; alter table public.anaira_user_permissions enable row level security;
create policy "roles authenticated read" on public.anaira_roles for select to authenticated using(true);
create policy "permissions authenticated read" on public.anaira_permissions for select to authenticated using(true);
create policy "role permissions authenticated read" on public.anaira_role_permissions for select to authenticated using(true);
create policy "user permissions tenant access" on public.anaira_user_permissions for all to authenticated using(public.anaira_can_access_tenant(restaurant_id)) with check(public.anaira_can_access_tenant(restaurant_id));
create or replace function public.anaira_set_user_permission(p_user_id uuid,p_restaurant_id uuid,p_permission_key text,p_allowed boolean) returns void language plpgsql security definer set search_path=public as $$ begin if not exists(select 1 from public.profiles p where p.id=auth.uid() and (p.is_super_admin=true or (p.restaurant_id=p_restaurant_id and p.role in ('admin','super_admin')))) then raise exception 'ADMIN_REQUIRED'; end if; insert into public.anaira_user_permissions(user_id,restaurant_id,permission_key,allowed) values(p_user_id,p_restaurant_id,p_permission_key,p_allowed) on conflict(user_id,restaurant_id,permission_key) do update set allowed=excluded.allowed; end; $$;
revoke all on function public.anaira_set_user_permission(uuid,uuid,text,boolean) from public; grant execute on function public.anaira_set_user_permission(uuid,uuid,text,boolean) to authenticated;
create or replace function public.anaira_user_has_permission(p_permission_key text) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_super_admin=true) or exists(select 1 from public.profiles p where p.id=auth.uid() and coalesce((select up.allowed from public.anaira_user_permissions up where up.user_id=p.id and up.restaurant_id=p.restaurant_id and up.permission_key=p_permission_key limit 1),exists(select 1 from public.anaira_role_permissions rp where rp.role_key=p.role and rp.permission_key=p_permission_key))=true); $$;
revoke all on function public.anaira_user_has_permission(text) from public; grant execute on function public.anaira_user_has_permission(text) to authenticated;
