alter table public.anaira_store_memberships add column if not exists catalog_source text not null default 'anaira_pos', add column if not exists integration_connection_id uuid references public.anaira_integration_connections_v2(id) on delete set null, add column if not exists manual_catalog_enabled boolean not null default false, add column if not exists store_config jsonb not null default '{}'::jsonb, add column if not exists image_config jsonb not null default '{}'::jsonb, add column if not exists last_sync_at timestamptz, add column if not exists sync_status text not null default 'not_configured';
alter table public.anaira_platform_stores add column if not exists builder_mode text not null default 'admin_builder', add column if not exists public_path text, add column if not exists settings jsonb not null default '{}'::jsonb;
create index if not exists anaira_store_membership_source_idx on public.anaira_store_memberships(store_id,catalog_source,enabled);
create index if not exists anaira_store_membership_connection_idx on public.anaira_store_memberships(integration_connection_id);
create table if not exists public.anaira_store_activity_log (id uuid primary key default gen_random_uuid(),store_id uuid not null references public.anaira_platform_stores(id) on delete cascade,restaurant_id uuid references public.restaurants(id) on delete set null,actor_user_id uuid references auth.users(id) on delete set null,action text not null,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
alter table public.anaira_store_activity_log enable row level security;
drop policy if exists anaira_store_activity_admin on public.anaira_store_activity_log;
create policy anaira_store_activity_admin on public.anaira_store_activity_log for all to authenticated using(anaira_current_is_super_admin() or restaurant_id=anaira_current_restaurant_id()) with check(anaira_current_is_super_admin() or restaurant_id=anaira_current_restaurant_id());
create index if not exists anaira_store_activity_idx on public.anaira_store_activity_log(store_id,created_at desc);
