-- CRM domain separation + transactional booking/reservation hardening.
-- Shared identity: crm_customers. Hotel lifecycle: crm_guest_stays. Restaurant lifecycle: crm_restaurant_visits.
-- The public booking/reservation functions remain provider-neutral and emit CRM/platform events.

-- See live database for the exact deployed definitions. This migration is the source-controlled record.

-- Customer 360 aggregation function
create or replace function public.anaira_get_customer_360(p_tenant_id uuid,p_customer_id uuid)
returns jsonb language plpgsql security invoker set search_path=public,pg_temp as $$
declare c jsonb; hotel jsonb; restaurant jsonb;
begin
 select to_jsonb(x) into c from (select id,full_name,phone,email,customer_type,vip,total_hotel_revenue,total_restaurant_revenue,total_stays,total_restaurant_visits,created_at,updated_at from public.crm_customers where tenant_id=p_tenant_id and id=p_customer_id) x;
 if c is null then raise exception 'Customer not found'; end if;
 select jsonb_build_object('stay_count',count(*),'hotel_revenue',coalesce(sum(total_amount),0),'stays',coalesce(jsonb_agg(to_jsonb(s) order by check_in_date desc) filter(where s.id is not null),'[]'::jsonb)) into hotel from (select id,room_number,booking_status,check_in_date,check_out_date,booking_source,total_amount,special_requests from public.crm_guest_stays where tenant_id=p_tenant_id and customer_id=p_customer_id order by check_in_date desc limit 100) s;
 select jsonb_build_object('visit_count',count(*),'restaurant_revenue',coalesce(sum(amount),0),'visits',coalesce(jsonb_agg(to_jsonb(v) order by visit_at desc) filter(where v.id is not null),'[]'::jsonb)) into restaurant from (select id,outlet_id,table_number,visit_at,guest_count,order_id,amount,payment_method from public.crm_restaurant_visits where tenant_id=p_tenant_id and customer_id=p_customer_id order by visit_at desc limit 100) v;
 return jsonb_build_object('customer',c,'hotel',hotel,'restaurant',restaurant,'separation',jsonb_build_object('shared_identity','crm_customers','hotel_domain','crm_guest_stays','restaurant_domain','crm_restaurant_visits','cross_domain_via','Customer 360 / events only'));
end; $$;

-- Transactional hotel booking: validate capacity + lock each inventory night + create PMS/CRM records atomically.
drop function if exists public.anaira_create_public_booking(text,text,text,text,date,date,uuid,integer,integer,text);
drop function if exists public.anaira_create_public_booking_by_id(uuid,text,text,text,date,date,uuid,integer,integer,text);
create or replace function public.anaira_create_public_booking_by_id(p_restaurant_id uuid,p_guest_name text,p_guest_phone text,p_guest_email text,p_check_in date,p_check_out date,p_room_type_id uuid,p_adults integer,p_children integer,p_source text)
returns public.booking_reservations language plpgsql security definer set search_path=public,pg_temp as $$
declare r public.restaurants; rt public.booking_room_types; rec public.booking_reservations; cid uuid; code text; nights integer; day date; inv public.booking_inventory%rowtype; pms_id uuid;
begin
 select * into r from public.restaurants where id=p_restaurant_id and status='active'; if r.id is null then raise exception 'Property not found'; end if;
 if p_check_out<=p_check_in then raise exception 'Invalid stay dates'; end if;
 if p_adults<=0 or p_children<0 then raise exception 'Invalid guest count'; end if;
 select * into rt from public.booking_room_types where id=p_room_type_id and restaurant_id=p_restaurant_id and active=true; if rt.id is null then raise exception 'Room type not found'; end if;
 if rt.max_occupancy < p_adults+p_children then raise exception 'Guest capacity exceeded'; end if;
 nights:=p_check_out-p_check_in;
 for day in select generate_series(p_check_in,p_check_out-1,interval '1 day')::date loop
  select * into inv from public.booking_inventory where restaurant_id=p_restaurant_id and room_type_id=p_room_type_id and stay_date=day for update;
  if inv.id is null or inv.closed or inv.total_rooms-inv.booked_rooms-inv.held_rooms<=0 then raise exception 'Room inventory unavailable for %',day; end if;
 end loop;
 cid:=public.anaira_resolve_crm_customer(p_restaurant_id,p_guest_name,p_guest_phone,p_guest_email);
 code:='ANB-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,10));
 insert into public.booking_reservations(restaurant_id,booking_code,customer_id,room_type_id,check_in,check_out,adults,children,guest_name,guest_phone,guest_email,status,payment_status,total_amount,source) values(p_restaurant_id,code,cid,rt.id,p_check_in,p_check_out,p_adults,p_children,p_guest_name,p_guest_phone,p_guest_email,'pending','unpaid',rt.base_rate*nights,p_source) returning * into rec;
 update public.booking_inventory set booked_rooms=booked_rooms+1 where restaurant_id=p_restaurant_id and room_type_id=p_room_type_id and stay_date>=p_check_in and stay_date<p_check_out;
 insert into public.pms_reservations(restaurant_id,booking_code,guest_name,guest_phone,check_in,check_out,status,source,total_amount,metadata) values(p_restaurant_id,rec.booking_code,p_guest_name,p_guest_phone,p_check_in,p_check_out,'reserved','anaira-booking-engine',rec.total_amount,jsonb_build_object('booking_reservation_id',rec.id,'customer_id',cid,'room_type_id',rt.id)) returning id into pms_id;
 insert into public.crm_guest_stays(tenant_id,customer_id,external_booking_id,property_id,room_type_id,check_in_date,check_out_date,nights,booking_source,booking_status,total_amount) values(p_restaurant_id,cid,rec.id::text,p_restaurant_id,rt.id,p_check_in,p_check_out,nights,p_source,'reserved',rec.total_amount);
 insert into public.anaira_integration_links(tenant_id,source_system,source_entity,source_id,target_system,target_entity,target_id) values(p_restaurant_id,'hotel-booking','booking',rec.id,'hotel-pms','reservation',pms_id) on conflict do nothing;
 insert into public.crm_interactions(customer_id,channel,interaction_type,subject,notes) values(cid,'booking_engine','hotel_booking','New hotel booking',jsonb_build_object('booking_id',rec.id,'booking_code',rec.booking_code,'pms_reservation_id',pms_id)::text);
 insert into public.anaira_platform_events(restaurant_id,event_name,source_plugin,aggregate_type,aggregate_id,payload) values(p_restaurant_id,'booking.created','hotel-booking','booking',rec.id,jsonb_build_object('booking_id',rec.id,'booking_code',rec.booking_code,'customer_id',cid,'room_type_id',rt.id,'check_in',p_check_in,'check_out',p_check_out,'pms_reservation_id',pms_id)),(p_restaurant_id,'crm.customer.booking_created','hotel-booking','customer',cid,jsonb_build_object('booking_id',rec.id,'booking_code',rec.booking_code)),(p_restaurant_id,'payment.authorization_required','hotel-booking','booking',rec.id,jsonb_build_object('amount',rec.total_amount,'currency','INR'));
 return rec;
end; $$;
create or replace function public.anaira_create_public_booking(p_slug text,p_guest_name text,p_guest_phone text,p_guest_email text,p_check_in date,p_check_out date,p_room_type_id uuid,p_adults integer,p_children integer,p_source text default 'direct') returns public.booking_reservations language plpgsql security definer set search_path=public,pg_temp as $$ declare r public.restaurants; rec public.booking_reservations; begin select * into r from public.restaurants where slug=p_slug and status='active' limit 1; if r.id is null then raise exception 'Property not found'; end if; select * into rec from public.anaira_create_public_booking_by_id(r.id,p_guest_name,p_guest_phone,p_guest_email,p_check_in,p_check_out,p_room_type_id,p_adults,p_children,p_source); return rec; end; $$;

-- Restaurant reservation: reject past/invalid requests and enforce actual table-slot availability.
drop function if exists public.anaira_create_public_restaurant_reservation(text,text,text,text,date,time,integer,text);
drop function if exists public.anaira_create_public_restaurant_reservation_by_id(uuid,text,text,text,date,time,integer,text);
create or replace function public.anaira_create_public_restaurant_reservation_by_id(p_restaurant_id uuid,p_guest_name text,p_guest_phone text,p_guest_email text,p_date date,p_time time,p_party_size integer,p_source text default 'anaira_marketplace') returns public.restaurant_reservations language plpgsql security definer set search_path=public,pg_temp as $$ declare r public.restaurants; rec public.restaurant_reservations; cid uuid; code text; begin select * into r from public.restaurants where id=p_restaurant_id and status='active'; if r.id is null then raise exception 'Restaurant not found'; end if; if p_date<current_date then raise exception 'Reservation date cannot be in the past'; end if; if p_party_size<=0 then raise exception 'Party size must be positive'; end if; if not exists(select 1 from public.anaira_marketplace_listings where restaurant_id=p_restaurant_id and marketplace_visible=true and approval_status='approved' and restaurant_reservation_enabled=true) then raise exception 'Restaurant reservation is not enabled'; end if; if not public.anaira_phase1_reservation_slot_available(p_restaurant_id,p_date,p_time,p_party_size,90) then raise exception 'No table available for this slot'; end if; cid:=public.anaira_resolve_crm_customer(p_restaurant_id,p_guest_name,p_guest_phone,p_guest_email); code:='ANR-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,10)); insert into public.restaurant_reservations(restaurant_id,reservation_code,customer_id,guest_name,guest_phone,guest_email,reservation_date,reservation_time,party_size,duration_minutes,status,source) values(p_restaurant_id,code,cid,p_guest_name,p_guest_phone,p_guest_email,p_date,p_time,p_party_size,90,'confirmed',p_source) returning * into rec; insert into public.crm_interactions(customer_id,channel,interaction_type,subject,notes) values(cid,'restaurant_reservation','restaurant_reservation','New restaurant reservation',jsonb_build_object('reservation_id',rec.id,'reservation_code',rec.reservation_code,'party_size',p_party_size)::text); insert into public.anaira_platform_events(restaurant_id,event_name,source_plugin,aggregate_type,aggregate_id,payload) values(p_restaurant_id,'restaurant.reservation.created','restaurant-reservation','reservation',rec.id,jsonb_build_object('reservation_id',rec.id,'reservation_code',rec.reservation_code,'customer_id',cid,'party_size',p_party_size)); return rec; end; $$;
create or replace function public.anaira_create_public_restaurant_reservation(p_slug text,p_guest_name text,p_guest_phone text,p_guest_email text,p_date date,p_time time,p_party_size integer,p_source text default 'direct') returns public.restaurant_reservations language plpgsql security definer set search_path=public,pg_temp as $$ declare r public.restaurants; rec public.restaurant_reservations; begin select * into r from public.restaurants where slug=p_slug and status='active' limit 1; if r.id is null then raise exception 'Restaurant not found'; end if; select * into rec from public.anaira_create_public_restaurant_reservation_by_id(r.id,p_guest_name,p_guest_phone,p_guest_email,p_date,p_time,p_party_size,p_source); return rec; end; $$;
