-- Fix: hms_room_inventory_blocks is room-scoped; resolve room type through hms_rooms.room_type_id.
-- Live equivalent has already been applied; this migration keeps the ZIP source consistent.
create or replace function public.anaira_inventory_dashboard(p_restaurant_id uuid,p_start date,p_end date)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare result jsonb;
begin
 if auth.uid() is null then raise exception 'Authentication required'; end if;
 if not(p_restaurant_id=public.anaira_current_restaurant_id() or public.anaira_current_is_super_admin()) then raise exception 'Tenant access denied'; end if;
 perform public.anaira_sync_hotel_inventory_range(p_restaurant_id,p_start,p_end);
 select jsonb_build_object(
 'timezone','Asia/Kolkata',
 'india_today',(now() at time zone 'Asia/Kolkata')::date,
 'room_types',coalesce((select jsonb_agg(jsonb_build_object('id',rt.id,'name',rt.name,'code',rt.code,'rooms',coalesce((select jsonb_agg(jsonb_build_object('id',rm.id,'room_number',rm.room_number,'floor',rm.floor,'building',rm.building,'status',rm.status,'housekeeping_status',rm.housekeeping_status,'active',rm.active,'booking_enabled',coalesce(rm.booking_enabled,true),'booking_block_reason',rm.booking_block_reason,'effective_status',case when exists(select 1 from public.hms_reservations r where r.restaurant_id=p_restaurant_id and r.room_id=rm.id and r.check_in<=p_start and r.check_out>p_start and lower(r.status)='checked_in') then 'occupied' when exists(select 1 from public.hms_reservations r where r.restaurant_id=p_restaurant_id and r.room_id=rm.id and r.check_in<=p_start and r.check_out>p_start and lower(r.status)='confirmed') then 'reserved' when lower(coalesce(rm.status,'')) in ('maintenance','out_of_order') then rm.status when exists(select 1 from public.hms_room_inventory_blocks b where b.room_id=rm.id and b.stay_date=p_start and b.active) then 'blocked' when coalesce(rm.booking_enabled,true)=false then 'blocked' when lower(coalesce(rm.housekeeping_status,'')) not in ('clean','inspected') then rm.housekeeping_status else 'available' end,'effective_housekeeping_status',case when exists(select 1 from public.hms_reservations r where r.restaurant_id=p_restaurant_id and r.room_id=rm.id and r.check_in<=p_start and r.check_out>p_start and lower(r.status)='checked_in') then 'dirty' else rm.housekeeping_status end) order by rm.room_number) from public.hms_rooms rm where rm.restaurant_id=rt.restaurant_id and rm.room_type_id=rt.id and coalesce(rm.active,true)),'[]'::jsonb)) order by rt.name) from public.hms_room_types rt where rt.restaurant_id=p_restaurant_id),'[]'::jsonb),
 'inventory',coalesce((select jsonb_agg(jsonb_build_object('stay_date',i.stay_date,'room_type_id',i.room_type_id,'total_rooms',i.total_rooms,'sold_rooms',i.sold_rooms,'blocked_rooms',i.blocked_rooms,'closed',i.closed,'stop_sell',i.stop_sell,'close_on_arrival',i.close_on_arrival,'close_on_departure',i.close_on_departure,'cutoff_hours',i.cutoff_hours,'available_rooms',greatest(0,i.total_rooms-i.sold_rooms-i.blocked_rooms-coalesce((select count(*) from public.hms_room_inventory_blocks b join public.hms_rooms rm on rm.id=b.room_id where b.restaurant_id=p_restaurant_id and rm.room_type_id=i.room_type_id and b.stay_date=i.stay_date and b.active),0))) order by i.stay_date,i.room_type_id) from public.hms_inventory i where i.restaurant_id=p_restaurant_id and i.stay_date>=p_start and i.stay_date<p_end),'[]'::jsonb),
 'reservations',coalesce((select jsonb_agg(jsonb_build_object('id',r.id,'reservation_code',r.reservation_code,'room_type_id',r.room_type_id,'room_id',r.room_id,'room_number',rm.room_number,'status',r.status,'check_in',r.check_in,'check_out',r.check_out,'guest_name',g.full_name,'guest_phone',g.phone) order by r.check_in,r.reservation_code) from public.hms_reservations r left join public.hms_guests g on g.id=r.guest_id left join public.hms_rooms rm on rm.id=r.room_id where r.restaurant_id=p_restaurant_id and r.check_in<p_end and r.check_out>p_start and lower(coalesce(r.status,'')) in ('confirmed','checked_in')),'[]'::jsonb)
 ) into result;
 return result;
end $$;
revoke all on function public.anaira_inventory_dashboard(uuid,date,date) from public;
grant execute on function public.anaira_inventory_dashboard(uuid,date,date) to authenticated;
