-- Anaira Partner CRM full runtime closure: onboarding/KYC, contracts, attribution,
-- idempotent commission, settlement approval/payout, statements and reconciliation.
alter table public.crm_partners add column if not exists kyc_status text not null default 'pending';
alter table public.crm_partners add column if not exists kyc_data jsonb not null default '{}'::jsonb;
alter table public.crm_partners add column if not exists contract_status text not null default 'none';
alter table public.crm_partners add column if not exists contract_expiry date;
alter table public.crm_partners add column if not exists account_manager_id uuid;
alter table public.crm_partners add column if not exists notes text;
alter table public.crm_partner_bookings add column if not exists idempotency_key text;
alter table public.crm_partner_bookings add column if not exists reservation_id uuid;
alter table public.crm_partner_bookings add column if not exists commission_rate numeric not null default 0;
alter table public.crm_partner_bookings add column if not exists commission_status text not null default 'pending';
alter table public.crm_partner_bookings add column if not exists cancellation_amount numeric not null default 0;
alter table public.crm_partner_bookings add column if not exists attribution_source text;
alter table public.crm_partner_bookings add column if not exists updated_at timestamptz not null default now();
create unique index if not exists crm_partner_booking_idempotency_uq on public.crm_partner_bookings(tenant_id,idempotency_key) where idempotency_key is not null;
alter table public.crm_partner_settlements add column if not exists approved_by uuid;
alter table public.crm_partner_settlements add column if not exists approved_at timestamptz;
alter table public.crm_partner_settlements add column if not exists payout_amount numeric not null default 0;
alter table public.crm_partner_settlements add column if not exists payout_reference text;
alter table public.crm_partner_settlements add column if not exists reconciled_at timestamptz;
create table if not exists public.crm_partner_contracts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,property_id uuid,partner_id uuid not null references public.crm_partners(id) on delete cascade,contract_number text not null,start_date date not null default current_date,end_date date,terms jsonb not null default '{}'::jsonb,status text not null default 'draft',approved_by uuid,approved_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.crm_partner_commission_rules(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,property_id uuid,partner_id uuid not null references public.crm_partners(id) on delete cascade,name text not null,commission_type text not null default 'percent',commission_value numeric not null default 0,applies_to text not null default 'booking',active boolean not null default true,valid_from date not null default current_date,valid_to date,created_at timestamptz not null default now());
create table if not exists public.crm_partner_booking_events(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,property_id uuid,partner_booking_id uuid not null references public.crm_partner_bookings(id) on delete cascade,event_type text not null,payload jsonb not null default '{}'::jsonb,idempotency_key text,created_at timestamptz not null default now());
create unique index if not exists crm_partner_booking_events_idem_uq on public.crm_partner_booking_events(tenant_id,idempotency_key) where idempotency_key is not null;
create table if not exists public.crm_partner_payouts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,property_id uuid,partner_id uuid not null references public.crm_partners(id) on delete cascade,settlement_id uuid references public.crm_partner_settlements(id) on delete set null,amount numeric not null default 0,status text not null default 'pending',payout_reference text,approved_by uuid,approved_at timestamptz,paid_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.crm_partner_statements(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,property_id uuid,partner_id uuid not null references public.crm_partners(id) on delete cascade,statement_number text not null,period_start date not null,period_end date not null,gross_amount numeric not null default 0,commission_amount numeric not null default 0,adjustments numeric not null default 0,net_payable numeric not null default 0,created_at timestamptz not null default now());
create unique index if not exists crm_partner_statements_number_uq on public.crm_partner_statements(tenant_id,statement_number);
create table if not exists public.crm_partner_reconciliation(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,property_id uuid,partner_id uuid not null references public.crm_partners(id) on delete cascade,settlement_id uuid references public.crm_partner_settlements(id) on delete set null,expected_commission numeric not null default 0,actual_commission numeric not null default 0,difference numeric generated always as (actual_commission-expected_commission) stored,status text not null default 'open',notes text,created_at timestamptz not null default now(),reconciled_at timestamptz);
create table if not exists public.crm_partner_kyc_events(id uuid primary key default gen_random_uuid(),tenant_id uuid not null,property_id uuid,partner_id uuid not null references public.crm_partners(id) on delete cascade,status text not null,payload jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());

do $$ declare t text; begin foreach t in array array['crm_partners','crm_partner_bookings','crm_partner_settlements','crm_partner_contracts','crm_partner_commission_rules','crm_partner_booking_events','crm_partner_payouts','crm_partner_statements','crm_partner_reconciliation','crm_partner_kyc_events'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists %I on public.%I',t||'_scope',t); execute format('create policy %I on public.%I for all to authenticated using(anaira_can_access_tenant(tenant_id)) with check(anaira_can_access_tenant(tenant_id))',t||'_scope',t); end loop; end $$;
create index if not exists crm_partner_bookings_scope_idx on public.crm_partner_bookings(tenant_id,property_id,partner_id,created_at desc);
create index if not exists crm_partner_contracts_scope_idx on public.crm_partner_contracts(tenant_id,property_id,partner_id,end_date);
create index if not exists crm_partner_commission_rules_scope_idx on public.crm_partner_commission_rules(tenant_id,property_id,partner_id,active);
create index if not exists crm_partner_settlements_scope_idx on public.crm_partner_settlements(tenant_id,property_id,partner_id,period_end desc);
create index if not exists crm_partner_payouts_scope_idx on public.crm_partner_payouts(tenant_id,property_id,partner_id,created_at desc);

create or replace function public.anaira_partner_onboard(p_partner_id uuid,p_kyc_status text default 'approved') returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare p public.crm_partners%rowtype; begin select * into p from public.crm_partners where id=p_partner_id for update; if not found or not ana​ira_can_access_tenant(p.tenant_id) then raise exception 'Unauthorized or partner not found'; end if; update public.crm_partners set kyc_status=p_kyc_status,contract_status=case when p_kyc_status='approved' then 'pending' else contract_status end,active=case when p_kyc_status='approved' then true else active end where id=p.id returning * into p; insert into public.crm_partner_kyc_events(tenant_id,property_id,partner_id,status,payload) values(p.tenant_id,p.property_id,p.id,p_kyc_status,jsonb_build_object('actor',auth.uid())); insert into public.crm_audit_logs(tenant_id,property_id,action,entity_type,entity_id,after_data) values(p.tenant_id,p.property_id,'partner_onboard','crm_partners',p.id,to_jsonb(p)); return jsonb_build_object('ok',true,'partner_id',p.id,'kyc_status',p.kyc_status); end $$;
revoke all on function public.anaira_partner_onboard(uuid,text) from public; grant execute on function public.anaira_partner_onboard(uuid,text) to authenticated;

create or replace function public.anaira_partner_contract_action(p_partner_id uuid,p_action text,p_end_date date default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare p public.crm_partners%rowtype; c public.crm_partner_contracts%rowtype; cid uuid; begin select * into p from public.crm_partners where id=p_partner_id for update; if not found or not ana​ira_can_access_tenant(p.tenant_id) then raise exception 'Unauthorized or partner not found'; end if; if p_action='create' then insert into public.crm_partner_contracts(tenant_id,property_id,partner_id,contract_number,start_date,end_date,status) values(p.tenant_id,p.property_id,p.id,'PARTNER-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS'),current_date,coalesce(p_end_date,current_date+365),'draft') returning * into c; elsif p_action='approve' then select id into cid from public.crm_partner_contracts where partner_id=p.id and tenant_id=p.tenant_id and status='draft' order by end_date desc limit 1; if cid is null then raise exception 'No draft contract'; end if; update public.crm_partner_contracts set status='active',approved_by=auth.uid(),approved_at=now() where id=cid returning * into c; elsif p_action='renew' then select id into cid from public.crm_partner_contracts where partner_id=p.id and tenant_id=p.tenant_id order by end_date desc limit 1; if cid is null then raise exception 'No contract'; end if; update public.crm_partner_contracts set end_date=coalesce(p_end_date,current_date+365),status='active' where id=cid returning * into c; else raise exception 'Unsupported action'; end if; update public.crm_partners set contract_status=c.status,contract_expiry=c.end_date where id=p.id; insert into public.crm_audit_logs(tenant_id,property_id,action,entity_type,entity_id,after_data) values(p.tenant_id,p.property_id,'partner_contract_'||p_action,'crm_partner_contracts',c.id,to_jsonb(c)); return jsonb_build_object('ok',true,'contract_id',c.id,'status',c.status,'end_date',c.end_date); end $$;
revoke all on function public.anaira_partner_contract_action(uuid,text,date) from public; grant execute on function public.anaira_partner_contract_action(uuid,text,date) to authenticated;

create or replace function public.anaira_partner_upsert_booking(p_partner_id uuid,p_booking_reference text,p_booking_amount numeric,p_customer_id uuid default null,p_property_id uuid default null,p_idempotency_key text default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare p public.crm_partners%rowtype; r public.crm_partner_bookings%rowtype; rate numeric; comm numeric; begin select * into p from public.crm_partners where id=p_partner_id; if not found or not ana​ira_can_access_tenant(p.tenant_id) then raise exception 'Unauthorized or partner not found'; end if; if p_idempotency_key is not null then select * into r from public.crm_partner_bookings where tenant_id=p.tenant_id and idempotency_key=p_idempotency_key; if found then return jsonb_build_object('ok',true,'duplicate',true,'booking_id',r.id,'commission_amount',r.commission_amount); end if; end if; rate:=coalesce((select commission_value from public.crm_partner_commission_rules where partner_id=p.id and tenant_id=p.tenant_id and active and commission_type='percent' and (valid_to is null or valid_to>=current_date) and valid_from<=current_date order by created_at desc limit 1),p.commission_percent); comm:=round(coalesce(p_booking_amount,0)*coalesce(rate,0)/100,2); insert into public.crm_partner_bookings(tenant_id,property_id,partner_id,customer_id,booking_reference,booking_amount,commission_amount,commission_rate,status,commission_status,idempotency_key,attribution_source) values(p.tenant_id,coalesce(p_property_id,p.property_id),p.id,p_customer_id,p_booking_reference,coalesce(p_booking_amount,0),comm,rate,'confirmed','pending',p_idempotency_key,'partner') returning * into r; insert into public.crm_partner_booking_events(tenant_id,property_id,partner_booking_id,event_type,payload,idempotency_key) values(p.tenant_id,r.property_id,r.id,'confirmed',jsonb_build_object('booking_reference',p_booking_reference,'commission',comm),case when p_idempotency_key is null then null else p_idempotency_key||':confirmed' end) on conflict do nothing; insert into public.crm_audit_logs(tenant_id,property_id,action,entity_type,entity_id,after_data) values(p.tenant_id,r.property_id,'partner_booking_attributed','crm_partner_bookings',r.id,to_jsonb(r)); return jsonb_build_object('ok',true,'booking_id',r.id,'commission_amount',comm,'commission_rate',rate); end $$;
revoke all on function public.anaira_partner_upsert_booking(uuid,text,numeric,uuid,uuid,text) from public; grant execute on function public.anaira_partner_upsert_booking(uuid,text,numeric,uuid,uuid,text) to authenticated;

create or replace function public.anaira_partner_calculate_commission(p_booking_id uuid,p_cancelled boolean default false,p_cancellation_amount numeric default 0) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare r public.crm_partner_bookings%rowtype; comm numeric; begin select * into r from public.crm_partner_bookings where id=p_booking_id for update; if not found or not ana​ira_can_access_tenant(r.tenant_id) then raise exception 'Unauthorized or booking not found'; end if; comm:=round(greatest(0,coalesce(r.booking_amount,0)-case when p_cancelled then coalesce(p_cancellation_amount,0) else 0 end)*coalesce(r.commission_rate,0)/100,2); update public.crm_partner_bookings set commission_amount=comm,cancellation_amount=case when p_cancelled then coalesce(p_cancellation_amount,0) else cancellation_amount end,commission_status='calculated',status=case when p_cancelled then 'cancelled' else status end,updated_at=now() where id=r.id returning * into r; insert into public.crm_partner_booking_events(tenant_id,property_id,partner_booking_id,event_type,payload) values(r.tenant_id,r.property_id,r.id,case when p_cancelled then 'cancelled' else 'commission_calculated' end,jsonb_build_object('commission',comm,'cancellation_amount',p_cancellation_amount)); return jsonb_build_object('ok',true,'booking_id',r.id,'commission_amount',comm); end $$;
revoke all on function public.anaira_partner_calculate_commission(uuid,boolean,numeric) from public; grant execute on function public.anaira_partner_calculate_commission(uuid,boolean,numeric) to authenticated;

create or replace function public.anaira_partner_create_settlement(p_partner_id uuid,p_from date,p_to date) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare p public.crm_partners%rowtype; s public.crm_partner_settlements%rowtype; g numeric; c numeric; begin select * into p from public.crm_partners where id=p_partner_id; if not found or not ana​ira_can_access_tenant(p.tenant_id) then raise exception 'Unauthorized or partner not found'; end if; select coalesce(sum(booking_amount),0),coalesce(sum(commission_amount),0) into g,c from public.crm_partner_bookings where tenant_id=p.tenant_id and partner_id=p.id and created_at::date between p_from and p_to and status<>'cancelled' and commission_status<>'paid'; insert into public.crm_partner_settlements(tenant_id,property_id,partner_id,period_start,period_end,gross_amount,commission_amount,payout_amount,status) values(p.tenant_id,p.property_id,p.id,p_from,p_to,g,c,c,'pending') returning * into s; insert into public.crm_audit_logs(tenant_id,property_id,action,entity_type,entity_id,after_data) values(p.tenant_id,p.property_id,'partner_settlement_created','crm_partner_settlements',s.id,to_jsonb(s)); return to_jsonb(s); end $$;
revoke all on function public.anaira_partner_create_settlement(uuid,date,date) from public; grant execute on function public.anaira_partner_create_settlement(uuid,date,date) to authenticated;

create or replace function public.anaira_partner_settlement_action(p_settlement_id uuid,p_action text,p_reference text default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare s public.crm_partner_settlements%rowtype; po public.crm_partner_payouts%rowtype; begin select * into s from public.crm_partner_settlements where id=p_settlement_id for update; if not found or not ana​ira_can_access_tenant(s.tenant_id) then raise exception 'Unauthorized or settlement not found'; end if; if p_action='approve' then update public.crm_partner_settlements set status='approved',approved_by=auth.uid(),approved_at=now() where id=s.id returning * into s; elsif p_action='payout' then if s.status<>'approved' then raise exception 'Settlement must be approved before payout'; end if; update public.crm_partner_settlements set status='paid',settled_at=now(),payout_reference=p_reference where id=s.id returning * into s; insert into public.crm_partner_payouts(tenant_id,property_id,partner_id,settlement_id,amount,status,payout_reference,approved_by,approved_at,paid_at) values(s.tenant_id,s.property_id,s.partner_id,s.id,s.payout_amount,'paid',p_reference,auth.uid(),now(),now()) returning * into po; elsif p_action='reconcile' then update public.crm_partner_settlements set status='reconciled',reconciled_at=now() where id=s.id returning * into s; else raise exception 'Unsupported settlement action'; end if; insert into public.crm_audit_logs(tenant_id,property_id,action,entity_type,entity_id,after_data) values(s.tenant_id,s.property_id,'partner_settlement_'||p_action,'crm_partner_settlements',s.id,to_jsonb(s)); return jsonb_build_object('ok',true,'settlement_id',s.id,'status',s.status); end $$;
revoke all on function public.anaira_partner_settlement_action(uuid,text,text) from public; grant execute on function public.anaira_partner_settlement_action(uuid,text,text) to authenticated;

create or replace function public.anaira_partner_generate_statement(p_partner_id uuid,p_from date,p_to date) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare p public.crm_partners%rowtype; s public.crm_partner_statements%rowtype; g numeric; c numeric; begin select * into p from public.crm_partners where id=p_partner_id; if not found or not ana​ira_can_access_tenant(p.tenant_id) then raise exception 'Unauthorized or partner not found'; end if; select coalesce(sum(booking_amount),0),coalesce(sum(commission_amount),0) into g,c from public.crm_partner_bookings where tenant_id=p.tenant_id and partner_id=p.id and created_at::date between p_from and p_to; insert into public.crm_partner_statements(tenant_id,property_id,partner_id,statement_number,period_start,period_end,gross_amount,commission_amount,net_payable) values(p.tenant_id,p.property_id,p.id,'PSTMT-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS'),p_from,p_to,g,c,c) returning * into s; insert into public.crm_audit_logs(tenant_id,property_id,action,entity_type,entity_id,after_data) values(p.tenant_id,p.property_id,'partner_statement_generated','crm_partner_statements',s.id,to_jsonb(s)); return to_jsonb(s); end $$;
revoke all on function public.anaira_partner_generate_statement(uuid,date,date) from public; grant execute on function public.anaira_partner_generate_statement(uuid,date,date) to authenticated;

create or replace function public.anaira_partner_reconcile(p_settlement_id uuid,p_actual numeric) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$ declare s public.crm_partner_settlements%rowtype; r public.crm_partner_reconciliation%rowtype; begin select * into s from public.crm_partner_settlements where id=p_settlement_id; if not found or not ana​ira_can_access_tenant(s.tenant_id) then raise exception 'Unauthorized or settlement not found'; end if; insert into public.crm_partner_reconciliation(tenant_id,property_id,partner_id,settlement_id,expected_commission,actual_commission,status,reconciled_at) values(s.tenant_id,s.property_id,s.partner_id,s.id,s.commission_amount,coalesce(p_actual,0),case when abs(coalesce(p_actual,0)-s.commission_amount)<0.01 then 'matched' else 'variance' end,now()) returning * into r; update public.crm_partner_settlements set status='reconciled',reconciled_at=now() where id=s.id; insert into public.crm_audit_logs(tenant_id,property_id,action,entity_type,entity_id,after_data) values(s.tenant_id,s.property_id,'partner_reconciled','crm_partner_reconciliation',r.id,to_jsonb(r)); return to_jsonb(r); end $$;
revoke all on function public.anaira_partner_reconcile(uuid,numeric) from public; grant execute on function public.anaira_partner_reconcile(uuid,numeric) to authenticated;
