import {NextResponse} from 'next/server';
import {supabaseAdmin} from '../../../../lib/supabaseAdmin';
import {DOMAIN_TABLES, workflowStatus} from '../../../../components/business/domainStore';

function tableFor(type,module){ const t=DOMAIN_TABLES?.[type]?.[module]; if(!t) throw new Error('Unsupported business module'); return t; }
async function actor(req,businessId){
 const admin=supabaseAdmin(); const auth=req.headers.get('authorization')||'';
 if(!auth.startsWith('Bearer ')) return {admin,user:null,allowed:false};
 const {data:u,error}=await admin.auth.getUser(auth.slice(7).trim()); if(error||!u?.user) return {admin,user:null,allowed:false};
 const [{data:p},{data:m}]=await Promise.all([
  admin.from('profiles').select('id,restaurant_id,is_super_admin').eq('id',u.user.id).maybeSingle(),
  admin.from('anaira_business_memberships').select('business_id,status').eq('business_id',businessId).eq('user_id',u.user.id).eq('status','active').maybeSingle()
 ]);
 return {admin,user:u.user,allowed:Boolean(p?.is_super_admin||p?.restaurant_id===businessId||m?.business_id===businessId)};
}
export async function GET(req){try{const u=new URL(req.url),type=u.searchParams.get('type'),module=u.searchParams.get('module'),business=u.searchParams.get('business');if(!type||!module||!business)return NextResponse.json({error:'type, module and business are required'},{status:400});const a=await actor(req,business);if(!a.allowed)return NextResponse.json({error:'Business access denied'},{status:403});const t=tableFor(type,module);const q=await a.admin.from(t).select('*').eq('business_id',business).order('sort_order').order('created_at',{ascending:false});if(q.error)throw q.error;return NextResponse.json({rows:q.data||[],statuses:workflowStatus(module)});}catch(e){return NextResponse.json({error:e.message||'Domain load failed'},{status:500});}}
export async function POST(req){try{const body=await req.json(),{type,module,business,id,data={},title,status='active',image_url=null,gallery=[]}=body;if(!type||!module||!business)return NextResponse.json({error:'type, module and business are required'},{status:400});const a=await actor(req,business);if(!a.allowed)return NextResponse.json({error:'Business access denied'},{status:403});const t=tableFor(type,module);const row={business_id:business,title:String(title||data.name||data.title||data.reference||data.code||'Untitled'),status,image_url,gallery,data,updated_at:new Date().toISOString()};let q=id?await a.admin.from(t).update(row).eq('id',id).eq('business_id',business).select().single():await a.admin.from(t).insert(row).select().single();if(q.error)throw q.error;await a.admin.from('anaira_business_domain_events_v16').insert({business_id:business,business_type:type,module_key:module,entity_id:q.data.id,event_type:id?'updated':'created',to_status:status,payload:{data}});return NextResponse.json({row:q.data});}catch(e){return NextResponse.json({error:e.message||'Domain save failed'},{status:500});}}
export async function PATCH(req){try{const body=await req.json(),{type,module,business,id,status,data={}}=body;if(!type||!module||!business||!id||!status)return NextResponse.json({error:'type, module, business, id and status are required'},{status:400});const a=await actor(req,business);if(!a.allowed)return NextResponse.json({error:'Business access denied'},{status:403});const t=tableFor(type,module);const old=await a.admin.from(t).select('status,data').eq('id',id).eq('business_id',business).single();if(old.error)throw old.error;const nextData={...(old.data.data||{}),...(data||{}),status};const q=await a.admin.from(t).update({status,data:nextData,updated_at:new Date().toISOString()}).eq('id',id).eq('business_id',business).select().single();if(q.error)throw q.error;await a.admin.from('anaira_business_domain_events_v16').insert({business_id:business,business_type:type,module_key:module,entity_id:id,event_type:'status_changed',from_status:old.data.status,to_status:status,payload:{data:nextData}});return NextResponse.json({row:q.data});}catch(e){return NextResponse.json({error:e.message||'Workflow transition failed'},{status:500});}}
export async function DELETE(req){try{const u=new URL(req.url),type=u.searchParams.get('type'),module=u.searchParams.get('module'),business=u.searchParams.get('business'),id=u.searchParams.get('id');if(!type||!module||!business||!id)return NextResponse.json({error:'type, module, business and id are required'},{status:400});const a=await actor(req,business);if(!a.allowed)return NextResponse.json({error:'Business access denied'},{status:403});const t=tableFor(type,module);const q=await a.admin.from(t).delete().eq('id',id).eq('business_id',business);if(q.error)throw q.error;await a.admin.from('anaira_business_domain_events_v16').insert({business_id:business,business_type:type,module_key:module,entity_id:id,event_type:'deleted',payload:{}});return NextResponse.json({ok:true});}catch(e){return NextResponse.json({error:e.message||'Domain delete failed'},{status:500});}}
