import {db} from '../../../../lib/server/provider';
import {requireTenant} from '../../../../lib/server/auth';
export const runtime='nodejs';
const schemas={
 customers:['full_name','phone','email','gender','date_of_birth','anniversary_date','address_line1','city','state','country','preferred_language','customer_type','vip','notes'],
 leads:['customer_id','lead_type','source','stage','estimated_value','next_follow_up','notes'],
 corporate:['company_name','contact_name','phone','email','negotiated_rate_notes','payment_terms','credit_limit','active'],
 partners:['partner_type','name','contact_name','phone','email','commission_percent','active'],
 reviews:['source','external_review_id','author_name','rating','review_text','reviewed_at','language','status']
};
function clean(v,k){if(v===undefined||v===null||v==='')return null;if(['vip','active'].includes(k)){if(typeof v==='boolean')return v;return ['1','true','yes','y'].includes(String(v).toLowerCase())}if(['estimated_value','credit_limit','commission_percent','rating'].includes(k))return Number(v)||0;return typeof v==='string'?v.trim():v}
async function one(s,tenantId,entity,row){const allowed=schemas[entity];if(!allowed)throw new Error(`Unsupported import type: ${entity}`);const p={tenant_id:tenantId};for(const k of allowed)if(k in row)p[k]=clean(row[k],k);
 if(entity==='customers'){if(!p.full_name)throw new Error('full_name is required');let existing=null;if(p.email){const q=await s.from('crm_customers').select('id').eq('tenant_id',tenantId).eq('email',p.email).maybeSingle();existing=q.data}if(!existing&&p.phone){const q=await s.from('crm_customers').select('id').eq('tenant_id',tenantId).eq('phone',p.phone).maybeSingle();existing=q.data}if(existing){const r=await s.from('crm_customers').update(p).eq('id',existing.id).eq('tenant_id',tenantId).select().single();if(r.error)throw r.error;return {mode:'updated',id:existing.id}}const r=await s.from('crm_customers').insert(p).select('id').single();if(r.error)throw r.error;return {mode:'inserted',id:r.data.id}}
 if(entity==='corporate'){if(!p.company_name)throw new Error('company_name is required');const q=await s.from('crm_corporate_accounts').select('id').eq('tenant_id',tenantId).eq('company_name',p.company_name).maybeSingle();if(q.data){const r=await s.from('crm_corporate_accounts').update(p).eq('id',q.data.id).eq('tenant_id',tenantId);if(r.error)throw r.error;return {mode:'updated',id:q.data.id}}const r=await s.from('crm_corporate_accounts').insert(p).select('id').single();if(r.error)throw r.error;return {mode:'inserted',id:r.data.id}}
 if(entity==='partners'){if(!p.name||!p.partner_type)throw new Error('name and partner_type are required');const q=await s.from('crm_partners').select('id').eq('tenant_id',tenantId).eq('name',p.name).maybeSingle();if(q.data){const r=await s.from('crm_partners').update(p).eq('id',q.data.id).eq('tenant_id',tenantId);if(r.error)throw r.error;return {mode:'updated',id:q.data.id}}const r=await s.from('crm_partners').insert(p).select('id').single();if(r.error)throw r.error;return {mode:'inserted',id:r.data.id}}
 if(entity==='reviews'){if(!p.source)throw new Error('source is required');if(p.external_review_id){const q=await s.from('crm_reviews').select('id').eq('tenant_id',tenantId).eq('source',p.source).eq('external_review_id',p.external_review_id).maybeSingle();if(q.data){const r=await s.from('crm_reviews').update(p).eq('id',q.data.id).eq('tenant_id',tenantId);if(r.error)throw r.error;return {mode:'updated',id:q.data.id}}}const r=await s.from('crm_reviews').insert(p).select('id').single();if(r.error)throw r.error;return {mode:'inserted',id:r.data.id}}
 if(entity==='leads'){if(!p.lead_type)throw new Error('lead_type is required');const r=await s.from('crm_leads').insert(p).select('id').single();if(r.error)throw r.error;return {mode:'inserted',id:r.data.id}}
}
export async function POST(req){try{const body=await req.json();const {tenantId,entity,rows}=body||{};const {user}=await requireTenant(req,tenantId);if(!Array.isArray(rows)||rows.length===0)throw new Error('rows must be a non-empty array');if(rows.length>500)throw new Error('Maximum 500 rows per import batch');const s=db();let inserted=0,updated=0,failed=0;const errors=[];for(let i=0;i<rows.length;i++){try{const r=await one(s,tenantId,entity,rows[i]||{});if(r.mode==='inserted')inserted++;else updated++}catch(e){failed++;errors.push({row:i+1,error:e.message})}}await s.from('crm_audit_logs').insert({tenant_id:tenantId,actor_id:user.id,entity_type:`import:${entity}`,entity_id:null,action:'batch_import',after_data:{rows:rows.length,inserted,updated,failed}}).catch(()=>{});return Response.json({ok:true,entity,processed:rows.length,inserted,updated,failed,errors:errors.slice(0,100)})}catch(e){return Response.json({ok:false,error:e.message},{status:400})}}
